/*
  filename: integralui.sidebar.js
  version : 1.0.0
  Copyright © 2016-2019 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(){var f=function(b,a){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return f(b,a)};return function(b,a){function c(){this.constructor=b}f(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}(),__decorate=this&&this.__decorate||function(f,b,a,c){var e=arguments.length,d=3>e?b:null===c?c=Object.getOwnPropertyDescriptor(b,a):c,g;
if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)d=Reflect.decorate(f,b,a,c);else for(var h=f.length-1;0<=h;h--)if(g=f[h])d=(3>e?g(d):3<e?g(b,a,d):g(b,a))||d;return 3<e&&d&&Object.defineProperty(b,a,d),d},__metadata=this&&this.__metadata||function(f,b){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(f,b)};Object.defineProperty(exports,"__esModule",{value:!0});
var core_1=require("@angular/core"),integralui_core_1=require("./integralui.core"),integralui_common_service_1=require("../services/integralui.common.service"),integralui_data_service_1=require("../services/integralui.data.service"),IntegralUISideContentPopup=function(f){function b(a,b){var c=f.call(this,a,b)||this;c.elemRef=a;c.commonService=b;c.headerHeight=0;c.headerOffsetHeight=0;c.placement=integralui_core_1.IntegralUIPlacement.Left;c.closed=new core_1.EventEmitter;return c}__extends(b,f);b.prototype.ngOnInit=
function(){this.generalClassName="iui-sidecontent-popup";this.initStyle()};b.prototype.ngAfterContentInit=function(){this.focus()};b.prototype.ngAfterViewInit=function(){};b.prototype.open=function(){this.isVisible=!0};b.prototype.close=function(){this.isVisible=!1;this.closed.emit(null)};b.prototype.processClose=function(){this.close()};b.prototype.getContentStyle=function(){var a={};switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:a.marginTop=this.size.height-this.maxSize.height+
"px";a.width=this.maxSize.width+"px";a.height=this.maxSize.height+"px";break;case integralui_core_1.IntegralUIPlacement.Right:a.width=this.maxSize.width+"px";a.height=this.maxSize.height-this.headerOffsetHeight+"px";break;case integralui_core_1.IntegralUIPlacement.Bottom:a.width=this.maxSize.width+"px";a.height=this.maxSize.height+"px";break;default:a.borderLeft=0,a.marginLeft=this.size.width-this.maxSize.width+"px",a.width=this.maxSize.width+"px",a.height=this.maxSize.height-this.headerOffsetHeight+
"px"}return a};b.prototype.getHeaderStyle=function(){return{borderTop:0,borderRight:0,borderLeft:0,height:this.headerHeight+"px"}};__decorate([core_1.Input(),__metadata("design:type",Number)],b.prototype,"headerHeight",void 0);__decorate([core_1.Input(),__metadata("design:type",Number)],b.prototype,"headerOffsetHeight",void 0);__decorate([core_1.Input(),__metadata("design:type",Number)],b.prototype,"placement",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],b.prototype,"title",
void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"closed",void 0);return b=__decorate([core_1.Component({selector:"iui-side-content-popup",template:'\n        <div [ngClass]="getControlClass()" [ngStyle]="getControlStyle()" tabindex="999">\n            <div *ngIf="placement % 2 == 1" class="iui-sidebar-header" style="padding-left:0;" [ngStyle]="getHeaderStyle()">\n                <div *ngIf="!templateObj.headerTemplate && title && title != \'\'" class="iui-sidebar-header-title">{{title}}</div>\n                <div class="iui-sidebar-header-content">\n                    <span [iuiTemplateOutlet]="templateObj.headerTemplate" [iuiTemplateOutletContext]="{$implicit: (templateObj.data)}"></span>\n                </div>\n            </div>\n            <div class="iui-sidebar-content" [ngStyle]="getContentStyle()">\n                <span [iuiTemplateOutlet]="templateObj.contentTemplate" [iuiTemplateOutletContext]="{$implicit: (templateObj.data)}"></span>\n            </div>\n        </div>\n    ',
encapsulation:core_1.ViewEncapsulation.None}),__metadata("design:paramtypes",[core_1.ElementRef,integralui_common_service_1.IntegralUICommonService])],b)}(integralui_core_1.IntegralUIPopup);exports.IntegralUISideContentPopup=IntegralUISideContentPopup;
var IntegralUISideBar=function(f){function b(a,b,e,d){var c=f.call(this,b)||this;c.elemRef=a;c.commonService=b;c.cmpResolver=e;c.baseService=d;c.closeTimer=null;c.openTimer=null;c.contentData=[];c.headerData=[];c.isTouchProcessed=!1;c.barOpacity=1;c.barSize={width:0,height:0};c.currentHeaderBlockPos=0;c.currentPlacement=integralui_core_1.IntegralUIPlacement.Left;c.contentSize={width:0,height:0};c.currentSize={width:0,height:0};c.headerBlockSize={width:0,height:0};c.headerHeight=0;c.headerOffsetHeight=
0;c.maxCtrlSize={width:0,height:0};c.minCtrlSize={width:0,height:0};c.expandValue=!1;c.isPopupVisible=!1;c.popupValue=!1;c.templateList=[];c.popupRef=null;c.popupCmp=null;c.tRef=null;c.animationSpeed=integralui_core_1.IntegralUISpeedMode.Normal;return c}__extends(b,f);b.prototype.ngOnInit=function(){this.baseService.setComponent(this);this.generalClassName="iui-sidebar";this.initStyle()};b.prototype.ngAfterViewInit=function(){var a=this,c=setTimeout(function(){var b=a.cmpResolver.resolveComponentFactory(integralui_core_1.IntegralUITComponent);
b&&a.headerRef&&(a.tRef=a.headerRef.createComponent(b));clearTimeout(c)},100)};b.prototype.ngAfterContentInit=function(){var a=this;a.updateTemplate();var c=setTimeout(function(){a.addPopup();clearTimeout(c)},1);a.updateLayout()};b.prototype.updateTemplate=function(){this.contentData.length=0;this.headerData.length=0;if(this.templates){this.templateList=this.templates.toArray();for(var a=0;a<this.templateList.length;a++)if(this.templateList[a].settings)switch(this.templateList[a].settings.type){case "header":this.headerData.push(this.templateList[a].getTemplate());
break;case "content":this.contentData.push(this.templateList[a].getTemplate())}}};b.prototype.removeCloseTimer=function(){this.closeTimer&&clearInterval(this.closeTimer)};b.prototype.removeOpenTimer=function(){this.openTimer&&clearInterval(this.openTimer)};b.prototype.ngOnDestroy=function(){this.removePopup();this.removeCloseTimer();this.removeOpenTimer();this.tRef&&this.tRef.destroy()};Object.defineProperty(b.prototype,"expanded",{get:function(){return this.expandValue},set:function(a){this.expandValue!=
a&&(this.expandValue=a,this.toggle())},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"placement",{get:function(){return this.currentPlacement},set:function(a){void 0!=a&&this.currentPlacement!=a&&(this.currentPlacement=a,this.updateLayout())},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"popup",{get:function(){return this.popupValue},set:function(a){this.popupValue!=a&&(this.popupValue=a,this.expanded=!1)},enumerable:!0,configurable:!0});b.prototype.addPopup=
function(){var a=this;if(a.appRef&&0<a.contentData.length){a.removePopup();var c=a.cmpResolver.resolveComponentFactory(IntegralUISideContentPopup);c&&(a.popupRef=a.appRef.createComponent(c),a.popupRef._component?a.popupCmp=a.popupRef._component:a.popupRef._hostElement&&(a.popupCmp=a.popupRef._hostElement.component),a.hidePopup(),a.popupCmp&&(a.popupCmp.templateObj={data:{},contentTemplate:a.contentData[0],headerTemplate:a.headerData[0]},a.popupCmp.closed.subscribe(function(c){a.hidePopup()})))}};
b.prototype.removePopup=function(){this.popupCmp&&this.popupCmp.closed&&this.popupCmp.closed.unsubscribe();this.popupRef&&this.popupRef.destroy();this.popupCmp=null};b.prototype.hidePopup=function(){this.popupCmp&&this.closePopup()};b.prototype.showPopup=function(){if(this.popupCmp){var a=this.commonService.getShiftPos(),c=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild);this.popupCmp.allowAnimation=this.allowAnimation;this.popupCmp.display="block";this.popupCmp.title=
this.title;this.popupCmp.headerHeight=this.headerHeight;this.popupCmp.headerOffsetHeight=this.headerOffsetHeight;this.popupCmp.placement=this.placement;switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:this.popupCmp.position={x:c.left+a.x,y:c.bottom+a.y-1};this.popupCmp.size={width:this.barSize.width,height:0};this.popupCmp.maxSize={width:this.barSize.width,height:this.maxCtrlSize.height-this.minCtrlSize.height};break;case integralui_core_1.IntegralUIPlacement.Right:this.popupCmp.position=
{x:c.left+a.x,y:c.top+a.y};this.popupCmp.size={width:0,height:this.barSize.height};this.popupCmp.maxSize={width:this.maxCtrlSize.width-this.minCtrlSize.width,height:this.barSize.height};break;case integralui_core_1.IntegralUIPlacement.Bottom:this.popupCmp.position={x:c.left+a.x,y:c.top+a.y-1};this.popupCmp.size={width:this.barSize.width,height:0};this.popupCmp.maxSize={width:this.barSize.width,height:this.maxCtrlSize.height-this.minCtrlSize.height};break;default:this.popupCmp.position={x:c.right+
a.x-1,y:c.top+a.y},this.popupCmp.size={width:0,height:this.barSize.height},this.popupCmp.maxSize={width:this.maxCtrlSize.width-this.minCtrlSize.width,height:this.barSize.height}}this.popupCmp.open();this.openPopup();this.isPopupVisible=!0}};b.prototype.headerMouseDown=function(a){this.isTouchProcessed||this.toggleButtonClicked();a.stopPropagation()};b.prototype.headerTouchStart=function(a){var c=this;c.isTouchProcessed=!0;c.toggleButtonClicked();setTimeout(function(){c.isTouchProcessed=!1},100);a.stopPropagation()};
b.prototype.toggleButtonClicked=function(){this.popup||this.placement==integralui_core_1.IntegralUIPlacement.Right||this.placement==integralui_core_1.IntegralUIPlacement.Bottom?this.popupCmp&&(this.isPopupVisible?this.hidePopup():this.showPopup()):this.expanded=!this.expanded};b.prototype.getCtrlSpace=function(a){var c=this.commonService.getPadding(this.elemRef.nativeElement),b=this.commonService.getBorderWidth(this.elemRef.nativeElement);return a?c.top+c.bottom+b.top+b.bottom:c.left+c.right+b.left+
b.right};b.prototype.getMaxSize=function(){return{width:this.maxCtrlSize.width+this.getCtrlSpace(),height:this.maxCtrlSize.height+this.getCtrlSpace(!0)}};b.prototype.getMinSize=function(){return{width:this.minCtrlSize.width+this.getCtrlSpace(),height:this.minCtrlSize.height+this.getCtrlSpace(!0)}};b.prototype.updateLayout=function(){var a=this,b=setTimeout(function(){a.clientRect={width:a.size.width,height:a.size.height};var c=a.headerButtonElem?{width:a.headerButtonElem.nativeElement.offsetHeight,
height:a.headerButtonElem.nativeElement.offsetHeight}:{width:0,height:0};a.headerBlockSize={width:a.headerBlockElem?a.headerBlockElem.nativeElement.offsetWidth:0,height:a.headerBlockElem?a.headerBlockElem.nativeElement.offsetHeight:0};var d=a.commonService.getPadding(a.headerElem.nativeElement),f=a.commonService.getBorderWidth(a.headerElem.nativeElement);a.headerHeight=Math.max(c.height,a.headerBlockSize.height);a.headerOffsetHeight=a.headerHeight+d.top+d.bottom+2;switch(a.currentPlacement){case integralui_core_1.IntegralUIPlacement.Top:a.barSize=
{width:a.clientRect.width,height:c.height+d.top+d.bottom+f.top+f.bottom};a.currentSize={width:a.clientRect.width,height:a.barSize.height};a.minCtrlSize={width:a.barSize.width,height:a.barSize.height};break;case integralui_core_1.IntegralUIPlacement.Right:a.barSize={width:c.width+d.left+d.right,height:a.clientRect.height};a.currentSize={width:a.barSize.width,height:a.clientRect.height-a.headerOffsetHeight};a.minCtrlSize={width:a.barSize.width,height:a.barSize.height};break;case integralui_core_1.IntegralUIPlacement.Bottom:a.barSize=
{width:a.clientRect.width,height:c.height+d.top+d.bottom+f.top+f.bottom};a.currentSize={width:a.clientRect.width,height:a.barSize.height};a.minCtrlSize={width:a.barSize.width,height:a.barSize.height};break;default:a.barSize={width:c.width+d.left+d.right,height:a.clientRect.height},a.currentSize={width:a.barSize.width,height:a.clientRect.height-a.headerOffsetHeight},a.minCtrlSize={width:a.barSize.width,height:a.barSize.height}}a.maxCtrlSize={width:a.size.width,height:a.size.height};a.currentHeaderBlockPos=
d.left+d.right;clearTimeout(b)},1)};b.prototype.getAnimationFactor=function(a,c){switch(this.animationSpeed){case integralui_core_1.IntegralUISpeedMode.VerySlow:var b=c?a/4:a/2;break;case integralui_core_1.IntegralUISpeedMode.Slow:b=c?a/8:a/4;break;case integralui_core_1.IntegralUISpeedMode.Fast:b=c?a/20:a/15;break;case integralui_core_1.IntegralUISpeedMode.VeryFast:b=c?a/30:a/25;break;default:b=c?a/15:a/10}return b};b.prototype.close=function(){this.expandValue=!1;this.popup?this.closePopup():this.closeNormal()};
b.prototype.closeNormal=function(){this.removeCloseTimer();this.removeOpenTimer();switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:this.closeFromTop();break;default:this.closeFromLeft()}};b.prototype.closeFromLeft=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.maxCtrlSize.width,!0),e=a.size.width/b;a.barOpacity=0;a.closeTimer=setInterval(function(){a.currentSize.width>a.minCtrlSize.width?(a.currentSize.width-=e,a.barOpacity=a.currentSize.width/a.maxCtrlSize.width):
(a.currentSize.width=a.minCtrlSize.width,a.barOpacity=1,a.removeCloseTimer())},5)}else a.currentSize.width=a.minCtrlSize.width,a.barOpacity=1};b.prototype.closeFromTop=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.maxCtrlSize.height,!0),e=a.size.height/b;a.barOpacity=0;a.closeTimer=setInterval(function(){a.currentSize.height>a.minCtrlSize.height?(a.currentSize.height-=e,a.barOpacity=a.currentSize.height/a.maxCtrlSize.height):(a.currentSize.height=a.minCtrlSize.height,a.barOpacity=
1,a.removeCloseTimer())},5)}else a.currentSize.height=a.minCtrlSize.height,a.barOpacity=1};b.prototype.closePopup=function(){this.removeCloseTimer();this.removeOpenTimer();switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:this.closePopupFromTop();break;case integralui_core_1.IntegralUIPlacement.Right:this.closePopupFromRight();break;case integralui_core_1.IntegralUIPlacement.Bottom:this.closePopupFromBottom();break;default:this.closePopupFromLeft()}};b.prototype.closePopupFromBottom=
function(){var a=this,b=a.popupCmp.position.y;if(a.allowAnimation){var e=a.getAnimationFactor(a.popupCmp.maxSize.height,!0),d=a.popupCmp.maxSize.height/e;a.closeTimer=setInterval(function(){0<a.popupCmp.size.height?(a.popupCmp.position={x:a.popupCmp.position.x,y:a.popupCmp.position.y+d},a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.size.height-d}):(a.popupCmp.position={x:a.popupCmp.position.x,y:b},a.popupCmp.size={width:a.popupCmp.size.width,height:0},a.popupCmp.display="none",a.isPopupVisible=
!1,a.removeCloseTimer())},5)}else a.popupCmp.position={x:a.popupCmp.position.x,y:b},a.popupCmp.size={width:a.popupCmp.size.width,height:0},a.popupCmp.display="none",a.isPopupVisible=!1};b.prototype.closePopupFromLeft=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.popupCmp.maxSize.width,!0),e=a.popupCmp.maxSize.width/b;a.closeTimer=setInterval(function(){0<a.popupCmp.size.width?a.popupCmp.size={width:a.popupCmp.size.width-e,height:a.popupCmp.size.height}:(a.popupCmp.size={width:0,
height:a.popupCmp.size.height},a.popupCmp.display="none",a.isPopupVisible=!1,a.removeCloseTimer())},5)}else a.popupCmp.size={width:0,height:a.popupCmp.size.height},a.popupCmp.display="none",a.isPopupVisible=!1};b.prototype.closePopupFromTop=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.popupCmp.maxSize.height,!0),e=a.popupCmp.maxSize.height/b;a.closeTimer=setInterval(function(){0<a.popupCmp.size.height?a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.size.height-
e}:(a.popupCmp.size={width:a.popupCmp.size.width,height:0},a.popupCmp.display="none",a.isPopupVisible=!1,a.removeCloseTimer())},5)}else a.popupCmp.size={width:a.popupCmp.size.width,height:0},a.popupCmp.display="none",a.isPopupVisible=!1};b.prototype.closePopupFromRight=function(){var a=this,b=a.popupCmp.position.x;if(a.allowAnimation){var e=a.getAnimationFactor(a.popupCmp.maxSize.width,!0),d=a.popupCmp.maxSize.width/e;a.closeTimer=setInterval(function(){0<a.popupCmp.size.width?(a.popupCmp.position=
{x:a.popupCmp.position.x+d,y:a.popupCmp.position.y},a.popupCmp.size={width:a.popupCmp.size.width-d,height:a.popupCmp.size.height}):(a.popupCmp.position={x:b,y:a.popupCmp.position.y},a.popupCmp.size={width:0,height:a.popupCmp.size.height},a.popupCmp.display="none",a.isPopupVisible=!1,a.removeCloseTimer())},5)}else a.popupCmp.position={x:b,y:a.popupCmp.position.y},a.popupCmp.size={width:0,height:a.popupCmp.size.height},a.popupCmp.display="none",a.isPopupVisible=!1};b.prototype.open=function(){this.expandValue=
!0;this.popup?this.openPopup():this.openNormal()};b.prototype.openNormal=function(){this.removeCloseTimer();this.removeOpenTimer();switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:this.openFromTop();break;case integralui_core_1.IntegralUIPlacement.Left:this.openFromLeft()}};b.prototype.openFromLeft=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.maxCtrlSize.width),e=a.size.width/b;a.barOpacity=1;a.openTimer=setInterval(function(){a.currentSize.width<a.maxCtrlSize.width?
(a.currentSize.width+=e,a.barOpacity=1-a.currentSize.width/a.maxCtrlSize.width):(a.currentSize.width=a.maxCtrlSize.width,a.barOpacity=0,a.removeOpenTimer())},5)}else a.currentSize.width=a.maxCtrlSize.width,a.barOpacity=0};b.prototype.openFromTop=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.maxCtrlSize.height),e=a.size.height/b;a.barOpacity=1;a.openTimer=setInterval(function(){a.currentSize.height<a.maxCtrlSize.height?(a.currentSize.height+=e,a.barOpacity=1-a.currentSize.height/
a.maxCtrlSize.height):(a.currentSize.height=a.maxCtrlSize.height,a.barOpacity=0,a.removeOpenTimer())},5)}else a.currentSize.height=a.maxCtrlSize.height,a.barOpacity=0};b.prototype.openPopup=function(){this.removeCloseTimer();this.removeOpenTimer();switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:this.openPopupFromTop();break;case integralui_core_1.IntegralUIPlacement.Right:this.openPopupFromRight();break;case integralui_core_1.IntegralUIPlacement.Bottom:this.openPopupFromBottom();
break;default:this.openPopupFromLeft()}};b.prototype.openPopupFromBottom=function(){var a=this,b=a.popupCmp.position.y;if(a.allowAnimation){var e=a.getAnimationFactor(a.popupCmp.maxSize.height),d=a.popupCmp.maxSize.height/e;a.openTimer=setInterval(function(){a.popupCmp.size.height<a.popupCmp.maxSize.height?(a.popupCmp.position={x:a.popupCmp.position.x,y:a.popupCmp.position.y-d},a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.size.height+d}):(a.popupCmp.position={x:a.popupCmp.position.x,
y:b-a.popupCmp.maxSize.height},a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.maxSize.height},a.removeOpenTimer())},5)}else a.popupCmp.position={x:a.popupCmp.position.x,y:b-a.popupCmp.maxSize.height},a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.maxSize.height}};b.prototype.openPopupFromLeft=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.popupCmp.maxSize.width),e=a.popupCmp.maxSize.width/b;a.openTimer=setInterval(function(){a.popupCmp.size.width<
a.popupCmp.maxSize.width?a.popupCmp.size={width:a.popupCmp.size.width+e,height:a.popupCmp.size.height}:(a.popupCmp.size={width:a.popupCmp.maxSize.width,height:a.popupCmp.size.height},a.removeOpenTimer())},5)}else a.popupCmp.size={width:a.popupCmp.maxSize.width,height:a.popupCmp.size.height}};b.prototype.openPopupFromTop=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.popupCmp.maxSize.height),e=a.popupCmp.maxSize.height/b;a.openTimer=setInterval(function(){a.popupCmp.size.height<
a.popupCmp.maxSize.height?a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.size.height+e}:(a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.maxSize.height},a.removeOpenTimer())},5)}else a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.maxSize.height}};b.prototype.openPopupFromRight=function(){var a=this,b=a.popupCmp.position.x;if(a.allowAnimation){var e=a.getAnimationFactor(a.popupCmp.maxSize.width),d=a.popupCmp.maxSize.width/e;a.openTimer=setInterval(function(){a.popupCmp.size.width<
a.popupCmp.maxSize.width?(a.popupCmp.position={x:a.popupCmp.position.x-d,y:a.popupCmp.position.y},a.popupCmp.size={width:a.popupCmp.size.width+d,height:a.popupCmp.size.height}):(a.popupCmp.position={x:b-a.popupCmp.maxSize.width,y:a.popupCmp.position.y},a.popupCmp.size={width:a.popupCmp.maxSize.width,height:a.popupCmp.size.height},a.removeOpenTimer())},5)}else a.popupCmp.position={x:b-a.popupCmp.maxSize.width,y:a.popupCmp.position.y},a.popupCmp.size={width:a.popupCmp.maxSize.width,height:a.popupCmp.size.height}};
b.prototype.toggle=function(){this.expanded?this.open():this.close()};b.prototype.getControlStyle=function(){var a={};switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:0<this.ctrlSize.width&&(a.width=this.ctrlSize.width+"px");a.height=this.currentSize.height+"px";break;case integralui_core_1.IntegralUIPlacement.Bottom:0<this.ctrlSize.width&&(a.width=this.ctrlSize.width+"px");a.height=this.currentSize.height+"px";break;default:a.width=this.currentSize.width+"px",0<this.ctrlSize.height&&
(a.height=this.ctrlSize.height+"px")}return a};b.prototype.getContentStyle=function(){var a={};switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:a.marginTop=this.currentSize.height-this.maxCtrlSize.height+"px";a.height=this.clientRect.height-this.headerOffsetHeight+"px";break;case integralui_core_1.IntegralUIPlacement.Left:a.marginLeft=this.currentSize.width-this.maxCtrlSize.width+"px",a.height=this.clientRect.height-this.headerOffsetHeight+"px"}return a};b.prototype.getHeaderStyle=
function(){var a={};switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:a.borderTop=0;a.borderRight=0;a.borderLeft=0;this.expanded||(a.borderBottom=0);break;case integralui_core_1.IntegralUIPlacement.Left:a.borderTop=0,a.borderRight=0,a.borderLeft=0}return a};__decorate([core_1.ContentChildren(integralui_core_1.IntegralUITemplate),__metadata("design:type",core_1.QueryList)],b.prototype,"templates",void 0);__decorate([core_1.ViewChild("header",{read:core_1.ViewContainerRef,"static":!1}),
__metadata("design:type",core_1.ViewContainerRef)],b.prototype,"headerRef",void 0);__decorate([core_1.ViewChild("header",{read:core_1.ElementRef,"static":!1}),__metadata("design:type",core_1.ElementRef)],b.prototype,"headerElem",void 0);__decorate([core_1.ViewChild("headerButton",{read:core_1.ElementRef,"static":!1}),__metadata("design:type",core_1.ElementRef)],b.prototype,"headerButtonElem",void 0);__decorate([core_1.ViewChild("headerBlock",{read:core_1.ElementRef,"static":!1}),__metadata("design:type",
core_1.ElementRef)],b.prototype,"headerBlockElem",void 0);__decorate([core_1.ViewChild("content",{read:core_1.ElementRef,"static":!1}),__metadata("design:type",core_1.ElementRef)],b.prototype,"contentElem",void 0);__decorate([core_1.Input(),__metadata("design:type",Number)],b.prototype,"animationSpeed",void 0);__decorate([core_1.Input(),__metadata("design:type",Object)],b.prototype,"appRef",void 0);__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],
b.prototype,"expanded",null);__decorate([core_1.Input(),__metadata("design:type",Number),__metadata("design:paramtypes",[Number])],b.prototype,"placement",null);__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],b.prototype,"popup",null);__decorate([core_1.Input(),__metadata("design:type",String)],b.prototype,"title",void 0);return b=__decorate([core_1.Component({selector:"iui-sidebar",template:'\n\t\t<div [ngClass]="getControlClass()" [ngStyle]="getControlStyle()">\n            <div *ngIf="placement % 2 == 1" class="iui-sidebar-line" [ngStyle]="{ top: headerOffsetHeight + \'px\', width: minCtrlSize.width + \'px\', height: maxCtrlSize.height + \'px\', opacity: barOpacity }"></div>\n            <div class="iui-sidebar-header" [ngStyle]="getHeaderStyle()" #header>\n                <div class="iui-sidebar-header-button" (mousedown)="headerMouseDown($event)" (touchstart)="headerTouchStart($event)" #headerButton><span></span></div>\n                <div *ngIf="!popup || placement % 2 == 0" class="iui-sidebar-header-block" [ngStyle]="{ marginLeft: currentHeaderBlockPos + \'px\', width: maxCtrlSize.width - minCtrlSize.width - currentHeaderBlockPos + \'px\'}" #headerBlock>\n                    <div *ngIf="headerData[0].length == 0 && title && title != \'\'" class="iui-sidebar-header-title">{{title}}</div>\n                    <div class="iui-sidebar-header-content">\n                        <span [iuiTemplateOutlet]="headerData[0]" [iuiTemplateOutletContext]="{$implicit: (data)}"></span>\n                    </div>\n                </div>\n            </div>\n            <div *ngIf="!popup && (placement == 0 || placement == 3)" class="iui-sidebar-content" [ngStyle]="getContentStyle()" #content>\n                <span [iuiTemplateOutlet]="contentData[0]" [iuiTemplateOutletContext]="{$implicit: (data)}"></span>\n            </div>\n\t\t</div>\n\t',
inputs:"controlStyle data enabled name size state".split(" "),providers:[integralui_core_1.IntegralUIBaseService,integralui_data_service_1.IntegralUIDataService],encapsulation:core_1.ViewEncapsulation.None}),__metadata("design:paramtypes",[core_1.ElementRef,integralui_common_service_1.IntegralUICommonService,core_1.ComponentFactoryResolver,integralui_core_1.IntegralUIBaseService])],b)}(integralui_core_1.IntegralUIBaseComponent);exports.IntegralUISideBar=IntegralUISideBar;