import { ComponentFactoryResolver, ElementRef, EventEmitter, Renderer } from '@angular/core';
import { IntegralUIBaseComponent, IntegralUISelectionMode, IntegralUISortOrder } from './integralui.core';
import { IntegralUICommonService } from '../services/integralui.common.service';
import { IntegralUIDataService } from '../services/integralui.data.service';
import { IntegralUIDragDropService } from '../services/integralui.dragdrop.service';
import { IntegralUIFilterService } from '../services/integralui.filter.service';
export declare enum IntegralUIGridLines {
    None = 0,
    Horizontal = 1,
    Vertical = 2,
    Both = 3,
}
export declare class IntegralUIBaseGrid extends IntegralUIBaseComponent {
    protected dataService: IntegralUIDataService;
    protected dragDropService: IntegralUIDragDropService;
    protected elemRef: ElementRef;
    protected elemRenderer: Renderer;
    protected commonService: IntegralUICommonService;
    protected filterService: IntegralUIFilterService;
    protected cmpResolver: ComponentFactoryResolver;
    protected currentColumnList: Array<any>;
    protected currentRowList: Array<any>;
    private dataColumns;
    private dataRows;
    protected options: any;
    scrollColumnList: Array<any>;
    scrollRowList: Array<any>;
    protected columnList: Array<any>;
    protected rowList: Array<any>;
    protected columnDataKey: string;
    protected rowDataKey: string;
    private dropMarkElem;
    private dragCmpRef;
    private dragCmp;
    private cloneElem;
    private cloneElemStartPos;
    protected hoverColumn: any;
    protected hoverRow: any;
    protected currentIndex: number;
    protected prevIndex: number;
    protected currentFocusCell: any;
    protected isKeyboardActive: boolean;
    protected allowUpdate: boolean;
    protected avgRowHeight: number;
    protected headerHeight: number;
    protected footerHeight: number;
    protected viewIndexRange: any;
    protected visibleRange: number;
    protected isHeaderVisible: boolean;
    protected isFooterVisible: boolean;
    protected scrollSize: {
        width: number;
        height: number;
    };
    protected clientRect: {
        width: number;
        height: number;
    };
    contentLeftPos: number;
    protected allColWidth: number;
    protected isColumnResizing: boolean;
    currentScrollPos: {
        x: number;
        y: number;
    };
    maxScrollPos: {
        x: number;
        y: number;
    };
    private accelerator;
    private scrollTimerID;
    private isScrollTimerActive;
    private scrollCount;
    protected isScrollActive: boolean;
    protected prevScrollPos: {
        x: number;
        y: number;
    };
    scrollBarSize: {
        width: number;
        height: number;
    };
    scrollLargeChange: {
        x: number;
        y: number;
    };
    protected currentSelectedColumn: any;
    protected currentSelectedRow: any;
    protected currentSelectionMode: IntegralUISelectionMode;
    private shiftFirstSelectedRow;
    private removeIndex;
    protected currentSelectedRows: Array<any>;
    appRef: any;
    gridLines: IntegralUIGridLines;
    rowHeight: number;
    allowDrag: boolean;
    allowDrop: boolean;
    allowFilter: boolean;
    allowFocus: boolean;
    columns: Array<any>;
    dataFields: any;
    focusedCell: any;
    paging: any;
    rows: Array<any>;
    selectedColumn: any;
    selectedRow: any;
    selectionMode: IntegralUISelectionMode;
    sorting: IntegralUISortOrder;
    afterSelect: EventEmitter<any>;
    beforeEdit: EventEmitter<any>;
    beforeSelect: EventEmitter<any>;
    change: EventEmitter<any>;
    columnAdding: EventEmitter<any>;
    columnAdded: EventEmitter<any>;
    columnClick: EventEmitter<any>;
    columnRemoving: EventEmitter<any>;
    columnRemoved: EventEmitter<any>;
    columnsCleared: EventEmitter<any>;
    columnSizeChanged: EventEmitter<any>;
    dragDrop: EventEmitter<any>;
    dragOver: EventEmitter<any>;
    keyDown: EventEmitter<any>;
    keyPress: EventEmitter<any>;
    keyUp: EventEmitter<any>;
    rowAdding: EventEmitter<any>;
    rowAdded: EventEmitter<any>;
    rowClick: EventEmitter<any>;
    rowDblClick: EventEmitter<any>;
    rowRemoving: EventEmitter<any>;
    rowRemoved: EventEmitter<any>;
    rowsCleared: EventEmitter<any>;
    loadComplete: EventEmitter<any>;
    scrollPosChanged: EventEmitter<any>;
    selectionChanged: EventEmitter<any>;
    updateComplete: EventEmitter<any>;
    constructor(dataService: IntegralUIDataService, dragDropService: IntegralUIDragDropService, elemRef: ElementRef, elemRenderer: Renderer, commonService?: IntegralUICommonService, filterService?: IntegralUIFilterService, cmpResolver?: ComponentFactoryResolver);
    ngOnInit(): void;
    addColumn(column: any): void;
    clearColumns(): void;
    insertColumnAt(column: any, index: number): void;
    insertColumnBefore(column: any, refColumn: any): void;
    insertColumnAfter(column: any, refColumn: any): void;
    removeColumn(column: any): boolean;
    removeColumnAt(index: number): boolean;
    protected callEventAddColumn(type: string, column: any, index?: number, refColumn?: any, flag?: boolean): void;
    protected callEventRemoveColumn(column: any, index?: number): boolean;
    addRow(row: any, parent?: any): void;
    clearRows(parent?: any): void;
    insertRowAt(row: any, index: number, parent?: any): void;
    insertRowBefore(row: any, refRow: any): void;
    insertRowAfter(row: any, refRow: any): void;
    removeRow(row: any): boolean;
    removeRowAt(index: number, parent?: any): boolean;
    protected callEventAddRow(type: string, row: any, index?: number, parent?: any, refRow?: any, flag?: boolean): void;
    protected callEventRemoveRow(row: any, index?: number, parent?: any): boolean;
    protected updateData(): void;
    protected updateDataFields(data?: any): void;
    protected updateOptions(value?: any): void;
    protected updateColumnFields(fields?: any): void;
    protected updateRowFields(fields?: any): void;
    protected updateCellFields(fields?: any): void;
    protected processLoadData(data: Array<any>, parent?: any, fields?: any, flat?: boolean): void;
    protected updateScrollColumnList(): void;
    protected updateScrollRowList(): void;
    private addDropMark(pos);
    protected removeDropMark(): void;
    protected callDragDropEvent(e: any, data: any, flag?: boolean): boolean;
    private checkEmptySpace(e);
    ctrlDragDrop(e: any): void;
    ctrlDragLeave(e: any): void;
    ctrlDragOver(e: any): void;
    private dropMark(e, flag?);
    private updateDragComponent(value);
    protected isDragAllowed(row: any): boolean;
    protected isDropAllowed(sourceData: any, targetRow: any, dropPos: number): any;
    protected processDragStart(e: any, row: any): void;
    protected processDragOver(e: any, row?: any, rowBounds?: any, flag?: boolean): void;
    protected processDragDrop(e: any, row?: any): void;
    protected drop(e: any, data: any): void;
    protected processDataDrop(e: any, row: any, data: any): void;
    protected callAfterSelectEvent(obj: any): void;
    filter(column: any, params?: any): void;
    cloneRow(row: any): any;
    protected createCloneList(list: Array<any>): any[];
    getColumnById(id: any): any;
    protected getColumnCurrentIndex(column: any): number;
    protected getColumnIndexFromList(column: any): number;
    protected getFilterTree(column: any): any;
    getList(key?: string, parent?: any): any;
    protected getObjFromRow(row: any): any;
    protected getRowCurrentIndex(row: any): number;
    getRowFromComponent(cmp: any): any;
    protected isChildOf(targetRow: any, row: any): boolean;
    protected isColumnVisible(column: any): boolean;
    protected isComponentIndexInRange(index: number): boolean;
    protected isIndexInRange(index: number): boolean;
    protected isRowAllowed(row: any, flag?: boolean): boolean;
    protected filterIsThereChildren(row: any, flag?: boolean): boolean;
    protected isRowEnabled(row: any): boolean;
    protected isRowFixed(row: any): boolean;
    protected isRowHovered(row: any): boolean;
    protected isRowSelected(row: any): boolean;
    protected isParentOf(targetRow: any, row: any): boolean;
    cellGotFocus(cell: any): void;
    cellLostFocus(cell: any): void;
    onContentScroll(e: any): void;
    cellMouseDown(e: any, cell: any): void;
    cellKeyDown(e: any, cell: any): void;
    cellKeyPress(e: any, cell: any): void;
    cellKeyUp(e: any, cell: any): void;
    processDownArrowKey(cell: any, e?: any): any;
    processEndKey(cell: any, e?: any): any;
    processHomeKey(cell: any, e?: any): any;
    processLeftArrowKey(cell: any): any;
    processPageDownKey(cell: any, e?: any): any;
    processPageUpKey(cell: any, e?: any): any;
    processRightArrowKey(cell: any): any;
    processUpArrowKey(cell: any, e?: any): any;
    protected getDownCell(cell: any): any;
    protected getNextCell(cell: any): any;
    protected getPrevCell(cell: any): any;
    protected getUpCell(cell: any): any;
    protected isFirstCell(cell: any): boolean;
    protected isFirstRow(cell: any): boolean;
    protected isLastCell(cell: any): boolean;
    protected isLastRow(cell: any): boolean;
    protected getRowFromCell(cell: any): any;
    moveFocusFromCell(cell: any, direction: string): any;
    getObjFromCell(cell: any): any;
    onWindowKeyDown(e: any): void;
    onWindowKeyUp(e: any): void;
    protected getContentSize(): {
        width: number;
        height: number;
    };
    refresh(obj?: any): void;
    suspendLayout(): void;
    resumeLayout(): void;
    updateLayout(): void;
    protected updateRange(): void;
    private updateCloneElemPos(e);
    protected onCtrlMouseEnter(e: any): void;
    protected onCtrlMouseLeave(e: any): void;
    private setCloneElem(clone, pos);
    private appendCloneElem();
    private closeCloneElem();
    private updatePaging(value?);
    scrollPos(value?: any): any;
    protected changeHorizontalScrollPos(value: number): void;
    protected changeVerticalScrollPos(value: number): void;
    gridMouseWheel(e: any): void;
    isVerScrollVisible(): boolean;
    isHorScrollVisible(): boolean;
    onVerticalScrollStart(e: any): void;
    onVerticalScrollEnd(e: any): void;
    onVerticalScrollChanged(e: any): void;
    onHorizontalScrollStart(e: any): void;
    onHorizontalScrollEnd(e: any): void;
    onHorizontalScrollChanged(e: any): void;
    updateView(): void;
    protected processScroll(e: any): void;
    private startScrollTimer(flag, interval?);
    private stopScrollTimer();
    private scrollTimerElapsed(flag);
    scrollTo(row: any): void;
    findRowById(id: any): any;
    findRowByText(text: string): any;
    clearSelection(): void;
    protected processColumnSelection(e: any, column: any, value?: any): any;
    protected clearComponentSelection(): void;
    private clearPrevSelection(row?);
    private isRowInSelectionList(row);
    protected processRowSelection(e: any, row: any, value?: any): void;
    selectRows(rows: Array<any>): void;
    protected updateRowSelection(e: any, row: any): void;
    protected sortColumn: any;
    protected sortComparer: any;
    sort(column: any, order: IntegralUISortOrder, comparer?: any): void;
    protected getCellIndexInCollection(cells: Array<any>, colIndex: number, colId: any): number;
    isSortingAllowed(): boolean;
    isSortingColumn(column: any): boolean;
    protected applySorting(list: Array<any>): void;
}
