/*
  filename: integralui.listbar.js
  version : 1.7.0
  Copyright © 2016-2020 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(){var f=function(b,a){f=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,e){a.__proto__=e}||function(a,e){for(var c in e)e.hasOwnProperty(c)&&(a[c]=e[c])};return f(b,a)};return function(b,a){function c(){this.constructor=b}f(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}();Object.defineProperty(exports,"__esModule",{value:!0});
var core_1=require("@angular/core"),integralui_core_1=require("./integralui.core"),integralui_common_service_1=require("../services/integralui.common.service"),integralui_data_service_1=require("../services/integralui.data.service"),integralui_listgroup_1=require("./integralui.listgroup"),i0=require("@angular/core"),i1=require("../services/integralui.data.service"),i2=require("../services/integralui.common.service"),i3=require("./integralui.core"),i4=require("@angular/common"),_c0=["buttonUp"],_c1=
["buttonDown"],_c2=["content"],_c3=function(f){return{display:f}},_c4=function(f){return{display:f}},_c5=function(f){return{"margin-top":f}},_c6=["*"],IntegralUIListBar=function(f){function b(a,c,e,b,g){var d=f.call(this,e)||this;d.elemRef=a;d.dataService=c;d.commonService=e;d.cmpResolver=b;d.baseService=g;d.numGroups=0;d.blockMarginTop=0;d.scrollPos={x:0,y:0};d.maxScrollPos={x:0,y:0};d.groupEventList=[];d.initScrollPos=0;d.isScrollActive=!1;d.isScrollVisible=!1;d.scrollCount=0;d.scrollTimer=null;
d.stopScrolling=!1;d.currentSelection=null;d.currentSelectedIndex=-1;d.selectedComponent=null;d.prevComponent=null;d.removeIndex=-1;d.tRef=null;d.mouseWheelSpeed=integralui_core_1.IntegralUISpeedMode.Normal;d.afterCollapse=new core_1.EventEmitter;d.afterExpand=new core_1.EventEmitter;d.afterSelect=new core_1.EventEmitter;d.beforeCollapse=new core_1.EventEmitter;d.beforeExpand=new core_1.EventEmitter;d.beforeSelect=new core_1.EventEmitter;d.groupAdding=new core_1.EventEmitter;d.groupAdded=new core_1.EventEmitter;
d.clear=new core_1.EventEmitter;d.groupRemoving=new core_1.EventEmitter;d.groupRemoved=new core_1.EventEmitter;d.selectionChanged=new core_1.EventEmitter;d.groupList=[];return d}__extends(b,f);Object.defineProperty(b.prototype,"selectedIndex",{get:function(){return this.currentSelectedIndex},set:function(a){this.currentSelectedIndex!=a&&(this.currentSelectedIndex=a,this.selectComponentByIndex(a))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectedGroup",{get:function(){return this.currentSelection},
set:function(a){this.currentSelection!=a&&(this.currentSelection=a,this.selectGroup(a))},enumerable:!0,configurable:!0});b.prototype.ngOnInit=function(){this.baseService.setComponent(this);this.dataService.init([{data:this.groups}]);this.generalClassName="iui-listbar";this.defaultStyle={general:{disabled:this.generalClassName+"-disabled",focused:this.generalClassName+"-focused",normal:this.generalClassName,hovered:this.generalClassName+"-hovered",selected:this.generalClassName+"-selected"}};this.updateStyle(this.controlStyle);
this.updateControlClass()};b.prototype.ngAfterViewInit=function(){var a=this,c=setTimeout(function(){var b=a.cmpResolver.resolveComponentFactory(integralui_core_1.IntegralUITComponent);b&&a.contentRef&&(a.tRef=a.contentRef.createComponent(b));clearTimeout(c)},100)};b.prototype.ngAfterContentInit=function(){this.groupList=this.contentList.toArray();this.numGroups=this.groupList.length;this.attachGroupEvents();0<this.numGroups&&(0<=this.selectedIndex?this.selectComponentByIndex(this.selectedIndex):
this.selectedGroup&&this.groups&&this.selectComponentByIndex(this.groups.indexOf(this.selectedGroup)));this.updateLayout()};b.prototype.ngOnDestroy=function(){this.tRef&&this.tRef.destroy()};b.prototype.ngAfterContentChecked=function(){this.contentList&&(this.groupList=this.contentList.toArray(),this.numGroups!=this.groupList.length&&(this.attachGroupEvents(),this.numGroups=this.groupList.length,this.selectComponentByIndex(this.selectedIndex)),0==this.numGroups&&(this.selectedComponent=null));this.clientRect=
{width:this.elemRef.nativeElement.firstElementChild.clientWidth,height:this.elemRef.nativeElement.firstElementChild.clientHeight};this.clientRect.width!=this.prevClientRect.width?(this.updateLayout(),this.prevClientRect.width=this.clientRect.width):this.clientRect.height!=this.prevClientRect.height&&(this.updateLayout(),this.prevClientRect.height=this.clientRect.height);this.updateLayout()};b.prototype.clearGroups=function(){this.dataService.clear();this.clear.emit(null)};b.prototype.addGroup=function(a){this.callEventAdd("add",
a)};b.prototype.insertGroupAt=function(a,c){this.callEventAdd("at",a,c)};b.prototype.insertGroupBefore=function(a,c){this.callEventAdd("ref",a,-1,c)};b.prototype.insertGroupAfter=function(a,c){this.callEventAdd("ref",a,-1,c,!0)};b.prototype.removeGroup=function(a){this.callEventRemove(a)};b.prototype.removeGroupAt=function(a){this.groups&&0<=a&&a<this.groups.length&&this.callEventRemove(this.groups[a])};b.prototype.callEventAdd=function(a,c,b,h,g){var e={cancel:!1,group:c};this.groupAdding.emit(e);
if(1!=e.cancel){switch(a){case "at":this.dataService.insert(c,b);break;case "ref":this.dataService.insertByRef(c,h,g);break;default:this.dataService.insert(c)}this.groupAdded.emit({group:c});this.selectedComponent||this.selectComponentByIndex(0)}};b.prototype.callEventRemove=function(a){var c={cancel:!1,group:a};this.groupRemoving.emit(c);1!=c.cancel&&(this.removeIndex=this.groups?this.groups.indexOf(a):-1,this.dataService.removeAt(a),this.groupRemoved.emit({group:a}))};b.prototype.closeGroups=function(a){this.groupList=
this.contentList.toArray();this.groupList.forEach(function(c,b){c!=a&&(c.selected=!1,c.collapse())})};b.prototype.toggleGroups=function(){var a=this;if(a.selectedComponent)var c=setTimeout(function(){var b=0,h=0,g=0,d=a.selectedComponent.getContentHeight();if(a.selectedComponent.expanded){a.prevComponent&&(b=a.prevComponent.getContentHeight());var f=setInterval(function(){h<d?(g=0==g?1:g+2,h+=g,b-=g,b=0<b?b:0,a.selectedComponent.setContentHeight(h+"px"),a.prevComponent&&a.prevComponent.setContentHeight(b+
"px")):(a.selectedComponent.setContentHeight("auto"),a.prevComponent&&(a.prevComponent.setContentHeight("0"),a.prevComponent.expanded=!1,a.invokeEvent("AFTER_COLLAPSE",a.prevComponent)),a.invokeEvent("AFTER_EXPAND",a.selectedComponent),clearInterval(f))},25)}else a.selectedComponent.setContentHeight("0"),a.prevComponent&&a.prevComponent.setContentHeight("auto");clearInterval(c)},100)};b.prototype.getGroupCurrentIndex=function(a){this.groupList=this.contentList.toArray();return a&&this.groupList?this.groupList.indexOf(a):
-1};b.prototype.getGroupDataIndex=function(a){return a&&(a=this.getGroupCurrentIndex(a),this.groups&&0<=a&&a<this.groups.length)?a:-1};b.prototype.getGroupData=function(a){return this.groups&&0<=a&&a<this.groups.length?this.groups[a]:null};b.prototype.getGroupIndex=function(a){return a&&this.groups?this.groups.indexOf(a):-1};b.prototype.getComponentData=function(a){if(a){if(a.data)return a.data;a=this.getGroupDataIndex(a);if(this.groups&&0<=a&&a<this.groups.length)return this.groups[a]}return null};
b.prototype.invokeEvent=function(a,c,b){var e=!0,g=this.getComponentData(c),d={cancel:!1,group:g};switch(a){case "AFTER_COLLAPSE":this.afterCollapse.emit({group:g});break;case "AFTER_EXPAND":this.afterExpand.emit({group:g});b||this.closeGroups(c);break;case "BEFORE_COLLAPSE":this.beforeCollapse.emit(d);e=!d.cancel;break;case "BEFORE_EXPAND":this.beforeExpand.emit(d),e=!d.cancel}return e};b.prototype.invokeMethod=function(a,c){var b=!0;switch(a){case "SELECT_GROUP":b=this.selectComponent(c)}return b};
b.prototype.isIndexInRange=function(a){this.contentList&&(this.groupList=this.contentList.toArray());return this.groupList?0<=a&&a<this.groupList.length:!1};b.prototype.attachGroupEvents=function(){var a=this;this.groupList=this.contentList.toArray();a.groupEventList&&(a.groupEventList.forEach(function(a){a.forEach(function(a){a.unsubscribe()})}),a.groupEventList.length=0);this.groupList&&0<this.groupList.length&&this.groupList.forEach(function(c){var b=[];b.push(c.beforeSelect.subscribe(function(b){var e=
{cancel:!1,group:a.getComponentData(c)};a.beforeSelect.emit(e);b.cancel=e.cancel}));b.push(c.afterSelect.subscribe(function(b){a.clearSelection(c)}));b.push(c.selectedChanged.subscribe(function(b){c.selected&&a.clearSelection(c)}));a.groupEventList.push(b)})};b.prototype.updateLayout=function(){this.contentElem&&(this.isScrollVisible=this.elemRef.nativeElement.firstElementChild.offsetHeight<this.contentElem.nativeElement.offsetHeight,this.maxScrollPos={x:0,y:this.isScrollVisible?this.elemRef.nativeElement.firstElementChild.offsetHeight-
this.contentElem.nativeElement.offsetHeight-(this.buttonUpElem.nativeElement.offsetHeight+this.buttonDownElem.nativeElement.offsetHeight)-2:0},this.initScrollPos=this.isScrollVisible?this.buttonUpElem.nativeElement.offsetHeight:0,this.isScrollVisible||(this.scrollPos.y=0))};b.prototype.scrollUpPressed=function(){this.isEnabled&&this.startScroll(!1)};b.prototype.scrollUpReleased=function(){this.isEnabled&&this.stopScroll()};b.prototype.scrollDownPressed=function(){this.isEnabled&&this.startScroll(!0)};
b.prototype.scrollDownReleased=function(){this.isEnabled&&this.stopScroll()};b.prototype.startScroll=function(a){var c=this;c.scrollTimer&&clearInterval(c.scrollTimer);c.scrollCount=0;c.isScrollActive=!0;c.scrollTimer=setInterval(function(){c.scrollTimerElapsed(a)},100)};b.prototype.stopScroll=function(){this.scrollTimer&&clearInterval(this.scrollTimer);this.isScrollActive=!1};b.prototype.scrollTimerElapsed=function(a){0==this.scrollCount&&(this.scrollCount=1);this.scrollCount+=5;this.stopScrolling=
!1;this.processScroll(a);this.stopScrolling&&this.stopScroll()};b.prototype.processScroll=function(a){a?this.scrollPos.y-this.scrollCount>this.maxScrollPos.y?this.scrollPos.y-=this.scrollCount:(this.stopScrolling=!0,this.scrollPos.y=this.maxScrollPos.y):0>this.scrollPos.y+this.scrollCount?this.scrollPos.y+=this.scrollCount:(this.stopScrolling=!0,this.scrollPos.y=0)};b.prototype.listMouseWheel=function(a){if(this.isEnabled){a.preventDefault();a=Math.max(-1,Math.min(1,a.wheelDelta||-a.detail));var c=
5;switch(this.mouseWheelSpeed){case integralui_core_1.IntegralUISpeedMode.VerySlow:c=15;break;case integralui_core_1.IntegralUISpeedMode.Slow:c=9;break;case integralui_core_1.IntegralUISpeedMode.Fast:c=3;break;case integralui_core_1.IntegralUISpeedMode.VeryFast:c=1}this.setScrollPos({x:0,y:this.scrollPos.y-Math.floor(this.clientRect.height/c)*a*-1})}};b.prototype.setScrollPos=function(a){a.y<this.maxScrollPos.y&&(a.y=this.maxScrollPos.y);0<a.y&&(a.y=0);this.scrollPos={x:0,y:a.y}};b.prototype.clearSelection=
function(a){this.groupList=this.contentList.toArray();this.groupList.forEach(function(c,b){c!=a&&(c.selected=!1,c.clearSelection())})};b.prototype.selectComponent=function(a){var c=this.getComponentData(a),b={cancel:!1,group:c};this.beforeSelect.emit(b);return 1!=b.cancel&&a&&a!=this.selectedComponent?(this.currentSelectedIndex=b=this.getGroupCurrentIndex(a),this.groups&&0<=b&&b<this.groups.length&&(this.currentSelection=this.groups[b]),this.prevComponent=this.selectedComponent,this.selectedComponent=
a,this.clearSelection(a),a.selected=!0,a.expanded=!0,this.afterSelect.emit({group:c}),this.selectionChanged.emit({index:b,group:this.getGroupData(this.getGroupDataIndex(a))}),!0):!1};b.prototype.selectComponentByIndex=function(a){this.isIndexInRange(a)&&this.selectComponent(this.groupList[a])};b.prototype.selectGroup=function(a){this.groups&&(this.currentSelectedIndex=this.groups.indexOf(a),this.selectComponentByIndex(this.currentSelectedIndex))};b.prototype.getControlStyle=function(){var a={};0<
this.ctrlSize.width&&(a.width=this.ctrlSize.width+"px");0<this.ctrlSize.height&&(a.height=this.ctrlSize.height+"px");return a};b.\u0275fac=function(a){return new (a||b)(i0.\u0275\u0275directiveInject(i0.ElementRef),i0.\u0275\u0275directiveInject(i1.IntegralUIDataService),i0.\u0275\u0275directiveInject(i2.IntegralUICommonService),i0.\u0275\u0275directiveInject(i0.ComponentFactoryResolver),i0.\u0275\u0275directiveInject(i3.IntegralUIBaseService))};b.\u0275cmp=i0.\u0275\u0275defineComponent({type:b,
selectors:[["iui-listbar"]],contentQueries:function(a,b,e){a&1&&i0.\u0275\u0275contentQuery(e,integralui_listgroup_1.IntegralUIListGroup,!0);if(a&2){var c;i0.\u0275\u0275queryRefresh(c=i0.\u0275\u0275loadQuery())&&(b.contentList=c)}},viewQuery:function(a,b){a&1&&(i0.\u0275\u0275viewQuery(_c0,!0,core_1.ElementRef),i0.\u0275\u0275viewQuery(_c1,!0,core_1.ElementRef),i0.\u0275\u0275viewQuery(_c2,!0,core_1.ViewContainerRef),i0.\u0275\u0275viewQuery(_c2,!0,core_1.ElementRef));if(a&2){var c;i0.\u0275\u0275queryRefresh(c=
i0.\u0275\u0275loadQuery())&&(b.buttonUpElem=c.first);i0.\u0275\u0275queryRefresh(c=i0.\u0275\u0275loadQuery())&&(b.buttonDownElem=c.first);i0.\u0275\u0275queryRefresh(c=i0.\u0275\u0275loadQuery())&&(b.contentRef=c.first);i0.\u0275\u0275queryRefresh(c=i0.\u0275\u0275loadQuery())&&(b.contentElem=c.first)}},inputs:{controlStyle:"controlStyle",data:"data",enabled:"enabled",name:"name",size:"size",state:"state",groups:"groups",mouseWheelSpeed:"mouseWheelSpeed",selectedIndex:"selectedIndex",selectedGroup:"selectedGroup"},
outputs:{afterCollapse:"afterCollapse",afterExpand:"afterExpand",afterSelect:"afterSelect",beforeCollapse:"beforeCollapse",beforeExpand:"beforeExpand",beforeSelect:"beforeSelect",groupAdding:"groupAdding",groupAdded:"groupAdded",clear:"clear",groupRemoving:"groupRemoving",groupRemoved:"groupRemoved",selectionChanged:"selectionChanged"},features:[i0.\u0275\u0275ProvidersFeature([integralui_core_1.IntegralUIBaseService,integralui_data_service_1.IntegralUIDataService]),i0.\u0275\u0275InheritDefinitionFeature],
ngContentSelectors:_c6,decls:10,vars:17,consts:[[3,"ngClass","ngStyle","DOMMouseScroll","mousewheel"],[1,"iui-listbar-button-up",3,"ngStyle","mousedown","mouseup"],["buttonUp",""],[1,"iui-listbar-button-up-icon",3,"ngStyle"],[1,"iui-listbar-content",3,"ngStyle"],["content",""],[1,"iui-listbar-button-down",3,"ngStyle","mousedown","mouseup"],["buttonDown",""],[1,"iui-listbar-button-down-icon",3,"ngStyle"]],template:function(a,b){a&1&&(i0.\u0275\u0275projectionDef(),i0.\u0275\u0275elementStart(0,"div",
0),i0.\u0275\u0275listener("DOMMouseScroll",function(a){return b.listMouseWheel(a)})("mousewheel",function(a){return b.listMouseWheel(a)}),i0.\u0275\u0275elementStart(1,"div",1,2),i0.\u0275\u0275listener("mousedown",function(){return b.scrollUpPressed()})("mouseup",function(){return b.scrollUpReleased()}),i0.\u0275\u0275element(3,"span",3),i0.\u0275\u0275elementEnd(),i0.\u0275\u0275elementStart(4,"div",4,5),i0.\u0275\u0275projection(6),i0.\u0275\u0275elementEnd(),i0.\u0275\u0275elementStart(7,"div",
6,7),i0.\u0275\u0275listener("mousedown",function(){return b.scrollDownPressed()})("mouseup",function(){return b.scrollDownReleased()}),i0.\u0275\u0275element(9,"span",8),i0.\u0275\u0275elementEnd(),i0.\u0275\u0275elementEnd());a&2&&(i0.\u0275\u0275property("ngClass",b.getControlClass())("ngStyle",b.getControlStyle()),i0.\u0275\u0275advance(1),i0.\u0275\u0275property("ngStyle",i0.\u0275\u0275pureFunction1(7,_c3,b.isScrollVisible?"block":"none")),i0.\u0275\u0275advance(2),i0.\u0275\u0275property("ngStyle",
i0.\u0275\u0275pureFunction1(9,_c4,0!=b.scrollPos.y?"inline-block":"none")),i0.\u0275\u0275advance(1),i0.\u0275\u0275property("ngStyle",i0.\u0275\u0275pureFunction1(11,_c5,b.scrollPos.y+b.initScrollPos-1+"px")),i0.\u0275\u0275advance(3),i0.\u0275\u0275property("ngStyle",i0.\u0275\u0275pureFunction1(13,_c3,b.isScrollVisible?"block":"none")),i0.\u0275\u0275advance(2),i0.\u0275\u0275property("ngStyle",i0.\u0275\u0275pureFunction1(15,_c4,b.scrollPos.y!=b.maxScrollPos.y?"inline-block":"none")))},directives:[i4.NgClass,
i4.NgStyle],encapsulation:2});return b}(integralui_core_1.IntegralUIBaseComponent);exports.IntegralUIListBar=IntegralUIListBar;
(function(){i0.\u0275setClassMetadata(IntegralUIListBar,[{type:core_1.Component,args:[{selector:"iui-listbar",template:'\n\t\t<div [ngClass]="getControlClass()" [ngStyle]="getControlStyle()" (DOMMouseScroll)="listMouseWheel($event)" (mousewheel)="listMouseWheel($event)">\n\t\t\t<div class="iui-listbar-button-up" [ngStyle]="{ display: isScrollVisible ? \'block\' : \'none\' }" (mousedown)="scrollUpPressed()" (mouseup)="scrollUpReleased()" #buttonUp>\n\t\t\t\t<span class="iui-listbar-button-up-icon" [ngStyle]="{ \'display\': scrollPos.y != 0 ? \'inline-block\' : \'none\' }"></span>\n\t\t\t</div>\n\t\t\t<div class="iui-listbar-content" [ngStyle]="{ \'margin-top\': scrollPos.y + initScrollPos - 1 + \'px\' }" #content>\n\t\t\t\t<ng-content></ng-content>\n\t\t\t</div>\n\t\t\t<div class="iui-listbar-button-down" [ngStyle]="{ display: isScrollVisible ? \'block\' : \'none\' }" (mousedown)="scrollDownPressed()" (mouseup)="scrollDownReleased()" #buttonDown>\n\t\t\t\t<span class="iui-listbar-button-down-icon" [ngStyle]="{ \'display\': scrollPos.y != maxScrollPos.y ? \'inline-block\' : \'none\' }"></span>\n\t\t\t</div>\n\t\t</div>\n\t',providers:[integralui_core_1.IntegralUIBaseService,
integralui_data_service_1.IntegralUIDataService],inputs:"controlStyle data enabled name size state".split(" "),encapsulation:core_1.ViewEncapsulation.None}]}],function(){return[{type:i0.ElementRef},{type:i1.IntegralUIDataService},{type:i2.IntegralUICommonService},{type:i0.ComponentFactoryResolver},{type:i3.IntegralUIBaseService}]},{buttonUpElem:[{type:core_1.ViewChild,args:["buttonUp",{read:core_1.ElementRef,"static":!1}]}],buttonDownElem:[{type:core_1.ViewChild,args:["buttonDown",{read:core_1.ElementRef,
"static":!1}]}],contentRef:[{type:core_1.ViewChild,args:["content",{read:core_1.ViewContainerRef,"static":!1}]}],contentElem:[{type:core_1.ViewChild,args:["content",{read:core_1.ElementRef,"static":!1}]}],contentList:[{type:core_1.ContentChildren,args:[integralui_listgroup_1.IntegralUIListGroup,{descendants:!0}]}],groups:[{type:core_1.Input}],mouseWheelSpeed:[{type:core_1.Input}],selectedIndex:[{type:core_1.Input}],selectedGroup:[{type:core_1.Input}],afterCollapse:[{type:core_1.Output}],afterExpand:[{type:core_1.Output}],
afterSelect:[{type:core_1.Output}],beforeCollapse:[{type:core_1.Output}],beforeExpand:[{type:core_1.Output}],beforeSelect:[{type:core_1.Output}],groupAdding:[{type:core_1.Output}],groupAdded:[{type:core_1.Output}],clear:[{type:core_1.Output}],groupRemoving:[{type:core_1.Output}],groupRemoved:[{type:core_1.Output}],selectionChanged:[{type:core_1.Output}]})})();