/*
  filename: integralui.button.js
  version : 1.2.0
  Copyright © 2016-2019 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(){var e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d])};return function(b,a){function d(){this.constructor=b}e(b,a);b.prototype=null===a?Object.create(a):(d.prototype=a.prototype,new d)}}();Object.defineProperty(exports,"__esModule",{value:!0});
var core_1=require("@angular/core"),animations_1=require("@angular/animations"),integralui_core_1=require("./integralui.core"),integralui_common_service_1=require("../services/integralui.common.service"),IntegralUIButton=function(e){function b(a,b){var c=e.call(this,b)||this;c.elemRef=a;c.commonService=b;c.animationState="out";c.pressedValue=!1;c.contentClass=[];c.clientRect={width:0,height:0};c.pressedChanged=new core_1.EventEmitter;return c}__extends(b,e);Object.defineProperty(b.prototype,"pressed",
{get:function(){return this.pressedValue},set:function(a){this.pressedValue!=a&&(this.state=(this.pressedValue=a)?this.state|integralui_core_1.IntegralUIObjectState.selected:this.state&~integralui_core_1.IntegralUIObjectState.selected,this.refresh(),this.pressedChanged.emit({pressed:this.pressedValue}))},enumerable:!0,configurable:!0});b.prototype.ngOnInit=function(){this.generalClassName="iui-button";this.contentClassName=this.generalClassName+"-content";this.initStyle()};b.prototype.initStyle=function(){this.defaultStyle=
{general:{disabled:this.generalClassName+"-disabled",focused:this.generalClassName+"-focused",normal:this.generalClassName,hovered:this.generalClassName+"-hovered",selected:this.generalClassName+"-selected"},content:{disabled:this.contentClassName+"-disabled",focused:this.contentClassName+"-focused",normal:this.contentClassName,hovered:this.contentClassName+"-hovered",selected:this.contentClassName+"-selected"}};this.updateStyle(this.controlStyle);this.refresh()};b.prototype.refresh=function(){this.updateControlClass();
this.updateContentClass()};b.prototype.ctrlMouseEnter=function(a){this.state|=integralui_core_1.IntegralUIObjectState.hovered;this.animationState="in"};b.prototype.ctrlMouseLeave=function(a){this.state&=~integralui_core_1.IntegralUIObjectState.hovered;this.animationState="out"};b.prototype.getControlStyle=function(){var a={};0<this.ctrlSize.width&&(a.width=this.ctrlSize.width+"px");0<this.ctrlSize.height&&(a.height=this.ctrlSize.height+"px");return a};b.prototype.updateContentClass=function(){this.contentClass.length=
0;this.contentClass.push(this.contentClassName);this.options.currentStyle&&(this.contentClass.push(this.options.currentStyle.content.normal),this.state&integralui_core_1.IntegralUIObjectState.disabled?this.contentClass.push(this.options.currentStyle.content.disabled):this.state&integralui_core_1.IntegralUIObjectState.focused?this.contentClass.push(this.options.currentStyle.content.focused):this.state&integralui_core_1.IntegralUIObjectState.selected?this.contentClass.push(this.options.currentStyle.content.selected):
this.state&integralui_core_1.IntegralUIObjectState.hovered&&this.contentClass.push(this.options.currentStyle.content.hovered))};b.prototype.getContentClass=function(){return this.contentClass};b.prototype.getContentStyle=function(a){return this.commonService.isString(a)?a:a?{disabled:this.commonService.isFieldAvailable(a.disabled,this.contentClassName+"-disabled"),focused:this.commonService.isFieldAvailable(a.focused,this.contentClassName+"-focused"),hovered:this.commonService.isFieldAvailable(a.hovered,
this.contentClassName+"-hovered"),normal:this.commonService.isFieldAvailable(a.normal,this.contentClassName),selected:this.commonService.isFieldAvailable(a.selected,this.contentClassName+"-selected")}:{disabled:this.defaultStyle.content.disabled,focused:this.defaultStyle.content.focused,hovered:this.defaultStyle.content.hovered,normal:this.defaultStyle.content.normal,selected:this.defaultStyle.content.selected}};b.prototype.updateStyle=function(a){this.options.currentStyle=a?{general:this.getGeneralStyle(a.general),
content:this.getContentStyle(a.button)}:{general:{disabled:this.defaultStyle.general.disabled,focused:this.defaultStyle.general.focused,hovered:this.defaultStyle.general.hovered,normal:this.defaultStyle.general.normal,selected:this.defaultStyle.general.selected},content:{disabled:this.defaultStyle.content.disabled,focused:this.defaultStyle.content.focused,hovered:this.defaultStyle.content.hovered,normal:this.defaultStyle.content.normal,selected:this.defaultStyle.content.selected}}};b.decorators=[{type:core_1.Component,
args:[{selector:"iui-button",template:'\n\t\t<div [ngClass]="getControlClass()" [ngStyle]="getControlStyle()" (mouseenter)="ctrlMouseEnter($event)" (mouseleave)="ctrlMouseLeave($event)" [@ctrlAnimation]="allowAnimation && animationState">\n\t\t\t<div [ngClass]="getContentClass()">\n\t\t\t\t<ng-content></ng-content>\n\t\t\t</div>\n\t\t</div>\n\t',inputs:"controlStyle data enabled name size state".split(" "),animations:[animations_1.trigger("ctrlAnimation",[animations_1.state("out",animations_1.style({transform:"scale(1)",
zIndex:"0"})),animations_1.state("in",animations_1.style({transform:"scale(1.05)",zIndex:"2"})),animations_1.transition("out => in",animations_1.animate("125ms ease-in")),animations_1.transition("in => out",animations_1.animate("125ms ease-out"))])],encapsulation:core_1.ViewEncapsulation.None}]}];b.ctorParameters=function(){return[{type:core_1.ElementRef},{type:integralui_common_service_1.IntegralUICommonService}]};b.propDecorators={pressed:[{type:core_1.Input}],pressedChanged:[{type:core_1.Output}]};
return b}(integralui_core_1.IntegralUIBaseComponent);exports.IntegralUIButton=IntegralUIButton;