import { ComponentFactoryResolver, ElementRef, EventEmitter, QueryList, ViewContainerRef } from '@angular/core';
import { IntegralUIBaseComponent } from './integralui.core';
import { IntegralUICommonService } from '../services/integralui.common.service';
import { IntegralUIDataService } from '../services/integralui.data.service';
export declare class IntegralUISlide {
    private elemRef;
    constructor(elemRef: ElementRef);
    size(): {
        width: number;
        height: number;
    };
    cloneElem(): any;
}
export declare class IntegralUISlideBar extends IntegralUIBaseComponent {
    protected dataService: IntegralUIDataService;
    protected commonService: IntegralUICommonService;
    protected cmpResolver: ComponentFactoryResolver;
    controlRef: ViewContainerRef;
    blockRef: ViewContainerRef;
    private animationTimeout;
    private animationTimer;
    buttons: Array<any>;
    arrowTopPos: number;
    arrowDisplay: string;
    private numSlides;
    private cloneAdded;
    private cloneElem;
    private slideList;
    contentSlideList: QueryList<IntegralUISlide>;
    blockElem: ElementRef;
    arrowElem: ElementRef;
    blockMargin: number;
    elemSize: any;
    blockSize: any;
    private slideSize;
    private currentSelection;
    private currentSelectedIndex;
    private selectedSlideComponent;
    private removeIndex;
    private trialRef;
    allowAnimation: boolean;
    animationPause: number;
    animationSpeed: string;
    slides: Array<any>;
    selectedIndex: number;
    selectedSlide: any;
    clear: EventEmitter<any>;
    slideAdding: EventEmitter<any>;
    slideAdded: EventEmitter<any>;
    slideChanged: EventEmitter<any>;
    slideRemoving: EventEmitter<any>;
    slideRemoved: EventEmitter<any>;
    constructor(dataService: IntegralUIDataService, commonService?: IntegralUICommonService, cmpResolver?: ComponentFactoryResolver);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngAfterContentInit(): void;
    ngOnDestroy(): void;
    ngAfterContentChecked(): void;
    private checkClone();
    clearSlides(): void;
    addSlide(slide: any): void;
    insertSlideAt(slide: any, index: number): void;
    insertSlideBefore(slide: any, refSlide: any): void;
    insertSlideAfter(slide: any, refSlide: any): void;
    removeSlide(slide: any): void;
    removeSlideAt(index: number): void;
    private callEventAdd(type, slide, index?, refSlide?, flag?);
    private callEventRemove(slide);
    getButtonClass(button: any): "" | "iui-slidebar-navigator-button-selected";
    private getSlideCurrentIndex(cmp);
    private getSlideDataIndex(cmp);
    private getSlideData(index);
    private isIndexInRange(index);
    ctrlMouseEnter(e: any): void;
    ctrlMouseLeave(e: any): void;
    prevSlide(): void;
    nextSlide(): void;
    protected updateLayout(): void;
    private cancelAnimation();
    private changeSlide();
    private getSpeedFactor();
    private startAnimation();
    private stopAnimation();
    private selectSlide(cmp);
    selectSlideByIndex(index: number): void;
}
