/*
  filename: integralui.rating.js
  version : 1.2.0
  Copyright © 2016-2018 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(){var d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(b,a){b.__proto__=a}||function(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])};return function(b,a){function c(){this.constructor=b}d(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}();Object.defineProperty(exports,"__esModule",{value:!0});
var core_1=require("@angular/core"),integralui_core_1=require("./integralui.core"),integralui_common_service_1=require("../services/integralui.common.service"),forms_1=require("@angular/forms"),IntegralUIRating=function(d){function b(a,b){var c=d.call(this,a,b)||this;c.elemRef=a;c.commonService=b;c.ctrlMaxValue=5;c.currentDivision=1;c.currentStepSize=16;c.currentIncrement=integralui_core_1.IntegralUIIncrementMode.Free;c.isRatingChangeActive=!1;c.contentSize={width:0,height:0};c.ratingSize={width:0,
height:0};c.ratingClass=[];return c}__extends(b,d);Object.defineProperty(b.prototype,"division",{get:function(){return this.currentDivision},set:function(a){void 0!=a&&1<=a&&(a=Math.floor(a),this.currentDivision!=a&&(this.currentDivision=a))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"value",{get:function(){return this.currentValue},set:function(a){var b=Math.floor(a);switch(this.currentIncrement){case integralui_core_1.IntegralUIIncrementMode.Partial:a=a>b+.25?b+.5:a>b+.75?
b+1:b;break;case integralui_core_1.IntegralUIIncrementMode.Full:a=a>b+.5?a=b+1:b}a=Math.max(0,Math.min(this.ctrlMaxValue*this.currentDivision,a));a!==this.currentValue&&a<=this.ctrlMaxValue*this.currentDivision&&(this.currentValue=a,this.onChange(a),this.processValueChange(),this.valueChanged.emit({value:this.currentValue}))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"increment",{get:function(){return this.currentIncrement},set:function(a){this.currentIncrement!=a&&(this.currentIncrement=
a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"max",{get:function(){return this.ctrlMaxValue},set:function(a){void 0!=a&&(a=Math.floor(a),this.ctrlMaxValue!=a&&(this.ctrlMaxValue=a,this.updateLayout()))},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"stepSize",{get:function(){return this.currentStepSize},set:function(a){void 0!=a&&(a=Math.floor(a),this.currentStepSize!=a&&1<=a&&(this.currentStepSize=a,this.updateLayout()))},enumerable:!0,configurable:!0});
b.prototype.ngOnInit=function(){this.generalClassName="iui-rating";this.contentClassName=this.generalClassName+"-content";this.ratingClassName=this.generalClassName+"-value";this.initStyle()};b.prototype.ngAfterViewInit=function(){this.updateLayout()};b.prototype.initStyle=function(){this.defaultStyle={general:{disabled:this.generalClassName+"-disabled",focused:this.generalClassName+"-focused",normal:this.generalClassName,hovered:this.generalClassName+"-hovered",selected:this.generalClassName+"-selected"},
content:{disabled:this.contentClassName+"-disabled",focused:this.contentClassName+"-focused",normal:this.contentClassName,hovered:this.contentClassName+"-hovered",selected:this.contentClassName+"-selected"},rating:{disabled:this.ratingClassName+"-disabled",focused:this.ratingClassName+"-focused",normal:this.ratingClassName,hovered:this.ratingClassName+"-hovered",selected:this.ratingClassName+"-selected"}};this.updateStyle(this.controlStyle);this.updateControlClass();this.updateContentClass();this.updateRatingClass()};
b.prototype.ngAfterContentChecked=function(){1==this.autoUpdate&&(this.clientRect={width:this.elemRef.nativeElement.firstElementChild.clientWidth,height:this.elemRef.nativeElement.firstElementChild.clientHeight},this.clientRect.width!=this.prevClientRect.width?(this.updateLayout(),this.prevClientRect.width=this.clientRect.width):this.clientRect.height!=this.prevClientRect.height&&(this.updateLayout(),this.prevClientRect.height=this.clientRect.height))};b.prototype.getContentWidth=function(){return this.contentSize.width};
b.prototype.getRatingWidth=function(){return this.ratingSize.width};b.prototype.processValueChange=function(){this.updateLayout()};b.prototype.updateLayout=function(){var a=this.commonService.getPadding(this.elemRef.nativeElement.firstElementChild);this.clientRect={width:this.elemRef.nativeElement.firstElementChild.clientWidth-(a.left+a.right),height:this.elemRef.nativeElement.firstElementChild.clientHeight-(a.top+a.bottom)};this.contentSize={width:this.ctrlMaxValue*this.currentStepSize,height:this.clientRect.height};
this.ratingSize={width:this.currentValue<this.ctrlMaxValue*this.currentDivision?this.currentValue*this.currentStepSize/this.currentDivision:this.contentSize.width,height:this.clientRect.height}};b.prototype.ctrlMouseDown=function(a){this.isEnabled&&1==a.which&&(this.isRatingChangeActive=!0,this.value=a.offsetX*this.currentDivision/this.currentStepSize,this.updateLayout(),a.stopPropagation())};b.prototype.ctrlMouseMove=function(a){this.isEnabled&&1==a.which&&this.isRatingChangeActive&&(this.value=
a.offsetX*this.currentDivision/this.currentStepSize,this.updateLayout(),a.stopPropagation())};b.prototype.ctrlMouseUp=function(a){this.isRatingChangeActive=!1};b.prototype.ctrlMouseWheel=function(a){this.isEnabled&&(a.preventDefault(),this.value+=-1*Math.max(-1,Math.min(1,a.wheelDelta||-a.detail)),a.stopPropagation())};b.prototype.ctrlTouchEnd=function(a){if(this.isEnabled){var b=this.commonService.getTouchData(a);if(b&&0<b.length){var d=this.commonService.getPageRect(this.elemRef.nativeElement),
e=this.commonService.getShiftPos();this.value=(b[0].pageX-d.left-e.x)*this.currentDivision/this.currentStepSize;this.updateLayout();a.stopPropagation()}}};b.prototype.onWindowMouseUp=function(a){this.isRatingChangeActive=!1};b.prototype.getControlStyle=function(){var a={width:this.getContentWidth()+"px"};0<this.ctrlSize.width&&(a.width=this.ctrlSize.width+"px");0<this.ctrlSize.height&&(a.height=this.ctrlSize.height+"px");return a};b.prototype.getRatingValueClass=function(){return this.ratingClass};
b.prototype.updateRatingClass=function(){this.ratingClass.length=0;this.ratingClass.push(this.ratingClassName);this.options.currentStyle&&(this.ratingClass.push(this.options.currentStyle.rating.normal),this.state&integralui_core_1.IntegralUIObjectState.disabled?this.ratingClass.push(this.options.currentStyle.rating.disabled):this.state&integralui_core_1.IntegralUIObjectState.focused?this.ratingClass.push(this.options.currentStyle.rating.focused):this.state&integralui_core_1.IntegralUIObjectState.selected?
this.ratingClass.push(this.options.currentStyle.rating.selected):this.state&integralui_core_1.IntegralUIObjectState.hovered&&this.ratingClass.push(this.options.currentStyle.rating.hovered))};b.prototype.getRatingStyle=function(a){return this.commonService.isString(a)?a:a?{disabled:this.commonService.isFieldAvailable(a.disabled,this.ratingClassName+"-disabled"),focused:this.commonService.isFieldAvailable(a.focused,this.ratingClassName+"-focused"),hovered:this.commonService.isFieldAvailable(a.hovered,
this.ratingClassName+"-hovered"),normal:this.commonService.isFieldAvailable(a.normal,this.ratingClassName),selected:this.commonService.isFieldAvailable(a.selected,this.ratingClassName+"-selected")}:{disabled:this.defaultStyle.rating.disabled,focused:this.defaultStyle.rating.focused,hovered:this.defaultStyle.rating.hovered,normal:this.defaultStyle.rating.normal,selected:this.defaultStyle.rating.selected}};b.prototype.updateStyle=function(a){this.options.currentStyle=a?{general:this.getGeneralStyle(a.general),
content:this.getContentStyle(a.content),rating:this.getRatingStyle(a.rating)}:{general:{disabled:this.defaultStyle.general.disabled,focused:this.defaultStyle.general.focused,hovered:this.defaultStyle.general.hovered,normal:this.defaultStyle.general.normal,selected:this.defaultStyle.general.selected},content:{disabled:this.defaultStyle.content.disabled,focused:this.defaultStyle.content.focused,hovered:this.defaultStyle.content.hovered,normal:this.defaultStyle.content.normal,selected:this.defaultStyle.content.selected},
rating:{disabled:this.defaultStyle.rating.disabled,focused:this.defaultStyle.rating.focused,hovered:this.defaultStyle.rating.hovered,normal:this.defaultStyle.rating.normal,selected:this.defaultStyle.rating.selected}}};b.decorators=[{type:core_1.Component,args:[{selector:"iui-rating",template:'\n\t\t<div [ngClass]="getControlClass()" [ngStyle]="getControlStyle()" draggable="true" (dragstart)="preventDragStart($event)" (mousedown)="ctrlMouseDown($event)" (mousemove)="ctrlMouseMove($event)" (mouseup)="ctrlMouseUp($event)" (DOMMouseScroll)="ctrlMouseWheel($event)" (mousewheel)="ctrlMouseWheel($event)" (touchend)="ctrlTouchEnd($event)">\n\t\t\t<div [ngClass]="getContentClass()" style="position:absolute" [ngStyle]="{ width: getContentWidth() + \'px\' }"></div>\n\t\t\t<div [ngClass]="getRatingValueClass()" style="position:absolute" [ngStyle]="{ width: getRatingWidth() + \'px\' }"></div>\n\t\t</div>\n\t',
inputs:"autoUpdate controlStyle data enabled name size state value".split(" "),outputs:["valueChanged"],providers:[{provide:forms_1.NG_VALUE_ACCESSOR,useExisting:core_1.forwardRef(function(){return b}),multi:!0}],encapsulation:core_1.ViewEncapsulation.None}]}];b.ctorParameters=function(){return[{type:core_1.ElementRef},{type:integralui_common_service_1.IntegralUICommonService}]};b.propDecorators={division:[{type:core_1.Input}],increment:[{type:core_1.Input}],max:[{type:core_1.Input}],stepSize:[{type:core_1.Input}],
onWindowMouseUp:[{type:core_1.HostListener,args:["document:mouseup",["$event"]]}]};return b}(integralui_core_1.IntegralUIBaseValueComponent);exports.IntegralUIRating=IntegralUIRating;