/*
  filename: integralui.base.grid.js
  version : 3.0.215
  Copyright © 2016-2019 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(){var l=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(c,a){c.__proto__=a}||function(c,a){for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b])};return function(c,a){function b(){this.constructor=c}l(c,a);c.prototype=null===a?Object.create(a):(b.prototype=a.prototype,new b)}}();Object.defineProperty(exports,"__esModule",{value:!0});
var core_1=require("@angular/core"),integralui_core_1=require("./integralui.core"),integralui_common_service_1=require("../services/integralui.common.service"),integralui_data_service_1=require("../services/integralui.data.service"),integralui_dragdrop_service_1=require("../services/integralui.dragdrop.service"),integralui_filter_service_1=require("../services/integralui.filter.service"),integralui_datepicker_1=require("./integralui.datepicker"),IntegralUIGridLines;
(function(l){l[l.None=0]="None";l[l.Horizontal=1]="Horizontal";l[l.Vertical=2]="Vertical";l[l.Both=3]="Both"})(IntegralUIGridLines=exports.IntegralUIGridLines||(exports.IntegralUIGridLines={}));
var IntegralUIBaseGrid=function(l){function c(a,b,e,c,h,f,g,k){var d=l.call(this,h)||this;d.dataService=a;d.dragDropService=b;d.elemRef=e;d.elemRenderer=c;d.commonService=h;d.filterService=f;d.changeRef=g;d.cmpResolver=k;d.dragGhost=null;d.emptyRowObj={cells:[],draggable:!1,isEmpty:!0,status:1,style:{}};d.dragMode=integralui_core_1.IntegralUIDragDropDisplayMode.Popup;d.animateColumnSize={width:0,height:0};d.animateRowSize={width:0,height:0};d.prevClickedObj=null;d.currentColumnList=[];d.currentRowList=
[];d.dataColumns=[];d.dataRows=[];d.options={};d.scrollColumnList=[];d.scrollRowList=[];d.columnDataKey="columns";d.rowDataKey="rows";d.dropMarkElem=null;d.dragCmpRef=null;d.dragCmp=null;d.cloneElem=null;d.cloneElemStartPos={x:0,y:0};d.isCtrlDragEntered=!1;d.isFirstDragEnter=!1;d.isDragHandleVisible=!1;d.dragRowList=[];d.targetDropRow=null;d.targetDropPos=-1;d.prevTargetDropPos=-1;d.dragHandlePos={top:-9999999,left:0};d.dragHandleShiftPos={x:0,y:0};d.dragObjIndent=0;d.isDragActive=!1;d.dragStartPos=
{x:0,y:0};d.dragEndPos={x:0,y:0};d.dropListRef=null;d.dropList=null;d.calendarRef=null;d.calendar=null;d.currentEditorCell=null;d.isPopupDelayed=!1;d.isEditorFocused=!1;d.originalEditorText="";d.originalEditorValue=null;d.expandColIndex=0;d.hoverCell=null;d.hoverColumn=null;d.hoverRow=null;d.isGridHovered=!1;d.currentIndex=0;d.prevIndex=0;d.tabIndexCount=0;d.ctrlCursor="default";d.columnStartPos={x:0,y:0};d.resizeColumn=null;d.resizeColumnIndex=-1;d.reorderColumn=null;d.columnReorderActive=!1;d.currentFocusCell=
null;d.isKeyboardActive=!1;d.allowUpdate=!0;d.avgRowHeight=0;d.columnPadding={top:0,right:0,bottom:0,left:0};d.currentGridLines=IntegralUIGridLines.Both;d.headerHeight=0;d.footerHeight=0;d.isExpandBoxVisible=!0;d.isLayoutUpdating=!1;d.viewIndexRange={left:0,middle:999,right:999};d.visibleRange=1;d.isAutoSizeColumnsActive=!1;d.isHeaderVisible=!0;d.isFooterVisible=!0;d.scrollSize={width:0,height:0};d.contentLeftPos=0;d.allColWidth=0;d.horScrollElemPos={bottom:0};d.cornerScrollElemPos={bottom:0};d.paginatorPos=
{top:0,left:0};d.currentPageNumber=1;d.onlyCurrentPage=!1;d.currentPageList=[];d.pageNumber=0;d.pageList=[];d.pageRowCount=0;d.paginatorHeight=0;d.originalScrollColumnList=[];d.reorderColumnObj=null;d.reorderColumnObjPos={top:0,left:0};d.reorderColumnStartPos={top:0,left:0};d.reorderColumnCurrentPos={top:0,left:0};d.reorderColIndex=-1;d.reorderNewColIndex=-1;d.startColumnReorder=!1;d.isColumnResizing=!1;d.currentScrollPos={x:0,y:0};d.isKeyPressed=!1;d.maxScrollPos={x:0,y:0};d.accelerator=.5;d.scrollTimerID=
null;d.isScrollTimerActive=!1;d.scrollCount=0;d.isScrollActive=!1;d.prevScrollPos={x:0,y:0};d.scrollBarSize={width:0,height:0};d.scrollLargeChange={x:0,y:0};d.currentSelectedColumn=null;d.currentSelectedRow=null;d.currentSelectionMode=integralui_core_1.IntegralUISelectionMode.One;d.shiftFirstSelectedRow=null;d.removeIndex=-1;d.currentSelectedRows=[];d.isExpandBoxTouched=!1;d.touchStartPos={x:0,y:0};d.touchEndPos={x:0,y:0};d.rowHeight=0;d.mouseWheelSpeed=integralui_core_1.IntegralUISpeedMode.Normal;
d.afterSelect=new core_1.EventEmitter;d.beforeEdit=new core_1.EventEmitter;d.beforeSelect=new core_1.EventEmitter;d.beforeUpdate=new core_1.EventEmitter;d.cellClick=new core_1.EventEmitter;d.cellDblClick=new core_1.EventEmitter;d.cellHover=new core_1.EventEmitter;d.cellRightClick=new core_1.EventEmitter;d.cellValueChanging=new core_1.EventEmitter;d.cellValueChanged=new core_1.EventEmitter;d.change=new core_1.EventEmitter;d.columnAdding=new core_1.EventEmitter;d.columnAdded=new core_1.EventEmitter;
d.columnClick=new core_1.EventEmitter;d.columnDblClick=new core_1.EventEmitter;d.columnHover=new core_1.EventEmitter;d.columnRightClick=new core_1.EventEmitter;d.columnOrderChanged=new core_1.EventEmitter;d.columnRemoving=new core_1.EventEmitter;d.columnRemoved=new core_1.EventEmitter;d.columnsCleared=new core_1.EventEmitter;d.columnSizeChanged=new core_1.EventEmitter;d.dragEnd=new core_1.EventEmitter;d.dragEnter=new core_1.EventEmitter;d.dragDrop=new core_1.EventEmitter;d.dragDropComplete=new core_1.EventEmitter;
d.dragLeave=new core_1.EventEmitter;d.dragOver=new core_1.EventEmitter;d.dragStart=new core_1.EventEmitter;d.keyDown=new core_1.EventEmitter;d.keyPress=new core_1.EventEmitter;d.keyUp=new core_1.EventEmitter;d.pageChanged=new core_1.EventEmitter;d.rowAdding=new core_1.EventEmitter;d.rowAdded=new core_1.EventEmitter;d.rowClick=new core_1.EventEmitter;d.rowDblClick=new core_1.EventEmitter;d.rowHover=new core_1.EventEmitter;d.rowRemoving=new core_1.EventEmitter;d.rowRemoved=new core_1.EventEmitter;d.rowRightClick=
new core_1.EventEmitter;d.rowsCleared=new core_1.EventEmitter;d.loadComplete=new core_1.EventEmitter;d.scrollPosChanged=new core_1.EventEmitter;d.selectionChanged=new core_1.EventEmitter;d.updateComplete=new core_1.EventEmitter;d.sortColumn=null;d.sortComparer=null;d.updateOptions();return d}__extends(c,l);c.prototype.getEmptyObj=function(a){for(var b=null,e=0;e<this.scrollRowList.length;e++)if(this.scrollRowList[e].status==a){b=this.scrollRowList[e];break}return b};c.prototype.removeEmptyRow=function(a){if(a=
this.getEmptyObj(a))a=this.scrollRowList.indexOf(a),0<=a&&this.scrollRowList.splice(a,1)};c.prototype.updateDragHandlePos=function(a){};c.prototype.updateScrollRowListDragOver=function(a){};Object.defineProperty(c.prototype,"allowColumnReorder",{set:function(a){this.options.allowColumnReorder=a},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"allowDrag",{set:function(a){this.options.allowDrag=a},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"allowDrop",{set:function(a){this.options.allowDrop=
a},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"allowFilter",{set:function(a){this.options.allowFilter=a},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"allowFocus",{set:function(a){this.options.allowFocus=a;a||(this.currentFocusCell=null);this.refresh()},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"autoSizeColumns",{get:function(){return this.isAutoSizeColumnsActive},set:function(a){this.isAutoSizeColumnsActive!=a&&(this.isAutoSizeColumnsActive=
a,this.updateLayout())},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"columns",{get:function(){return this.dataColumns},set:function(a){this.dataColumns=a;this.updateData()},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"dataFields",{set:function(a){this.updateDataFields(a)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"focusedCell",{get:function(){return this.currentFocusCell?this.currentFocusCell.data:null},set:function(a){this.currentFocusCell!=
a&&this.updateFocusCell(this.getObjFromCell(a))},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"gridLines",{get:function(){return this.currentGridLines},set:function(a){this.currentGridLines!=a&&(this.currentGridLines=a,this.refresh())},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"paging",{set:function(a){this.updatePaging(a);this.resetPageNumber();this.updateCurrentLayout()},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"rows",{get:function(){return this.dataRows},
set:function(a){this.dataRows=a;this.updateData()},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"selectedColumn",{get:function(){return this.currentSelectedColumn},set:function(a){this.currentSelectedColumn!=a&&this.processColumnSelection(null,a)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"selectedRow",{get:function(){return this.currentSelectedRow},set:function(a){this.currentSelectedRow!=a&&this.processRowSelection(null,a)},enumerable:!0,configurable:!0});
Object.defineProperty(c.prototype,"selectionMode",{get:function(){return this.currentSelectionMode},set:function(a){this.currentSelectionMode!=a&&(this.currentSelectionMode=a,this.clearPrevSelection(this.currentSelectionMode!=integralui_core_1.IntegralUISelectionMode.None?this.currentSelectedRow:null),this.refresh(),this.currentSelectionMode==integralui_core_1.IntegralUISelectionMode.None&&(this.currentSelectedRow=null,this.selectionChanged.emit(null)))},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,
"showExpandBox",{get:function(){return this.isExpandBoxVisible},set:function(a){this.isExpandBoxVisible!=a&&(this.isExpandBoxVisible=a,this.updateLayout())},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"showScroll",{get:function(){return this.options.showScroll},set:function(a){this.updateShowScroll(a)},enumerable:!0,configurable:!0});Object.defineProperty(c.prototype,"sorting",{set:function(a){this.options.sorting=a},enumerable:!0,configurable:!0});c.prototype.ngOnInit=function(){this.dataService.init([{data:this.columns,
fields:this.options.columnFields,key:this.columnDataKey},{data:this.rows,fields:this.options.rowFields,key:this.rowDataKey}])};c.prototype.addColumn=function(a){this.callEventAddColumn("add",a)};c.prototype.clearColumns=function(){this.dataService.clear(null,this.columnDataKey);this.columnsCleared.emit(null);this.currentScrollPos.x=0};c.prototype.insertColumnAt=function(a,b){this.callEventAddColumn("at",a,b)};c.prototype.insertColumnBefore=function(a,b){this.callEventAddColumn("ref",a,-1,b)};c.prototype.insertColumnAfter=
function(a,b){this.callEventAddColumn("ref",a,-1,b,!0)};c.prototype.removeColumn=function(a){return this.callEventRemoveColumn(a)};c.prototype.removeColumnAt=function(a){return this.callEventRemoveColumn(null,a)};c.prototype.callEventAddColumn=function(a,b,e,d,c){var h={cancel:!1,column:b};this.columnAdding.emit(h);if(1!=h.cancel){switch(a){case "at":this.dataService.insert(b,e,null,null,!1,this.columnDataKey);break;case "ref":this.dataService.insertByRef(b,d,c,this.columnDataKey);break;default:this.dataService.insert(b,
-1,null,null,!1,this.columnDataKey)}this.columnAdded.emit({column:b})}};c.prototype.callEventRemoveColumn=function(a,b){var e={cancel:!1,column:a};this.columnRemoving.emit(e);return 1!=e.cancel&&(this.removeIndex=this.columns?this.columns.indexOf(a):-1,e=this.dataService.removeAt(a,b,null,this.columnDataKey),e.result)?(this.columnRemoved.emit({column:e.obj}),!0):!1};c.prototype.addRow=function(a,b){this.callEventAddRow("add",a,-1,b)};c.prototype.clearRows=function(a){this.dataService.clear(a,this.rowDataKey);
this.rowsCleared.emit({parent:a});this.clearSelection();this.currentScrollPos.y=0};c.prototype.insertRowAt=function(a,b,e){this.callEventAddRow("at",a,b,e)};c.prototype.insertRowBefore=function(a,b){this.callEventAddRow("ref",a,-1,null,b)};c.prototype.insertRowAfter=function(a,b){this.callEventAddRow("ref",a,-1,null,b,!0)};c.prototype.removeRow=function(a){return this.callEventRemoveRow(a)};c.prototype.removeRowAt=function(a,b){return this.callEventRemoveRow(null,a,b)};c.prototype.callEventAddRow=
function(a,b,e,d,c,f){var h={cancel:!1,row:b};this.rowAdding.emit(h);if(1!=h.cancel){switch(a){case "at":this.dataService.insert(b,e,d,null,!1,this.rowDataKey);break;case "ref":this.dataService.insertByRef(b,c,f,this.rowDataKey);break;default:this.dataService.insert(b,-1,d,null,!1,this.rowDataKey)}this.rowAdded.emit({row:b})}};c.prototype.callEventRemoveRow=function(a,b,e){var d={cancel:!1,row:a};this.rowRemoving.emit(d);return 1!=d.cancel&&(this.removeIndex=this.rows?this.rows.indexOf(a):-1,a=this.dataService.removeAt(a,
b,e,this.rowDataKey),a.result)?(this.rowRemoved.emit({row:a.obj}),!0):!1};c.prototype.cellClickEvent=function(a,b){this.isEnabled&&1==a.which&&this.cellClick.emit({cell:b.data,event:a})};c.prototype.cellDblClickEvent=function(a,b){this.isEnabled&&1==a.which&&this.cellDblClick.emit({cell:b.data,event:a})};c.prototype.cellRightClickEvent=function(a,b){this.isEnabled&&this.cellRightClick.emit({cell:b.data,event:a})};c.prototype.columnClickEvent=function(a,b){var e=this;if(e.isEnabled&&1==a.which)if(e.allowAnimation)var d=
setTimeout(function(){e.columnClick.emit({column:b.data,event:a});clearTimeout(d)},250);else e.columnClick.emit({column:b.data,event:a})};c.prototype.columnDblClickEvent=function(a,b){this.isEnabled&&1==a.which&&this.columnDblClick.emit({column:b.data,event:a})};c.prototype.columnRightClickEvent=function(a,b){this.isEnabled&&this.columnRightClick.emit({column:b.data,event:a})};c.prototype.rowClickEvent=function(a,b){this.isEnabled&&1==a.which&&this.rowClick.emit({event:a,row:b.data})};c.prototype.rowDblClickEvent=
function(a,b){if(this.isEnabled&&1==a.which){var e={cancel:!1,event:a,row:b.data};this.rowDblClick.emit(e);1!=e.cancel&&this.toggle(b.data)}};c.prototype.rowRightClickEvent=function(a,b){this.isEnabled&&this.rowRightClick.emit({event:a,row:b.data})};c.prototype.updateData=function(){};c.prototype.updateDataFields=function(a){a?(this.updateColumnFields(a.column),this.updateRowFields(a.row),this.updateCellFields(a.cell)):(this.updateColumnFields(),this.updateRowFields(),this.updateCellFields())};c.prototype.updateOptions=
function(a){a?(this.options={allowAnimation:this.commonService.isFieldAvailable(a.allowAnimation,!0),allowCellFocus:this.commonService.isFieldAvailable(a.allowCellFocus,!0),allowColumnReorder:this.commonService.isFieldAvailable(a.allowColumnReorder,!1),allowDrag:this.commonService.isFieldAvailable(a.allowDrag,!1),allowDrop:this.commonService.isFieldAvailable(a.allowDrop,!0),allowFilter:this.commonService.isFieldAvailable(a.allowFilter,!1),allowFocus:this.commonService.isFieldAvailable(a.allowFocus,
!1),animationSpeed:200,autoExpand:this.commonService.isFieldAvailable(a.autoExpand,!0),displayMode:this.commonService.isFieldAvailable(a.displayMode,"normal"),editorSettings:{activate:"click"},enabled:this.commonService.isFieldAvailable(a.enabled,!0),expandColIndex:this.commonService.isFieldAvailable(a.expandColIndex,void 0!=this.options.expandColIndex?this.options.expandColIndex:0),fillSpace:this.commonService.isFieldAvailable(a.fillSpace,!1),gridLines:this.commonService.isFieldAvailable(a.gridLines,
"both"),hoverSelection:this.commonService.isFieldAvailable(a.hoverSelection,!1),indent:this.commonService.isFieldAvailable(a.indent,15),labelEdit:this.commonService.isFieldAvailable(a.labelEdit,!1),loadRows:[],mouseWheelSpeed:this.commonService.isFieldAvailable(a.mouseWheelSpeed,"normal"),pathSeparator:this.commonService.isFieldAvailable(a.pathSeparator,"\\"),rowHeight:this.commonService.isFieldAvailable(a.rowHeight,-1),rtl:this.commonService.isFieldAvailable(a.rtl,!1),selectedColumn:this.commonService.isFieldAvailable(a.selectedColumn,
this.currentSelectedColumn?this.currentSelectedColumn:null),selectedIndex:-1,selectedRow:this.commonService.isFieldAvailable(a.selectedRow,this.currentSelectedRow?this.currentSelectedRow:null),selectedRows:[],selectionMode:this.commonService.isFieldAvailable(a.selectionMode,integralui_core_1.IntegralUISelectionMode.One),showFooter:this.commonService.isFieldAvailable(a.showFooter,!0),showHeader:this.commonService.isFieldAvailable(a.showHeader,!0),showIcons:this.commonService.isFieldAvailable(a.showIcons,
!0),sorting:this.commonService.isFieldAvailable(a.sorting,integralui_core_1.IntegralUISortOrder.None)},this.updatePaging(a.paging),this.updateDataFields(a.dataFields),this.updateShowScroll(a.showScroll)):(this.options={allowAnimation:!0,allowCellFocus:!0,allowColumnReorder:!1,allowDrag:!1,allowDrop:!0,allowFilter:!1,allowFocus:!1,animationSpeed:200,autoExpand:!0,displayMode:"normal",editorSettings:{activate:"click"},enabled:!0,expandColIndex:0,fillSpace:!1,gridLines:"both",hoverSelection:!1,indent:15,
labelEdit:!1,loadRows:[],mouseWheelSpeed:"normal",pathSeparator:"\\",rowHeight:-1,rtl:!1,selectedColumn:null,selectedIndex:-1,selectedRow:null,selectedRows:[],selectionMode:integralui_core_1.IntegralUISelectionMode.One,showFooter:!0,showHeader:!0,showIcons:!0,sorting:integralui_core_1.IntegralUISortOrder.None},this.updatePaging(),this.updateDataFields(),this.updateShowScroll())};c.prototype.updateColumnFields=function(a){this.options.columnFields=a?{aggregation:a.aggregation?a.aggregation:"aggregation",
allowDrag:a.allowDrag?a.allowDrag:"allowDrag",allowDrop:a.allowDrop?a.allowDrop:"allowDrop",allowFilter:a.allowFilter?a.allowFilter:"allowFilter",allowGrouping:a.allowGrouping?a.allowGrouping:"allowGrouping",allowResize:a.allowResize?a.allowResize:"allowResize",canSelect:a.canSelect?a.canSelect:"canSelect",cellTemplateUrl:a.cellTemplateUrl?a.cellTemplateUrl:"cellTemplateUrl",comparer:a.comparer?a.comparer:"comparer",contentAlignment:a.contentAlignment?a.contentAlignment:"contentAlignment",contextMenu:a.contextMenu?
a.contextMenu:"contextMenu",editorType:a.editorType?a.editorType:"editorType",editorSettings:a.editorSettings?a.editorSettings:"editorSettings",editorTemplate:a.editorTemplate?a.editorTemplate:"editorTemplate",filterParams:a.filterParams?a.filterParams:"filterParams",filterTemplate:a.filterTemplate?a.filterTemplate:"filterTemplate",fixed:a.fixed?a.fixed:"fixed",fixedWidth:a.fixedWidth?a.fixedWidth:"fixedWidth",footerAlignment:a.footerAlignment?a.footerAlignment:"footerAlignment",footerContent:a.footerContent?
a.footerContent:"footerContent",footerTemplate:a.footerTemplate?a.footerTemplate:"footerTemplate",footerTemplateModel:a.footerTemplateModel?a.footerTemplateModel:"footerTemplateModel",footerText:a.footerText?a.footerText:"footerText",footerTooltip:a.footerTooltip?a.footerTooltip:"footerTooltip",groupText:a.groupText?a.groupText:"groupText",headerAlignment:a.headerAlignment?a.headerAlignment:"headerAlignment",headerContent:a.headerContent?a.headerContent:"headerContent",headerTemplate:a.headerTemplate?
a.headerTemplate:"headerTemplate",headerTemplateModel:a.headerTemplateModel?a.headerTemplateModel:"headerTemplateModel",headerText:a.headerText?a.headerText:"headerText",headerTooltip:a.headerTooltip?a.headerTooltip:"headerTooltip",icon:a.icon?a.icon:"icon",id:a.id?a.id:"id",minWidth:a.minWidth?a.minWidth:"minWidth",maxWidth:a.maxWidth?a.maxWidth:"maxWidth",selected:a.selected?a.selected:"selected",style:a.style?a.style:"style",templateSettings:a.templateSettings?a.templateSettings:"templateSettings",
visible:a.visible?a.visible:"visible",width:a.width?a.width:"width"}:{aggregation:"aggregation",allowDrag:"allowDrag",allowDrop:"allowDrop",allowFilter:"allowFilter",allowGrouping:"allowGrouping",allowResize:"allowResize",canSelect:"canSelect",cellTemplateUrl:"cellTemplateUrl",comparer:"comparer",contentAlignment:"contentAlignment",contextMenu:"contextMenu",editorType:"editorType",editorSettings:"editorSettings",editorTemplate:"editorTemplate",filterParams:"filterParams",filterTemplate:"filterTemplate",
footerTemplateModel:"footerTemplateModel",fixed:"fixed",fixedWidth:"fixedWidth",footerAlignment:"footerAlignment",footerContent:"footerContent",footerTemplate:"footerTemplate",footerText:"footerText",footerTooltip:"footerTooltip",groupText:"groupText",headerAlignment:"headerAlignment",headerContent:"headerContent",headerTemplate:"headerTemplate",headerTemplateModel:"headerTemplateModel",headerText:"headerText",headerTooltip:"headerTooltip",icon:"icon",id:"id",minWidth:"minWidth",maxWidth:"maxWidth",
selected:"selected",style:"style",templateSettings:"templateSettings",visible:"visible",width:"width"};this.dataService&&this.dataService.updateDataFields(this.options.columnFields,this.columnDataKey)};c.prototype.updateRowFields=function(a){this.options.rowFields=a?{allowDrag:a.allowDrag?a.allowDrag:"allowDrag",allowDrop:a.allowDrop?a.allowDrop:"allowDrop",allowEdit:a.allowEdit?a.allowEdit:"allowEdit",allowFocus:a.allowFocus?a.allowFocus:"allowFocus",autoCheck:a.autoCheck?a.autoCheck:"autoCheck",
canSelect:a.canSelect?a.canSelect:"canSelect",cells:a.cells?a.cells:"cells",checkBoxSettings:a.checkBoxSettings?a.checkBoxSettings:"checkBoxSettings",checked:a.checked?a.checked:"checked",checkState:a.checkState?a.checkState:"checkState",content:a.content?a.content:"content",contextMenu:a.contextMenu?a.contextMenu:"contextMenu",gid:a.gid?a.gid:"gid",enabled:a.enabled?a.enabled:"enabled",expanded:a.expanded?a.expanded:"expanded",fixed:a.fixed?a.fixed:"fixed",hasChildren:a.hasChildren?a.hasChildren:
"hasChildren",icon:a.icon?a.icon:"icon",id:a.id?a.id:"id",objects:a.rows?a.rows:"rows",pid:a.pid?a.pid:"pid",rows:a.rows?a.rows:"rows",selected:a.selected?a.selected:"selected",statusIcon:a.statusIcon?a.statusIcon:"statusIcon",style:a.style?a.style:"style",subobjects:a.cells?a.cells:"cells",templateObj:a.templateObj?a.templateObj:"templateObj",text:a.text?a.text:"text",tooltip:a.tooltip?a.tooltip:"tooltip",value:a.value?a.value:"value",visible:a.visible?a.visible:"visible"}:{allowDrag:"allowDrag",
allowDrop:"allowDrop",allowFocus:"allowFocus",canSelect:"canSelect",cells:"cells",content:"content",contextMenu:"contextMenu",enabled:"enabled",expanded:"expanded",fixed:"fixed",gid:"gid",hasChildren:"hasChildren",icon:"icon",id:"id",objects:"rows",pid:"pid",rows:"rows",selected:"selected",statusIcon:"statusIcon",style:"style",subobjects:"cells",text:"text",tooltip:"tooltip",value:"value",visible:"visible"};this.dataService&&this.dataService.updateDataFields(this.options.rowFields,this.rowDataKey)};
c.prototype.updateCellFields=function(a){this.options.cellFields=a?{allowDrag:a.allowDrag?a.allowDrag:"allowDrag",allowEdit:a.allowEdit?a.allowEdit:"allowEdit",cid:a.cid?a.cid:"cid",content:a.content?a.content:"content",contextMenu:a.contextMenu?a.contextMenu:"contextMenu",editorSettings:a.editorSettings?a.editorSettings:"editorSettings",enabled:a.enabled?a.enabled:"enabled",expanded:a.expanded?a.expanded:"expanded",isGroup:a.isGroup?a.isGroup:"isGroup",labelEdit:a.labelEdit?a.labelEdit:"labelEdit",
rid:a.rid?a.rid:"rid",selected:a.selected?a.selected:"selected",style:a.style?a.style:"style",tag:a.tag?a.tag:"tag",templateObj:a.templateObj?a.templateObj:"templateObj",text:a.text?a.text:"text",tooltip:a.tooltip?a.tooltip:"tooltip",value:a.value?a.value:"value",valueID:a.valueID?a.valueID:"valueID",valueType:a.valueType?a.valueType:"valueType"}:{allowDrag:"allowDrag",allowEdit:"allowEdit",cid:"cid",content:"content",contextMenu:"contextMenu",editorSettings:"editorSettings",enabled:"enabled",expanded:"expanded",
isGroup:"isGroup",labelEdit:"labelEdit",rid:"rid",selected:"selected",style:"style",tag:"tag",templateObj:"templateObj",text:"text",tooltip:"tooltip",value:"value",valueID:"valueID",valueType:"valueType"}};c.prototype.updateShowScroll=function(a){this.options.showScroll=a?{horizontal:this.commonService.isFieldAvailable(a.horizontal,!0),vertical:this.commonService.isFieldAvailable(a.vertical,!0)}:{horizontal:!0,vertical:!0}};c.prototype.processLoadData=function(a,b,e,d){var c=this;c.clearRows(b);c.updateRowFields(e);
var f=[];if(a)if(d||void 0==d){var g=[];a.forEach(function(a,b){var e=a[c.options.rowFields.pid];g[e]?(g[e][c.options.rowFields.rows]||(g[e][c.options.rowFields.rows]=[]),g[a[c.options.rowFields.id]]=a,g[e][c.options.rowFields.rows].push(a)):(g[a[c.options.rowFields.id]]=a,f.push(a))});g.length=0}else f=a;if(b)for(b[c.options.rowFields.rows]=f,a=0;a<b[c.options.rowFields.rows].length;a++)b[c.options.rowFields.rows][a][c.options.rowFields.pid]=b[c.options.rowFields.id];else if(c.rows)for(a=c.rows.length=
0;a<f.length;a++)c.rows.push(f[a]);c.loadComplete.emit(null);this.updateLayout()};c.prototype.createScrollRowList=function(){for(var a=this.scrollRowList.length=0;100>a;a++){var b=this.createEmptyRowObj();this.scrollRowList.push(b)}};c.prototype.createEmptyRowObj=function(){for(var a={clickPos:{x:0,y:0},cells:[],data:{},draggable:!1,indent:0,inlineStyle:{},isEmpty:!0,isGroup:!1,style:{}},b=0;1E3>b;b++)a.cells[b]=this.createEmptyCellObj();return a};c.prototype.createEmptyCellObj=function(){return{align:"",
colIndex:-1,data:{},display:"none",editorClass:"",editorList:[],editorSettings:{},editorStyle:"",editorType:null,editorValue:null,expandBoxAllowed:!1,indent:0,inlineStyle:{},isEditorEnabled:!0,isEditorVisible:!0,isEmpty:!0,rowIndex:-1,style:{content:"iui-grid-row-cell-content"},tabIndex:-1,width:100,height:"auto"}};c.prototype.resetRowObj=function(a){a&&(a.clickPos={x:0,y:0},a.data={},a.draggable=!1,a.indent=0,a.inlineStyle={},a.isEmpty=!0,a.isGroup=!1,a.style={})};c.prototype.resetCellObj=function(a){a&&
(a.align="",a.colIndex=-1,a.data={},a.display="none",a.editorClass="",a.editorList=[],a.editorSettings={},a.editorStyle="",a.editorType=null,a.editorValue=null,a.expandBoxAllowed=!1,a.indent=0,a.inlineStyle={},a.isEditorEnabled=!0,a.isEditorVisible=!0,a.isEmpty=!0,a.rowIndex=-1,a.style={content:"iui-grid-row-cell-content"},a.tabIndex=-1,a.width=100,a.height="auto")};c.prototype.updateScrollColumnList=function(){};c.prototype.updateScrollRowList=function(a){};c.prototype.addDropMark=function(a){this.appRef&&
(this.removeDropMark(),a=this.cmpResolver.resolveComponentFactory(integralui_core_1.IntegralUIDragWindow))&&(this.dragCmpRef=this.appRef.createComponent(a),this.dragCmpRef._component?this.dragCmp=this.dragCmpRef._component:this.dragCmpRef._hostElement&&(this.dragCmp=this.dragCmpRef._hostElement.component))};c.prototype.removeDropMark=function(){this.dragCmpRef&&this.dragCmpRef.destroy();this.dragCmp=null};c.prototype.callDragDropEvent=function(a,b,e){var d=this;b={action:b.action,cancel:!1,dragRow:b.source,
dropPos:b.dropPos,event:a,isDropAllowed:b.allow,mousePos:this.commonService.getMousePos(a),resume:function(){d.drop(a,d.dragDropService.getData());d.dragDropService.clearData()},sourceCtrl:b.sourceCtrl,targetCtrl:b.targetCtrl,targetRow:b.target};e?this.dragDrop.emit(b):this.dragOver.emit(b);return b.cancel};c.prototype.checkEmptySpace=function(a){var b=this.getContentSize(),e=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild);b=e.top+b.height;e=e.bottom;a=this.commonService.getMousePos(a);
var d=this.commonService.getShiftPos();a.x-=d.x;a.y-=d.y;return a.y>=b&&a.y<=e};c.prototype.ctrlDragEnter=function(a){this.isEnabled&&this.processDragEnter(a)};c.prototype.ctrlDragDrop=function(a){this.isEnabled&&this.processDragDrop(a);this.removeDropMark();a.stopPropagation()};c.prototype.ctrlDragLeave=function(a){this.isEnabled&&this.processDragLeave(a)};c.prototype.ctrlDragOver=function(a){this.isEnabled&&this.processDragOver(a);a.stopPropagation()};c.prototype.ctrlDragEnd=function(a){this.removeDropMark();
var b=this.dragDropService.getData();b.targetCtrl&&b.targetCtrl.removeDropMark&&b.targetCtrl.removeDropMark();this.rowDragEnd(a,null)};c.prototype.removeDragHandle=function(){this.isDragHandleVisible=!1;this.targetDropRow=null;this.targetDropPos=-1};c.prototype.dropMark=function(a,b){if(this.dragMode==integralui_core_1.IntegralUIDragDropDisplayMode.Handle)b||this.removeDragHandle(),this.updateScrollRowListDragOver(null);else if(this.dragCmp||this.isScrollTimerActive||this.addDropMark({x:a.pageX,y:a.pageY}),
this.dragCmp){var e="none";this.options.allowDrop&&(e=b?"block":"none");this.dragCmp.display=e}};c.prototype.updateDragComponent=function(a){this.dragCmp&&this.dragCmp.updatePos(a)};c.prototype.isDragAllowed=function(a){return this.options.allowDrag?a&&(a[this.options.rowFields.allowDrag]||void 0===a[this.options.rowFields.allowDrag])?!0:!1:!1};c.prototype.isDropAllowed=function(a,b,e){var d=this.options.allowDrop;if(d&&a&&b&&(d=b[this.options.rowFields.allowDrop]||void 0===b[this.options.rowFields.allowDrop]?
!0:!1))if(Array.isArray(a))for(var c=0;c<a.length;c++){if(this.commonService.isEqual(a[c][this.options.rowFields.id],b[this.options.rowFields.id])||0===e&&this.isParentOf(b,a[c])||this.isChildOf(b,a[c])){d=!1;break}if(!d)break}else if(this.commonService.isEqual(a[this.options.rowFields.id],b[this.options.rowFields.id])||0===e&&this.isParentOf(b,a)||this.isChildOf(b,a))d=!1;return d};c.prototype.processDragStart=function(a,b){this.dragMode==integralui_core_1.IntegralUIDragDropDisplayMode.Handle?this.processDragStartHandle(a,
b):this.processDragStartPopup(a,b)};c.prototype.processDragStartHandle=function(a,b){this.dragDropService.clearData();if(!this.isDragAllowed(b))a.preventDefault();else if(b)if(this.isDragAllowed(b)){var e={clone:this.cloneRow(b),handle:this.dragRowList,source:b,sourceCtrl:this,sourceData:this.rows};switch(this.selectionMode){case integralui_core_1.IntegralUISelectionMode.MultiSimple:e.clone=this.createCloneList(this.currentSelectedRows);e.source=this.currentSelectedRows;break;case integralui_core_1.IntegralUISelectionMode.MultiExtended:e.clone=
this.createCloneList(this.currentSelectedRows),e.source=this.currentSelectedRows}var d={action:a.shiftKey?"copy":"move",cancel:!1,dragRow:e.source,dropPos:-1,event:a,isDropAllowed:this.options.allowDrop,mousePos:this.commonService.getMousePos(a),sourceCtrl:e.sourceCtrl,targetCtrl:this,targetRow:null};this.dragStart.emit(d);1==d.cancel?a.preventDefault():(this.isFirstDragEnter=!0,this.dragDropService.setData(e))}else this.ctrlCursor="no-drop"};c.prototype.processDragStartPopup=function(a,b){this.dragDropService.clearData();
if(!this.isDragAllowed(b))a.preventDefault();else if(b)if(this.isDragAllowed(b)){var e={clone:this.cloneRow(b),source:b,sourceCtrl:this,sourceData:this.rows};switch(this.selectionMode){case integralui_core_1.IntegralUISelectionMode.MultiSimple:e.clone=this.createCloneList(this.currentSelectedRows);e.source=this.currentSelectedRows;break;case integralui_core_1.IntegralUISelectionMode.MultiExtended:e.clone=this.createCloneList(this.currentSelectedRows),e.source=this.currentSelectedRows}var d={action:a.shiftKey?
"copy":"move",cancel:!1,dragRow:e.source,dropPos:-1,event:a,isDropAllowed:this.options.allowDrop,mousePos:this.commonService.getMousePos(a),sourceCtrl:e.sourceCtrl,targetCtrl:this,targetRow:null};this.dragStart.emit(d);1==d.cancel?a.preventDefault():(this.isFirstDragEnter=this.isDragActive=!0,this.addDropMark({x:a.pageX,y:a.pageY}),this.dropMark(a),a.dataTransfer?(a.dataTransfer.effectAllowed="move",a.dataTransfer.setData("text",b[this.options.rowFields.id]?b[this.options.rowFields.id].toString():
"")):a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.effectAllowed="move",a.originalEvent.dataTransfer.setData("text",b[this.options.rowFields.id]?b[this.options.rowFields.id].toString():"")),this.dragDropService.setData(e))}else a.dataTransfer?a.dataTransfer.effectAllowed="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.effectAllowed="none")};c.prototype.processDragEnter=function(a){a.preventDefault();if(!this.isCtrlDragEntered){this.isCtrlDragEntered=
!0;var b=this.dragDropService.getData();if(!this.isFirstDragEnter&&this.dragMode==integralui_core_1.IntegralUIDragDropDisplayMode.Handle&&(this.dragRowList=b.handle)){for(var e=0;e<this.dragRowList.length;e++){var d=this.getObjIndexFromScrollList(this.dragRowList[e].data);0<=d&&this.scrollRowList.splice(d,1)}this.isDragHandleVisible=!0;this.targetDropPos=2;this.targetDropRow=0<this.scrollRowList.length?this.scrollRowList[this.scrollRowList.length-1].data:null;this.scrollRowList.splice(this.scrollRowList.length,
0,{cells:[],draggable:!1,isEmpty:!0,status:1,style:{}})}this.isFirstDragEnter=!1;a={action:a.shiftKey?"copy":"move",dragRow:b.source,dropPos:-1,event:a,isDropAllowed:this.options.allowDrop,mousePos:this.commonService.getMousePos(a),sourceCtrl:b.sourceCtrl,targetCtrl:this,targetRow:null};this.dragEnter.emit(a)}};c.prototype.processDragLeave=function(a){a.preventDefault();if(this.isCtrlDragEntered){var b=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild),e=this.commonService.getMousePos(a),
d=this.commonService.getShiftPos();e.x-=d.x;e.y-=d.y;if(e.x<=b.left||e.x>=b.right||e.y<=b.top||e.y>=b.bottom)this.isCtrlDragEntered=!1,this.dragMode==integralui_core_1.IntegralUIDragDropDisplayMode.Handle&&this.updateScrollRowList(),this.stopScrollTimer(),b=this.dragDropService.getData(),b={action:a.shiftKey?"copy":"move",dragRow:b.source,dropPos:-1,event:a,isDropAllowed:!1,mousePos:this.commonService.getMousePos(a),sourceCtrl:b.sourceCtrl,targetCtrl:null,targetRow:null},this.dragLeave.emit(b);this.dropMark(a)}};
c.prototype.processDragOver=function(a,b,e,d){this.dragMode==integralui_core_1.IntegralUIDragDropDisplayMode.Handle?this.processDragOverHandle(a,b,e,d):this.processDragOverPopup(a,b,e,d)};c.prototype.processDragOverHandle=function(a,b,e,d){a.preventDefault();this.processDragEnter(a);this.hoverRow=null;this.changeCursor();var c=this.isDragActive;if(c){var f=this.dragDropService.getData();c=this.commonService.getShiftPos();if(b&&!b.isEmpty){var g=this.commonService.getMousePos(a);g.x-=c.x;g.y-=c.y;
e=this.dragDropService.getDropPos(g,e,d,"group"==b.data.type?"full":null);c=this.isDropAllowed(f.source,b.data,e);d=this.callDragDropEvent(a,{action:a.shiftKey?"copy":"move",source:f.source,dropPos:e,allow:c,sourceCtrl:f.sourceCtrl,target:b.data,targetCtrl:this});c&&1!=d?(this.isDragHandleVisible=!0,this.dragRowList=f.handle,this.targetDropPos=e,this.updateScrollRowListDragOver(b.data),this.dragObjIndent=this.getObjFromRow(b.data).indent,b.data[this.options.rowFields.rows]&&0<b.data[this.options.rowFields.rows].length&&
(this.dragObjIndent+=this.options.indent),this.updateDragHandlePos(a),this.dragDropService.setData({action:a.shiftKey?"copy":"move",clone:f.clone,handle:f.handle,source:f.source,sourceCtrl:f.sourceCtrl,sourceData:f.sourceData,target:b.data,targetCtrl:this,dropPos:e})):(this.ctrlCursor="no-drop",this.dropMark(a,!0),this.targetDropPos=-1,this.updateScrollRowListDragOver(b.data),this.updateDragHandlePos(a))}else this.options.allowDrop?(this.dragRowList=f.handle,this.updateDragHandlePos(a)):(this.ctrlCursor=
"no-drop",this.dropMark(a))}};c.prototype.processDragOverPopup=function(a,b,e,d){a.preventDefault();this.processDragEnter(a);var c=!0;a.dataTransfer?c="none"===a.dataTransfer.effectAllowed?!1:!0:a.originalEvent&&a.originalEvent.dataTransfer&&(c="none"===a.originalEvent.dataTransfer.effectAllowed?!1:!0);if(c){var f=this.dragDropService.getData();c=this.commonService.getShiftPos();if(b&&!b.isEmpty){var g=this.commonService.getMousePos(a);g.x-=c.x;g.y-=c.y;g=this.dragDropService.getDropPos(g,e,d,"group"==
b.data.type?"full":null);c=this.isDropAllowed(f.source,b.data,g);e={action:a.shiftKey?"copy":"move",source:f.source,dropPos:g,allow:c,sourceCtrl:f.sourceCtrl,target:b.data,targetCtrl:this};e=this.callDragDropEvent(a,e);if(c&&1!=e){d=this.commonService.getMousePos(a);e=d.y+16;d=d.x+20;var k="iui-dragwin-icon";switch(g){case 0:k+=" iui-dragwin-move-in";break;case 1:k+=" iui-dragwin-move-up";break;case 2:k+=" iui-dragwin-move-down"}a.shiftKey&&(k+="-copy");this.updateDragComponent({"class":k,top:e,left:d,
text:b.data[this.options.rowFields.text]});this.dropMark(a,c);this.dragDropService.setData({action:a.shiftKey?"copy":"move",clone:f.clone,source:f.source,sourceCtrl:f.sourceCtrl,sourceData:f.sourceData,target:b.data,targetCtrl:this,dropPos:g})}else a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a)}else this.options.allowDrop?(c=this.checkEmptySpace(a),e={action:a.shiftKey?"copy":"move",source:f.source,
dropPos:-1,allow:c,sourceCtrl:f.sourceCtrl,target:null,targetCtrl:this},e=this.callDragDropEvent(a,e),c&&1!=e?(g=this.commonService.getMousePos(a),e=g.y+16,d=g.x+20,k="iui-dragwin-icon iui-dragwin-move-end",a.shiftKey&&(k+="-copy"),this.updateDragComponent({"class":k,top:e,left:d,text:this.name?this.name:"Component"}),this.dropMark(a,c&&!this.isScrollTimerActive),this.dragDropService.setData({action:a.shiftKey?"copy":"move",clone:f.clone,source:f.source,sourceCtrl:f.sourceCtrl,sourceData:f.sourceData,
target:null,targetCtrl:this,dropPos:-1})):(a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a))):(a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a))}};c.prototype.processDragDrop=function(a,b){a.preventDefault();var e=!0;a.dataTransfer?e="none"===a.dataTransfer.effectAllowed?!1:!0:
a.originalEvent&&a.originalEvent.dataTransfer&&(e="none"===a.originalEvent.dataTransfer.effectAllowed?!1:!0);var d=this.dragDropService.getData();e&&((e=b&&!b.isEmpty?this.isDropAllowed(d.source,b.data,d.dropPos):this.checkEmptySpace(a))&&d.source&&(this.callDragDropEvent(a,{action:a.shiftKey?"copy":"move",source:d.source,dropPos:d.dropPos,allow:e,sourceCtrl:d.sourceCtrl,target:d.target,targetCtrl:this},!0)?e=!1:this.drop(a,d)),d.sourceCtrl&&d.sourceCtrl.removeDropMark&&d.sourceCtrl.removeDropMark());
e?this.dragDropService.clearData():this.dragMode==integralui_core_1.IntegralUIDragDropDisplayMode.Handle&&this.updateLayout();this.isDragActive=!1;this.clearDragDropSettings();var c=this,f=setTimeout(function(){c.dropMark(a);if(e){var b={action:a.shiftKey?"copy":"move",dragRow:d.source,dropPos:d.dropPos,event:a,isDropAllowed:!0,mousePos:c.commonService.getMousePos(a),sourceCtrl:d.sourceCtrl,targetCtrl:c,targetRow:d.target};c.dragDropComplete.emit(b)}clearTimeout(f)},150)};c.prototype.clearDragDropSettings=
function(){this.dragDropService.clearData();this.isDragHandleVisible=this.isDragActive=!1;this.dragStartPos={x:0,y:0};this.dragEndPos={x:0,y:0};this.changeCursor()};c.prototype.drop=function(a,b){if(b&&b.sourceCtrl){var e=a.shiftKey&&b.clone?b.clone:b.source;if(Array.isArray(e)){for(var d=[],c=0;c<e.length;c++)d.push(e[c]);if(0<d.length){for(c=0;c<d.length;c++)this.processDataDrop(a,d[c],b);this.clearPrevSelection(d[d.length-1])}}else this.processDataDrop(a,e,b),this.clearPrevSelection(e);b.sourceCtrl!=
b.targetCtrl&&b.sourceCtrl.updateLayout&&b.sourceCtrl.updateLayout();this.updateLayout()}this.isCtrlDragEntered=!1};c.prototype.processDataDrop=function(a,b,e){var d=a.shiftKey;!a.shiftKey&&e.sourceCtrl&&e.sourceCtrl.removeRow&&(d=e.sourceCtrl.removeRow(b));if(d)switch(e.dropPos){case 0:this.dragMode==integralui_core_1.IntegralUIDragDropDisplayMode.Handle?this.insertRowAt(b,0,e.target):this.insertRowAt(b,-1,e.target);break;case 1:this.insertRowBefore(b,e.target);break;case 2:this.insertRowAfter(b,
e.target);break;default:this.addRow(b)}};c.prototype.callAfterSelectEvent=function(a){this.afterSelect.emit({obj:a});this.selectionChanged.emit(null)};c.prototype.rowDragEnd=function(a,b){var e=this.dragDropService.getData();e={action:a.shiftKey?"copy":"move",dragRow:e.source,dropPos:e.dropPos,event:a,mousePos:this.commonService.getMousePos(a),sourceCtrl:e.sourceCtrl,targetCtrl:this,targetRow:e.target};this.dragEnd.emit(e)};c.prototype.addCalendar=function(){var a=this;if(a.appRef){a.removeCalendar();
var b=a.cmpResolver.resolveComponentFactory(integralui_datepicker_1.IntegralUICalendarPopup);b&&(a.calendarRef=a.appRef.createComponent(b),a.calendarRef._component?a.calendar=a.calendarRef._component:a.calendarRef._hostElement&&(a.calendar=a.calendarRef._hostElement.component),a.hideCalendar(),a.calendar&&(a.calendar.closed.subscribe(function(b){a.hideCalendar()}),a.calendar.dateChanged.subscribe(function(b){a.hideCalendar();a.currentEditorCell&&1!=a.callCellValueChanging(a.currentEditorCell,b.date)&&
(a.currentEditorCell.data.value=b.date,a.updateScrollRowList(),a.callCellValueChanged(a.currentEditorCell));a.isPopupDelayed=!0;setTimeout(function(){a.isPopupDelayed=!1},250)})))}};c.prototype.addDropList=function(){var a=this;if(a.appRef){a.removeDropList();var b=a.cmpResolver.resolveComponentFactory(integralui_core_1.IntegralUIListPopup);b&&(a.dropListRef=a.appRef.createComponent(b),a.dropListRef._component?a.dropList=a.dropListRef._component:a.dropListRef._hostElement&&(a.dropList=a.dropListRef._hostElement.component),
a.hideDropList(),a.dropList&&(a.dropList.closed.subscribe(function(b){a.hideDropList()}),a.dropList.selectionChanged.subscribe(function(b){a.hideDropList();b.item&&a.currentEditorCell&&1!=a.callCellValueChanging(a.currentEditorCell,b.item.value)&&(a.currentEditorCell.data[a.options.cellFields.value]=b.item.value,a.callCellValueChanged(a.currentEditorCell));a.isPopupDelayed=!0;setTimeout(function(){a.isPopupDelayed=!1},250)})))}};c.prototype.callCellValueChanging=function(a,b){var e={cancel:!1,cell:a.data,
text:a.data[this.options.cellFields.text],value:void 0!=b?b:a.data[this.options.cellFields.value]};this.cellValueChanging.emit(e);return e.cancel};c.prototype.callCellValueChanged=function(a){this.cellValueChanged.emit({cell:a.data,text:a.data[this.options.cellFields.text],value:a.data[this.options.cellFields.value]})};c.prototype.closeEditor=function(){this.currentEditorCell=null;this.originalEditorText="";this.originalEditorValue=null;this.isEditorFocused=!1};c.prototype.editCheckBoxValue=function(a){if(a.isEditorEnabled){var b=
void 0!=a.data[this.options.cellFields.value]?a.data[this.options.cellFields.value]:"unchecked";if(1!=this.callCellValueChanging(a)){b="checked"==b||1==b?"checked":a.editorSettings&&a.editorSettings.threeState&&"indeterminate"==b?"indeterminate":"unchecked";var e="unchecked";if(a.editorSettings&&a.editorSettings.threeState)switch(b){case "checked":e="unchecked";break;case "indeterminate":e="checked";break;case "unchecked":e="indeterminate"}else e="unchecked"==b?!0:!1;a.data[this.options.cellFields.value]=
e;this.updateScrollRowList();this.callCellValueChanged(a)}}};c.prototype.editorClick=function(a){a.stopPropagation()};c.prototype.editorDblClickEvent=function(a){a.stopPropagation()};c.prototype.editorKeyDown=function(a,b){if(this.currentEditorCell)switch(a.keyCode){case 13:switch(b){case "numeric":this.callCellValueChanged(this.currentEditorCell);break;default:this.cellValueChanged.emit({cell:this.currentEditorCell.data,orgText:this.originalEditorText,text:this.currentEditorCell.data[this.options.cellFields.text],
value:this.currentEditorCell.data[this.options.cellFields.value]})}this.closeEditor();break;case 27:switch(b){case "numeric":this.currentEditorCell.data[this.options.cellFields.value]=this.originalEditorValue;break;default:this.currentEditorCell.data[this.options.cellFields.text]=this.originalEditorText}this.closeEditor()}};c.prototype.editorLostFocus=function(a){if(this.currentEditorCell)switch(a){case "numeric":this.currentEditorCell.data[this.options.cellFields.value]=this.originalEditorValue;
break;default:this.currentEditorCell.data[this.options.cellFields.text]=this.originalEditorText}this.closeEditor()};c.prototype.editorMouseDown=function(a,b){};c.prototype.editorMouseWheel=function(a){a.stopPropagation()};c.prototype.editorNumericValueChange=function(a,b){b&&!isNaN(b)&&(a.data[this.options.cellFields.value]=Math.min(Math.max(Number(b),a.editorSettings&&void 0!=a.editorSettings.min?a.editorSettings.min:-9999999),a.editorSettings&&void 0!=a.editorSettings.max?a.editorSettings.max:9999999),
this.callCellValueChanged(a))};c.prototype.editorPreventDragStart=function(a){a.preventDefault();a.stopPropagation()};c.prototype.editorValueChanged=function(a,b){this.isLayoutUpdating||this.isScrollActive||this.callCellValueChanged(b)};c.prototype.getCellEditorClass=function(a){var b="",e=a.editorSettings&&a.editorSettings.style?a.editorSettings.style:{};switch(a.editorType){case integralui_core_1.IntegralUIEditorType.CheckBox:b="iui-editor-checkbox"+(e.general?" "+e.general:"");switch(a.editorValue){case "checked":b+=
e.checked?" "+e.checked:" iui-editor-checkbox-checked";break;case "indeterminate":b+=e.indeterminate?" "+e.indeterminate:" iui-editor-checkbox-indeterminate";break;default:b+=e.unchecked?" "+e.unchecked:" iui-editor-checkbox-unchecked"}a.isEditorEnabled||(b+=e.disabled?" "+e.disabled:" iui-editor-checkbox-disabled")}return b};c.prototype.getCellEditorList=function(a){return void 0!=a[this.options.columnFields.editorSettings]&&void 0!=a[this.options.columnFields.editorSettings].list?a[this.options.columnFields.editorSettings].list:
[]};c.prototype.getCellEditorSettings=function(a){return void 0!=a[this.options.columnFields.editorSettings]?a[this.options.columnFields.editorSettings]:{}};c.prototype.getCellEditorStyle=function(a){var b={},e=a.editorSettings&&a.editorSettings.style?a.editorSettings.style:{};switch(a.editorType){case integralui_core_1.IntegralUIEditorType.Rating:b=e}return b};c.prototype.getCellEditorType=function(a){return void 0!=a[this.options.columnFields.editorType]?a[this.options.columnFields.editorType]:
integralui_core_1.IntegralUIEditorType.None};c.prototype.getCellEditorVisibility=function(a,b){var e=!0;switch((void 0!=b[this.options.cellFields.editorSettings]?b[this.options.cellFields.editorSettings]:{}).visible){case integralui_core_1.IntegralUIVisibility.None:e=!1}return e};c.prototype.getCellField=function(a){switch(a){case "text":return this.options.cellFields.text;case "value":return this.options.cellFields.value}};c.prototype.getCellText=function(a){return void 0!=a.data[this.options.cellFields.text]?
a.data[this.options.cellFields.text]:""};c.prototype.getCellValue=function(a){var b=void 0!=a.data[this.options.cellFields.value]?a.data[this.options.cellFields.value]:null;switch(a.editorType){case integralui_core_1.IntegralUIEditorType.CheckBox:a.editorSettings&&(b="checked"==b||1==b?"checked":a.editorSettings.threeState&&"indeterminate"==b?"indeterminate":"unchecked");break;case integralui_core_1.IntegralUIEditorType.Date:var e="en-US",d={year:"numeric",month:"numeric",day:"numeric"};if(a.editorSettings)switch(e=
a.editorSettings.locales?a.editorSettings.locales:"en-US",a.editorSettings.format){case integralui_core_1.IntegralUIDateFormat.Long:d.weekday="long";break;case integralui_core_1.IntegralUIDateFormat.Custom:d=a.editorSettings.formatOptions}b=b?b.toLocaleString(e,d):"";break;case integralui_core_1.IntegralUIEditorType.DropList:b=this.commonService.isObject(b)?b?b.text:"":void 0!=b&&a.editorSettings?this.findItemByValue(b,a.editorSettings.items):"";break;case integralui_core_1.IntegralUIEditorType.Image:b=
Array.isArray(b)?b:[{src:b}];break;case integralui_core_1.IntegralUIEditorType.Progress:b=this.getEditorProgressValue(a);break;case integralui_core_1.IntegralUIEditorType.Numeric:b=void 0!=a.data[this.options.cellFields.value]?a.data[this.options.cellFields.value]:"";break;case integralui_core_1.IntegralUIEditorType.TextBox:b=void 0!=a.data[this.options.cellFields.text]?a.data[this.options.cellFields.text]:""}return b};c.prototype.findItemByValue=function(a,b){for(var e="",d=0;d<b.length;d++)if(void 0!=
b[d].value&&b[d].value==a){e=void 0!=b[d].text&&""!=b[d].text?b[d].text:b[d].value.toString();break}return e};c.prototype.getEditorProgressStyle=function(a){return{width:a.editorValue+"%","z-index":2}};c.prototype.getEditorProgressValue=function(a){var b=a.editorSettings&&void 0!=a.editorSettings.min?a.editorSettings.min:0,e=a.editorSettings&&void 0!=a.editorSettings.max?a.editorSettings.max:100;return(a=a.data[this.options.cellFields.value])&&!isNaN(a)&&!isNaN(e)&&0<e?100*Math.min(Math.max(a,b),
e)/e:0};c.prototype.hideCalendar=function(){this.calendar&&(this.calendar.display="none")};c.prototype.hideDropList=function(){this.dropList&&(this.dropList.display="none")};c.prototype.isCellEditorEnabled=function(a,b){return 0!=(void 0!=b[this.options.cellFields.editorSettings]?b[this.options.cellFields.editorSettings]:{}).enabled?!0:!1};c.prototype.openEditor=function(a,b,e){this.currentEditorCell=b;this.isEditorFocused=!0;switch(e){case "numeric":this.originalEditorValue=b.data[this.options.cellFields.value];
break;default:this.originalEditorText=b.data[this.options.cellFields.text]}};c.prototype.removeCalendar=function(){this.calendar&&(this.calendar.closed&&this.calendar.closed.unsubscribe(),this.calendar.dateChanged&&this.calendar.dateChanged.unsubscribe());this.calendarRef&&this.calendarRef.destroy();this.calendar=null};c.prototype.removeDropList=function(){this.dropList&&(this.dropList.closed&&this.dropList.closed.unsubscribe(),this.dropList.selectionChanged&&this.dropList.selectionChanged.unsubscribe());
this.dropListRef&&this.dropListRef.destroy();this.dropList=null};c.prototype.showPopup=function(a,b,e,d){a=this.commonService.getShiftPos();e=this.commonService.getPageRect(e.nativeElement);d=this.commonService.getPageRect(d.nativeElement);switch(b.editorType){case integralui_core_1.IntegralUIEditorType.Date:this.calendar&&(this.calendar.allowAnimation=!1,this.calendar.calendarStyle=b.editorSettings&&b.editorSettings.style&&b.editorSettings.style.calendar?b.editorSettings.style.calendar:null,this.calendar.date=
b.data.value,this.calendar.display="block",this.calendar.firstDayOfWeek=b.editorSettings&&void 0!=b.editorSettings.firstDayOfWeek?b.editorSettings.firstDayOfWeek:integralui_core_1.IntegralUIWeekDays.Sunday,this.calendar.position={x:d.left+a.x-1,y:e.bottom+a.y},this.calendar.size=b.editorSettings&&b.editorSettings.calendarSize?b.editorSettings.calendarSize:{width:250,height:200},this.allowAnimation&&(this.calendar.position.y-=2),this.calendar.refresh(),this.calendar.open(),this.currentEditorCell=b,
this.calendar.focus());break;case integralui_core_1.IntegralUIEditorType.DropList:this.dropList&&(this.dropList.allowAnimation=!1,this.dropList.display="block",this.dropList.items=b.editorSettings&&b.editorSettings.items?b.editorSettings.items:[],this.dropList.listStyle=b.editorSettings&&b.editorSettings.style&&b.editorSettings.style.list?b.editorSettings.style.list:null,this.dropList.minWidth=b.editorSettings&&b.editorSettings.minWidth?b.editorSettings.minWidth:d.width,this.dropList.maxVisibleItems=
b.editorSettings&&b.editorSettings.maxVisibleItems?b.editorSettings.maxVisibleItems:5,this.dropList.position={x:d.left+a.x-1,y:e.bottom+a.y},this.dropList.size={width:Math.max(d.width,this.dropList.minWidth),height:0},this.dropList.refresh(),this.dropList.open(),this.currentEditorCell=b,this.dropList.focus())}};c.prototype.selectTextBoxContent=function(a){a.target&&setTimeout(function(){a.target.setSelectionRange(0,a.target.value.length)},1)};c.prototype.expandBoxMouseDown=function(a,b){this.isEnabled&&
(1!=a.buttons||this.isExpandBoxTouched||this.toggle(b),this.isExpandBoxTouched=!1);a.stopPropagation()};c.prototype.expandBoxMouseUp=function(a){this.isExpandBoxTouched=!1;a.stopPropagation()};c.prototype.expandBoxTouchStart=function(a,b){this.isEnabled&&(this.isExpandBoxTouched=!0,this.toggle(b));a.stopPropagation()};c.prototype.toggle=function(a,b){};c.prototype.updateExpandingCell=function(a,b){var e=0,d=this.getExpandingColumn();d&&(e=d[this.options.columnFields.id]);(e=this.getCellByColumnId(a[this.options.rowFields.cells],
e))&&(e[this.options.cellFields.expanded]=b)};c.prototype.convertToCSV=function(a){for(var b="",e=0;e<a.length;e++){var d="",c=a[e];if(0<c.length){for(var f=0;f<c.length;f++)d+=c[f].text+",";d=d.slice(0,-1);d+="\r\n"}b+=d}return b};c.prototype.exportToCSV=function(){for(var a=[],b=[],e=0;e<this.currentColumnList.length;e++){var d=this.currentColumnList[e].data;d={text:void 0!=d[this.options.columnFields.headerText]?d[this.options.columnFields.headerText].toString():""};b.push(d)}a.push(b);for(var c=
this.getFullList(),f=0;f<c.length;f++){var g=c[f];b=[];for(e=0;e<this.currentColumnList.length;e++){var k=this.getCellByColumnId(g[this.options.rowFields.cells],this.currentColumnList[e].data[this.options.columnFields.id]);d={};d.text=k?k.value?k.value instanceof Date?k.value.toLocaleDateString():JSON.stringify(k.value):k.text?0<=k.text.indexOf(",")?JSON.stringify(k.text):k.text:"":"";b.push(d)}a.push(b)}return this.convertToCSV(a)};c.prototype.exportToJSON=function(a,b,e,d){a=this.exportColumnsToJSON(a,
e);b=this.exportRowsToJSON(b,e,d);return'[\n{ "columns": '+a+' },\n{ "rows": '+b+" }\n]"};c.prototype.exportColumnsToJSON=function(a,b){return JSON.stringify(this.columns,a?a:[this.options.columnFields.allowDrag,this.options.columnFields.allowDrop,this.options.columnFields.allowFilter,this.options.columnFields.allowGrouping,this.options.columnFields.allowResize,this.options.columnFields.canSelect,this.options.columnFields.cellTemplateUrl,this.options.columnFields.columns,this.options.columnFields.contentAlignment,
this.options.columnFields.contextMenu,this.options.columnFields.editorType,this.options.columnFields.editorSettings,this.options.columnFields.editorTemplate,this.options.columnFields.filterParams,this.options.columnFields.fixed,this.options.columnFields.fixedWidth,this.options.columnFields.footerAlignment,this.options.columnFields.footerContent,this.options.columnFields.footerText,this.options.columnFields.footerTooltip,this.options.columnFields.groupText,this.options.columnFields.headerAlignment,
this.options.columnFields.headerContent,this.options.columnFields.headerText,this.options.columnFields.headerTooltip,this.options.columnFields.icon,this.options.columnFields.id,this.options.columnFields.minWidth,this.options.columnFields.maxWidth,this.options.columnFields.pid,this.options.columnFields.selected,this.options.columnFields.style,this.options.columnFields.visible,this.options.columnFields.width],b?b:null)};c.prototype.exportRowsToJSON=function(a,b,e){b=b?b:null;var d=0==e?this.rows:this.getFullList();
a=a?a:[this.options.rowFields.allowCellFocus,this.options.rowFields.allowDrag,this.options.rowFields.allowDrop,this.options.rowFields.allowEdit,this.options.rowFields.allowFocus,this.options.rowFields.autoCheck,this.options.rowFields.canSelect,this.options.rowFields.cells,this.options.rowFields.checked,this.options.rowFields.checkState,this.options.rowFields.content,this.options.rowFields.contextMenu,this.options.rowFields.gid,this.options.rowFields.enabled,this.options.rowFields.expanded,this.options.rowFields.fixed,
this.options.rowFields.hasChildren,this.options.rowFields.icon,this.options.rowFields.id,this.options.rowFields.pid,this.options.rowFields.selected,this.options.rowFields.statusIcon,this.options.rowFields.style,this.options.rowFields.text,this.options.rowFields.tooltip,this.options.rowFields.value,this.options.rowFields.visible,this.options.cellFields.allowDrag,this.options.cellFields.allowEdit,this.options.cellFields.cid,this.options.cellFields.content,this.options.cellFields.contextMenu,this.options.cellFields.editorSettings,
this.options.cellFields.enabled,this.options.cellFields.isGroup,this.options.cellFields.rid,this.options.cellFields.selected,this.options.cellFields.style,this.options.cellFields.tag,this.options.cellFields.text,this.options.cellFields.tooltip,this.options.cellFields.value,this.options.cellFields.valueID,this.options.cellFields.valueType];0==e&&a.push(this.options.rowFields.rows);return JSON.stringify(d,a,b)};c.prototype.filter=function(a,b){if(a)a[this.options.columnFields.filterParams]=b;else for(var e=
0;e<this.currentColumnList.length;e++)this.currentColumnList[e].data[this.options.columnFields.filterParams]=null;this.updateLayout();this.change.emit({type:"filtering"})};c.prototype.changeCursor=function(a){a="default";if(this.isEnabled)if(this.isDragActive&&this.dragMode==integralui_core_1.IntegralUIDragDropDisplayMode.Handle)a="move";else if(0<=this.resizeColumnIndex||this.isColumnResizing)a="ew-resize";this.ctrlCursor=a};c.prototype.checkStatus=function(a){var b=!1;switch(a){case "column-reorder":b=
this.columnReorderActive}return b};c.prototype.cloneRow=function(a){return this.dataService.clone(a,this.rowDataKey)};c.prototype.createCloneList=function(a){for(var b=[],e=0;e<a.length;e++)b.push(this.cloneRow(a[e]));return b};c.prototype.getCellByColumnId=function(a,b){var e=null;if(a)for(var d=0;d<a.length;d++)if(a[d][this.options.cellFields.cid]==b){e=a[d];break}return e};c.prototype.getCellWidth=function(a,b){var e=this.getColumnWidth(b);b&&this.getColumnIndexFromList(b)==this.expandColIndex&&
(e-=a.indent);return 0<e?e:0};c.prototype.getColumnAllowResize=function(a){return(a=a[this.options.columnFields.allowResize])?{left:this.commonService.isFieldAvailable(a.left,!0),right:this.commonService.isFieldAvailable(a.right,!0)}:{left:!0,right:!0}};c.prototype.getColumnById=function(a){var b=null,e=this.dataService.getList(null,this.columnDataKey);if(e)for(var d=0;d<e.length;d++)if(e[d][this.options.columnFields.id]==a){b=e[d];break}return b};c.prototype.getColumnCurrentIndex=function(a){return a?
this.getColumnIndexFromList(a):-1};c.prototype.getColumnIndexFromList=function(a){for(var b=-1,e=0;e<this.currentColumnList.length;e++)if(this.currentColumnList[e].data==a){b=e;break}return b};c.prototype.getColumnIndex=function(a){var b=this.dataService.getList(null,this.columnDataKey);return b?b.indexOf(a):-1};c.prototype.getColumnRealIndex=function(a){var b=this.dataService.getList(null,this.columnDataKey);return 0<=a&&a<b.length&&a<this.currentColumnList.length?b.indexOf(this.currentColumnList[a].data):
-1};c.prototype.getPrevColumnIndex=function(a){var b=this.dataService.getList(null,this.columnDataKey);a=b?b.indexOf(a):-1;return 0<a?a-1:-1};c.prototype.getNextColumnIndex=function(a){var b=this.dataService.getList(null,this.columnDataKey);a=b?b.indexOf(a):-1;return b&&a<b.length-1?a+1:b.length-1};c.prototype.getLastColumnIndex=function(){var a=this.dataService.getList(null,this.columnDataKey);return a?a.length-1:-1};c.prototype.getColumnWidth=function(a,b){var e=this.options.columnFields.width;
switch(b){case "min":return e=this.options.columnFields.minWidth,a&&void 0!=a[e]?a[e]:0;case "max":return e=this.options.columnFields.maxWidth,a&&void 0!=a[e]?a[e]:9999999}return a&&void 0!=a[e]?a[e]:100};c.prototype.setColumnWidth=function(a,b){if(a&&1!=a[this.options.columnFields.fixedWidth]){var e=this.getColumnWidth(a,"min"),d=this.getColumnWidth(a,"max");e=Math.min(d,Math.max(e,b));a[this.options.columnFields.width]=1<e?e:0}};c.prototype.getPrevColumn=function(a,b){var e=null,d=this.getColumnIndexFromList(a)-
1;if(0<=d)for(;0<=d;d--){var c=this.getColumnWidth(this.currentColumnList[d].data),f=this.getColumnWidth(this.currentColumnList[d].data,"min");c=b?!0:c>f;if(!this.isColumnWidthFixed(d)&&c){e=this.currentColumnList[d].data;break}}return e};c.prototype.getExpandingColumn=function(){return 0<=this.expandColIndex&&this.expandColIndex<this.currentColumnList.length?this.currentColumnList[this.expandColIndex].data:null};c.prototype.getFilterTree=function(a){for(var b=null,e=0;e<this.currentColumnList.length;e++)if(this.currentColumnList[e].data==
a){b=this.currentColumnList[e].filter;break}return b};c.prototype.getCurrentList=function(){for(var a=[],b=0;b<this.currentRowList.length;b++)a.push(this.currentRowList[b].data);return a};c.prototype.getList=function(a,b){switch(a){case "current":return this.getCurrentList();case "selected":return this.currentSelectedRows}return this.dataService.getList(b,this.rowDataKey)};c.prototype.getFullList=function(){return[]};c.prototype.getTopRow=function(){return 0<this.scrollRowList.length?this.scrollRowList[0].data:
null};c.prototype.getObjFromRow=function(a){for(var b=null,e=0;e<this.currentRowList.length;e++)if(this.currentRowList[e].data==a){b=this.currentRowList[e];break}return b};c.prototype.createScrollObjFromRow=function(a,b,e){return null};c.prototype.getObjIndexFromScrollList=function(a){for(var b=-1,e=0;e<this.scrollRowList.length;e++)if(this.scrollRowList[e].data==a){b=e;break}return b};c.prototype.getRowCurrentIndex=function(a){return a?(a=this.getObjFromRow(a))&&this.currentRowList?this.currentRowList.indexOf(a):
-1:-1};c.prototype.getRowIndent=function(a,b){var e=this.columnPadding.left;this.isExpandBoxAllowed(b)&&(e+=a.indent);return e};c.prototype.getRowLevel=function(a){return 0};c.prototype.getRowFromComponent=function(a){return null};c.prototype.isChildOf=function(a,b){return!1};c.prototype.isColumnVisible=function(a){return a&&0!=a[this.options.columnFields.visible]?!0:!1};c.prototype.isColumnWidthFixed=function(a){return 0<=a&&a<this.currentColumnList.length?1==this.currentColumnList[a].data[this.options.columnFields.fixedWidth]:
!1};c.prototype.isComponentIndexInRange=function(a){return this.rowList?0<=a&&a<this.rowList.length:!1};c.prototype.isExpandBoxAllowed=function(a){return a?this.getColumnIndexFromList(a)==this.expandColIndex:!1};c.prototype.isIndexInRange=function(a,b){return b?0<=a&&a<b.length:!1};c.prototype.isRowAllowed=function(a,b){if(0==a[this.options.rowFields.visible])return!1;if(0==this.options.allowFilter)return!0;var e=!0;if(a)for(var d,c,f=0;f<a[this.options.rowFields.cells].length;f++){e=!0;c=a[this.options.rowFields.cells][f];
d=c[this.options.cellFields.cid];d=this.getColumnById(d);!d&&f<this.currentColumnList.length&&(d=this.currentColumnList[f].data);if(d&&d[this.options.columnFields.filterParams]){var g=d[this.options.columnFields.filterParams],k=c[this.options.cellFields.value]?c[this.options.cellFields.value]:c[this.options.cellFields.text];g&&(g.callback?e=g.callback(k,c,a):(e=this.filterService.match(k,g.conditions,g.formula,this.getFilterTree(d),g.caseSensitive),!e&&g.allowParent&&(e=this.filterIsThereChildren(a,
b))))}if(!e)break}return e};c.prototype.filterIsThereChildren=function(a,b){var e=!1,d=a[this.options.rowFields.rows];if(d)for(var c=0;c<d.length&&!(e=this.isRowAllowed(d[c],b));c++);return e};c.prototype.isRowEnabled=function(a){return!0};c.prototype.isRowFixed=function(a){return!1};c.prototype.isRowHovered=function(a){return this.isDragActive||this.isScrollTimerActive||!a||a!=this.hoverRow?!1:!0};c.prototype.isRowSelected=function(a){return a&&1==a[this.options.rowFields.selected]?!0:!1};c.prototype.isParentOf=
function(a,b){return!1};c.prototype.processStateChanged=function(){this.updateLayout()};c.prototype.updateExpandStatus=function(){};c.prototype.moveColumn=function(a,b,e,d){if(a){var c=-1;switch(b){case integralui_core_1.IntegralUIMoveDirection.After:c=e?this.getNextColumnIndex(e):-1;break;case integralui_core_1.IntegralUIMoveDirection.At:c=d;break;case integralui_core_1.IntegralUIMoveDirection.Before:c=e?this.getColumnIndex(e):-1;break;case integralui_core_1.IntegralUIMoveDirection.First:c=0;break;
case integralui_core_1.IntegralUIMoveDirection.Last:c=this.getLastColumnIndex();break;case integralui_core_1.IntegralUIMoveDirection.Left:c=this.getPrevColumnIndex(a);break;case integralui_core_1.IntegralUIMoveDirection.Right:c=this.getNextColumnIndex(a)}(b=this.dataService.getList(null,this.columnDataKey))&&0<=c&&c<b.length&&(this.allowUpdate=!1,e=b.indexOf(a),this.moveObject(e,c,b),this.allowUpdate=!0,this.columnOrderChanged.emit({column:a}),this.updateLayout())}};c.prototype.cellGotFocus=function(a){this.isEnabled&&
this.refresh()};c.prototype.cellLostFocus=function(a){this.isEnabled&&this.refresh()};c.prototype.onContentScroll=function(a){a.srcElement.scrollTop=0;a.srcElement.scrollLeft=0;a.target.scrollTop=0;a.target.scrollLeft=0};c.prototype.onGridScroll=function(a){a.srcElement.scrollTop=0;a.srcElement.scrollLeft=0;a.target.scrollTop=0;a.target.scrollLeft=0};c.prototype.cellMouseEnter=function(a,b){this.isEnabled&&(this.cellHover.emit({cell:b.data}),this.hoverCell=b)};c.prototype.cellMouseLeave=function(a){this.hoverCell=
null};c.prototype.cellMouseDown=function(a,b){if(this.isEnabled&&1==a.which&&(this.currentFocusCell=b,b.editorType))switch(b.editorType){case integralui_core_1.IntegralUIEditorType.CheckBox:this.editCheckBoxValue(b)}};c.prototype.cellMouseUp=function(a,b,e,d){if(b.isEditorEnabled)switch(b.editorType){case integralui_core_1.IntegralUIEditorType.Date:this.openDropDown(a,b,e,d);break;case integralui_core_1.IntegralUIEditorType.DropList:this.openDropDown(a,b,e,d);break;case integralui_core_1.IntegralUIEditorType.Numeric:this.openEditor(a,
b,"numeric");break;case integralui_core_1.IntegralUIEditorType.TextBox:this.openEditor(a,b)}};c.prototype.cellTouchEnd=function(a,b,e,d){switch(b.editorType){case integralui_core_1.IntegralUIEditorType.CheckBox:this.editCheckBoxValue(b);break;case integralui_core_1.IntegralUIEditorType.Date:this.openDropDown(a,b,e,d);break;case integralui_core_1.IntegralUIEditorType.DropList:this.openDropDown(a,b,e,d);break;case integralui_core_1.IntegralUIEditorType.Numeric:this.openEditor(a,b,"numeric");break;case integralui_core_1.IntegralUIEditorType.TextBox:this.openEditor(a,
b)}};c.prototype.openDropDown=function(a,b,e,d){};c.prototype.cellKeyDown=function(a,b){if(this.isEnabled){var e={cancel:!1,cell:b.data,event:a};this.keyDown.emit(e);switch(a.keyCode){case 13:this.beforeEdit.emit(e);break;case 33:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processPageUpKey(b));break;case 34:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processPageDownKey(b));break;case 35:!e.cancel&&this.options.allowFocus&&
(a.preventDefault(),this.isKeyboardActive=!0,this.processEndKey(b));break;case 36:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processHomeKey(b));break;case 37:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processLeftArrowKey(b));break;case 38:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processUpArrowKey(b));break;case 39:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),
this.isKeyboardActive=!0,this.processRightArrowKey(b));break;case 40:!e.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processDownArrowKey(b))}}this.isKeyPressed=!0};c.prototype.cellKeyPress=function(a,b){var e={cancel:!1,cell:b.data,event:a};this.isEnabled&&this.keyPress.emit(e)};c.prototype.cellKeyUp=function(a,b){var e={cancel:!1,cell:b.data,event:a};this.isEnabled&&this.keyUp.emit(e);this.isKeyPressed=!1};c.prototype.isCellFocused=function(a){return this.currentFocusCell?
a.data==this.currentFocusCell.data:!1};c.prototype.processDownArrowKey=function(a,b){var e=this.getDownCell(this.isKeyPressed?this.currentFocusCell:a);if(e&&!e.isEmpty){this.updateFocusCell(e);var d=this.getRowFromCell(e);d&&(this.processRowSelection(b,d.data),this.isLastRow(e)&&(this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y+2*this.avgRowHeight}),this.currentFocusCell.rowIndex-=2),this.refresh())}return e&&!e.isEmpty?e:null};c.prototype.processEndKey=function(a,b){var e=null;
if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,y:this.maxScrollPos.y});var d=this;setTimeout(function(){if(d.visibleRange<=d.scrollRowList.length){var c=d.getLastScrollIndex();0<=c&&(c=d.scrollRowList[c])&&c.cells&&0<=a.colIndex&&a.colIndex<c.cells.length&&(e=c.cells[a.colIndex],d.updateFocusCell(e),d.processRowSelection(b,c.data))}},1)}return e};c.prototype.processHomeKey=function(a,b){var e=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,
y:0});var d=this;setTimeout(function(){var c=d.scrollRowList[0];c&&c&&c.cells&&0<=a.colIndex&&a.colIndex<c.cells.length&&(e=c.cells[a.colIndex],d.updateFocusCell(e),d.processRowSelection(b,c.data))},1)}return e};c.prototype.processLeftArrowKey=function(a){if((a=this.getPrevCell(this.isKeyPressed?this.currentFocusCell:a))&&!a.isEmpty){this.updateFocusCell(a);this.isFirstCell(a)&&this.scrollPos({x:this.currentScrollPos.x-2*a.width,y:this.currentScrollPos.y});var b=this;setTimeout(function(){b.refresh()},
1)}return a&&!a.isEmpty?a:null};c.prototype.processPageDownKey=function(a,b){var e=null,d=this;0<this.scrollRowList.length&&(d.scrollPos({x:d.currentScrollPos.x,y:d.currentScrollPos.y+d.avgRowHeight*(d.visibleRange-1)}),setTimeout(function(){var c=0<=a.rowIndex&&a.rowIndex<d.visibleRange?a.rowIndex:d.visibleRange-1;d.currentScrollPos.y==d.maxScrollPos.y&&(c=d.getLastScrollIndex());0<=c&&(c=d.scrollRowList[c])&&c.cells&&0<=a.colIndex&&a.colIndex<c.cells.length&&(e=c.cells[a.colIndex],d.updateFocusCell(e),
d.processRowSelection(b,c.data))},1));return e};c.prototype.processPageUpKey=function(a,b){var e=null,d=this;0<d.scrollRowList.length&&(d.scrollPos({x:d.currentScrollPos.x,y:d.currentScrollPos.y-d.avgRowHeight*(d.visibleRange-1)}),setTimeout(function(){var c=0<=a.rowIndex&&a.rowIndex<d.visibleRange?a.rowIndex:0;0==d.currentScrollPos.y&&(c=0);(c=d.scrollRowList[c])&&c.cells&&0<=a.colIndex&&a.colIndex<c.cells.length&&(e=c.cells[a.colIndex],d.updateFocusCell(e),d.processRowSelection(b,c.data))},1));
return e};c.prototype.processRightArrowKey=function(a){if((a=this.getNextCell(this.isKeyPressed?this.currentFocusCell:a))&&!a.isEmpty){this.updateFocusCell(a);this.isLastCell(a)?this.scrollPos({x:this.currentScrollPos.x+2*a.width,y:this.currentScrollPos.y}):a.colIndex>=this.currentColumnList.length-2&&this.scrollPos({x:this.maxScrollPos.x,y:this.currentScrollPos.y});var b=this;setTimeout(function(){b.refresh()},1)}return a&&!a.isEmpty?a:null};c.prototype.processUpArrowKey=function(a,b){var e=this.getUpCell(a);
if(e&&!e.isEmpty){this.updateFocusCell(e);var c=this.getRowFromCell(e);c&&(this.processRowSelection(b,c.data),this.isFirstRow(e)&&(this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y-this.avgRowHeight}),this.currentFocusCell.rowIndex++))}return e&&!e.isEmpty?e:null};c.prototype.getDownCell=function(a){if(a&&0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var b=a.rowIndex<this.scrollRowList.length-1?a.rowIndex+1:-1;return(b=0<=b?this.scrollRowList[b]:null)&&0<=a.colIndex&&a.colIndex<
b.cells.length?b.cells[a.colIndex]:null}return null};c.prototype.getNextCell=function(a){if(a&&0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var b=this.scrollRowList[a.rowIndex];a=a.colIndex;a=0<=a&&a<this.viewIndexRange.middle&&a<b.cells.length-1?a+1:this.viewIndexRange.middle-this.viewIndexRange.left;return 0<=a?b.cells[a]:null}return null};c.prototype.getLastScrollIndex=function(){for(var a=0,b=0;b<this.scrollRowList.length;b++)if(this.scrollRowList[b].isEmpty){a=b-1;break}return a};c.prototype.getPrevCell=
function(a){if(a&&0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var b=this.scrollRowList[a.rowIndex];a=a.colIndex;a=0<a&&a<b.cells.length?a-1:0;return 0<=a?b.cells[a]:null}return null};c.prototype.getUpCell=function(a){if(a&&0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var b=0<a.rowIndex?a.rowIndex-1:-1;return(b=0<=b?this.scrollRowList[b]:null)&&0<=a.colIndex&&a.colIndex<b.cells.length?b.cells[a.colIndex]:null}return null};c.prototype.isFirstCell=function(a){return 0==a.colIndex?!0:
!1};c.prototype.isFirstRow=function(a){return 0==a.rowIndex?!0:!1};c.prototype.isLastCell=function(a){return a.colIndex==this.viewIndexRange.middle-this.viewIndexRange.left?!0:!1};c.prototype.isLastRow=function(a){return a.rowIndex==this.visibleRange-2?!0:!1};c.prototype.getRowFromCell=function(a){return 0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length?this.scrollRowList[a.rowIndex]:null};c.prototype.moveFocusFromCell=function(a,b){if(!this.options.allowFocus)return null;var e=null,c=this.getObjFromCell(a);
if(c)switch(b){case "down":e=this.processDownArrowKey(c);break;case "end":e=this.processEndKey(c);break;case "home":e=this.processHomeKey(c);break;case "left":e=this.processLeftArrowKey(c);break;case "pagedown":e=this.processPageDownKey(c);break;case "pageup":e=this.processPageUpKey(c);break;case "right":e=this.processRightArrowKey(c);break;case "up":e=this.processUpArrowKey(c)}return e?e.data:null};c.prototype.getObjFromCell=function(a){for(var b=null,e=0;e<this.scrollRowList.length;e++)for(var c=
this.scrollRowList[e],h=0;h<c.cells.length;h++){var f=c.cells[h];if(f.data==a){b=f;break}}return b};c.prototype.updateFocusCell=function(a){a?(this.currentFocusCell={},this.currentFocusCell.isEmpty=!1,this.currentFocusCell.data=a.data,this.currentFocusCell.colIndex=a.colIndex,this.currentFocusCell.rowIndex=a.rowIndex):this.currentFocusCell=null};c.prototype.onWindowKeyDown=function(a){this.isEnabled&&this.isKeyboardActive&&a.preventDefault();this.isDragActive&&27==a.keyCode&&(this.dropMark(a),this.clearDragDropSettings(),
this.dragMode==integralui_core_1.IntegralUIDragDropDisplayMode.Handle&&this.updateScrollRowList())};c.prototype.onWindowKeyUp=function(a){this.isKeyboardActive=!1};c.prototype.getContentSize=function(){return{width:0,height:0}};c.prototype.refresh=function(a){this.clearComponentSelection();for(a=0;a<this.currentSelectedRows.length;a++){var b=this.getRowCurrentIndex(this.currentSelectedRows[a]);this.isComponentIndexInRange(b)&&(this.rowList[b].state|=integralui_core_1.IntegralUIObjectState.selected)}};
c.prototype.suspendLayout=function(){this.allowUpdate=!1};c.prototype.resumeLayout=function(){this.allowUpdate=!0;this.updateLayout()};c.prototype.updateCurrentLayout=function(){};c.prototype.updateLayout=function(){};c.prototype.updateColumnWidth=function(){if(this.isAutoSizeColumnsActive){for(var a=0,b,e,c=0,h=[],f=0;f<this.currentColumnList.length;f++)b=this.getColumnWidth(this.currentColumnList[f].data),e=this.getColumnWidth(this.currentColumnList[f].data,"min"),b>=e&&(a+=b+this.columnPadding.left+
this.columnPadding.right+6,1!=this.currentColumnList[f].data[this.options.columnFields.fixedWidth]&&(c++,h.push(this.currentColumnList[f])));0<c&&(b=this.isVerScrollVisible()?20:0,this.updateColumnWidthByFactor(h,(this.clientRect.width-b-a)/c))}};c.prototype.updateColumnWidthByFactor=function(a,b){var e=0;var c=0;for(var h=[],f=0;f<a.length;f++){var g=this.getColumnWidth(a[f].data);var k=this.getColumnWidth(a[f].data,"min");1==a[f].data[this.options.columnFields.fixedWidth]&&(k=g);g>=k&&(g+b<=k?(e+=
g+b-k,this.setColumnWidth(a[f].data,k),this.updateCellWidth(a[f].data)):(h.push(a[f]),c++))}if(0<c)if(g=e/c,0!=g)this.updateColumnWidthByFactor(h,b+g);else for(f=0;f<h.length;f++)g=this.getColumnWidth(h[f].data)+b,this.setColumnWidth(h[f].data,g),this.updateCellWidth(h[f].data)};c.prototype.checkWidthChanges=function(){if(this.isAutoSizeColumnsActive){for(var a=0,b,c=0;c<this.currentColumnList.length;c++)b=this.getColumnWidth(this.currentColumnList[c].data),this.getColumnWidth(this.currentColumnList[c].data,
"min"),a+=b+this.columnPadding.left+this.columnPadding.right+6;c=this.isVerScrollVisible()?20:0;a=this.clientRect.width-c-a-2;if(0<a)for(c=this.currentColumnList.length-1;0<=c;c--)if(!this.isColumnWidthFixed(c)){b=this.getColumnWidth(this.currentColumnList[c].data)+a;this.setColumnWidth(this.currentColumnList[c].data,b);this.updateCellWidth(this.currentColumnList[c].data);break}}};c.prototype.updateCellWidth=function(a){for(var b=0;b<this.scrollRowList.length;b++)for(var c=this.scrollRowList[b],d=
this.getColumnCurrentIndex(a),h=0;h<c.cells.length;h++)if(c.cells[h].colIndex==d-this.viewIndexRange.left){d=this.getCellWidth(c,a);if(this.getColumnIndexFromList(a)==this.expandColIndex){var f=this.getColumnWidth(a);f=0<f?f:this.columnPadding.left;c.cells[h].indent=0==d?f:this.getRowIndent(c,a)}c.cells[h].width=d;break}};c.prototype.updateRange=function(){};c.prototype.getFooterBottomPos=function(){var a=this.isHorScrollVisible()?16:0;this.isPaginationEnabled()&&(a+=this.paginatorHeight);return a};
c.prototype.onCtrlMouseEnter=function(a){this.isEnabled&&1==a.buttons&&this.cloneElem&&(this.cloneElem.style.display="block");this.elemRenderer.setElementStyle(this.elemRef.nativeElement,"cursor","default")};c.prototype.onCtrlMouseLeave=function(a){this.isEnabled&&1==a.buttons&&this.cloneElem&&(this.cloneElem.style.display="none");this.stopScrollTimer()};c.prototype.currentPage=function(a){this.currentPageNumber!=a&&1<=a&&a<=this.pageList.length&&(this.currentPageNumber=a,this.updateCurrentLayout());
return this.currentPageNumber};c.prototype.getMaxPages=function(){return this.pageList?this.pageList.length:0};c.prototype.firstPage=function(){1!=this.currentPageNumber&&(this.currentPageNumber=1,this.updateCurrentLayout())};c.prototype.lastPage=function(){this.currentPageNumber!=this.pageList.length&&(this.currentPageNumber=this.pageList.length,this.updateCurrentLayout())};c.prototype.nextPage=function(){this.currentPageNumber<this.pageList.length&&(this.currentPageNumber++,this.updateCurrentLayout())};
c.prototype.prevPage=function(){1<this.currentPageNumber&&(this.currentPageNumber--,this.updateCurrentLayout())};c.prototype.resetPageNumber=function(){this.currentPageNumber=1};c.prototype.updatePageNumber=function(){this.currentPageNumber>this.pageList.length&&(0==this.pageList.length?this.resetPageNumber():this.currentPageNumber=this.pageList.length)};c.prototype.updatePaging=function(a){this.options.paging=a?{enabled:this.commonService.isFieldAvailable(a.enabled,!1),showControlPanel:this.commonService.isFieldAvailable(a.showControlPanel,
!0),pageSize:this.commonService.isFieldAvailable(a.pageSize,100)}:{enabled:!1,showControlPanel:!0,pageSize:100}};c.prototype.paginatorPageChanged=function(a){this.currentPageNumber=a.value;this.updateCurrentLayout();this.pageChanged.emit({page:this.currentPageNumber,maxPages:this.getMaxPages(),pageSize:this.options.paging.pageSize})};c.prototype.isPaginationEnabled=function(){return this.options.paging.enabled&&this.options.paging.showControlPanel};c.prototype.getColumnOpacity=function(a){return this.columnReorderActive&&
a.data==this.reorderColumn&&this.isGridHovered?0:1};c.prototype.updateOrignalScrollColumnList=function(){for(var a=this.originalScrollColumnList.length=0;a<this.scrollColumnList.length;a++)this.originalScrollColumnList.push(this.scrollColumnList[a])};c.prototype.updateReorderColumnPos=function(){if(this.reorderColumn){for(var a=0,b,c=0;c<this.originalScrollColumnList.length&&this.originalScrollColumnList[c]!=this.reorderColumnObj;c++)b=this.getColumnWidth(this.originalScrollColumnList[c].data),a+=
b+this.columnPadding.left+this.columnPadding.right+6;this.reorderColumnObjPos.left=a+this.reorderColumnCurrentPos.left-this.reorderColumnStartPos.left;var d=this.getHeaderRect();this.reorderNewColIndex=this.reorderColIndex=this.getColumnIndexFromScrollList(this.reorderColumn);for(c=a=0;c<this.originalScrollColumnList.length;c++)if(b=this.getColumnWidth(this.originalScrollColumnList[c].data)+this.columnPadding.left+this.columnPadding.right+6,a+=b,0!=this.originalScrollColumnList[c].data[this.options.columnFields.allowDrop]&&
this.reorderColumnCurrentPos.left-d.left<a){this.reorderNewColIndex=c;break}this.reorderColIndex!=this.reorderNewColIndex&&this.moveObject(this.reorderColIndex,this.reorderNewColIndex,this.scrollColumnList)}};c.prototype.getHeaderRect=function(){return{top:0,right:0,bottom:0,left:0,height:0,width:0,x:0,y:0}};c.prototype.resetReorderColumnSettings=function(){this.reorderColumn=this.reorderColumnObj=null;this.startColumnReorder=this.columnReorderActive=!1};c.prototype.restoreColumnOrder=function(){if(0<
this.originalScrollColumnList.length)for(var a=this.scrollColumnList.length=0;a<this.originalScrollColumnList.length;a++)this.scrollColumnList.push(this.originalScrollColumnList[a])};c.prototype.getColumnIndexFromScrollList=function(a){for(var b=-1,c=0;c<this.scrollColumnList.length;c++)if(this.scrollColumnList[c].data==a){b=c;break}return b};c.prototype.moveObject=function(a,b,c){this.isIndexInRange(a,c)&&this.isIndexInRange(b,c)&&c.splice(b,0,c.splice(a,1)[0])};c.prototype.scrollPos=function(a){a&&
(this.currentScrollPos={x:Math.max(0,Math.min(a.x,this.maxScrollPos.x)),y:Math.max(0,Math.min(a.y,this.maxScrollPos.y))});return{x:Math.floor(this.currentScrollPos.x),y:Math.floor(this.currentScrollPos.y)}};c.prototype.changeHorizontalScrollPos=function(a){this.currentScrollPos.x=Math.max(0,Math.min(a,this.maxScrollPos.x));this.currentScrollPos.x!=this.prevScrollPos.x&&(this.updateRange(),this.scrollPosChanged.emit({value:this.scrollPos()}),this.prevScrollPos.x=this.currentScrollPos.x)};c.prototype.changeVerticalScrollPos=
function(a){this.currentScrollPos.y=Math.max(0,Math.min(a,this.maxScrollPos.y));this.currentScrollPos.y!=this.prevScrollPos.y&&(this.updateView(),this.scrollPosChanged.emit({value:this.scrollPos()}),this.prevScrollPos.y=this.currentScrollPos.y)};c.prototype.gridMouseWheel=function(a){a.preventDefault();this.hideCalendar();this.hideDropList();if(this.isEnabled){this.hoverRow=null;var b=Math.max(-1,Math.min(1,a.wheelDelta||-a.detail)),c=5;switch(this.mouseWheelSpeed){case integralui_core_1.IntegralUISpeedMode.VerySlow:c=
15;break;case integralui_core_1.IntegralUISpeedMode.Slow:c=9;break;case integralui_core_1.IntegralUISpeedMode.Fast:c=3;break;case integralui_core_1.IntegralUISpeedMode.VeryFast:c=1}this.isVerScrollVisible()&&(c=Math.floor(this.clientRect.height/c),this.mouseWheelSpeed==integralui_core_1.IntegralUISpeedMode.VerySlow&&0<this.avgRowHeight&&(c=this.avgRowHeight),this.changeVerticalScrollPos(this.currentScrollPos.y+c*b*-1))}a.stopPropagation()};c.prototype.isVerScrollVisible=function(){return this.isEnabled&&
this.options.showScroll.vertical&&0<this.scrollSize.height?!0:!1};c.prototype.isHorScrollVisible=function(){return this.isEnabled&&this.options.showScroll.horizontal&&0<this.scrollSize.width?!0:!1};c.prototype.onVerticalScrollStart=function(a){this.hoverRow=null;this.isScrollActive=!0};c.prototype.onVerticalScrollEnd=function(a){this.isScrollActive=!1};c.prototype.onVerticalScrollChanged=function(a){this.changeVerticalScrollPos(a.value)};c.prototype.onHorizontalScrollStart=function(a){this.hoverRow=
null;this.isScrollActive=!0};c.prototype.onHorizontalScrollEnd=function(a){this.isScrollActive=!1};c.prototype.onHorizontalScrollChanged=function(a){this.currentScrollPos.x=a.value;this.scrollPosChanged.emit({value:this.scrollPos()});var b=this,c=setTimeout(function(){b.updateRange();clearTimeout(c)},1)};c.prototype.updateView=function(a){this.currentIndex=0<this.avgRowHeight?Math.floor(this.currentScrollPos.y/this.avgRowHeight):0;this.currentIndex!=this.prevIndex&&(this.updateScrollRowList(a),this.prevIndex=
this.currentIndex)};c.prototype.processScroll=function(a,b,c){if(this.isEnabled)if(this.isVerScrollVisible()){var d=this.commonService.getShiftPos();a=this.commonService.getMousePos(a);a.x-=d.x;a.y-=d.y;d=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild);b=d.top+this.headerHeight+(b?b:0)+25;c=d.bottom-this.footerHeight-(c?c:0)-25;this.isHorScrollVisible()&&(c-=16);a.y<b&&0<this.currentScrollPos.y?this.startScrollTimer(!1):a.y>c&&this.currentScrollPos.y<this.maxScrollPos.y?
this.startScrollTimer(!0):this.stopScrollTimer()}else this.stopScrollTimer()};c.prototype.startScrollTimer=function(a,b){var c=this;c.removeDropMark();c.isScrollTimerActive||(c.accelerator=.5,c.scrollCount=0,c.isScrollTimerActive=!0,c.scrollTimerID=setInterval(function(){c.scrollTimerElapsed(a)},b?b:100))};c.prototype.stopScrollTimer=function(){this.scrollTimerID&&(clearInterval(this.scrollTimerID),this.scrollTimerID=null);this.accelerator=.5;this.scrollCount=0;this.isScrollTimerActive=!1};c.prototype.scrollTimerElapsed=
function(a){var b=this.currentScrollPos;0===this.scrollCount&&(this.scrollCount=5);this.scrollCount+=5;this.accelerator+=.5;var c=this.scrollCount+=Math.floor(this.accelerator);this.currentScrollPos.y=a?this.currentScrollPos.y+c>this.maxScrollPos.y?this.maxScrollPos.y:this.currentScrollPos.y+c:0>this.currentScrollPos.y-c?0:this.currentScrollPos.y-c;(0>=b.y||this.currentScrollPos.y<b.y)&&this.stopScrollTimer()};c.prototype.scrollTo=function(a){a&&(a=this.getRowCurrentIndex(a),0<=a&&this.scrollPos({x:this.currentScrollPos.x,
y:this.avgRowHeight*(a+1-this.visibleRange/2)}),this.updateLayout())};c.prototype.findRowById=function(a){return this.dataService.findObjectById(a,this.rowDataKey)};c.prototype.findRowByText=function(a){return this.dataService.findObjectByText(a,this.rowDataKey)};c.prototype.clearSelection=function(){this.clearPrevSelection();this.refresh()};c.prototype.processColumnSelection=function(a,b,c){if(b)0!=b[this.options.columnFields.canSelect]&&(a=!0,this.currentSelectedColumn&&(a=!this.commonService.isEqual(this.currentSelectedColumn[this.options.columnFields.id],
b[this.options.columnFields.id])),c={cancel:!1,obj:b},this.beforeSelect.emit(c),a&&1!=c.cancel&&(this.currentSelectedColumn&&(this.currentSelectedColumn[this.options.columnFields.selected]=!1,this.refresh(this.currentSelectedColumn)),this.currentSelectedColumn=b,b[this.options.columnFields.selected]=!0,this.refresh(b),this.callAfterSelectEvent(b)));else return this.currentSelectedColumn};c.prototype.clearComponentSelection=function(){this.rowList.forEach(function(a){return a.state&=~integralui_core_1.IntegralUIObjectState.selected})};
c.prototype.clearPrevSelection=function(a){for(var b=0;b<this.currentSelectedRows.length;b++)a&&!this.commonService.isEqual(this.currentSelectedRows[b][this.options.rowFields.id],a[this.options.rowFields.id])?this.currentSelectedRows[b][this.options.rowFields.selected]=!1:a||(this.currentSelectedRows[b][this.options.rowFields.selected]=!1);this.currentSelectedRows.length=0;a&&this.isRowEnabled(a)&&this.currentSelectedRows.push(a)};c.prototype.isRowInSelectionList=function(a){var b=!1,c=this.currentSelectedRows;
if(a&&c)for(var d=0;d<c.length;d++)if(this.commonService.isEqual(c[d][this.options.rowFields.id],a[this.options.rowFields.id])){b=!0;break}return b};c.prototype.processRowSelection=function(a,b,c){if(b&&this.selectionMode!=integralui_core_1.IntegralUISelectionMode.None&&0!=b[this.options.rowFields.canSelect]){var d=0<this.currentSelectedRows.length;if(this.isRowEnabled(b)){var e=this.currentSelectedRow,f=!0;e&&(f=a&&(a.ctrlKey||a.metaKey)||!this.commonService.isEqual(e[this.options.rowFields.id],
b[this.options.rowFields.id])||0==e[this.options.rowFields.selected]);var g={cancel:!1,obj:b};this.beforeSelect.emit(g);if(1!=g.cancel)if(g=a&&(a.shiftKey||a.ctrlKey||a.metaKey)?!0:!1,f){this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiExtended&&(f=!this.isRowInSelectionList(b)||!g||a&&a.shiftKey);f&&(this.selectionMode==integralui_core_1.IntegralUISelectionMode.One?this.clearPrevSelection():a&&a.shiftKey?this.clearPrevSelection():g||this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiSimple||
1!=this.currentSelectedRows.length&&this.isRowInSelectionList(b)||this.clearPrevSelection());this.currentSelectedRow=b;if(a&&a.shiftKey&&this.selectionMode!=integralui_core_1.IntegralUISelectionMode.One){if(this.shiftFirstSelectedRow||(this.shiftFirstSelectedRow=e),a=this.getRowCurrentIndex(this.shiftFirstSelectedRow),c=this.getRowCurrentIndex(b),a>c&&(d=a,a=c,c=d),this.isIndexInRange(a,this.currentRowList)&&this.isIndexInRange(c,this.currentRowList))for(;a<=c;a++)0!=this.currentRowList[a].data[this.options.rowFields.canSelect]&&
(this.currentRowList[a].data[this.options.rowFields.selected]=!0,this.currentSelectedRows.push(this.currentRowList[a].data))}else g||this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiSimple?(a=null==b[this.options.rowFields.selected]||"undefined"==b[this.options.rowFields.selected]?!1:b[this.options.rowFields.selected],b[this.options.rowFields.selected]=!a,b[this.options.rowFields.selected]?this.isRowInSelectionList(b)||this.currentSelectedRows.push(b):this.currentSelectedRows=this.currentSelectedRows.filter(function(a){return a!=
b})):(b[this.options.rowFields.selected]=!0,this.isRowInSelectionList(b)||this.currentSelectedRows.push(b)),this.shiftFirstSelectedRow=null;this.callAfterSelectEvent(b);this.refresh()}else g||this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiSimple?(a=null===b[this.options.rowFields.selected]||"undefined"==b[this.options.rowFields.selected]?!1:b[this.options.rowFields.selected],c&&"undefined"!=c&&(a=c),b[this.options.rowFields.selected]=!a,b[this.options.rowFields.selected]?this.isRowInSelectionList(b)||
this.currentSelectedRows.push(b):this.currentSelectedRows=this.currentSelectedRows.filter(function(a){return a!=b}),this.shiftFirstSelectedRow=null,this.callAfterSelectEvent(b),this.refresh()):g||this.selectionMode&integralui_core_1.IntegralUISelectionMode.MultiSimple||1!=this.currentSelectedRows.length&&this.isRowInSelectionList(b)||(this.shiftFirstSelectedRow=null,this.clearPrevSelection(b),this.refresh(),d&&this.selectionChanged.emit(null))}else this.clearPrevSelection(),this.currentSelectedRow=
null,this.refresh(),d&&this.selectionChanged.emit(null)}};c.prototype.selectRows=function(a){if(a&&Array.isArray(a)){for(var b=this.currentSelectedRows.length=0;b<a.length;b++)a[b][this.options.rowFields.selected]=!0,this.currentSelectedRows.push(a[b]);0<a.length?(this.currentSelectedRow=a[a.length-1],this.callAfterSelectEvent(this.currentSelectedRow)):this.currentSelectedRow=null;this.refresh()}};c.prototype.updateRowSelection=function(a,b){var c=a&&(a.shiftKey||a.ctrlKey||a.metaKey)?!0:!1;this.selectionMode==
integralui_core_1.IntegralUISelectionMode.MultiExtended&&0!=b[this.options.rowFields.canSelect]&&0<this.currentSelectedRows.length&&!a.shiftKey&&!c&&1==a.which&&(c=this.currentSelectedRows.length,this.clearPrevSelection(),this.currentSelectedRow=b,b[this.options.rowFields.selected]=!0,this.currentSelectedRows.push(b),1<c&&this.callAfterSelectEvent(b),this.refresh())};c.prototype.sort=function(a,b,c){this.sortColumn=a;this.sortComparer=c;this.options.sorting=b;this.updateLayout();this.change.emit({type:"sorting"})};
c.prototype.getCellIndexInCollection=function(a,b,c){var d=-1;if(a)for(var e=0;e<a.length;e++)if(void 0==a[e][this.options.cellFields.cid]){d=b;break}else if(a[e][this.options.cellFields.cid]==c){d=e;break}return d};c.prototype.isSortingAllowed=function(){return this.options.sorting==integralui_core_1.IntegralUISortOrder.Ascending||this.options.sorting==integralui_core_1.IntegralUISortOrder.Descending};c.prototype.isSortingColumn=function(a){return a&&a==this.sortColumn?!0:!1};c.prototype.applySorting=
function(a){var b=this;if(a&&(!b.sortColumn||0!=b.sortColumn[b.options.columnFields.visible])){var c=b.getColumnCurrentIndex(b.sortColumn),d=0<=c?c:b.options.expandColIndex;if(d<b.currentColumnList.length){var h=b.currentColumnList[d].data[b.options.columnFields.id];b.sortColumn&&b.sortColumn[b.options.columnFields.comparer]?a.sort(b.sortColumn[b.options.columnFields.comparer]):b.sortComparer?a.sort(b.sortComparer):b.isSortingAllowed()&&a.sort(function(a,c){var e=null,f=null;if(a[b.options.rowFields.cells]){var g=
b.getCellIndexInCollection(a[b.options.rowFields.cells],d,h);0<=g&&((e=a[b.options.rowFields.cells][g][b.options.cellFields.value])||(e=a[b.options.rowFields.cells][g][b.options.cellFields.text]),b.commonService.isObject(e)&&(e=e.value?e.value:e.text))}c[b.options.rowFields.cells]&&(g=b.getCellIndexInCollection(c[b.options.rowFields.cells],d,h),0<=g&&((f=c[b.options.rowFields.cells][g][b.options.cellFields.value])||(f=c[b.options.rowFields.cells][g][b.options.cellFields.text]),b.commonService.isObject(f)&&
(f=f.value?f.value:f.text)));e=void 0!=e?e:null;f=void 0!=f?f:null;switch(b.options.sorting){case integralui_core_1.IntegralUISortOrder.Ascending:if(e<f)return-1;if(e>f)return 1;break;case integralui_core_1.IntegralUISortOrder.Descending:if(e>f)return-1;if(e<f)return 1;break;default:return 0}})}}};c.prototype.getColumnInlineStyle=function(a){var b={header:"",footer:""};a&&(b={header:this.commonService.isFieldAvailable(a.header,""),footer:this.commonService.isFieldAvailable(a.footer,"")});return b};
c.prototype.getRowInlineStyle=function(a,b){var c=a||{};b&&(c.display="none");return c};c.prototype.columnTouchStart=function(a,b){this.isEnabled&&this.processColumnSelection(a,b.data);a.stopPropagation()};c.prototype.rowTouchStart=function(a,b){this.isEnabled&&this.processRowSelection(a,b.data)};c.prototype.ctrlTouchStart=function(a){a.preventDefault();this.isEnabled&&(a=this.commonService.getTouchData(a))&&0<a.length&&(this.touchStartPos={x:a[0].pageX,y:a[0].pageY})};c.prototype.ctrlTouchEnd=function(a){var b=
this;if(b.isEnabled){(a=b.commonService.getTouchData(a))&&0<a.length&&(b.touchEndPos={x:a[0].pageX,y:a[0].pageY});var c=b.touchEndPos.x-b.touchStartPos.x,d=b.touchEndPos.y-b.touchStartPos.y,h=!1,f=!1,g=b.touchStartPos,k=b.currentScrollPos.x,l=b.currentScrollPos.y,m=setInterval(function(){var a=b.currentScrollPos;-20>c?(g.x-=10,g.x>b.touchEndPos.x?a.x+=10:(a.x=k-c,h=!0)):20<c?(g.x+=10,g.x<b.touchEndPos.x?a.x-=10:(a.x=k-c,h=!0)):h=!0;-20>d?(g.y-=10,g.y>b.touchEndPos.y?a.y+=10:(a.y=l-d,f=!0)):20<d?(g.y+=
10,g.y<b.touchEndPos.y?a.y-=10:(a.y=l-d,f=!0)):f=!0;b.scrollPos(a);h&&f&&clearInterval(m)},5);b.touchStartPos=b.touchEndPos}};c.decorators=[{type:core_1.Component,args:[{selector:"iui-basegrid",template:"",providers:[integralui_data_service_1.IntegralUIDataService]}]}];c.ctorParameters=function(){return[{type:integralui_data_service_1.IntegralUIDataService},{type:integralui_dragdrop_service_1.IntegralUIDragDropService},{type:core_1.ElementRef},{type:core_1.Renderer},{type:integralui_common_service_1.IntegralUICommonService},
{type:integralui_filter_service_1.IntegralUIFilterService},{type:core_1.ChangeDetectorRef},{type:core_1.ComponentFactoryResolver}]};c.propDecorators={dragMode:[{type:core_1.Input}],appRef:[{type:core_1.Input}],autoUpdate:[{type:core_1.Input}],rowHeight:[{type:core_1.Input}],allowColumnReorder:[{type:core_1.Input}],allowDrag:[{type:core_1.Input}],allowDrop:[{type:core_1.Input}],allowFilter:[{type:core_1.Input}],allowFocus:[{type:core_1.Input}],autoSizeColumns:[{type:core_1.Input}],columns:[{type:core_1.Input}],
dataFields:[{type:core_1.Input}],focusedCell:[{type:core_1.Input}],gridLines:[{type:core_1.Input}],mouseWheelSpeed:[{type:core_1.Input}],paging:[{type:core_1.Input}],rows:[{type:core_1.Input}],selectedColumn:[{type:core_1.Input}],selectedRow:[{type:core_1.Input}],selectionMode:[{type:core_1.Input}],showExpandBox:[{type:core_1.Input}],showScroll:[{type:core_1.Input}],sorting:[{type:core_1.Input}],afterSelect:[{type:core_1.Output}],beforeEdit:[{type:core_1.Output}],beforeSelect:[{type:core_1.Output}],
beforeUpdate:[{type:core_1.Output}],cellClick:[{type:core_1.Output}],cellDblClick:[{type:core_1.Output}],cellHover:[{type:core_1.Output}],cellRightClick:[{type:core_1.Output}],cellValueChanging:[{type:core_1.Output}],cellValueChanged:[{type:core_1.Output}],change:[{type:core_1.Output}],columnAdding:[{type:core_1.Output}],columnAdded:[{type:core_1.Output}],columnClick:[{type:core_1.Output}],columnDblClick:[{type:core_1.Output}],columnHover:[{type:core_1.Output}],columnRightClick:[{type:core_1.Output}],
columnOrderChanged:[{type:core_1.Output}],columnRemoving:[{type:core_1.Output}],columnRemoved:[{type:core_1.Output}],columnsCleared:[{type:core_1.Output}],columnSizeChanged:[{type:core_1.Output}],dragEnd:[{type:core_1.Output}],dragEnter:[{type:core_1.Output}],dragDrop:[{type:core_1.Output}],dragDropComplete:[{type:core_1.Output}],dragLeave:[{type:core_1.Output}],dragOver:[{type:core_1.Output}],dragStart:[{type:core_1.Output}],keyDown:[{type:core_1.Output}],keyPress:[{type:core_1.Output}],keyUp:[{type:core_1.Output}],
pageChanged:[{type:core_1.Output}],rowAdding:[{type:core_1.Output}],rowAdded:[{type:core_1.Output}],rowClick:[{type:core_1.Output}],rowDblClick:[{type:core_1.Output}],rowHover:[{type:core_1.Output}],rowRemoving:[{type:core_1.Output}],rowRemoved:[{type:core_1.Output}],rowRightClick:[{type:core_1.Output}],rowsCleared:[{type:core_1.Output}],loadComplete:[{type:core_1.Output}],scrollPosChanged:[{type:core_1.Output}],selectionChanged:[{type:core_1.Output}],updateComplete:[{type:core_1.Output}],onWindowKeyDown:[{type:core_1.HostListener,
args:["document:keydown",["$event"]]}],onWindowKeyUp:[{type:core_1.HostListener,args:["document:keyup",["$event"]]}]};return c}(integralui_core_1.IntegralUIBaseComponent);exports.IntegralUIBaseGrid=IntegralUIBaseGrid;