import { ChangeDetectorRef, ComponentFactoryResolver, ElementRef, EventEmitter, Renderer2 } from '@angular/core';
import { IntegralUIBaseComponent, IntegralUIContentVisibility, IntegralUIDragDropDisplayMode, IntegralUIEditorType, IntegralUIMoveDirection, IntegralUISelectionMode, IntegralUISortOrder, IntegralUISpeedMode } from './integralui.core';
import { IntegralUICommonService } from '../services/integralui.common.service';
import { IntegralUIDataService } from '../services/integralui.data.service';
import { IntegralUIDragDropService } from '../services/integralui.dragdrop.service';
import { IntegralUIFilterService } from '../services/integralui.filter.service';
import * as i0 from "@angular/core";
export declare enum IntegralUIGridLines {
    None = 0,
    Horizontal = 1,
    Vertical = 2,
    Both = 3
}
export declare class IntegralUIBaseGrid extends IntegralUIBaseComponent {
    protected dataService: IntegralUIDataService;
    protected dragDropService: IntegralUIDragDropService;
    protected elemRef: ElementRef;
    protected elemRenderer: Renderer2;
    protected commonService?: IntegralUICommonService;
    protected filterService?: IntegralUIFilterService;
    protected changeRef?: ChangeDetectorRef;
    protected cmpResolver?: ComponentFactoryResolver;
    animateColumnSize: any;
    animateRowSize: any;
    protected prevClickedObj: any;
    headerData: Array<any>;
    rowData: Array<any>;
    rowHoverData: Array<any>;
    rowSelectData: Array<any>;
    cellData: Array<any>;
    footerData: Array<any>;
    protected completeColumnList: Array<any>;
    protected completeLeftColumnList: Array<any>;
    protected completeRightColumnList: Array<any>;
    protected currentColumnList: Array<any>;
    protected currentLeftColumnList: Array<any>;
    protected currentRightColumnList: Array<any>;
    protected currentRowList: Array<any>;
    private dataColumns;
    private dataRows;
    protected flatCompleteColumnList: Array<any>;
    protected flatCompleteLeftColumnList: Array<any>;
    protected flatCompleteRightColumnList: Array<any>;
    protected flatCurrentColumnList: Array<any>;
    protected flatCurrentLeftColumnList: Array<any>;
    protected flatCurrentRightColumnList: Array<any>;
    protected maxColumnLevels: number;
    options: any;
    scrollColumnList: Array<any>;
    scrollLeftColumnList: Array<any>;
    scrollRightColumnList: Array<any>;
    scrollFooterList: Array<any>;
    scrollLeftFooterList: Array<any>;
    scrollRightFooterList: Array<any>;
    scrollRowList: Array<any>;
    scrollLeftRowList: Array<any>;
    scrollRightRowList: Array<any>;
    protected columnList: Array<any>;
    protected rowList: Array<any>;
    protected columnDataKey: string;
    protected rowDataKey: string;
    private dropMarkElem;
    private dragCmpRef;
    private dragCmp;
    private cloneElem;
    private cloneElemStartPos;
    protected isCtrlDragEntered: boolean;
    protected isFirstDragEnter: boolean;
    isDragHandleVisible: boolean;
    dragRowList: Array<any>;
    protected targetDropRow: any;
    protected targetDropPos: number;
    protected prevTargetDropPos: number;
    dragHandlePos: any;
    protected dragHandleShiftPos: any;
    dragObjIndent: number;
    protected isDragActive: boolean;
    protected dragStartPos: any;
    protected dragEndPos: any;
    protected clickedCell: any;
    private dropList;
    private dropListRef;
    private calendar;
    private calendarRef;
    private colorPopup;
    private colorPopupRef;
    protected colorPanelSize: any;
    currentEditorCell: any;
    protected isPopupDelayed: boolean;
    isEditorFocused: boolean;
    protected originalEditorText: string;
    protected originalEditorValue: any;
    protected currentExpandColumnID: any;
    protected expandColIndex: number;
    hoverCell: any;
    protected hoverColumn: any;
    hoverRow: any;
    protected isGridHovered: boolean;
    protected currentIndex: number;
    protected prevIndex: number;
    protected tabIndexCount: number;
    ctrlCursor: string;
    blockHoverRect: any;
    blockSelectRect: Array<any>;
    blockSelectHeight: number;
    hoverRowObj: any;
    protected columnStartPos: {
        x: number;
        y: number;
    };
    protected resizeColumn: any;
    protected resizeColumnIndex: number;
    protected reorderColumn: any;
    protected columnReorderActive: boolean;
    protected currentFocusCell: any;
    protected isKeyboardActive: boolean;
    protected allowUpdate: boolean;
    protected avgRowHeight: number;
    blockMarginTop: number;
    blockSize: any;
    leftBlockSize: any;
    rightBlockSize: any;
    protected columnPadding: any;
    protected currentGridLines: IntegralUIGridLines;
    protected currentHeaderHeight: number;
    protected currentFooterHeight: number;
    protected isExpandBoxVisible: boolean;
    protected isLayoutUpdating: boolean;
    isHoverTemplatePresent: boolean;
    isSelectedTemplatePresent: boolean;
    numVisibleCells: number;
    viewIndexRange: any;
    fixedLeftViewIndexRange: number;
    fixedRightViewIndexRange: number;
    visibleRange: number;
    protected isAutoSizeColumnsActive: boolean;
    protected isHeaderVisible: boolean;
    protected isFooterVisible: boolean;
    isUpdateActive: boolean;
    protected scrollSize: {
        width: number;
        height: number;
    };
    contentLeftPos: number;
    protected initialContentLeftPos: number;
    protected allColWidth: number;
    horScrollElemPos: any;
    cornerScrollElemPos: any;
    paginatorPos: any;
    currentPageNumber: number;
    protected onlyCurrentPage: boolean;
    protected currentPageList: Array<any>;
    protected pageNumber: number;
    protected pageList: Array<any>;
    protected pageRowCount: number;
    paginatorHeight: number;
    protected originalScrollColumnList: Array<any>;
    protected reorderColumnObj: any;
    protected reorderColumnObjPos: any;
    protected reorderColumnStartPos: any;
    protected reorderColumnCurrentPos: any;
    protected reorderColIndex: number;
    protected reorderNewColIndex: number;
    protected startColumnReorder: boolean;
    protected isColumnResizing: boolean;
    currentScrollPos: {
        x: number;
        y: number;
    };
    protected isKeyPressed: boolean;
    maxScrollPos: {
        x: number;
        y: number;
    };
    private accelerator;
    private scrollTimerID;
    protected isScrollTimerActive: boolean;
    private scrollCount;
    protected isScrollActive: boolean;
    protected prevScrollPos: {
        x: number;
        y: number;
    };
    scrollBarSize: {
        width: number;
        height: number;
    };
    scrollLargeChange: {
        x: number;
        y: number;
    };
    protected currentSelectedColumn: any;
    protected currentSelectedRow: any;
    protected currentSelectionMode: IntegralUISelectionMode;
    protected isRowClicked: boolean;
    private shiftFirstSelectedRow;
    private removeIndex;
    currentSelectedRows: Array<any>;
    protected isExpandBoxTouched: boolean;
    protected touchStartPos: any;
    protected touchEndPos: any;
    appRef: any;
    autoUpdate: boolean;
    set allowColumnReorder(value: boolean);
    set allowDrag(value: boolean);
    set allowDrop(value: boolean);
    set allowFilter(value: boolean);
    set allowFocus(value: boolean);
    set autoSizeColumns(value: boolean);
    get autoSizeColumns(): boolean;
    set columns(value: Array<any>);
    get columns(): Array<any>;
    set dataFields(value: any);
    set focusedCell(value: any);
    get focusedCell(): any;
    footerHeight: number;
    set gridLines(value: IntegralUIGridLines);
    get gridLines(): IntegralUIGridLines;
    headerHeight: number;
    mouseWheelSpeed: IntegralUISpeedMode;
    set paging(value: any);
    rowContentVisibility: IntegralUIContentVisibility;
    rowHeight: number;
    set rows(value: Array<any>);
    get rows(): Array<any>;
    set selectedColumn(value: any);
    get selectedColumn(): any;
    set selectedRow(value: any);
    get selectedRow(): any;
    set selectionMode(value: IntegralUISelectionMode);
    get selectionMode(): IntegralUISelectionMode;
    set showExpandBox(value: boolean);
    get showExpandBox(): boolean;
    showHoverRow: boolean;
    set showScroll(value: any);
    get showScroll(): any;
    set sorting(value: IntegralUISortOrder);
    afterSelect: EventEmitter<any>;
    beforeEdit: EventEmitter<any>;
    beforeSelect: EventEmitter<any>;
    beforeUpdate: EventEmitter<any>;
    cellClick: EventEmitter<any>;
    cellDblClick: EventEmitter<any>;
    cellHover: EventEmitter<any>;
    cellRightClick: EventEmitter<any>;
    cellValueChanging: EventEmitter<any>;
    cellValueChanged: EventEmitter<any>;
    change: EventEmitter<any>;
    columnAdding: EventEmitter<any>;
    columnAdded: EventEmitter<any>;
    columnClick: EventEmitter<any>;
    columnDblClick: EventEmitter<any>;
    columnHover: EventEmitter<any>;
    columnRightClick: EventEmitter<any>;
    columnOrderChanged: EventEmitter<any>;
    columnRemoving: EventEmitter<any>;
    columnRemoved: EventEmitter<any>;
    columnsCleared: EventEmitter<any>;
    columnSizeChanged: EventEmitter<any>;
    dragEnd: EventEmitter<any>;
    dragEnter: EventEmitter<any>;
    dragDrop: EventEmitter<any>;
    dragDropComplete: EventEmitter<any>;
    dragLeave: EventEmitter<any>;
    dragOver: EventEmitter<any>;
    dragStart: EventEmitter<any>;
    keyDown: EventEmitter<any>;
    keyPress: EventEmitter<any>;
    keyUp: EventEmitter<any>;
    pageChanged: EventEmitter<any>;
    rowAdding: EventEmitter<any>;
    rowAdded: EventEmitter<any>;
    rowClick: EventEmitter<any>;
    rowDblClick: EventEmitter<any>;
    rowHover: EventEmitter<any>;
    rowRemoving: EventEmitter<any>;
    rowRemoved: EventEmitter<any>;
    rowRightClick: EventEmitter<any>;
    rowsCleared: EventEmitter<any>;
    loadComplete: EventEmitter<any>;
    scrollPosChanged: EventEmitter<any>;
    selectionChanged: EventEmitter<any>;
    updateComplete: EventEmitter<any>;
    constructor(dataService: IntegralUIDataService, dragDropService: IntegralUIDragDropService, elemRef: ElementRef, elemRenderer: Renderer2, commonService?: IntegralUICommonService, filterService?: IntegralUIFilterService, changeRef?: ChangeDetectorRef, cmpResolver?: ComponentFactoryResolver);
    ngOnInit(): void;
    addColumn(column: any): void;
    clearColumns(): void;
    insertColumnAt(column: any, index: number): void;
    insertColumnBefore(column: any, refColumn: any): void;
    insertColumnAfter(column: any, refColumn: any): void;
    removeColumn(column: any): boolean;
    removeColumnAt(index: number): boolean;
    protected callEventAddColumn(type: string, column: any, index?: number, refColumn?: any, flag?: boolean): void;
    protected callEventRemoveColumn(column: any, index?: number): boolean;
    addRow(row: any, parent?: any): void;
    clearRows(parent?: any): void;
    insertRowAt(row: any, index: number, parent?: any): void;
    insertRowBefore(row: any, refRow: any): void;
    insertRowAfter(row: any, refRow: any): void;
    removeRow(row: any): boolean;
    removeRowAt(index: number, parent?: any): boolean;
    protected callEventAddRow(type: string, row: any, index?: number, parent?: any, refRow?: any, flag?: boolean): void;
    protected callEventRemoveRow(row: any, index?: number, parent?: any): boolean;
    cellClickEvent(e: any, obj: any): void;
    cellDblClickEvent(e: any, obj: any): void;
    cellRightClickEvent(e: any, obj: any): void;
    columnClickEvent(e: any, obj: any): void;
    columnDblClickEvent(e: any, obj: any): void;
    columnRightClickEvent(e: any, obj: any): void;
    rowClickEvent(e: any, obj: any): void;
    rowDblClickEvent(e: any, obj: any): void;
    rowRightClickEvent(e: any, obj: any): void;
    protected updateData(): void;
    protected updateDataFields(data?: any): void;
    protected updateOptions(value?: any): void;
    protected updateColumnFields(fields?: any): void;
    protected updateRowFields(fields?: any): void;
    protected updateCellFields(fields?: any): void;
    protected updateShowScroll(value?: any): void;
    protected processLoadData(data: Array<any>, parent?: any, fields?: any, flat?: boolean): void;
    protected calcMaxColumnLevels(list: Array<any>, level: number): void;
    protected getColumnSpan(column: any): number;
    protected isColumnWithChildrenVisible(column: any): boolean;
    protected createColumnLevel(list: Array<any>, level: number, fixed?: string, pid?: any): void;
    protected updateColumnCompleteList(): void;
    protected createScrollRowList(): void;
    protected createScrollNormalRowList(): void;
    protected createScrollLeftRowList(): void;
    protected createScrollRightRowList(): void;
    protected createEmptyRowObj(): {
        clickPos: {
            x: number;
            y: number;
        };
        cells: any[];
        data: {};
        draggable: boolean;
        indent: number;
        inlineStyle: {};
        isEmpty: boolean;
        isGroup: boolean;
        style: {};
    };
    protected createEmptyCellObj(): any;
    protected updateScrollRowListLimit(limit: number): void;
    protected updateScrollNormalRowListLimit(limit: number): void;
    protected updateScrollLeftRowListLimit(limit: number): void;
    protected updateScrollRightRowListLimit(limit: number): void;
    protected getNumScrollColumns(fixed?: string): any;
    protected getNumVisibleColumns(fixed?: string): number;
    protected resetRowObj(obj: any): void;
    protected resetCellObj(obj: any): void;
    protected updateScrollColumnList(): void;
    protected updateScrollRowList(flag?: boolean): void;
    protected addDropMark(pos: any): void;
    removeDropMark(): void;
    protected callDragDropEvent(e: any, data: any, flag?: boolean): {
        action: any;
        cancel: boolean;
        dragRow: any;
        dropPos: any;
        event: any;
        isDropAllowed: any;
        mousePos: {
            x: any;
            y: any;
        };
        resume: () => void;
        sourceCtrl: any;
        targetCtrl: any;
        targetRow: any;
    };
    private checkEmptySpace;
    ctrlDragEnter(e: any): void;
    ctrlDragDrop(e: any): void;
    ctrlDragLeave(e: any): void;
    ctrlDragOver(e: any): void;
    ctrlDragEnd(e: any): void;
    protected removeDragHandle(): void;
    protected dropMark(e: any, flag?: boolean): void;
    protected updateDragComponent(value: any): void;
    protected isDragAllowed(row: any): boolean;
    protected isDropAllowed(sourceData: any, targetRow: any, dropPos: number): any;
    protected processDragStart(e: any, row: any): void;
    protected processDragStartHandle(e: any, row: any): void;
    protected processDragStartPopup(e: any, row: any): void;
    protected processDragEnter(e: any): void;
    protected processDragLeave(e: any): void;
    protected processDragOver(e: any, rowObj?: any, rowBounds?: any, flag?: boolean, type?: string): void;
    protected processDragOverHandle(e: any, rowObj?: any, rowBounds?: any, flag?: boolean, type?: string): void;
    protected processDragOverPopup(e: any, rowObj?: any, rowBounds?: any, flag?: boolean, type?: string): void;
    protected processDragDrop(e: any, rowObj?: any): void;
    protected clearDragDropSettings(): void;
    protected drop(e: any, data: any): void;
    protected processDataDrop(e: any, row: any, data: any): void;
    protected callAfterSelectEvent(obj: any): void;
    rowDragEnd(e: any, obj: any): void;
    protected dragGhost: any;
    dragMode: IntegralUIDragDropDisplayMode;
    protected emptyRowObj: any;
    protected getEmptyObj(status: number): any;
    protected removeEmptyRow(status: number): void;
    protected updateDragHandlePos(e: any): void;
    protected updateScrollRowListDragOver(row: any): void;
    protected addCalendar(): void;
    protected addColorPopup(): void;
    protected addDropList(): void;
    protected callCellValueChanging(obj: any, value?: any): boolean;
    protected callCellValueChanged(obj: any): void;
    closeEditor(): void;
    editCheckBoxValue(obj: any): void;
    editorClick(e: any): void;
    editorDblClickEvent(e: any): void;
    editorKeyDown(e: any, type?: string): void;
    editorLostFocus(type?: string): void;
    editorMouseDown(e: any, obj: any): void;
    editorMouseWheel(e: any): void;
    editorMouseTouch(e: any, obj: any): void;
    editorNumericValueChange(obj: any, value: any): void;
    editorPreventDragStart(e: any): void;
    editorValueChanged(e: any, obj: any): void;
    protected getCellEditorClass(obj: any): string;
    getCellEditorList(column: any): any;
    getCellEditorSettings(column: any): any;
    getCellEditorStyle(obj: any): any;
    getCellEditorType(column: any): any;
    getCellEditorVisibility(column: any, cell: any): boolean;
    getCellField(key: string): any;
    getCellText(obj: any): any;
    getCellValue(obj: any): any;
    getEditorColorValue(obj: any): string;
    protected findItemByValue(value: any, list: Array<any>): string;
    getEditorProgressStyle(obj: any): any;
    getEditorProgressValue(obj: any): number;
    getHoverRow(): any;
    protected hideCalendar(): void;
    protected hideColorPopup(): void;
    protected hideDropList(): void;
    isCellEditorEnabled(column: any, cell: any): boolean;
    protected isEditorPresent(type: IntegralUIEditorType): boolean;
    private isEditorPresentInList;
    openEditor(e: any, obj: any, type?: string): void;
    protected removeCalendar(): void;
    protected removeColorPopup(): void;
    protected removeDropList(): void;
    protected showPopup(e: any, obj: any, rowElem: any, colElem: any): void;
    selectTextBoxContent(e: any): void;
    expandBoxMouseDown(e: any, row: any): void;
    expandBoxMouseUp(e: any, row: any): void;
    expandBoxTouchStart(e: any, row: any): void;
    toggle(row?: any, value?: boolean): void;
    protected updateExpandingCell(row: any, value: boolean): void;
    protected convertToCSV(list: Array<any>): string;
    exportToCSV(): string;
    exportToJSON(columnFields?: any, rowFields?: any, spacing?: any, flat?: boolean): string;
    protected exportColumnsToJSON(fields?: any, spacing?: any): string;
    protected exportRowsToJSON(fields?: any, spacing?: any, flat?: boolean): string;
    filter(column: any, params?: any): void;
    protected changeCursor(flag?: boolean): void;
    checkStatus(type?: string): boolean;
    clearHoverRow(row?: any): void;
    cloneRow(row: any): any;
    protected createCloneList(list: Array<any>): any[];
    protected createFlatColumnList(list: Array<any>): any[];
    createFlatList(list: Array<any>, field: string, result: Array<any>): void;
    createColumnListInRange(list: Array<any>, result: Array<any>): void;
    protected getColumnListInRange(fixed?: string): any[];
    getCellByColumnId(list: Array<any>, id: any): any;
    protected getCellWidth(rowObj: any, column: any, colIndex?: number): number;
    protected getColumnAllowResize(column: any): {
        left: any;
        right: any;
    };
    getColumnById(id: any): any;
    protected getColumnCurrentIndex(column: any): number;
    protected getColumnIndexFromList(column: any): number;
    protected getColumnList(fixed?: string): any[];
    protected getCurrentColumnList(fixed?: string): any[];
    protected getColumnIndex(column: any, targetlist?: Array<any>): any;
    protected getColumnRealIndex(j: number): any;
    protected getPrevColumnIndex(column: any, targetlist?: Array<any>): number;
    protected getPrevFlatColumn(column: any, fixed?: string, skipFixedWidth?: boolean): any;
    protected getPrevFlatColumnIndex(column: any, fixed?: string, skipFixedWidth?: boolean): number;
    protected getNextColumnIndex(column: any, targetlist?: Array<any>): number;
    protected getNextFlatColumn(column: any, fixed?: string, skipFixedWidth?: boolean): any;
    protected getNextFlatColumnIndex(column: any, fixed?: string, skipFixedWidth?: boolean): number;
    protected getLastColumnIndex(targetlist?: Array<any>): number;
    getColumnWidth(column: any, type?: string): number;
    protected getColumnWidthFromChildren(column: any): number;
    protected getMinColumnWidthFromChildren(column: any): number;
    setColumnWidth(column: any, width: number, flag?: boolean): void;
    protected getPrevColumn(column: any, flag?: boolean): any;
    protected getExpandingColumn(): any;
    updateExpandingColumnID(): void;
    protected getFilterTree(column: any): any;
    private getCurrentList;
    getList(key?: string, parent?: any): Array<any>;
    getFullList(): Array<any>;
    getTopRow(): any;
    protected getObjFromRow(row: any): any;
    protected createScrollObjFromRow(row: any, rowObj?: any, scrollIndex?: number): any;
    protected getObjIndexFromScrollList(row: any, fixed?: string): number;
    protected getObjFromScrollList(row: any, fixed?: string): any;
    protected getRowCurrentIndex(row: any): number;
    protected getRowIndent(rowObj: any, column: any, colIndex?: number): number;
    getRowLevel(row: any): number;
    protected getRowList(fixed?: string): any[];
    getRowFromComponent(cmp: any): any;
    protected getRowScrollIndex(row: any): number;
    protected isChildOf(targetRow: any, row: any): boolean;
    protected isColumnExpanded(column: any): boolean;
    protected isColumnFixed(column: any, fixed?: string): boolean;
    protected isColumnVisible(column: any): boolean;
    protected isColumnWidthFixed(column: any): boolean;
    protected isComponentIndexInRange(index: number): boolean;
    isContentAllowed(row: any, type: string): boolean;
    protected isExpandBoxAllowed(column: any): boolean;
    protected isIndexInRange(index: number, list: Array<any>): boolean;
    protected isRowAllowed(row: any, flag?: boolean): boolean;
    protected filterIsThereChildren(row: any, flag?: boolean): boolean;
    protected isRowEnabled(row: any): boolean;
    protected isRowFixed(row: any): boolean;
    protected isRowHovered(row: any): boolean;
    protected isRowSelected(row: any): boolean;
    protected isParentOf(targetRow: any, row: any): boolean;
    isThereFixedColumns(fixed: string): boolean;
    processStateChanged(): void;
    updateExpandStatus(): void;
    protected resetHoverRowObj(): void;
    getSelectBlockRect(i: number): any;
    hoverBlockMouseMove(e: any): void;
    hoverBlockMouseLeave(e: any): void;
    rowMouseEnter(e: any, obj: any): void;
    rowMouseLeave(e: any, obj: any): void;
    getParentColumnList(column: any): any[];
    moveColumn(column: any, direction: IntegralUIMoveDirection, targetColumn?: any, position?: number): void;
    paginatorMouseEnter(e: any): void;
    scrollMouseEnter(e: any): void;
    cellGotFocus(cell: any): void;
    cellLostFocus(cell: any): void;
    onContentScroll(e: any): void;
    onGridScroll(e: any): void;
    cellMouseEnter(e: any, obj: any): void;
    cellMouseLeave(e: any): void;
    cellMouseDown(e: any, obj: any): void;
    cellMouseUp(e: any, obj: any, i: number, j: number, fixed?: string): void;
    cellTouchEnd(e: any, obj: any, i: number, j: number, fixed?: string): void;
    protected openDropDown(e: any, obj: any, i: number, j: number, fixed?: string): void;
    cellKeyDown(e: any, cell: any): void;
    cellKeyPress(e: any, cell: any): void;
    cellKeyUp(e: any, cell: any): void;
    isCellFocused(obj: any): boolean;
    processDownArrowKey(cell: any, e?: any): any;
    processEndKey(cell: any, e?: any): any;
    processHomeKey(cell: any, e?: any): any;
    processLeftArrowKey(cell: any): any;
    processPageDownKey(cell: any, e?: any): any;
    processPageUpKey(cell: any, e?: any): any;
    processRightArrowKey(cell: any): any;
    processUpArrowKey(cell: any, e?: any): any;
    protected getDownCell(cell: any): any;
    protected getNextCell(cell: any): any;
    private getLastScrollIndex;
    protected getPrevCell(cell: any): any;
    protected getUpCell(cell: any): any;
    protected isFirstCell(cell: any): boolean;
    protected isFirstRow(cell: any): boolean;
    protected isLastCell(cell: any): boolean;
    protected isLastRow(cell: any): boolean;
    protected getRowFromCell(cell: any): any;
    moveFocusFromCell(cell: any, direction: string): any;
    getObjFromCell(cell: any): any;
    protected updateFocusCell(obj: any): void;
    onWindowKeyDown(e: any): void;
    onWindowKeyUp(e: any): void;
    checkForSelectionChange(): void;
    protected getContentSize(): {
        width: number;
        height: number;
    };
    refresh(obj?: any): void;
    suspendLayout(): void;
    resumeLayout(): void;
    protected updateCurrentLayout(): void;
    updateLayout(): void;
    protected isThereChildColumns(column: any, allFixed?: boolean): boolean;
    protected areChildColumnsFixed(list: Array<any>): boolean;
    protected updateColumnWidth(column?: any): void;
    private changeColumnWidth;
    protected calcColumnWidthFromChildren(column: any): number;
    private updateColumnWidthByFactor;
    protected checkWidthChanges(): void;
    protected updateCellWidth(column: any): void;
    protected updateChildColumnsWidth(column: any, newWidth: number, changeFactor: number): void;
    protected resizeChildColumns(column: any, factor: number): void;
    protected resizeParentColumn(column: any, factor: number): void;
    protected updateWidthByFactor(column: any, factor: number): void;
    protected updateRange(): void;
    getBlockBottomPos(): number;
    getBlockRightPos(): 0 | 16;
    protected onCtrlMouseEnter(e: any): void;
    protected onCtrlMouseLeave(e: any): void;
    currentPage(value?: number): number;
    getMaxPages(): number;
    firstPage(): void;
    lastPage(): void;
    nextPage(): void;
    prevPage(): void;
    protected resetPageNumber(): void;
    protected updatePageNumber(): void;
    private updatePaging;
    paginatorPageChanged(e: any): void;
    isPaginationEnabled(): any;
    getColumnOpacity(obj: any): number;
    protected updateOrignalScrollColumnList(): void;
    protected updateReorderColumnPos(): void;
    protected getHeaderRect(): {
        top: number;
        right: number;
        bottom: number;
        left: number;
        height: number;
        width: number;
        x: number;
        y: number;
    };
    protected resetReorderColumnSettings(): void;
    protected restoreColumnOrder(): void;
    protected getColumnIndexFromScrollList(column: any): number;
    protected moveObject(from: number, to: number, list: Array<any>): void;
    scrollPos(value?: any): any;
    protected changeHorizontalScrollPos(value: number): void;
    protected changeVerticalScrollPos(value: number): void;
    gridMouseWheel(e: any): void;
    isVerScrollVisible(): boolean;
    isHorScrollVisible(): boolean;
    onVerticalScrollStart(e: any): void;
    onVerticalScrollEnd(e: any): void;
    onVerticalScrollChanged(e: any): void;
    onHorizontalScrollStart(e: any): void;
    onHorizontalScrollEnd(e: any): void;
    onHorizontalScrollChanged(e: any): void;
    scrollMouseDown(e: any): void;
    protected updateSelectContentPos(): void;
    updateView(flag?: boolean): void;
    protected processScroll(e: any, extraTopSpace?: number, extraBottomSpace?: number): void;
    private startScrollTimer;
    private stopScrollTimer;
    private scrollTimerElapsed;
    scrollTo(row: any): void;
    findRowById(id: any): any;
    findRowByText(text: string): any;
    clearSelection(): void;
    protected processColumnSelection(e: any, column: any, value?: any): any;
    protected clearComponentSelection(): void;
    private clearPrevSelection;
    private isRowInSelectionList;
    protected processRowSelection(e: any, row: any, value?: any): any;
    selectRows(rows: Array<any>): void;
    protected updateRowSelection(e: any, row: any): void;
    protected sortColumn: any;
    protected sortComparer: any;
    sort(column: any, order: IntegralUISortOrder, comparer?: any): void;
    protected getCellIndexInCollection(cells: Array<any>, colIndex: number, colId: any): number;
    isSortingAllowed(): boolean;
    isSortingColumn(column: any): boolean;
    protected applySorting(list: Array<any>): void;
    protected getColumnInlineStyle(value: any): any;
    protected getRowInlineStyle(value: any, hide?: boolean): any;
    columnTouchStart(e: any, obj: any): void;
    rowTouchStart(e: any, obj: any): void;
    ctrlTouchStart(e: any): void;
    ctrlTouchEnd(e: any): void;
    static ɵfac: i0.ɵɵFactoryDef<IntegralUIBaseGrid, never>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<IntegralUIBaseGrid, "iui-basegrid", never, { "appRef": "appRef"; "autoUpdate": "autoUpdate"; "allowColumnReorder": "allowColumnReorder"; "allowDrag": "allowDrag"; "allowDrop": "allowDrop"; "allowFilter": "allowFilter"; "allowFocus": "allowFocus"; "autoSizeColumns": "autoSizeColumns"; "columns": "columns"; "dataFields": "dataFields"; "focusedCell": "focusedCell"; "footerHeight": "footerHeight"; "gridLines": "gridLines"; "headerHeight": "headerHeight"; "mouseWheelSpeed": "mouseWheelSpeed"; "paging": "paging"; "rowContentVisibility": "rowContentVisibility"; "rowHeight": "rowHeight"; "rows": "rows"; "selectedColumn": "selectedColumn"; "selectedRow": "selectedRow"; "selectionMode": "selectionMode"; "showExpandBox": "showExpandBox"; "showHoverRow": "showHoverRow"; "showScroll": "showScroll"; "sorting": "sorting"; "dragMode": "dragMode"; }, { "afterSelect": "afterSelect"; "beforeEdit": "beforeEdit"; "beforeSelect": "beforeSelect"; "beforeUpdate": "beforeUpdate"; "cellClick": "cellClick"; "cellDblClick": "cellDblClick"; "cellHover": "cellHover"; "cellRightClick": "cellRightClick"; "cellValueChanging": "cellValueChanging"; "cellValueChanged": "cellValueChanged"; "change": "change"; "columnAdding": "columnAdding"; "columnAdded": "columnAdded"; "columnClick": "columnClick"; "columnDblClick": "columnDblClick"; "columnHover": "columnHover"; "columnRightClick": "columnRightClick"; "columnOrderChanged": "columnOrderChanged"; "columnRemoving": "columnRemoving"; "columnRemoved": "columnRemoved"; "columnsCleared": "columnsCleared"; "columnSizeChanged": "columnSizeChanged"; "dragEnd": "dragEnd"; "dragEnter": "dragEnter"; "dragDrop": "dragDrop"; "dragDropComplete": "dragDropComplete"; "dragLeave": "dragLeave"; "dragOver": "dragOver"; "dragStart": "dragStart"; "keyDown": "keyDown"; "keyPress": "keyPress"; "keyUp": "keyUp"; "pageChanged": "pageChanged"; "rowAdding": "rowAdding"; "rowAdded": "rowAdded"; "rowClick": "rowClick"; "rowDblClick": "rowDblClick"; "rowHover": "rowHover"; "rowRemoving": "rowRemoving"; "rowRemoved": "rowRemoved"; "rowRightClick": "rowRightClick"; "rowsCleared": "rowsCleared"; "loadComplete": "loadComplete"; "scrollPosChanged": "scrollPosChanged"; "selectionChanged": "selectionChanged"; "updateComplete": "updateComplete"; }, never, never>;
}
