/*
  filename: integralui.core.js
  version : 3.2.0
  Copyright © 2016-2019 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(){var a=function(b,c){a=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return a(b,c)};return function(b,c){function d(){this.constructor=b}a(b,c);b.prototype=null===c?Object.create(c):(d.prototype=c.prototype,new d)}}(),__decorate=this&&this.__decorate||function(a,b,c,d){var f=arguments.length,e=3>f?b:null===d?d=Object.getOwnPropertyDescriptor(b,c):d,g;
if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)e=Reflect.decorate(a,b,c,d);else for(var h=a.length-1;0<=h;h--)if(g=a[h])e=(3>f?g(e):3<f?g(b,c,e):g(b,c))||e;return 3<f&&e&&Object.defineProperty(b,c,e),e},__metadata=this&&this.__metadata||function(a,b){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(a,b)};Object.defineProperty(exports,"__esModule",{value:!0});
var core_1=require("@angular/core"),integralui_common_service_1=require("../services/integralui.common.service"),integralui_data_service_1=require("../services/integralui.data.service"),IntegralUIDraggable=function(){function a(a,c){this.elemRef=a;this.elemRenderer=c;this.currentSettings=!1}Object.defineProperty(a.prototype,"settings",{get:function(){return this.currentSettings},set:function(a){this.currentSettings!=a&&(this.currentSettings=a,this.elemRef&&this.elemRenderer.setElementAttribute(this.elemRef.nativeElement,
"draggable",this.currentSettings.toString()))},enumerable:!0,configurable:!0});a.prototype.ngAfterViewInit=function(){this.settings&&this.elemRenderer.setElementAttribute(this.elemRef.nativeElement,"draggable","true")};__decorate([core_1.Input("iuiDraggable"),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],a.prototype,"settings",null);return a=__decorate([core_1.Directive({selector:"[iuiDraggable]"}),__metadata("design:paramtypes",[core_1.ElementRef,core_1.Renderer])],
a)}();exports.IntegralUIDraggable=IntegralUIDraggable;
var IntegralUITemplate=function(){function a(){}a.prototype.getTemplate=function(){return this.template};__decorate([core_1.Input("iuiTemplate"),__metadata("design:type",Object)],a.prototype,"settings",void 0);__decorate([core_1.ContentChild(core_1.TemplateRef,{"static":!1}),__metadata("design:type",core_1.TemplateRef)],a.prototype,"template",void 0);return a=__decorate([core_1.Directive({selector:"[iuiTemplate]"}),__metadata("design:paramtypes",[])],a)}();exports.IntegralUITemplate=IntegralUITemplate;
var IntegralUITemplateOutlet=function(){function a(a){this.containerRef=a}a.prototype.ngOnChanges=function(a){this.removeView();this.createView()};a.prototype.ngOnDestroy=function(){this.removeView()};a.prototype.createView=function(){this.iuiTemplateOutlet&&(this.viewRef=this.containerRef.createEmbeddedView(this.iuiTemplateOutlet,this.iuiTemplateOutletContext))};a.prototype.removeView=function(){this.viewRef&&this.containerRef.remove(this.containerRef.indexOf(this.viewRef))};__decorate([core_1.Input(),
__metadata("design:type",Object)],a.prototype,"iuiTemplateOutletContext",void 0);__decorate([core_1.Input(),__metadata("design:type",core_1.TemplateRef)],a.prototype,"iuiTemplateOutlet",void 0);return a=__decorate([core_1.Directive({selector:"[iuiTemplateOutlet]"}),__metadata("design:paramtypes",[core_1.ViewContainerRef])],a)}();exports.IntegralUITemplateOutlet=IntegralUITemplateOutlet;var IntegralUIAnchorStyle;
(function(a){a[a.None=0]="None";a[a.Top=1]="Top";a[a.Right=2]="Right";a[a.Bottom=4]="Bottom";a[a.Left=8]="Left"})(IntegralUIAnchorStyle=exports.IntegralUIAnchorStyle||(exports.IntegralUIAnchorStyle={}));var IntegralUICheckState;(function(a){a[a.Unchecked=0]="Unchecked";a[a.Indeterminate=1]="Indeterminate";a[a.Checked=2]="Checked"})(IntegralUICheckState=exports.IntegralUICheckState||(exports.IntegralUICheckState={}));var IntegralUIDateFormat;
(function(a){a[a.Short=0]="Short";a[a.Long=1]="Long";a[a.Custom=2]="Custom"})(IntegralUIDateFormat=exports.IntegralUIDateFormat||(exports.IntegralUIDateFormat={}));var IntegralUIDirection;(function(a){a[a.None=0]="None";a[a.Above=1]="Above";a[a.Right=2]="Right";a[a.Below=4]="Below";a[a.Left=8]="Left"})(IntegralUIDirection=exports.IntegralUIDirection||(exports.IntegralUIDirection={}));var IntegralUIDragDropDisplayMode;
(function(a){a[a.Popup=0]="Popup";a[a.Handle=1]="Handle"})(IntegralUIDragDropDisplayMode=exports.IntegralUIDragDropDisplayMode||(exports.IntegralUIDragDropDisplayMode={}));var IntegralUIEditorType;
(function(a){a[a.None=0]="None";a[a.Button=1]="Button";a[a.CheckBox=2]="CheckBox";a[a.Date=3]="Date";a[a.DropList=4]="DropList";a[a.Image=5]="Image";a[a.Label=6]="Label";a[a.ListScroller=7]="ListScroller";a[a.Numeric=8]="Numeric";a[a.Progress=9]="Progress";a[a.Rating=10]="Rating";a[a.Slider=11]="Slider";a[a.TextBox=12]="TextBox"})(IntegralUIEditorType=exports.IntegralUIEditorType||(exports.IntegralUIEditorType={}));var IntegralUINumericDisplayMode;
(function(a){a[a.InBound=0]="InBound";a[a.LeftRight=1]="LeftRight";a[a.UpDown=2]="UpDown"})(IntegralUINumericDisplayMode=exports.IntegralUINumericDisplayMode||(exports.IntegralUINumericDisplayMode={}));var IntegralUIItemDisplayMode;(function(a){a[a.Partial=0]="Partial";a[a.Full=1]="Full"})(IntegralUIItemDisplayMode=exports.IntegralUIItemDisplayMode||(exports.IntegralUIItemDisplayMode={}));var IntegralUIObjectState;
(function(a){a[a.normal=0]="normal";a[a.hovered=1]="hovered";a[a.selected=2]="selected";a[a.focused=4]="focused";a[a.disabled=8]="disabled"})(IntegralUIObjectState=exports.IntegralUIObjectState||(exports.IntegralUIObjectState={}));var IntegralUIOrientation;(function(a){a[a.Horizontal=0]="Horizontal";a[a.Vertical=1]="Vertical"})(IntegralUIOrientation=exports.IntegralUIOrientation||(exports.IntegralUIOrientation={}));var IntegralUIIncrementMode;
(function(a){a[a.Free=0]="Free";a[a.Partial=1]="Partial";a[a.Full=2]="Full"})(IntegralUIIncrementMode=exports.IntegralUIIncrementMode||(exports.IntegralUIIncrementMode={}));var IntegralUIMoveDirection;(function(a){a[a.After=0]="After";a[a.At=1]="At";a[a.Before=2]="Before";a[a.Down=3]="Down";a[a.First=4]="First";a[a.Left=5]="Left";a[a.Last=6]="Last";a[a.Right=7]="Right";a[a.Up=8]="Up"})(IntegralUIMoveDirection=exports.IntegralUIMoveDirection||(exports.IntegralUIMoveDirection={}));var IntegralUIPlacement;
(function(a){a[a.Top=0]="Top";a[a.Right=1]="Right";a[a.Bottom=2]="Bottom";a[a.Left=3]="Left"})(IntegralUIPlacement=exports.IntegralUIPlacement||(exports.IntegralUIPlacement={}));var IntegralUIScrollMode;(function(a){a[a.Horizontal=0]="Horizontal";a[a.Vertical=1]="Vertical"})(IntegralUIScrollMode=exports.IntegralUIScrollMode||(exports.IntegralUIScrollMode={}));var IntegralUISelectionMode;
(function(a){a[a.None=0]="None";a[a.One=1]="One";a[a.MultiSimple=2]="MultiSimple";a[a.MultiExtended=3]="MultiExtended"})(IntegralUISelectionMode=exports.IntegralUISelectionMode||(exports.IntegralUISelectionMode={}));var IntegralUISortOrder;(function(a){a[a.None=0]="None";a[a.Ascending=1]="Ascending";a[a.Descending=2]="Descending"})(IntegralUISortOrder=exports.IntegralUISortOrder||(exports.IntegralUISortOrder={}));var IntegralUISpeedMode;
(function(a){a[a.VerySlow=0]="VerySlow";a[a.Slow=1]="Slow";a[a.Normal=2]="Normal";a[a.Fast=3]="Fast";a[a.VeryFast=4]="VeryFast"})(IntegralUISpeedMode=exports.IntegralUISpeedMode||(exports.IntegralUISpeedMode={}));var IntegralUITabScrollMode;(function(a){a[a.None=0]="None";a[a.InBound=1]="InBound";a[a.OutBound=2]="OutBound"})(IntegralUITabScrollMode=exports.IntegralUITabScrollMode||(exports.IntegralUITabScrollMode={}));var IntegralUITabStripPlacement;
(function(a){a[a.Top=0]="Top";a[a.Right=1]="Right";a[a.Middle=2]="Middle";a[a.Bottom=3]="Bottom";a[a.Left=4]="Left"})(IntegralUITabStripPlacement=exports.IntegralUITabStripPlacement||(exports.IntegralUITabStripPlacement={}));var IntegralUIToolItemType;
(function(a){a[a.Button=0]="Button";a[a.CheckBox=1]="CheckBox";a[a.Date=2]="Date";a[a.DropList=3]="DropList";a[a.Image=4]="Image";a[a.Label=5]="Label";a[a.ListScroller=6]="ListScroller";a[a.Numeric=7]="Numeric";a[a.Progress=8]="Progress";a[a.Rating=9]="Rating";a[a.Separator=10]="Separator";a[a.Slider=11]="Slider";a[a.TextBox=12]="TextBox"})(IntegralUIToolItemType=exports.IntegralUIToolItemType||(exports.IntegralUIToolItemType={}));var IntegralUIVisibility;
(function(a){a[a.None=0]="None";a[a.Hover=1]="Hover";a[a.Click=2]="Click";a[a.Always=3]="Always"})(IntegralUIVisibility=exports.IntegralUIVisibility||(exports.IntegralUIVisibility={}));var IntegralUIWeekDays;(function(a){a[a.Monday=0]="Monday";a[a.Tuesday=1]="Tuesday";a[a.Wednesday=2]="Wednesday";a[a.Thursday=3]="Thursday";a[a.Friday=4]="Friday";a[a.Saturday=5]="Saturday";a[a.Sunday=6]="Sunday"})(IntegralUIWeekDays=exports.IntegralUIWeekDays||(exports.IntegralUIWeekDays={}));
var IntegralUIBaseComponent=function(){function a(a){this.commonService=a;this.ctrlState=IntegralUIObjectState.normal;this.isEnabled=!0;this.options={};this.clientRect={width:0,height:0};this.ctrlSize={width:0,height:0};this.prevClientRect={width:0,height:0};this.generalClassName="";this.defaultStyle={};this.ctrlClass=[];this.allowAnimation=!1;this.enabledChanged=new core_1.EventEmitter;this.sizeChanged=new core_1.EventEmitter;this.styleChanged=new core_1.EventEmitter;this.stateChanged=new core_1.EventEmitter;
this.options={currentStyle:null}}Object.defineProperty(a.prototype,"enabled",{get:function(){return this.isEnabled},set:function(a){void 0!=a&&this.isEnabled!=a&&(this.isEnabled=a,this.enabledChanged.emit(this),this.state=this.isEnabled?this.state&~IntegralUIObjectState.disabled:this.state|IntegralUIObjectState.disabled)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"size",{get:function(){return this.ctrlSize},set:function(a){if(a){var c=!1;a.width&&this.ctrlSize.width!=a.width&&
(this.ctrlSize.width=a.width,c=!0);a.height&&this.ctrlSize.height!=a.height&&(this.ctrlSize.height=a.height,c=!0);c&&this.sizeChanged.emit({size:this.ctrlSize})}},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"state",{get:function(){return this.ctrlState},set:function(a){this.ctrlState!=a&&(this.ctrlState=a,this.updateControlClass(),this.processStateChanged(),this.stateChanged.emit(this))},enumerable:!0,configurable:!0});a.prototype.ngOnInit=function(){this.generalClassName="iui-control";
this.initStyle()};a.prototype.initStyle=function(){this.defaultStyle={general:{disabled:this.generalClassName+"-disabled",focused:this.generalClassName+"-focused",normal:this.generalClassName,hovered:this.generalClassName+"-hovered",selected:this.generalClassName+"-selected"}};this.updateStyle(this.controlStyle);this.updateControlClass()};a.prototype.processStateChanged=function(){};a.prototype.updateControlClass=function(){this.ctrlClass.length=0;this.ctrlClass.push(this.generalClassName);this.options.currentStyle&&
this.options.currentStyle.general&&(this.ctrlClass.push(this.options.currentStyle.general.normal),this.state&IntegralUIObjectState.disabled?this.ctrlClass.push(this.options.currentStyle.general.disabled):this.state&IntegralUIObjectState.focused?this.ctrlClass.push(this.options.currentStyle.general.focused):this.state&IntegralUIObjectState.selected?this.ctrlClass.push(this.options.currentStyle.general.selected):this.state&IntegralUIObjectState.hovered&&this.ctrlClass.push(this.options.currentStyle.general.hovered),
this.allowAnimation&&(this.state&IntegralUIObjectState.hovered?this.ctrlClass.push(this.defaultStyle.general.normal+"-enter"):this.ctrlClass.push(this.defaultStyle.general.normal+"-leave")))};a.prototype.getControlClass=function(){return this.ctrlClass};a.prototype.getDefaultStyle=function(){return{general:this.getDefaultGeneralStyle()}};a.prototype.getDefaultGeneralStyle=function(){return this.defaultStyle&&this.defaultStyle.general?{disabled:this.defaultStyle.general.disabled,focused:this.defaultStyle.general.focused,
hovered:this.defaultStyle.general.hovered,normal:this.defaultStyle.general.normal,selected:this.defaultStyle.general.selected}:{}};a.prototype.getGeneralStyle=function(a){if(this.commonService){if(this.commonService.isString(a))return a;if(a)return{disabled:this.commonService.isFieldAvailable(a.disabled,this.generalClassName+"-disabled"),focused:this.commonService.isFieldAvailable(a.focused,this.generalClassName+"-focused"),hovered:this.commonService.isFieldAvailable(a.hovered,this.generalClassName+
"-hovered"),normal:this.commonService.isFieldAvailable(a.normal,this.generalClassName),selected:this.commonService.isFieldAvailable(a.selected,this.generalClassName+"-selected")}}return this.getDefaultGeneralStyle()};a.prototype.updateStyle=function(a){this.options.currentStyle=a?{general:this.getGeneralStyle(a.general)}:this.getDefaultStyle()};__decorate([core_1.Input(),__metadata("design:type",Boolean)],a.prototype,"allowAnimation",void 0);__decorate([core_1.Input(),__metadata("design:type",Object)],
a.prototype,"controlStyle",void 0);__decorate([core_1.Input(),__metadata("design:type",Object)],a.prototype,"data",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],a.prototype,"name",void 0);__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],a.prototype,"enabled",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],a.prototype,"size",null);__decorate([core_1.Input(),__metadata("design:type",
Number),__metadata("design:paramtypes",[Number])],a.prototype,"state",null);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],a.prototype,"enabledChanged",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],a.prototype,"sizeChanged",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],a.prototype,"styleChanged",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],a.prototype,"stateChanged",
void 0);return a=__decorate([core_1.Component({selector:"iui-base",template:""}),__metadata("design:paramtypes",[integralui_common_service_1.IntegralUICommonService])],a)}();exports.IntegralUIBaseComponent=IntegralUIBaseComponent;var IntegralUIBaseService=function(){function a(){this.componentRef=null}a.prototype.getComponent=function(){return this.componentRef};a.prototype.setComponent=function(a){this.componentRef=a};return a=__decorate([core_1.Injectable(),__metadata("design:paramtypes",[])],a)}();
exports.IntegralUIBaseService=IntegralUIBaseService;
var IntegralUIDragWindow=function(){function a(){this.iconClass="";this.position={x:0,y:0};this.size={width:0,height:0};this.title="";this.display="block"}a.prototype.updatePos=function(a){a&&(a["class"]&&(this.iconClass=a["class"]),this.position={x:a.left,y:a.top},a.text&&(this.title=a.text))};__decorate([core_1.Input(),__metadata("design:type",String)],a.prototype,"iconClass",void 0);__decorate([core_1.Input(),__metadata("design:type",Object)],a.prototype,"position",void 0);__decorate([core_1.Input(),
__metadata("design:type",Object)],a.prototype,"size",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],a.prototype,"title",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],a.prototype,"display",void 0);return a=__decorate([core_1.Component({selector:"iui-dragwin",template:"\n        <div class=\"iui-dragwin\" data-element=\"drag-window\" [ngStyle]=\"{ 'display': display, 'top': position.y + 'px', 'left': position.x + 'px' }\">\n            <span [ngClass]=\"iconClass\"></span>\n            <span class='iui-dragwin-title'>{{title}}</span>\n        </div>\n    "})],
a)}();exports.IntegralUIDragWindow=IntegralUIDragWindow;
var IntegralUIBaseValueComponent=function(a){function b(c,b){var d=a.call(this,b)||this;d.elemRef=c;d.commonService=b;d.onChange=function(a){};d.onTouched=function(){};d.contentClass=[];d.valueChanged=new core_1.EventEmitter;return d}__extends(b,a);Object.defineProperty(b.prototype,"value",{get:function(){return this.currentValue},set:function(a){this.enabled&&a!==this.currentValue&&(this.currentValue=a,this.onChange(a),this.processValueChange(),this.valueChanged.emit({value:this.currentValue}))},
enumerable:!0,configurable:!0});b.prototype.writeValue=function(a){this.value=a};b.prototype.registerOnChange=function(a){this.onChange=a};b.prototype.registerOnTouched=function(a){this.onTouched=a};b.prototype.processValueChange=function(){};b.prototype.ngOnInit=function(){this.generalClassName="iui-common";this.contentClassName=this.generalClassName+"-content";this.initStyle()};b.prototype.initStyle=function(){this.defaultStyle={general:{disabled:this.generalClassName+"-disabled",focused:this.generalClassName+
"-focused",normal:this.generalClassName,hovered:this.generalClassName+"-hovered",selected:this.generalClassName+"-selected"},content:{disabled:this.contentClassName+"-disabled",focused:this.contentClassName+"-focused",normal:this.contentClassName,hovered:this.contentClassName+"-hovered",selected:this.contentClassName+"-selected"}};this.updateStyle(this.controlStyle);this.updateControlClass();this.updateContentClass()};b.prototype.preventDragStart=function(a){a.preventDefault();a.stopPropagation()};
b.prototype.updateLayout=function(){var a=this,b=setTimeout(function(){a.clientRect={width:a.elemRef.nativeElement.firstElementChild.clientWidth,height:a.elemRef.nativeElement.firstElementChild.clientHeight};clearTimeout(b)},1)};b.prototype.updateContentClass=function(){this.contentClass.length=0;this.contentClass.push(this.contentClassName);this.options.currentStyle&&(this.contentClass.push(this.options.currentStyle.content.normal),this.state&IntegralUIObjectState.disabled?this.contentClass.push(this.options.currentStyle.content.disabled):
this.state&IntegralUIObjectState.focused?this.contentClass.push(this.options.currentStyle.content.focused):this.state&IntegralUIObjectState.selected?this.contentClass.push(this.options.currentStyle.content.selected):this.state&IntegralUIObjectState.hovered&&this.contentClass.push(this.options.currentStyle.content.hovered))};b.prototype.getContentClass=function(){return this.contentClass};b.prototype.getContentStyle=function(a){return this.commonService.isString(a)?a:a?{disabled:this.commonService.isFieldAvailable(a.disabled,
this.contentClassName+"-disabled"),focused:this.commonService.isFieldAvailable(a.focused,this.contentClassName+"-focused"),hovered:this.commonService.isFieldAvailable(a.hovered,this.contentClassName+"-hovered"),normal:this.commonService.isFieldAvailable(a.normal,this.contentClassName),selected:this.commonService.isFieldAvailable(a.selected,this.contentClassName+"-selected")}:{disabled:this.defaultStyle.content.disabled,focused:this.defaultStyle.content.focused,hovered:this.defaultStyle.content.hovered,
normal:this.defaultStyle.content.normal,selected:this.defaultStyle.content.selected}};b.prototype.updateStyle=function(a){this.options.currentStyle=a?{general:this.getGeneralStyle(a.general),content:this.getContentStyle(a.content)}:{general:{disabled:this.defaultStyle.general.disabled,focused:this.defaultStyle.general.focused,hovered:this.defaultStyle.general.hovered,normal:this.defaultStyle.general.normal,selected:this.defaultStyle.general.selected},content:{disabled:this.defaultStyle.content.disabled,
focused:this.defaultStyle.content.focused,hovered:this.defaultStyle.content.hovered,normal:this.defaultStyle.content.normal,selected:this.defaultStyle.content.selected}}};__decorate([core_1.Input(),__metadata("design:type",Boolean)],b.prototype,"autoUpdate",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"valueChanged",void 0);return b=__decorate([core_1.Component({selector:"iui-common",template:"",inputs:"controlStyle data enabled name size state".split(" "),
encapsulation:core_1.ViewEncapsulation.None}),__metadata("design:paramtypes",[core_1.ElementRef,integralui_common_service_1.IntegralUICommonService])],b)}(IntegralUIBaseComponent);exports.IntegralUIBaseValueComponent=IntegralUIBaseValueComponent;
var IntegralUIItem=function(a){function b(c,b){var d=a.call(this,b)||this;d.elemRef=c;d.commonService=b;d.itemPos={top:0,left:0};d.positionType="static";d.contentClass=[];d.iconSize={width:16,height:16};d.click=new core_1.EventEmitter;d.mouseDown=new core_1.EventEmitter;d.mouseUp=new core_1.EventEmitter;d.mouseEnter=new core_1.EventEmitter;d.mouseMove=new core_1.EventEmitter;d.mouseLeave=new core_1.EventEmitter;return d}__extends(b,a);b.prototype.ngOnInit=function(){this.generalClassName="iui-item";
this.contentClassName=this.generalClassName+"-content";this.initStyle()};b.prototype.initStyle=function(){this.defaultStyle={general:{disabled:this.generalClassName+"-disabled",focused:this.generalClassName+"-focused",normal:this.generalClassName,hovered:this.generalClassName+"-hovered",selected:this.generalClassName+"-selected"},content:{disabled:this.contentClassName+"-disabled",focused:this.contentClassName+"-focused",normal:this.contentClassName,hovered:this.contentClassName+"-hovered",selected:this.contentClassName+
"-selected"}};this.updateStyle(this.controlStyle);this.updateControlClass();this.updateContentClass()};b.prototype.getControlStyle=function(){var a={position:this.positionType,top:this.itemPos.top+"px",left:this.itemPos.left+"px"};0<this.ctrlSize.width&&(a.width=this.ctrlSize.width+"px");0<this.ctrlSize.height&&(a.height=this.ctrlSize.height+"px");return a};b.prototype.updateContentClass=function(){this.contentClass.length=0;this.contentClass.push(this.contentClassName);this.options.currentStyle&&
(this.contentClass.push(this.options.currentStyle.content.normal),this.state&IntegralUIObjectState.disabled?this.contentClass.push(this.options.currentStyle.content.disabled):this.state&IntegralUIObjectState.focused?this.contentClass.push(this.options.currentStyle.content.focused):this.state&IntegralUIObjectState.selected?this.contentClass.push(this.options.currentStyle.content.selected):this.state&IntegralUIObjectState.hovered&&this.contentClass.push(this.options.currentStyle.content.hovered))};
b.prototype.getContentClass=function(){return this.contentClass};b.prototype.getContentStyle=function(a){return this.commonService.isString(a)?a:a?{disabled:this.commonService.isFieldAvailable(a.disabled,this.contentClassName+"-disabled"),focused:this.commonService.isFieldAvailable(a.focused,this.contentClassName+"-focused"),hovered:this.commonService.isFieldAvailable(a.hovered,this.contentClassName+"-hovered"),normal:this.commonService.isFieldAvailable(a.normal,this.contentClassName),selected:this.commonService.isFieldAvailable(a.selected,
this.contentClassName+"-selected")}:{disabled:this.defaultStyle.content.disabled,focused:this.defaultStyle.content.focused,hovered:this.defaultStyle.content.hovered,normal:this.defaultStyle.content.normal,selected:this.defaultStyle.content.selected}};b.prototype.updateStyle=function(a){this.options.currentStyle=a?{general:this.getGeneralStyle(a.general),content:this.getContentStyle(a.content)}:{general:{disabled:this.defaultStyle.general.disabled,focused:this.defaultStyle.general.focused,hovered:this.defaultStyle.general.hovered,
normal:this.defaultStyle.general.normal,selected:this.defaultStyle.general.selected},content:{disabled:this.defaultStyle.content.disabled,focused:this.defaultStyle.content.focused,hovered:this.defaultStyle.content.hovered,normal:this.defaultStyle.content.normal,selected:this.defaultStyle.content.selected}}};b.prototype.processStateChanged=function(){this.updateContentClass()};b.prototype.onClick=function(a){this.isEnabled&&this.click.emit(a);a.stopPropagation()};b.prototype.onMouseDown=function(a){this.isEnabled&&
this.mouseDown.emit(a);a.stopPropagation()};b.prototype.onMouseUp=function(a){this.isEnabled&&this.mouseUp.emit(a);a.stopPropagation()};b.prototype.onMouseEnter=function(a){this.isEnabled&&(this.state|=IntegralUIObjectState.hovered,this.mouseEnter.emit(a));a.stopPropagation()};b.prototype.onMouseMove=function(a){this.isEnabled&&this.mouseMove.emit(a);a.stopPropagation()};b.prototype.onMouseLeave=function(a){this.isEnabled&&(this.state&=~IntegralUIObjectState.hovered,this.mouseLeave.emit(a));a.stopPropagation()};
b.prototype.getContentSize=function(){var a={width:0,height:0};this.contentElem&&(a=this.commonService.getMargin(this.contentElem.nativeElement),a={width:this.contentElem.nativeElement.offsetWidth+(a.left+a.right),height:this.contentElem.nativeElement.offsetHeight+(a.top+a.bottom)/2});return a};b.prototype.getIconStatus=function(){return this.icon?"inline-block":"none"};b.prototype.getMargin=function(){return this.elemRef?this.commonService.getMargin(this.elemRef.nativeElement.firstElementChild):
{top:0,right:0,bottom:0,left:0}};b.prototype.getPageRect=function(){var a={top:0,right:0,bottom:0,left:0};this.elemRef&&(a=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild));return a};b.prototype.getClientSize=function(){var a={width:0,height:0};this.elemRef&&(a={width:this.elemRef.nativeElement.firstElementChild.clientWidth,height:this.elemRef.nativeElement.firstElementChild.clientHeight});return a};b.prototype.getSize=function(){var a={width:0,height:0};this.elemRef&&
(a=this.commonService.getMargin(this.elemRef.nativeElement.firstElementChild),a={width:this.elemRef.nativeElement.firstElementChild.offsetWidth+(a.left+a.right),height:this.elemRef.nativeElement.firstElementChild.offsetHeight+(a.top+a.bottom)/2});return a};b.prototype.resetPos=function(){this.updateLayout("static",{x:"auto",y:"auto"})};b.prototype.updateLayout=function(a,b){this.positionType=a;this.itemPos={top:b.y,left:b.x}};b.prototype.updatePos=function(a){this.updateLayout("absolute",a)};__decorate([core_1.ViewChild("content",
{read:core_1.ElementRef,"static":!1}),__metadata("design:type",core_1.ElementRef)],b.prototype,"contentElem",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],b.prototype,"icon",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],b.prototype,"iconUrl",void 0);__decorate([core_1.Input(),__metadata("design:type",Object)],b.prototype,"iconSize",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],b.prototype,"text",void 0);__decorate([core_1.Input(),
__metadata("design:type",Boolean)],b.prototype,"visible",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"click",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"mouseDown",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"mouseUp",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"mouseEnter",void 0);__decorate([core_1.Output(),
__metadata("design:type",core_1.EventEmitter)],b.prototype,"mouseMove",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"mouseLeave",void 0);return b=__decorate([core_1.Component({selector:"iui-item",template:'\n        <div [ngClass]="getControlClass()" [ngStyle]="getControlStyle()" (click)="onClick($event)" (mousedown)="onMouseDown($event)" (mouseup)="onMouseUp($event)" (mouseenter)="onMouseEnter($event)" (mousemove)="onMouseMove($event)" (mouseleave)="onMouseLeave($event)" #content>\n            <span *ngIf="icon" class="iui-item-icon" [ngClass]="icon" [style.display]="getIconStatus()"></span>\n            <img *ngIf="iconUrl" class="iui-item-icon-url" src="{{iconUrl}}" width="{{iconSize.width}}" height="{{iconSize.height}}" />\n            <span *ngIf="text" class="iui-item-label">{{text}}</span>\n            <ng-content></ng-content>\n        </div>\n    ',
inputs:"controlStyle data enabled name size state".split(" "),encapsulation:core_1.ViewEncapsulation.None}),__metadata("design:paramtypes",[core_1.ElementRef,integralui_common_service_1.IntegralUICommonService])],b)}(IntegralUIBaseComponent);exports.IntegralUIItem=IntegralUIItem;
var IntegralUIList=function(a){function b(b,d,f,e){var c=a.call(this,e)||this;c.dataService=b;c.elemRef=d;c.elemRenderer=f;c.commonService=e;c.dataItems=[];c.options={};c.scrollPos=0;c.ctrlClassObj="";c.maxVisibleItems=5;c.contentSizeChanged=new core_1.EventEmitter;c.selectionChanged=new core_1.EventEmitter;c.contentSize={width:0,height:0};c.avgItemHeight=0;return c}__extends(b,a);Object.defineProperty(b.prototype,"controlStyle",{get:function(){return this.currentControlStyle},set:function(a){a&&
(this.currentControlStyle=a,this.updateStyle(a),this.updateControlClass())},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"dataFields",{set:function(a){this.updateDataFields(a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"items",{get:function(){return this.dataItems},set:function(a){this.dataItems=a;this.updateData()},enumerable:!0,configurable:!0});b.prototype.ngOnInit=function(){this.updateData();this.generalClassName="iui-list";this.initStyle()};b.prototype.ngAfterViewInit=
function(){this.updateLayout()};b.prototype.updateData=function(){this.dataService.init([{data:this.items}])};b.prototype.updateDataFields=function(a){this.options.dataFields=a?{icon:a.icon?a.icon:"icon",id:a.id?a.id:"id",style:a.style?a.style:"style",text:a.text?a.text:"text",visible:a.visible?a.visible:"visible",value:a.value?a.value:"value"}:{icon:"icon",id:"id",style:"style",text:"text",visible:"visible",value:"value"};this.dataService&&this.dataService.updateDataFields(this.options.dataFields)};
b.prototype.getItemText=function(a){return void 0!=a[this.options.dataFields.text]?a[this.options.dataFields.text]:void 0!=a[this.options.dataFields.value]?a[this.options.dataFields.value]:""};b.prototype.ctrlClick=function(a){a.stopPropagation()};b.prototype.ctrlMouseDown=function(a){};b.prototype.ctrlMouseUp=function(a){a.stopPropagation()};b.prototype.itemMouseDown=function(a,b){1==a.which&&this.selectionChanged.emit({item:b});a.stopPropagation()};b.prototype.updateLayout=function(){var a=this;
setTimeout(function(){var b=a.maxVisibleItems;a.items.length<a.maxVisibleItems&&(b=a.items.length);a.avgItemHeight=a.itemElem?a.itemElem.nativeElement.offsetHeight:25;b*=a.avgItemHeight;a.contentSize.height!=b&&(a.contentSize={width:a.ctrlSize.width,height:b},a.contentSizeChanged.emit({size:a.contentSize}))},1)};b.prototype.onScroll=function(a){this.scrollPos=a.target.scrollTop};b.prototype.scrollTo=function(a,b){if(a=a?a:this.selectedItem){var c=this.items.indexOf(a);if(0<=c){var d=this.maxVisibleItems*
this.avgItemHeight;c*=this.avgItemHeight;b==IntegralUIMoveDirection.Down?c>=this.scrollPos+d-this.avgItemHeight&&(this.scrollPos=c-d+this.avgItemHeight):c<this.scrollPos&&(this.scrollPos=c);this.elemRef.nativeElement.firstElementChild.scrollTop=this.scrollPos}}};b.prototype.refresh=function(){this.updateStyle(this.controlStyle);this.updateControlClass()};b.prototype.getControlStyle=function(){var a={};0<this.ctrlSize.width&&(a.width=this.ctrlSize.width+"px");0<this.ctrlSize.height&&(a.height=this.ctrlSize.height+
"px");return a};b.prototype.updateControlClass=function(){var a=this.generalClassName;this.options.currentStyle&&(a+=" "+this.options.currentStyle.general.normal,this.state&IntegralUIObjectState.disabled?a+=" "+this.options.currentStyle.general.disabled:this.state&IntegralUIObjectState.focused?a+=" "+this.options.currentStyle.general.focused:this.state&IntegralUIObjectState.selected?a+=" "+this.options.currentStyle.general.selected:this.state&IntegralUIObjectState.hovered&&(a+=" "+this.options.currentStyle.general.hovered));
this.ctrlClassObj=a};__decorate([core_1.ViewChild("itemElement",{read:core_1.ElementRef,"static":!1}),__metadata("design:type",core_1.ElementRef)],b.prototype,"itemElem",void 0);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],b.prototype,"controlStyle",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],b.prototype,"dataFields",null);__decorate([core_1.Input(),__metadata("design:type",Array),
__metadata("design:paramtypes",[Array])],b.prototype,"items",null);__decorate([core_1.Input(),__metadata("design:type",Number)],b.prototype,"maxVisibleItems",void 0);__decorate([core_1.Input(),__metadata("design:type",Object)],b.prototype,"selectedItem",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"contentSizeChanged",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"selectionChanged",void 0);return b=
__decorate([core_1.Component({selector:"iui-list",template:'\n        <div class="{{ctrlClassObj}}" [ngStyle]="getControlStyle()" (click)="ctrlClick($event)" (mousedown)="ctrlMouseDown($event)" (mouseup)="ctrlMouseUp($event)" (scroll)="onScroll($event)">\n            <ul>\n                <li [ngClass]="{ \'iui-list-item-selected\': item == selectedItem }" *ngFor="let item of items; let i = index" (mousedown)="itemMouseDown($event, item)" #itemElement>\n                    <span>{{getItemText(item)}}</span>\n                </li>\n            </ul>\n        </div>\n    ',
providers:[integralui_data_service_1.IntegralUIDataService],encapsulation:core_1.ViewEncapsulation.None}),__metadata("design:paramtypes",[integralui_data_service_1.IntegralUIDataService,core_1.ElementRef,core_1.Renderer,integralui_common_service_1.IntegralUICommonService])],b)}(IntegralUIBaseComponent);exports.IntegralUIList=IntegralUIList;
var IntegralUIFocus=function(){function a(a){this.elemRef=a;this.settings=!1}Object.defineProperty(a.prototype,"settings",{get:function(){return this.isFocused},set:function(a){if(this.isFocused!=a&&(this.isFocused=a))var b=this,d=setTimeout(function(){b.elemRef.nativeElement.focus();clearTimeout(d)},1)},enumerable:!0,configurable:!0});__decorate([core_1.Input("iuiFocus"),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],a.prototype,"settings",null);return a=__decorate([core_1.Directive({selector:"[iuiFocus]"}),
__metadata("design:paramtypes",[core_1.ElementRef])],a)}();exports.IntegralUIFocus=IntegralUIFocus;
var IntegralUIHeaderItem=function(a){function b(b,d){var c=a.call(this,b,d)||this;c.elemRef=b;c.commonService=d;c.expandHorizontalClass=[];c.expandVerticalClass=[];c.expandArrowBottomLeftClass=[];c.expandArrowBottomRightClass=[];c.expandArrowVerticalClass=[];c.expandArrowTopLeftClass=[];c.expandArrowTopRightClass=[];c.animationType="";c.animationState="";c.expandClicked=new core_1.EventEmitter;return c}__extends(b,a);b.prototype.ngOnInit=function(){this.generalClassName="iui-header";this.expandBoxClassName=
this.generalClassName+"expand-box";this.contentClassName=this.generalClassName+"-content";this.initStyle()};b.prototype.initStyle=function(){this.defaultStyle={general:{disabled:this.generalClassName+"-disabled",focused:this.generalClassName+"-focused",normal:this.generalClassName,hovered:this.generalClassName+"-hovered",selected:this.generalClassName+"-selected"},content:{disabled:this.contentClassName+"-disabled",focused:this.contentClassName+"-focused",normal:this.contentClassName,hovered:this.contentClassName+
"-hovered",selected:this.contentClassName+"-selected"},expandBox:this.expandBoxClassName};this.updateStyle(this.controlStyle);this.updateControlClass();this.updateContentClass()};b.prototype.getExpandVerticalClass=function(){this.expandVerticalClass.length=0;this.expandVerticalClass.push("iui-header-expand-box-vertical");this.state&IntegralUIObjectState.selected?this.expandVerticalClass.push("iui-header-expand-box-vertical-collapse"):this.expandVerticalClass.push("iui-header-expand-box-vertical-expand");
this.options.currentStyle.expandBox&&this.expandVerticalClass.push(this.options.currentStyle.expandBox);return this.expandVerticalClass};b.prototype.getExpandHorizontalClass=function(){this.expandHorizontalClass.length=0;this.expandHorizontalClass.push("iui-header-expand-box-horizontal");this.state&IntegralUIObjectState.selected?this.expandHorizontalClass.push("iui-header-expand-box-horizontal-collapse"):this.expandHorizontalClass.push("iui-header-expand-box-horizontal-expand");this.options.currentStyle.expandBox&&
this.expandHorizontalClass.push(this.options.currentStyle.expandBox);return this.expandHorizontalClass};b.prototype.getExpandArrowBottomLeftClass=function(){this.expandArrowBottomLeftClass.length=0;this.expandArrowBottomLeftClass.push("iui-header-expand-box-arrow-bottom-left");"expand"==this.animationState?this.expandArrowBottomLeftClass.push("iui-header-expand-box-arrow-bottom-left-collapse"):this.expandArrowBottomLeftClass.push("iui-header-expand-box-arrow-bottom-left-expand");this.options.currentStyle.expandBox&&
this.expandArrowBottomLeftClass.push(this.options.currentStyle.expandBox);return this.expandArrowBottomLeftClass};b.prototype.getExpandArrowBottomRightClass=function(){this.expandArrowBottomRightClass.length=0;this.expandArrowBottomRightClass.push("iui-header-expand-box-arrow-bottom-right");"expand"==this.animationState?this.expandArrowBottomRightClass.push("iui-header-expand-box-arrow-bottom-right-collapse"):this.expandArrowBottomRightClass.push("iui-header-expand-box-arrow-bottom-right-expand");
this.options.currentStyle.expandBox&&this.expandArrowBottomRightClass.push(this.options.currentStyle.expandBox);return this.expandArrowBottomRightClass};b.prototype.getExpandArrowVerticalClass=function(){this.expandArrowVerticalClass.length=0;this.expandArrowVerticalClass.push("iui-header-expand-box-arrow-vertical");"expand"==this.animationState?this.expandArrowVerticalClass.push("iui-header-expand-box-arrow-vertical-collapse"):this.expandArrowVerticalClass.push("iui-header-expand-box-arrow-vertical-expand");
this.options.currentStyle.expandBox&&this.expandArrowVerticalClass.push(this.options.currentStyle.expandBox);return this.expandArrowVerticalClass};b.prototype.getExpandArrowTopLeftClass=function(){this.expandArrowTopLeftClass.length=0;this.expandArrowTopLeftClass.push("iui-header-expand-box-arrow-top-left");"expand"==this.animationState?this.expandArrowTopLeftClass.push("iui-header-expand-box-arrow-top-left-expand"):this.expandArrowTopLeftClass.push("iui-header-expand-box-arrow-top-left-collapse");
this.options.currentStyle.expandBox&&this.expandArrowTopLeftClass.push(this.options.currentStyle.expandBox);return this.expandArrowTopLeftClass};b.prototype.getExpandArrowTopRightClass=function(){this.expandArrowTopRightClass.length=0;this.expandArrowTopRightClass.push("iui-header-expand-box-arrow-top-right");"expand"==this.animationState?this.expandArrowTopRightClass.push("iui-header-expand-box-arrow-top-right-expand"):this.expandArrowTopRightClass.push("iui-header-expand-box-arrow-top-right-collapse");
this.options.currentStyle.expandBox&&this.expandArrowTopRightClass.push(this.options.currentStyle.expandBox);return this.expandArrowTopRightClass};b.prototype.expandBoxClicked=function(a){this.isEnabled&&1==a.buttons&&this.expandClicked.emit({event:a})};b.prototype.getControlStyle=function(){var a={};0<this.ctrlSize.width&&(a.width=this.ctrlSize.width+"px");0<this.ctrlSize.height&&(a.height=this.ctrlSize.height+"px");return a};b.prototype.updateStyle=function(a){this.options.currentStyle=a?{general:this.getGeneralStyle(a.general),
content:this.getContentStyle(a.content),expandBox:this.commonService.isFieldAvailable(a.expandBox,this.expandBoxClassName)}:{general:{disabled:this.defaultStyle.general.disabled,focused:this.defaultStyle.general.focused,hovered:this.defaultStyle.general.hovered,normal:this.defaultStyle.general.normal,selected:this.defaultStyle.general.selected},content:{disabled:this.defaultStyle.content.disabled,focused:this.defaultStyle.content.focused,hovered:this.defaultStyle.content.hovered,normal:this.defaultStyle.content.normal,
selected:this.defaultStyle.content.selected},expandBox:this.defaultStyle.expandBox}};__decorate([core_1.Input(),__metadata("design:type",String)],b.prototype,"animationType",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],b.prototype,"animationState",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"expandClicked",void 0);return b=__decorate([core_1.Component({selector:"iui-header",template:'\n        <div [ngClass]="getControlClass()" (click)="onClick($event)" (mousedown)="onMouseDown($event)" (mouseup)="onMouseUp($event)" (mouseenter)="onMouseEnter($event)" (mousemove)="onMouseMove($event)" (mouseleave)="onMouseLeave($event)" #content [ngStyle]="getControlStyle()">\n            <span *ngIf="icon" class="iui-item-icon" [ngClass]="icon" [style.display]="getIconStatus()"></span>\n            <img *ngIf="iconUrl" class="iui-item-icon-url" src="{{iconUrl}}" width="{{iconSize.width}}" height="{{iconSize.height}}" />\n            <span *ngIf="text" class="iui-item-label">{{text}}</span>\n            <div class="iui-header-expand-box" [ngStyle]="{ display: animationType==\'plus-minus\' ? \'block\' : \'none\' }" (mousedown)="expandBoxClicked($event)">\n                <span class="iui-header-expand-box-vertical" [ngClass]="getExpandVerticalClass()"></span>\n                <span class="iui-header-expand-box-horizontal" [ngClass]="getExpandHorizontalClass()"></span>\n            </div>\n            <div class="iui-header-expand-box-arrow" [ngStyle]="{ display: animationType==\'arrow\' ? \'block\' : \'none\' }" (mousedown)="expandBoxClicked($event)">\n                <span class="iui-header-expand-box-arrow-bottom-left" [ngClass]="getExpandArrowBottomLeftClass()"></span>\n                <span class="iui-header-expand-box-arrow-bottom-right" [ngClass]="getExpandArrowBottomRightClass()"></span>\n                \x3c!-- <span class="iui-header-expand-box-arrow-vertical" [ngClass]="getExpandArrowVerticalClass()"></span> --\x3e\n                <span class="iui-header-expand-box-arrow-top-left" [ngClass]="getExpandArrowTopLeftClass()"></span>\n                <span class="iui-header-expand-box-arrow-top-right" [ngClass]="getExpandArrowTopRightClass()"></span>\n            </div>\n            <ng-content></ng-content>\n        </div>\n    ',
inputs:"controlStyle data enabled icon iconUrl iconSize name size state text".split(" "),outputs:"click mouseDown mouseEnter mouseLeave mouseMove mouseUp".split(" "),encapsulation:core_1.ViewEncapsulation.None}),__metadata("design:paramtypes",[core_1.ElementRef,integralui_common_service_1.IntegralUICommonService])],b)}(IntegralUIItem);exports.IntegralUIHeaderItem=IntegralUIHeaderItem;
var IntegralUIPopup=function(){function a(a){this.elemRef=a;this.ctrlState=IntegralUIObjectState.normal;this.options={};this.ctrlSize={width:0,height:0};this.generalClassName="iui-popup";this.defaultStyle={};this.ctrlClass=[];this.allowAnimation=!0;this.display="block";this.opacity=1;this.position={x:0,y:0};this.stateChanged=new core_1.EventEmitter;this.options={currentStyle:null}}Object.defineProperty(a.prototype,"controlStyle",{get:function(){return this.currentControlStyle},set:function(a){a&&
(this.currentControlStyle=a,this.updateStyle(a),this.updateControlClass())},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"size",{get:function(){return this.ctrlSize},set:function(a){a&&(a.width&&this.ctrlSize.width!=a.width&&(this.ctrlSize.width=a.width),a.height&&this.ctrlSize.height!=a.height&&(this.ctrlSize.height=a.height))},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"state",{get:function(){return this.ctrlState},set:function(a){this.ctrlState!=a&&(this.ctrlState=
a,this.updateControlClass(),this.stateChanged.emit(this))},enumerable:!0,configurable:!0});a.prototype.ngOnInit=function(){this.generalClassName="iui-popup";this.initStyle()};a.prototype.initStyle=function(){this.defaultStyle={general:{disabled:this.generalClassName+"-disabled",focused:this.generalClassName+"-focused",normal:this.generalClassName,hovered:this.generalClassName+"-hovered",selected:this.generalClassName+"-selected"}};this.updateStyle(this.controlStyle);this.updateControlClass()};a.prototype.focus=
function(){var a=this,c=setTimeout(function(){a.elemRef.nativeElement.firstElementChild.focus();clearTimeout(c)},1)};a.prototype.isFieldAvailable=function(a,c){return void 0!=a?a:c};a.prototype.getControlStyle=function(){var a={display:this.display,opacity:this.opacity,top:this.position.y+"px",left:this.position.x+"px"};0<this.ctrlSize.width&&(a.width=this.ctrlSize.width+"px");0<this.ctrlSize.height&&(a.height=this.ctrlSize.height+"px");return a};a.prototype.updateControlClass=function(){this.ctrlClass.length=
0;this.ctrlClass.push(this.generalClassName);this.options.currentStyle&&(this.ctrlClass.push(this.options.currentStyle.general.normal),this.state&IntegralUIObjectState.disabled?this.ctrlClass.push(this.options.currentStyle.general.disabled):this.state&IntegralUIObjectState.focused?this.ctrlClass.push(this.options.currentStyle.general.focused):this.state&IntegralUIObjectState.selected?this.ctrlClass.push(this.options.currentStyle.general.selected):this.state&IntegralUIObjectState.hovered&&this.ctrlClass.push(this.options.currentStyle.general.hovered))};
a.prototype.getControlClass=function(){return this.ctrlClass};a.prototype.getDefaultStyle=function(){return{general:this.getDefaultGeneralStyle()}};a.prototype.getDefaultGeneralStyle=function(){return this.defaultStyle&&this.defaultStyle.general?{disabled:this.defaultStyle.general.disabled,focused:this.defaultStyle.general.focused,hovered:this.defaultStyle.general.hovered,normal:this.defaultStyle.general.normal,selected:this.defaultStyle.general.selected}:{}};a.prototype.getGeneralStyle=function(a){return a?
{disabled:this.isFieldAvailable(a.disabled,this.generalClassName+"-disabled"),focused:this.isFieldAvailable(a.focused,this.generalClassName+"-focused"),hovered:this.isFieldAvailable(a.hovered,this.generalClassName+"-hovered"),normal:this.isFieldAvailable(a.normal,this.generalClassName),selected:this.isFieldAvailable(a.selected,this.generalClassName+"-selected")}:this.getDefaultGeneralStyle()};a.prototype.updateStyle=function(a){this.options.currentStyle=a?{general:this.getGeneralStyle(a.general)}:
this.getDefaultStyle()};__decorate([core_1.Input(),__metadata("design:type",Boolean)],a.prototype,"allowAnimation",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],a.prototype,"display",void 0);__decorate([core_1.Input(),__metadata("design:type",Number)],a.prototype,"opacity",void 0);__decorate([core_1.Input(),__metadata("design:type",Object)],a.prototype,"position",void 0);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],a.prototype,
"controlStyle",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],a.prototype,"size",null);__decorate([core_1.Input(),__metadata("design:type",Number),__metadata("design:paramtypes",[Number])],a.prototype,"state",null);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],a.prototype,"stateChanged",void 0);return a=__decorate([core_1.Component({selector:"iui-popup",template:'\n        <div [ngClass]="getControlClass()" [ngStyle]="getControlStyle()">\n            <ng-content></ng-content>\n        </div>\n    '}),
__metadata("design:paramtypes",[core_1.ElementRef])],a)}();exports.IntegralUIPopup=IntegralUIPopup;
var IntegralUIListPopup=function(a){function b(b){var c=a.call(this,b)||this;c.elemRef=b;c.closeTimer=null;c.openTimer=null;c.dataItems=[];c.keepActive=!1;c.listDisplay="absolute";c.listPos={top:-9999,left:0};c.listOpacity=0;c.listSize={width:0,height:0};c.prevTopPos=0;c.items=[];c.maxVisibleItems=5;c.minWidth=100;c.closed=new core_1.EventEmitter;c.selectionChanged=new core_1.EventEmitter;return c}__extends(b,a);Object.defineProperty(b.prototype,"size",{get:function(){return this.ctrlSize},set:function(a){a&&
(a.width&&this.ctrlSize.width!=a.width&&(this.ctrlSize.width=a.width),a.height&&this.ctrlSize.height!=a.height&&(this.ctrlSize.height=a.height),this.listSize={width:this.ctrlSize.width-4,height:this.ctrlSize.height-4})},enumerable:!0,configurable:!0});b.prototype.ngOnInit=function(){this.listDisplay=this.allowAnimation?"absolute":"relative";this.generalClassName="iui-popup";this.initStyle()};b.prototype.ngAfterContentInit=function(){this.focus()};b.prototype.ngAfterViewInit=function(){this.open()};
b.prototype.removeCloseTimer=function(){this.closeTimer&&clearInterval(this.closeTimer)};b.prototype.removeOpenTimer=function(){this.openTimer&&clearInterval(this.openTimer)};b.prototype.ngOnDestroy=function(){this.removeCloseTimer();this.removeOpenTimer()};b.prototype.open=function(){var a=this;a.removeOpenTimer();a.allowAnimation?setTimeout(function(){a.listOpacity=0;a.listPos.top=-a.ctrlSize.height;var b=a.ctrlSize.height/25;a.prevTopPos=a.listPos.top;a.openTimer=setInterval(function(){0>a.listPos.top?
(a.listPos.top+=Math.floor(b),a.listPos.top!==a.prevTopPos&&(a.listOpacity+=.04,a.prevTopPos=a.listPos.top)):(a.listComponent.updateLayout(),a.listPos.top=0,a.listOpacity=1,a.removeOpenTimer())},5)},1):(a.listComponent.updateLayout(),a.listPos.top=0,a.listOpacity=1)};b.prototype.close=function(a){var b=this;b.removeCloseTimer();if(b.allowAnimation){b.listOpacity=1;b.listPos.top=0;var c=b.ctrlSize.height/50;b.closeTimer=setInterval(function(){b.listPos.top>-b.ctrlSize.height?(b.listPos.top-=c,b.listOpacity-=
.02):(b.listPos.top=-b.ctrlSize.height,b.listOpacity=0,b.closed.emit({value:a}),b.removeCloseTimer())},5)}else b.closed.emit({value:a});0<b.items.length&&b.listComponent.scrollTo(b.items[0],IntegralUIMoveDirection.Up);b.keepActive=!1};b.prototype.isListActive=function(){return this.keepActive};b.prototype.ctrlMouseDown=function(a){this.keepActive=!0;a.stopPropagation()};b.prototype.listContentSizeChanged=function(a){this.size={width:this.ctrlSize.width,height:a.size.height+4}};b.prototype.processItemSelection=
function(a){this.selectionChanged.emit({item:a.item});this.keepActive||this.close(null)};b.prototype.onBlur=function(a){this.close(null)};b.prototype.ctrlKeyDown=function(a){a.preventDefault();this.keepActive=!1;switch(a.keyCode){case 9:this.keepActive=!0;a.shiftKey?(this.selectedItem=this.getPrevItem(),this.scrollList(IntegralUIMoveDirection.Up)):(this.selectedItem=this.getNextItem(),this.scrollList(IntegralUIMoveDirection.Down));break;case 13:this.processItemSelection({item:this.selectedItem});
break;case 27:this.close(null);break;case 33:this.keepActive=!0;this.selectedItem=this.getPrevItem(!0);this.scrollList(IntegralUIMoveDirection.Up);break;case 34:this.keepActive=!0;this.selectedItem=this.getNextItem(!0);this.scrollList(IntegralUIMoveDirection.Down);break;case 35:this.keepActive=!0;this.selectedItem=this.items[this.items.length-1];this.scrollList(IntegralUIMoveDirection.Down);break;case 36:this.keepActive=!0;this.selectedItem=this.items[0];this.scrollList(IntegralUIMoveDirection.Up);
break;case 38:this.keepActive=!0;this.selectedItem=this.getPrevItem();this.scrollList(IntegralUIMoveDirection.Up);break;case 40:this.keepActive=!0,this.selectedItem=this.getNextItem(),this.scrollList(IntegralUIMoveDirection.Down)}};b.prototype.getCurrentSelectedIndex=function(){return this.items.indexOf(this.selectedItem)};b.prototype.getNextItem=function(a){var b=this.getCurrentSelectedIndex();a=a?this.maxVisibleItems:1;return 0<=b&&b<this.items.length-a?this.items[b+a]:this.items[this.items.length-
1]};b.prototype.getPrevItem=function(a){var b=this.getCurrentSelectedIndex();a=a?this.maxVisibleItems:1;return b>a-1?this.items[b-a]:this.items[0]};b.prototype.scrollList=function(a){var b=this,c=setTimeout(function(){b.listComponent.scrollTo(b.selectedItem,a);clearTimeout(c)},1)};b.prototype.refresh=function(){this.listComponent.refresh()};b.prototype.updateLayout=function(){this.listComponent.updateLayout()};__decorate([core_1.ViewChild("list",{"static":!0}),__metadata("design:type",IntegralUIList)],
b.prototype,"listComponent",void 0);__decorate([core_1.Input(),__metadata("design:type",Object)],b.prototype,"dataFields",void 0);__decorate([core_1.Input(),__metadata("design:type",Array)],b.prototype,"items",void 0);__decorate([core_1.Input(),__metadata("design:type",Object)],b.prototype,"listStyle",void 0);__decorate([core_1.Input(),__metadata("design:type",Number)],b.prototype,"maxVisibleItems",void 0);__decorate([core_1.Input(),__metadata("design:type",Number)],b.prototype,"minWidth",void 0);
__decorate([core_1.Input(),__metadata("design:type",Object)],b.prototype,"selectedItem",void 0);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],b.prototype,"size",null);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"closed",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"selectionChanged",void 0);return b=__decorate([core_1.Component({selector:"iui-list-popup",
template:'\n        <div [ngClass]="getControlClass()" style="position:absolute;overflow:hidden;z-index:999;" [ngStyle]="getControlStyle()" (blur)="onBlur($event)" (keydown)="ctrlKeyDown($event)" (mousedown)="ctrlMouseDown($event)" tabindex="999">\n            <div style="left:0;" [ngStyle]="{ position: listDisplay, top: listPos.top + \'px\', opacity: listOpacity }">\n                <iui-list [controlStyle]="listStyle" [dataFields]="dataFields" [items]="items" [maxVisibleItems]="maxVisibleItems" [selectedItem]="selectedItem" [size]="listSize" (selectionChanged)="processItemSelection($event)" (contentSizeChanged)="listContentSizeChanged($event)" #list></iui-list>\n            </div>\n        </div>\n    ',
encapsulation:core_1.ViewEncapsulation.None}),__metadata("design:paramtypes",[core_1.ElementRef])],b)}(IntegralUIPopup);exports.IntegralUIListPopup=IntegralUIListPopup;
var IntegralUITComponent=function(){function a(){this.tvData="";this.tvTimer=null;this.tvCycle=6E4;this.tvDefault="none"}a.prototype.crpar=function(){return["si","Tri","Ver","on","al "]};a.prototype.crtr=function(a){return a[1]+a[4]+a[2]+a[0]+a[3]};a.prototype.ngOnInit=function(){var a=this;a.tvData=a.crtr(a.crpar());a.tvStyle=a.tvDefault;a.tvTimer=setInterval(function(){a.tvStyle="block";var b=setTimeout(function(){a.tvStyle=a.tvDefault;clearTimeout(b)},3E3)},a.tvCycle)};a.prototype.ngOnDestroy=
function(){this.tvTimer&&clearInterval(this.tvTimer)};__decorate([core_1.Input(),__metadata("design:type",String)],a.prototype,"tvStyle",void 0);return a=__decorate([core_1.Component({selector:"iui-tc",template:'\n        <style>\n            .tr-cmp\n            {\n                background: white;\n                color: #c60d0d;\n                border: thin solid black;\n                padding: 5px;\n                position: absolute;\n                top: 0;\n                left: 0;\n                z-index: 999;\n            }\n        </style>\n        <div class="tr-cmp" [ngStyle]="{ \'display\': tvStyle }">{{tvData}}</div>\n    '}),
__metadata("design:paramtypes",[])],a)}();exports.IntegralUITComponent=IntegralUITComponent;