/*
  filename: integralui.sidebar.js
  version : 1.0.0
  Copyright © 2016-2020 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(){var d=function(b,a){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])};return d(b,a)};return function(b,a){function c(){this.constructor=b}d(b,a);b.prototype=null===a?Object.create(a):(c.prototype=a.prototype,new c)}}();Object.defineProperty(exports,"__esModule",{value:!0});
var core_1=require("@angular/core"),integralui_core_1=require("./integralui.core"),integralui_common_service_1=require("../services/integralui.common.service"),integralui_data_service_1=require("../services/integralui.data.service"),i0=require("@angular/core"),i1=require("../services/integralui.common.service"),i2=require("@angular/common"),i3=require("./integralui.core");
function IntegralUISideContentPopup_div_1_div_1_Template(d,b){d&1&&(i0.\u0275\u0275elementStart(0,"div",7),i0.\u0275\u0275text(1),i0.\u0275\u0275elementEnd());if(d&2){var a=i0.\u0275\u0275nextContext(2);i0.\u0275\u0275advance(1);i0.\u0275\u0275textInterpolate(a.title)}}var _c0=function(d){return{$implicit:d}};
function IntegralUISideContentPopup_div_1_Template(d,b){d&1&&(i0.\u0275\u0275elementStart(0,"div",4),i0.\u0275\u0275template(1,IntegralUISideContentPopup_div_1_div_1_Template,2,1,"div",5),i0.\u0275\u0275elementStart(2,"div",6),i0.\u0275\u0275element(3,"span",3),i0.\u0275\u0275elementEnd(),i0.\u0275\u0275elementEnd());if(d&2){var a=i0.\u0275\u0275nextContext();i0.\u0275\u0275property("ngStyle",a.getHeaderStyle());i0.\u0275\u0275advance(1);i0.\u0275\u0275property("ngIf",!a.templateObj.headerTemplate&&
a.title&&""!=a.title);i0.\u0275\u0275advance(2);i0.\u0275\u0275property("iuiTemplateOutlet",a.templateObj.headerTemplate)("iuiTemplateOutletContext",i0.\u0275\u0275pureFunction1(4,_c0,a.templateObj.data))}}var _c1=["header"],_c2=["headerButton"],_c3=["headerBlock"],_c4=["content"],_c5=function(d,b,a,c){return{top:d,width:b,height:a,opacity:c}};
function IntegralUISideBar_div_1_Template(d,b){d&1&&i0.\u0275\u0275element(0,"div",8);if(d&2){var a=i0.\u0275\u0275nextContext();i0.\u0275\u0275property("ngStyle",i0.\u0275\u0275pureFunction4(1,_c5,a.headerOffsetHeight+"px",a.minCtrlSize.width+"px",a.maxCtrlSize.height+"px",a.barOpacity))}}
function IntegralUISideBar_div_7_div_2_Template(d,b){d&1&&(i0.\u0275\u0275elementStart(0,"div",14),i0.\u0275\u0275text(1),i0.\u0275\u0275elementEnd());if(d&2){var a=i0.\u0275\u0275nextContext(2);i0.\u0275\u0275advance(1);i0.\u0275\u0275textInterpolate(a.title)}}var _c6=function(d,b){return{marginLeft:d,width:b}};
function IntegralUISideBar_div_7_Template(d,b){d&1&&(i0.\u0275\u0275elementStart(0,"div",9,10),i0.\u0275\u0275template(2,IntegralUISideBar_div_7_div_2_Template,2,1,"div",11),i0.\u0275\u0275elementStart(3,"div",12),i0.\u0275\u0275element(4,"span",13),i0.\u0275\u0275elementEnd(),i0.\u0275\u0275elementEnd());if(d&2){var a=i0.\u0275\u0275nextContext();i0.\u0275\u0275property("ngStyle",i0.\u0275\u0275pureFunction2(4,_c6,a.currentHeaderBlockPos+"px",a.maxCtrlSize.width-a.minCtrlSize.width-a.currentHeaderBlockPos+
"px"));i0.\u0275\u0275advance(2);i0.\u0275\u0275property("ngIf",0==a.headerData[0].length&&a.title&&""!=a.title);i0.\u0275\u0275advance(2);i0.\u0275\u0275property("iuiTemplateOutlet",a.headerData[0])("iuiTemplateOutletContext",i0.\u0275\u0275pureFunction1(7,_c0,a.data))}}
function IntegralUISideBar_div_8_Template(d,b){d&1&&(i0.\u0275\u0275elementStart(0,"div",15,16),i0.\u0275\u0275element(2,"span",13),i0.\u0275\u0275elementEnd());if(d&2){var a=i0.\u0275\u0275nextContext();i0.\u0275\u0275property("ngStyle",a.getContentStyle());i0.\u0275\u0275advance(2);i0.\u0275\u0275property("iuiTemplateOutlet",a.contentData[0])("iuiTemplateOutletContext",i0.\u0275\u0275pureFunction1(3,_c0,a.data))}}
var IntegralUISideContentPopup=function(d){function b(a,c){var b=d.call(this,a,c)||this;b.elemRef=a;b.commonService=c;b.headerHeight=0;b.headerOffsetHeight=0;b.placement=integralui_core_1.IntegralUIPlacement.Left;b.closed=new core_1.EventEmitter;return b}__extends(b,d);b.prototype.ngOnInit=function(){this.generalClassName="iui-sidecontent-popup";this.initStyle()};b.prototype.ngAfterContentInit=function(){this.focus()};b.prototype.ngAfterViewInit=function(){};b.prototype.open=function(){this.isVisible=
!0};b.prototype.close=function(){this.isVisible=!1;this.closed.emit(null)};b.prototype.processClose=function(){this.close()};b.prototype.getContentStyle=function(){var a={};switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:a.marginTop=this.size.height-this.maxSize.height+"px";a.width=this.maxSize.width+"px";a.height=this.maxSize.height+"px";break;case integralui_core_1.IntegralUIPlacement.Right:a.width=this.maxSize.width+"px";a.height=this.maxSize.height-this.headerOffsetHeight+
"px";break;case integralui_core_1.IntegralUIPlacement.Bottom:a.width=this.maxSize.width+"px";a.height=this.maxSize.height+"px";break;default:a.borderLeft=0,a.marginLeft=this.size.width-this.maxSize.width+"px",a.width=this.maxSize.width+"px",a.height=this.maxSize.height-this.headerOffsetHeight+"px"}return a};b.prototype.getHeaderStyle=function(){return{borderTop:0,borderRight:0,borderLeft:0,height:this.headerHeight+"px"}};b.\u0275fac=function(a){return new (a||b)(i0.\u0275\u0275directiveInject(i0.ElementRef),
i0.\u0275\u0275directiveInject(i1.IntegralUICommonService))};b.\u0275cmp=i0.\u0275\u0275defineComponent({type:b,selectors:[["iui-side-content-popup"]],inputs:{headerHeight:"headerHeight",headerOffsetHeight:"headerOffsetHeight",placement:"placement",title:"title"},outputs:{closed:"closed"},features:[i0.\u0275\u0275InheritDefinitionFeature],decls:4,vars:8,consts:[["tabindex","999",3,"ngClass","ngStyle"],["class","iui-sidebar-header","style","padding-left:0;",3,"ngStyle",4,"ngIf"],[1,"iui-sidebar-content",
3,"ngStyle"],[3,"iuiTemplateOutlet","iuiTemplateOutletContext"],[1,"iui-sidebar-header",2,"padding-left","0",3,"ngStyle"],["class","iui-sidebar-header-title",4,"ngIf"],[1,"iui-sidebar-header-content"],[1,"iui-sidebar-header-title"]],template:function(a,c){a&1&&(i0.\u0275\u0275elementStart(0,"div",0),i0.\u0275\u0275template(1,IntegralUISideContentPopup_div_1_Template,4,6,"div",1),i0.\u0275\u0275elementStart(2,"div",2),i0.\u0275\u0275element(3,"span",3),i0.\u0275\u0275elementEnd(),i0.\u0275\u0275elementEnd());
a&2&&(i0.\u0275\u0275property("ngClass",c.getControlClass())("ngStyle",c.getControlStyle()),i0.\u0275\u0275advance(1),i0.\u0275\u0275property("ngIf",1==c.placement%2),i0.\u0275\u0275advance(1),i0.\u0275\u0275property("ngStyle",c.getContentStyle()),i0.\u0275\u0275advance(1),i0.\u0275\u0275property("iuiTemplateOutlet",c.templateObj.contentTemplate)("iuiTemplateOutletContext",i0.\u0275\u0275pureFunction1(6,_c0,c.templateObj.data)))},directives:[i2.NgClass,i2.NgStyle,i2.NgIf,i3.IntegralUITemplateOutlet],
encapsulation:2});return b}(integralui_core_1.IntegralUIPopup);exports.IntegralUISideContentPopup=IntegralUISideContentPopup;
(function(){i0.\u0275setClassMetadata(IntegralUISideContentPopup,[{type:core_1.Component,args:[{selector:"iui-side-content-popup",template:'\n        <div [ngClass]="getControlClass()" [ngStyle]="getControlStyle()" tabindex="999">\n            <div *ngIf="placement % 2 == 1" class="iui-sidebar-header" style="padding-left:0;" [ngStyle]="getHeaderStyle()">\n                <div *ngIf="!templateObj.headerTemplate && title && title != \'\'" class="iui-sidebar-header-title">{{title}}</div>\n                <div class="iui-sidebar-header-content">\n                    <span [iuiTemplateOutlet]="templateObj.headerTemplate" [iuiTemplateOutletContext]="{$implicit: (templateObj.data)}"></span>\n                </div>\n            </div>\n            <div class="iui-sidebar-content" [ngStyle]="getContentStyle()">\n                <span [iuiTemplateOutlet]="templateObj.contentTemplate" [iuiTemplateOutletContext]="{$implicit: (templateObj.data)}"></span>\n            </div>\n        </div>\n    ',encapsulation:core_1.ViewEncapsulation.None}]}],
function(){return[{type:i0.ElementRef},{type:i1.IntegralUICommonService}]},{headerHeight:[{type:core_1.Input}],headerOffsetHeight:[{type:core_1.Input}],placement:[{type:core_1.Input}],title:[{type:core_1.Input}],closed:[{type:core_1.Output}]})})();
var IntegralUISideBar=function(d){function b(a,c,b,g){var e=d.call(this,c)||this;e.elemRef=a;e.commonService=c;e.cmpResolver=b;e.baseService=g;e.closeTimer=null;e.openTimer=null;e.contentData=[];e.headerData=[];e.isTouchProcessed=!1;e.barOpacity=1;e.barSize={width:0,height:0};e.currentHeaderBlockPos=0;e.currentPlacement=integralui_core_1.IntegralUIPlacement.Left;e.contentSize={width:0,height:0};e.currentSize={width:0,height:0};e.headerBlockSize={width:0,height:0};e.headerHeight=0;e.headerOffsetHeight=
0;e.maxCtrlSize={width:0,height:0};e.minCtrlSize={width:0,height:0};e.expandValue=!1;e.isPopupVisible=!1;e.popupValue=!1;e.templateList=[];e.popupRef=null;e.popupCmp=null;e.tRef=null;e.animationSpeed=integralui_core_1.IntegralUISpeedMode.Normal;return e}__extends(b,d);b.prototype.ngOnInit=function(){this.baseService.setComponent(this);this.generalClassName="iui-sidebar";this.initStyle()};b.prototype.ngAfterViewInit=function(){var a=this,c=setTimeout(function(){var b=a.cmpResolver.resolveComponentFactory(integralui_core_1.IntegralUITComponent);
b&&a.headerRef&&(a.tRef=a.headerRef.createComponent(b));clearTimeout(c)},100)};b.prototype.ngAfterContentInit=function(){var a=this;a.updateTemplate();var c=setTimeout(function(){a.addPopup();clearTimeout(c)},1);a.updateLayout()};b.prototype.updateTemplate=function(){this.contentData.length=0;this.headerData.length=0;if(this.templates){this.templateList=this.templates.toArray();for(var a=0;a<this.templateList.length;a++)if(this.templateList[a].settings)switch(this.templateList[a].settings.type){case "header":this.headerData.push(this.templateList[a].getTemplate());
break;case "content":this.contentData.push(this.templateList[a].getTemplate())}}};b.prototype.removeCloseTimer=function(){this.closeTimer&&clearInterval(this.closeTimer)};b.prototype.removeOpenTimer=function(){this.openTimer&&clearInterval(this.openTimer)};b.prototype.ngOnDestroy=function(){this.removePopup();this.removeCloseTimer();this.removeOpenTimer();this.tRef&&this.tRef.destroy()};Object.defineProperty(b.prototype,"expanded",{get:function(){return this.expandValue},set:function(a){this.expandValue!=
a&&(this.expandValue=a,this.toggle())},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"placement",{get:function(){return this.currentPlacement},set:function(a){void 0!=a&&this.currentPlacement!=a&&(this.currentPlacement=a,this.updateLayout())},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"popup",{get:function(){return this.popupValue},set:function(a){this.popupValue!=a&&(this.popupValue=a,this.expanded=!1)},enumerable:!0,configurable:!0});b.prototype.addPopup=
function(){var a=this;if(a.appRef&&0<a.contentData.length){a.removePopup();var c=a.cmpResolver.resolveComponentFactory(IntegralUISideContentPopup);c&&(a.popupRef=a.appRef.createComponent(c),a.popupRef.instance&&(a.popupCmp=a.popupRef.instance),a.hidePopup(),a.popupCmp&&(a.popupCmp.templateObj={data:{},contentTemplate:a.contentData[0],headerTemplate:a.headerData[0]},a.popupCmp.closed.subscribe(function(c){a.hidePopup()})))}};b.prototype.removePopup=function(){this.popupCmp&&this.popupCmp.closed&&this.popupCmp.closed.unsubscribe();
this.popupRef&&this.popupRef.destroy();this.popupCmp=null};b.prototype.hidePopup=function(){this.popupCmp&&this.closePopup()};b.prototype.showPopup=function(){if(this.popupCmp){var a=this.commonService.getShiftPos(),c=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild);this.popupCmp.allowAnimation=this.allowAnimation;this.popupCmp.display="block";this.popupCmp.title=this.title;this.popupCmp.headerHeight=this.headerHeight;this.popupCmp.headerOffsetHeight=this.headerOffsetHeight;
this.popupCmp.placement=this.placement;switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:this.popupCmp.position={x:c.left+a.x,y:c.bottom+a.y-1};this.popupCmp.size={width:this.barSize.width,height:0};this.popupCmp.maxSize={width:this.barSize.width,height:this.maxCtrlSize.height-this.minCtrlSize.height};break;case integralui_core_1.IntegralUIPlacement.Right:this.popupCmp.position={x:c.left+a.x,y:c.top+a.y};this.popupCmp.size={width:0,height:this.barSize.height};this.popupCmp.maxSize=
{width:this.maxCtrlSize.width-this.minCtrlSize.width,height:this.barSize.height};break;case integralui_core_1.IntegralUIPlacement.Bottom:this.popupCmp.position={x:c.left+a.x,y:c.top+a.y-1};this.popupCmp.size={width:this.barSize.width,height:0};this.popupCmp.maxSize={width:this.barSize.width,height:this.maxCtrlSize.height-this.minCtrlSize.height};break;default:this.popupCmp.position={x:c.right+a.x-1,y:c.top+a.y},this.popupCmp.size={width:0,height:this.barSize.height},this.popupCmp.maxSize={width:this.maxCtrlSize.width-
this.minCtrlSize.width,height:this.barSize.height}}this.popupCmp.open();this.openPopup();this.isPopupVisible=!0}};b.prototype.headerMouseDown=function(a){this.isTouchProcessed||this.toggleButtonClicked();a.stopPropagation()};b.prototype.headerTouchStart=function(a){var c=this;c.isTouchProcessed=!0;c.toggleButtonClicked();setTimeout(function(){c.isTouchProcessed=!1},100);a.stopPropagation()};b.prototype.toggleButtonClicked=function(){this.popup||this.placement==integralui_core_1.IntegralUIPlacement.Right||
this.placement==integralui_core_1.IntegralUIPlacement.Bottom?this.popupCmp&&(this.isPopupVisible?this.hidePopup():this.showPopup()):this.expanded=!this.expanded};b.prototype.getCtrlSpace=function(a){var c=this.commonService.getPadding(this.elemRef.nativeElement),b=this.commonService.getBorderWidth(this.elemRef.nativeElement);return a?c.top+c.bottom+b.top+b.bottom:c.left+c.right+b.left+b.right};b.prototype.getMaxSize=function(){return{width:this.maxCtrlSize.width+this.getCtrlSpace(),height:this.maxCtrlSize.height+
this.getCtrlSpace(!0)}};b.prototype.getMinSize=function(){return{width:this.minCtrlSize.width+this.getCtrlSpace(),height:this.minCtrlSize.height+this.getCtrlSpace(!0)}};b.prototype.updateLayout=function(){var a=this,b=setTimeout(function(){a.clientRect={width:a.size.width,height:a.size.height};var c=a.headerButtonElem?{width:a.headerButtonElem.nativeElement.offsetHeight,height:a.headerButtonElem.nativeElement.offsetHeight}:{width:0,height:0};a.headerBlockSize={width:a.headerBlockElem?a.headerBlockElem.nativeElement.offsetWidth:
0,height:a.headerBlockElem?a.headerBlockElem.nativeElement.offsetHeight:0};var d=a.commonService.getPadding(a.headerElem.nativeElement),f=a.commonService.getBorderWidth(a.headerElem.nativeElement);a.headerHeight=Math.max(c.height,a.headerBlockSize.height);a.headerOffsetHeight=a.headerHeight+d.top+d.bottom+2;switch(a.currentPlacement){case integralui_core_1.IntegralUIPlacement.Top:a.barSize={width:a.clientRect.width,height:c.height+d.top+d.bottom+f.top+f.bottom};a.currentSize={width:a.clientRect.width,
height:a.barSize.height};a.minCtrlSize={width:a.barSize.width,height:a.barSize.height};break;case integralui_core_1.IntegralUIPlacement.Right:a.barSize={width:c.width+d.left+d.right,height:a.clientRect.height};a.currentSize={width:a.barSize.width,height:a.clientRect.height-a.headerOffsetHeight};a.minCtrlSize={width:a.barSize.width,height:a.barSize.height};break;case integralui_core_1.IntegralUIPlacement.Bottom:a.barSize={width:a.clientRect.width,height:c.height+d.top+d.bottom+f.top+f.bottom};a.currentSize=
{width:a.clientRect.width,height:a.barSize.height};a.minCtrlSize={width:a.barSize.width,height:a.barSize.height};break;default:a.barSize={width:c.width+d.left+d.right,height:a.clientRect.height},a.currentSize={width:a.barSize.width,height:a.clientRect.height-a.headerOffsetHeight},a.minCtrlSize={width:a.barSize.width,height:a.barSize.height}}a.maxCtrlSize={width:a.size.width,height:a.size.height};a.currentHeaderBlockPos=d.left+d.right;clearTimeout(b)},1)};b.prototype.getAnimationFactor=function(a,
b){switch(this.animationSpeed){case integralui_core_1.IntegralUISpeedMode.VerySlow:var c=b?a/4:a/2;break;case integralui_core_1.IntegralUISpeedMode.Slow:c=b?a/8:a/4;break;case integralui_core_1.IntegralUISpeedMode.Fast:c=b?a/20:a/15;break;case integralui_core_1.IntegralUISpeedMode.VeryFast:c=b?a/30:a/25;break;default:c=b?a/15:a/10}return c};b.prototype.close=function(){this.expandValue=!1;this.popup?this.closePopup():this.closeNormal()};b.prototype.closeNormal=function(){this.removeCloseTimer();this.removeOpenTimer();
switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:this.closeFromTop();break;default:this.closeFromLeft()}};b.prototype.closeFromLeft=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.maxCtrlSize.width,!0),e=a.size.width/b;a.barOpacity=0;a.closeTimer=setInterval(function(){a.currentSize.width>a.minCtrlSize.width?(a.currentSize.width-=e,a.barOpacity=a.currentSize.width/a.maxCtrlSize.width):(a.currentSize.width=a.minCtrlSize.width,a.barOpacity=1,a.removeCloseTimer())},
5)}else a.currentSize.width=a.minCtrlSize.width,a.barOpacity=1};b.prototype.closeFromTop=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.maxCtrlSize.height,!0),e=a.size.height/b;a.barOpacity=0;a.closeTimer=setInterval(function(){a.currentSize.height>a.minCtrlSize.height?(a.currentSize.height-=e,a.barOpacity=a.currentSize.height/a.maxCtrlSize.height):(a.currentSize.height=a.minCtrlSize.height,a.barOpacity=1,a.removeCloseTimer())},5)}else a.currentSize.height=a.minCtrlSize.height,
a.barOpacity=1};b.prototype.closePopup=function(){this.removeCloseTimer();this.removeOpenTimer();switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:this.closePopupFromTop();break;case integralui_core_1.IntegralUIPlacement.Right:this.closePopupFromRight();break;case integralui_core_1.IntegralUIPlacement.Bottom:this.closePopupFromBottom();break;default:this.closePopupFromLeft()}};b.prototype.closePopupFromBottom=function(){var a=this,b=a.popupCmp.position.y;if(a.allowAnimation){var e=
a.getAnimationFactor(a.popupCmp.maxSize.height,!0),d=a.popupCmp.maxSize.height/e;a.closeTimer=setInterval(function(){0<a.popupCmp.size.height?(a.popupCmp.position={x:a.popupCmp.position.x,y:a.popupCmp.position.y+d},a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.size.height-d}):(a.popupCmp.position={x:a.popupCmp.position.x,y:b},a.popupCmp.size={width:a.popupCmp.size.width,height:0},a.popupCmp.display="none",a.isPopupVisible=!1,a.removeCloseTimer())},5)}else a.popupCmp.position={x:a.popupCmp.position.x,
y:b},a.popupCmp.size={width:a.popupCmp.size.width,height:0},a.popupCmp.display="none",a.isPopupVisible=!1};b.prototype.closePopupFromLeft=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.popupCmp.maxSize.width,!0),e=a.popupCmp.maxSize.width/b;a.closeTimer=setInterval(function(){0<a.popupCmp.size.width?a.popupCmp.size={width:a.popupCmp.size.width-e,height:a.popupCmp.size.height}:(a.popupCmp.size={width:0,height:a.popupCmp.size.height},a.popupCmp.display="none",a.isPopupVisible=
!1,a.removeCloseTimer())},5)}else a.popupCmp.size={width:0,height:a.popupCmp.size.height},a.popupCmp.display="none",a.isPopupVisible=!1};b.prototype.closePopupFromTop=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.popupCmp.maxSize.height,!0),e=a.popupCmp.maxSize.height/b;a.closeTimer=setInterval(function(){0<a.popupCmp.size.height?a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.size.height-e}:(a.popupCmp.size={width:a.popupCmp.size.width,height:0},a.popupCmp.display=
"none",a.isPopupVisible=!1,a.removeCloseTimer())},5)}else a.popupCmp.size={width:a.popupCmp.size.width,height:0},a.popupCmp.display="none",a.isPopupVisible=!1};b.prototype.closePopupFromRight=function(){var a=this,b=a.popupCmp.position.x;if(a.allowAnimation){var e=a.getAnimationFactor(a.popupCmp.maxSize.width,!0),d=a.popupCmp.maxSize.width/e;a.closeTimer=setInterval(function(){0<a.popupCmp.size.width?(a.popupCmp.position={x:a.popupCmp.position.x+d,y:a.popupCmp.position.y},a.popupCmp.size={width:a.popupCmp.size.width-
d,height:a.popupCmp.size.height}):(a.popupCmp.position={x:b,y:a.popupCmp.position.y},a.popupCmp.size={width:0,height:a.popupCmp.size.height},a.popupCmp.display="none",a.isPopupVisible=!1,a.removeCloseTimer())},5)}else a.popupCmp.position={x:b,y:a.popupCmp.position.y},a.popupCmp.size={width:0,height:a.popupCmp.size.height},a.popupCmp.display="none",a.isPopupVisible=!1};b.prototype.open=function(){this.expandValue=!0;this.popup?this.openPopup():this.openNormal()};b.prototype.openNormal=function(){this.removeCloseTimer();
this.removeOpenTimer();switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:this.openFromTop();break;case integralui_core_1.IntegralUIPlacement.Left:this.openFromLeft()}};b.prototype.openFromLeft=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.maxCtrlSize.width),e=a.size.width/b;a.barOpacity=1;a.openTimer=setInterval(function(){a.currentSize.width<a.maxCtrlSize.width?(a.currentSize.width+=e,a.barOpacity=1-a.currentSize.width/a.maxCtrlSize.width):(a.currentSize.width=
a.maxCtrlSize.width,a.barOpacity=0,a.removeOpenTimer())},5)}else a.currentSize.width=a.maxCtrlSize.width,a.barOpacity=0};b.prototype.openFromTop=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.maxCtrlSize.height),e=a.size.height/b;a.barOpacity=1;a.openTimer=setInterval(function(){a.currentSize.height<a.maxCtrlSize.height?(a.currentSize.height+=e,a.barOpacity=1-a.currentSize.height/a.maxCtrlSize.height):(a.currentSize.height=a.maxCtrlSize.height,a.barOpacity=0,a.removeOpenTimer())},
5)}else a.currentSize.height=a.maxCtrlSize.height,a.barOpacity=0};b.prototype.openPopup=function(){this.removeCloseTimer();this.removeOpenTimer();switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:this.openPopupFromTop();break;case integralui_core_1.IntegralUIPlacement.Right:this.openPopupFromRight();break;case integralui_core_1.IntegralUIPlacement.Bottom:this.openPopupFromBottom();break;default:this.openPopupFromLeft()}};b.prototype.openPopupFromBottom=function(){var a=this,b=
a.popupCmp.position.y;if(a.allowAnimation){var e=a.getAnimationFactor(a.popupCmp.maxSize.height),d=a.popupCmp.maxSize.height/e;a.openTimer=setInterval(function(){a.popupCmp.size.height<a.popupCmp.maxSize.height?(a.popupCmp.position={x:a.popupCmp.position.x,y:a.popupCmp.position.y-d},a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.size.height+d}):(a.popupCmp.position={x:a.popupCmp.position.x,y:b-a.popupCmp.maxSize.height},a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.maxSize.height},
a.removeOpenTimer())},5)}else a.popupCmp.position={x:a.popupCmp.position.x,y:b-a.popupCmp.maxSize.height},a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.maxSize.height}};b.prototype.openPopupFromLeft=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.popupCmp.maxSize.width),e=a.popupCmp.maxSize.width/b;a.openTimer=setInterval(function(){a.popupCmp.size.width<a.popupCmp.maxSize.width?a.popupCmp.size={width:a.popupCmp.size.width+e,height:a.popupCmp.size.height}:
(a.popupCmp.size={width:a.popupCmp.maxSize.width,height:a.popupCmp.size.height},a.removeOpenTimer())},5)}else a.popupCmp.size={width:a.popupCmp.maxSize.width,height:a.popupCmp.size.height}};b.prototype.openPopupFromTop=function(){var a=this;if(a.allowAnimation){var b=a.getAnimationFactor(a.popupCmp.maxSize.height),e=a.popupCmp.maxSize.height/b;a.openTimer=setInterval(function(){a.popupCmp.size.height<a.popupCmp.maxSize.height?a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.size.height+
e}:(a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.maxSize.height},a.removeOpenTimer())},5)}else a.popupCmp.size={width:a.popupCmp.size.width,height:a.popupCmp.maxSize.height}};b.prototype.openPopupFromRight=function(){var a=this,b=a.popupCmp.position.x;if(a.allowAnimation){var e=a.getAnimationFactor(a.popupCmp.maxSize.width),d=a.popupCmp.maxSize.width/e;a.openTimer=setInterval(function(){a.popupCmp.size.width<a.popupCmp.maxSize.width?(a.popupCmp.position={x:a.popupCmp.position.x-
d,y:a.popupCmp.position.y},a.popupCmp.size={width:a.popupCmp.size.width+d,height:a.popupCmp.size.height}):(a.popupCmp.position={x:b-a.popupCmp.maxSize.width,y:a.popupCmp.position.y},a.popupCmp.size={width:a.popupCmp.maxSize.width,height:a.popupCmp.size.height},a.removeOpenTimer())},5)}else a.popupCmp.position={x:b-a.popupCmp.maxSize.width,y:a.popupCmp.position.y},a.popupCmp.size={width:a.popupCmp.maxSize.width,height:a.popupCmp.size.height}};b.prototype.toggle=function(){this.expanded?this.open():
this.close()};b.prototype.getControlStyle=function(){var a={};switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:0<this.ctrlSize.width&&(a.width=this.ctrlSize.width+"px");a.height=this.currentSize.height+"px";break;case integralui_core_1.IntegralUIPlacement.Bottom:0<this.ctrlSize.width&&(a.width=this.ctrlSize.width+"px");a.height=this.currentSize.height+"px";break;default:a.width=this.currentSize.width+"px",0<this.ctrlSize.height&&(a.height=this.ctrlSize.height+"px")}return a};
b.prototype.getContentStyle=function(){var a={};switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:a.marginTop=this.currentSize.height-this.maxCtrlSize.height+"px";a.height=this.clientRect.height-this.headerOffsetHeight+"px";break;case integralui_core_1.IntegralUIPlacement.Left:a.marginLeft=this.currentSize.width-this.maxCtrlSize.width+"px",a.height=this.clientRect.height-this.headerOffsetHeight+"px"}return a};b.prototype.getHeaderStyle=function(){var a={};switch(this.placement){case integralui_core_1.IntegralUIPlacement.Top:a.borderTop=
0;a.borderRight=0;a.borderLeft=0;this.expanded||(a.borderBottom=0);break;case integralui_core_1.IntegralUIPlacement.Left:a.borderTop=0,a.borderRight=0,a.borderLeft=0}return a};b.\u0275fac=function(a){return new (a||b)(i0.\u0275\u0275directiveInject(i0.ElementRef),i0.\u0275\u0275directiveInject(i1.IntegralUICommonService),i0.\u0275\u0275directiveInject(i0.ComponentFactoryResolver),i0.\u0275\u0275directiveInject(i3.IntegralUIBaseService))};b.\u0275cmp=i0.\u0275\u0275defineComponent({type:b,selectors:[["iui-sidebar"]],
contentQueries:function(a,b,e){a&1&&i0.\u0275\u0275contentQuery(e,integralui_core_1.IntegralUITemplate,!0);if(a&2){var c;i0.\u0275\u0275queryRefresh(c=i0.\u0275\u0275loadQuery())&&(b.templates=c)}},viewQuery:function(a,b){a&1&&(i0.\u0275\u0275viewQuery(_c1,!0,core_1.ViewContainerRef),i0.\u0275\u0275viewQuery(_c1,!0,core_1.ElementRef),i0.\u0275\u0275viewQuery(_c2,!0,core_1.ElementRef),i0.\u0275\u0275viewQuery(_c3,!0,core_1.ElementRef),i0.\u0275\u0275viewQuery(_c4,!0,core_1.ElementRef));if(a&2){var c;
i0.\u0275\u0275queryRefresh(c=i0.\u0275\u0275loadQuery())&&(b.headerRef=c.first);i0.\u0275\u0275queryRefresh(c=i0.\u0275\u0275loadQuery())&&(b.headerElem=c.first);i0.\u0275\u0275queryRefresh(c=i0.\u0275\u0275loadQuery())&&(b.headerButtonElem=c.first);i0.\u0275\u0275queryRefresh(c=i0.\u0275\u0275loadQuery())&&(b.headerBlockElem=c.first);i0.\u0275\u0275queryRefresh(c=i0.\u0275\u0275loadQuery())&&(b.contentElem=c.first)}},inputs:{controlStyle:"controlStyle",data:"data",enabled:"enabled",name:"name",
size:"size",state:"state",animationSpeed:"animationSpeed",appRef:"appRef",expanded:"expanded",placement:"placement",popup:"popup",title:"title"},features:[i0.\u0275\u0275ProvidersFeature([integralui_core_1.IntegralUIBaseService,integralui_data_service_1.IntegralUIDataService]),i0.\u0275\u0275InheritDefinitionFeature],decls:9,vars:6,consts:[[3,"ngClass","ngStyle"],["class","iui-sidebar-line",3,"ngStyle",4,"ngIf"],[1,"iui-sidebar-header",3,"ngStyle"],["header",""],[1,"iui-sidebar-header-button",3,"mousedown",
"touchstart"],["headerButton",""],["class","iui-sidebar-header-block",3,"ngStyle",4,"ngIf"],["class","iui-sidebar-content",3,"ngStyle",4,"ngIf"],[1,"iui-sidebar-line",3,"ngStyle"],[1,"iui-sidebar-header-block",3,"ngStyle"],["headerBlock",""],["class","iui-sidebar-header-title",4,"ngIf"],[1,"iui-sidebar-header-content"],[3,"iuiTemplateOutlet","iuiTemplateOutletContext"],[1,"iui-sidebar-header-title"],[1,"iui-sidebar-content",3,"ngStyle"],["content",""]],template:function(a,b){a&1&&(i0.\u0275\u0275elementStart(0,
"div",0),i0.\u0275\u0275template(1,IntegralUISideBar_div_1_Template,1,6,"div",1),i0.\u0275\u0275elementStart(2,"div",2,3),i0.\u0275\u0275elementStart(4,"div",4,5),i0.\u0275\u0275listener("mousedown",function(a){return b.headerMouseDown(a)})("touchstart",function(a){return b.headerTouchStart(a)}),i0.\u0275\u0275element(6,"span"),i0.\u0275\u0275elementEnd(),i0.\u0275\u0275template(7,IntegralUISideBar_div_7_Template,5,9,"div",6),i0.\u0275\u0275elementEnd(),i0.\u0275\u0275template(8,IntegralUISideBar_div_8_Template,
3,5,"div",7),i0.\u0275\u0275elementEnd());a&2&&(i0.\u0275\u0275property("ngClass",b.getControlClass())("ngStyle",b.getControlStyle()),i0.\u0275\u0275advance(1),i0.\u0275\u0275property("ngIf",1==b.placement%2),i0.\u0275\u0275advance(1),i0.\u0275\u0275property("ngStyle",b.getHeaderStyle()),i0.\u0275\u0275advance(5),i0.\u0275\u0275property("ngIf",!b.popup||0==b.placement%2),i0.\u0275\u0275advance(1),i0.\u0275\u0275property("ngIf",!b.popup&&(0==b.placement||3==b.placement)))},directives:[i2.NgClass,i2.NgStyle,
i2.NgIf,i3.IntegralUITemplateOutlet],encapsulation:2});return b}(integralui_core_1.IntegralUIBaseComponent);exports.IntegralUISideBar=IntegralUISideBar;
(function(){i0.\u0275setClassMetadata(IntegralUISideBar,[{type:core_1.Component,args:[{selector:"iui-sidebar",template:'\n\t\t<div [ngClass]="getControlClass()" [ngStyle]="getControlStyle()">\n            <div *ngIf="placement % 2 == 1" class="iui-sidebar-line" [ngStyle]="{ top: headerOffsetHeight + \'px\', width: minCtrlSize.width + \'px\', height: maxCtrlSize.height + \'px\', opacity: barOpacity }"></div>\n            <div class="iui-sidebar-header" [ngStyle]="getHeaderStyle()" #header>\n                <div class="iui-sidebar-header-button" (mousedown)="headerMouseDown($event)" (touchstart)="headerTouchStart($event)" #headerButton><span></span></div>\n                <div *ngIf="!popup || placement % 2 == 0" class="iui-sidebar-header-block" [ngStyle]="{ marginLeft: currentHeaderBlockPos + \'px\', width: maxCtrlSize.width - minCtrlSize.width - currentHeaderBlockPos + \'px\'}" #headerBlock>\n                    <div *ngIf="headerData[0].length == 0 && title && title != \'\'" class="iui-sidebar-header-title">{{title}}</div>\n                    <div class="iui-sidebar-header-content">\n                        <span [iuiTemplateOutlet]="headerData[0]" [iuiTemplateOutletContext]="{$implicit: (data)}"></span>\n                    </div>\n                </div>\n            </div>\n            <div *ngIf="!popup && (placement == 0 || placement == 3)" class="iui-sidebar-content" [ngStyle]="getContentStyle()" #content>\n                <span [iuiTemplateOutlet]="contentData[0]" [iuiTemplateOutletContext]="{$implicit: (data)}"></span>\n            </div>\n\t\t</div>\n\t',inputs:"controlStyle data enabled name size state".split(" "),
providers:[integralui_core_1.IntegralUIBaseService,integralui_data_service_1.IntegralUIDataService],encapsulation:core_1.ViewEncapsulation.None}]}],function(){return[{type:i0.ElementRef},{type:i1.IntegralUICommonService},{type:i0.ComponentFactoryResolver},{type:i3.IntegralUIBaseService}]},{templates:[{type:core_1.ContentChildren,args:[integralui_core_1.IntegralUITemplate,{descendants:!0}]}],headerRef:[{type:core_1.ViewChild,args:["header",{read:core_1.ViewContainerRef,"static":!1}]}],headerElem:[{type:core_1.ViewChild,
args:["header",{read:core_1.ElementRef,"static":!1}]}],headerButtonElem:[{type:core_1.ViewChild,args:["headerButton",{read:core_1.ElementRef,"static":!1}]}],headerBlockElem:[{type:core_1.ViewChild,args:["headerBlock",{read:core_1.ElementRef,"static":!1}]}],contentElem:[{type:core_1.ViewChild,args:["content",{read:core_1.ElementRef,"static":!1}]}],animationSpeed:[{type:core_1.Input}],appRef:[{type:core_1.Input}],expanded:[{type:core_1.Input}],placement:[{type:core_1.Input}],popup:[{type:core_1.Input}],
title:[{type:core_1.Input}]})})();