/*
  filename: integralui.base.grid.js
  version : 1.2.0
  Copyright © 2016-2017 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(k,b){function a(){this.constructor=k}for(var d in b)b.hasOwnProperty(d)&&(k[d]=b[d]);k.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)},__decorate=this&&this.__decorate||function(k,b,a,d){var e=arguments.length,c=3>e?b:null===d?d=Object.getOwnPropertyDescriptor(b,a):d,g;if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)c=Reflect.decorate(k,b,a,d);else for(var f=k.length-1;0<=f;f--)if(g=k[f])c=(3>e?g(c):3<e?g(b,a,c):
g(b,a))||c;return 3<e&&c&&Object.defineProperty(b,a,c),c},__metadata=this&&this.__metadata||function(k,b){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(k,b)},core_1=require("@angular/core"),integralui_core_1=require("./integralui.core"),integralui_common_service_1=require("../services/integralui.common.service"),integralui_data_service_1=require("../services/integralui.data.service"),integralui_dragdrop_service_1=require("../services/integralui.dragdrop.service"),
integralui_filter_service_1=require("../services/integralui.filter.service"),IntegralUIGridLines;(function(k){k[k.None=0]="None";k[k.Horizontal=1]="Horizontal";k[k.Vertical=2]="Vertical";k[k.Both=3]="Both"})(IntegralUIGridLines=exports.IntegralUIGridLines||(exports.IntegralUIGridLines={}));
var IntegralUIBaseGrid=function(k){function b(a,d,e,b,g,f,h){var c=k.call(this,g)||this;c.dataService=a;c.dragDropService=d;c.elemRef=e;c.elemRenderer=b;c.commonService=g;c.filterService=f;c.cmpResolver=h;c.currentColumnList=[];c.currentRowList=[];c.dataColumns=[];c.dataRows=[];c.options={};c.scrollColumnList=[];c.scrollRowList=[];c.columnDataKey="columns";c.rowDataKey="rows";c.dropMarkElem=null;c.dragCmpRef=null;c.dragCmp=null;c.cloneElem=null;c.cloneElemStartPos={x:0,y:0};c.hoverColumn=null;c.hoverRow=
null;c.currentIndex=0;c.prevIndex=0;c.currentFocusCell=null;c.isKeyboardActive=!1;c.allowUpdate=!0;c.avgRowHeight=0;c.headerHeight=0;c.footerHeight=0;c.viewIndexRange={left:0,middle:999,right:999};c.visibleRange=1;c.isHeaderVisible=!0;c.isFooterVisible=!0;c.scrollSize={width:0,height:0};c.clientRect={width:0,height:0};c.contentLeftPos=0;c.allColWidth=0;c.isColumnResizing=!1;c.currentScrollPos={x:0,y:0};c.maxScrollPos={x:0,y:0};c.accelerator=.5;c.scrollTimerID=null;c.isScrollTimerActive=!1;c.scrollCount=
0;c.isScrollActive=!1;c.prevScrollPos={x:0,y:0};c.scrollBarSize={width:0,height:0};c.scrollLargeChange={x:0,y:0};c.currentSelectedColumn=null;c.currentSelectedRow=null;c.currentSelectionMode=integralui_core_1.IntegralUISelectionMode.One;c.shiftFirstSelectedRow=null;c.removeIndex=-1;c.currentSelectedRows=[];c.gridLines=IntegralUIGridLines.Both;c.rowHeight=0;c.afterSelect=new core_1.EventEmitter;c.beforeEdit=new core_1.EventEmitter;c.beforeSelect=new core_1.EventEmitter;c.change=new core_1.EventEmitter;
c.columnAdding=new core_1.EventEmitter;c.columnAdded=new core_1.EventEmitter;c.columnClick=new core_1.EventEmitter;c.columnRemoving=new core_1.EventEmitter;c.columnRemoved=new core_1.EventEmitter;c.columnsCleared=new core_1.EventEmitter;c.columnSizeChanged=new core_1.EventEmitter;c.dragDrop=new core_1.EventEmitter;c.dragOver=new core_1.EventEmitter;c.keyDown=new core_1.EventEmitter;c.keyPress=new core_1.EventEmitter;c.keyUp=new core_1.EventEmitter;c.rowAdding=new core_1.EventEmitter;c.rowAdded=new core_1.EventEmitter;
c.rowClick=new core_1.EventEmitter;c.rowDblClick=new core_1.EventEmitter;c.rowRemoving=new core_1.EventEmitter;c.rowRemoved=new core_1.EventEmitter;c.rowsCleared=new core_1.EventEmitter;c.loadComplete=new core_1.EventEmitter;c.scrollPosChanged=new core_1.EventEmitter;c.selectionChanged=new core_1.EventEmitter;c.updateComplete=new core_1.EventEmitter;c.sortColumn=null;c.sortComparer=null;c.updateOptions();return c}__extends(b,k);Object.defineProperty(b.prototype,"allowDrag",{set:function(a){this.options.allowDrag=
a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"allowDrop",{set:function(a){this.options.allowDrop=a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"allowFilter",{set:function(a){this.options.allowFilter=a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"allowFocus",{set:function(a){this.options.allowFocus=a;a||(this.currentFocusCell=null);this.refresh()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"columns",{get:function(){return this.dataColumns},
set:function(a){this.dataColumns=a;this.updateData()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"dataFields",{set:function(a){this.updateDataFields(a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"focusedCell",{get:function(){return this.currentFocusCell},set:function(a){this.currentFocusCell!=a&&(this.currentFocusCell=a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"paging",{set:function(a){this.updatePaging(a)},enumerable:!0,configurable:!0});
Object.defineProperty(b.prototype,"rows",{get:function(){return this.dataRows},set:function(a){this.dataRows=a;this.updateData()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectedColumn",{get:function(){return this.currentSelectedColumn},set:function(a){this.currentSelectedColumn!=a&&this.processColumnSelection(null,a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectedRow",{get:function(){return this.currentSelectedRow},set:function(a){this.currentSelectedRow!=
a&&this.processRowSelection(null,a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectionMode",{get:function(){return this.currentSelectionMode},set:function(a){this.currentSelectionMode!=a&&(this.currentSelectionMode=a,this.clearPrevSelection(this.currentSelectionMode!=integralui_core_1.IntegralUISelectionMode.None?this.currentSelectedRow:null),this.refresh(),this.currentSelectionMode==integralui_core_1.IntegralUISelectionMode.None&&(this.currentSelectedRow=null,this.selectionChanged.emit(null)))},
enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"sorting",{set:function(a){this.options.sorting=a},enumerable:!0,configurable:!0});b.prototype.ngOnInit=function(){this.dataService.init([{data:this.columns,fields:this.options.columnFields,key:this.columnDataKey},{data:this.rows,fields:this.options.rowFields,key:this.rowDataKey}])};b.prototype.addColumn=function(a){this.callEventAddColumn("add",a)};b.prototype.clearColumns=function(){this.dataService.clear(null,this.columnDataKey);
this.columnsCleared.emit(null);this.currentScrollPos.x=0};b.prototype.insertColumnAt=function(a,d){this.callEventAddColumn("at",a,d)};b.prototype.insertColumnBefore=function(a,d){this.callEventAddColumn("ref",a,-1,d)};b.prototype.insertColumnAfter=function(a,d){this.callEventAddColumn("ref",a,-1,d,!0)};b.prototype.removeColumn=function(a){return this.callEventRemoveColumn(a)};b.prototype.removeColumnAt=function(a){return this.callEventRemoveColumn(null,a)};b.prototype.callEventAddColumn=function(a,
d,e,c,b){var g={cancel:!1,column:d};this.columnAdding.emit(g);if(1!=g.cancel){switch(a){case "at":this.dataService.insert(d,e,null,null,!1,this.columnDataKey);break;case "ref":this.dataService.insertByRef(d,c,b,this.columnDataKey);break;default:this.dataService.insert(d,-1,null,null,!1,this.columnDataKey)}this.columnAdded.emit({column:d})}};b.prototype.callEventRemoveColumn=function(a,d){var e={cancel:!1,column:a};this.columnRemoving.emit(e);return 1!=e.cancel&&(this.removeIndex=this.columns?this.columns.indexOf(a):
-1,e=this.dataService.removeAt(a,d,null,this.columnDataKey),e.result)?(this.columnRemoved.emit({column:e.obj}),!0):!1};b.prototype.addRow=function(a,d){this.callEventAddRow("add",a,-1,d)};b.prototype.clearRows=function(a){this.dataService.clear(a,this.rowDataKey);this.rowsCleared.emit({parent:a});this.clearSelection();this.currentScrollPos.y=0};b.prototype.insertRowAt=function(a,d,e){this.callEventAddRow("at",a,d,e)};b.prototype.insertRowBefore=function(a,d){this.callEventAddRow("ref",a,-1,null,d)};
b.prototype.insertRowAfter=function(a,d){this.callEventAddRow("ref",a,-1,null,d,!0)};b.prototype.removeRow=function(a){return this.callEventRemoveRow(a)};b.prototype.removeRowAt=function(a,d){return this.callEventRemoveRow(null,a,d)};b.prototype.callEventAddRow=function(a,d,e,c,b,f){var g={cancel:!1,row:d};this.rowAdding.emit(g);if(1!=g.cancel){switch(a){case "at":this.dataService.insert(d,e,c,null,!1,this.rowDataKey);break;case "ref":this.dataService.insertByRef(d,b,f,this.rowDataKey);break;default:this.dataService.insert(d,
-1,c,null,!1,this.rowDataKey)}this.rowAdded.emit({row:d})}};b.prototype.callEventRemoveRow=function(a,d,e){var c={cancel:!1,row:a};this.rowRemoving.emit(c);return 1!=c.cancel&&(this.removeIndex=this.rows?this.rows.indexOf(a):-1,a=this.dataService.removeAt(a,d,e,this.rowDataKey),a.result)?(this.rowRemoved.emit({row:a.obj}),!0):!1};b.prototype.updateData=function(){};b.prototype.updateDataFields=function(a){a?(this.updateColumnFields(a.column),this.updateRowFields(a.row),this.updateCellFields(a.cell)):
(this.updateColumnFields(),this.updateRowFields(),this.updateCellFields())};b.prototype.updateOptions=function(a){a?(this.options={allowAnimation:this.commonService.isFieldAvailable(a.allowAnimation,!0),allowCellFocus:this.commonService.isFieldAvailable(a.allowCellFocus,!0),allowColumnReorder:this.commonService.isFieldAvailable(a.allowColumnReorder,!1),allowDrag:this.commonService.isFieldAvailable(a.allowDrag,!1),allowDrop:this.commonService.isFieldAvailable(a.allowDrop,!0),allowFilter:this.commonService.isFieldAvailable(a.allowFilter,
!1),allowFocus:this.commonService.isFieldAvailable(a.allowFocus,!1),animationSpeed:200,autoExpand:this.commonService.isFieldAvailable(a.autoExpand,!0),displayMode:this.commonService.isFieldAvailable(a.displayMode,"normal"),editorSettings:{activate:"click"},enabled:this.commonService.isFieldAvailable(a.enabled,!0),expandColIndex:this.commonService.isFieldAvailable(a.expandColIndex,void 0!=this.options.expandColIndex?this.options.expandColIndex:0),fillSpace:this.commonService.isFieldAvailable(a.fillSpace,
!1),gridLines:this.commonService.isFieldAvailable(a.gridLines,"both"),hoverSelection:this.commonService.isFieldAvailable(a.hoverSelection,!1),indent:this.commonService.isFieldAvailable(a.indent,15),labelEdit:this.commonService.isFieldAvailable(a.labelEdit,!1),loadRows:[],mouseWheelSpeed:this.commonService.isFieldAvailable(a.mouseWheelSpeed,"normal"),pathSeparator:this.commonService.isFieldAvailable(a.pathSeparator,"\\"),rowHeight:this.commonService.isFieldAvailable(a.rowHeight,-1),rtl:this.commonService.isFieldAvailable(a.rtl,
!1),selectedColumn:this.commonService.isFieldAvailable(a.selectedColumn,this.currentSelectedColumn?this.currentSelectedColumn:null),selectedIndex:-1,selectedRow:this.commonService.isFieldAvailable(a.selectedRow,this.currentSelectedRow?this.currentSelectedRow:null),selectedRows:[],selectionMode:this.commonService.isFieldAvailable(a.selectionMode,integralui_core_1.IntegralUISelectionMode.One),showFooter:this.commonService.isFieldAvailable(a.showFooter,!0),showHeader:this.commonService.isFieldAvailable(a.showHeader,
!0),showIcons:this.commonService.isFieldAvailable(a.showIcons,!0),sorting:this.commonService.isFieldAvailable(a.sorting,integralui_core_1.IntegralUISortOrder.None)},this.updatePaging(a.paging),this.updateDataFields(a.dataFields)):(this.options={allowAnimation:!0,allowCellFocus:!0,allowColumnReorder:!1,allowDrag:!1,allowDrop:!0,allowFilter:!1,allowFocus:!1,animationSpeed:200,autoExpand:!0,displayMode:"normal",editorSettings:{activate:"click"},enabled:!0,expandColIndex:0,fillSpace:!1,gridLines:"both",
hoverSelection:!1,indent:15,labelEdit:!1,loadRows:[],mouseWheelSpeed:"normal",pathSeparator:"\\",rowHeight:-1,rtl:!1,selectedColumn:null,selectedIndex:-1,selectedRow:null,selectedRows:[],selectionMode:integralui_core_1.IntegralUISelectionMode.One,showFooter:!0,showHeader:!0,showIcons:!0,sorting:integralui_core_1.IntegralUISortOrder.None},this.updatePaging(),this.updateDataFields())};b.prototype.updateColumnFields=function(a){this.options.columnFields=a?{allowDrag:a.allowDrag?a.allowDrag:"allowDrag",
allowDrop:a.allowDrop?a.allowDrop:"allowDrop",allowFilter:a.allowFilter?a.allowFilter:"allowFilter",allowGrouping:a.allowGrouping?a.allowGrouping:"allowGrouping",cellTemplateUrl:a.cellTemplateUrl?a.cellTemplateUrl:"cellTemplateUrl",comparer:a.comparer?a.comparer:"comparer",contentAlignment:a.contentAlignment?a.contentAlignment:"contentAlignment",contextMenu:a.contextMenu?a.contextMenu:"contextMenu",editorType:a.editorType?a.editorType:"editorType",editorSettings:a.editorSettings?a.editorSettings:
"editorSettings",editorTemplate:a.editorTemplate?a.editorTemplate:"editorTemplate",filterParams:a.filterParams?a.filterParams:"filterParams",filterTemplate:a.filterTemplate?a.filterTemplate:"filterTemplate",fixed:a.fixed?a.fixed:"fixed",fixedWidth:a.fixedWidth?a.fixedWidth:"fixedWidth",footerAlignment:a.footerAlignment?a.footerAlignment:"footerAlignment",footerContent:a.footerContent?a.footerContent:"footerContent",footerTemplate:a.footerTemplate?a.footerTemplate:"footerTemplate",footerTemplateModel:a.footerTemplateModel?
a.footerTemplateModel:"footerTemplateModel",footerText:a.footerText?a.footerText:"footerText",footerTooltip:a.footerTooltip?a.footerTooltip:"footerTooltip",groupText:a.groupText?a.groupText:"groupText",headerAlignment:a.headerAlignment?a.headerAlignment:"headerAlignment",headerContent:a.headerContent?a.headerContent:"headerContent",headerTemplate:a.headerTemplate?a.headerTemplate:"headerTemplate",headerTemplateModel:a.headerTemplateModel?a.headerTemplateModel:"headerTemplateModel",headerText:a.headerText?
a.headerText:"headerText",headerTooltip:a.headerTooltip?a.headerTooltip:"headerTooltip",icon:a.icon?a.icon:"icon",id:a.id?a.id:"id",minWidth:a.minWidth?a.minWidth:"minWidth",maxWidth:a.maxWidth?a.maxWidth:"maxWidth",selected:a.selected?a.selected:"selected",style:a.style?a.style:"style",templateSettings:a.templateSettings?a.templateSettings:"templateSettings",visible:a.visible?a.visible:"visible",width:a.width?a.width:"width"}:{allowDrag:"allowDrag",allowDrop:"allowDrop",allowFilter:"allowFilter",
allowGrouping:"allowGrouping",cellTemplateUrl:"cellTemplateUrl",comparer:"comparer",contentAlignment:"contentAlignment",contextMenu:"contextMenu",editorType:"editorType",editorSettings:"editorSettings",editorTemplate:"editorTemplate",filterParams:"filterParams",filterTemplate:"filterTemplate",footerTemplateModel:"footerTemplateModel",fixed:"fixed",fixedWidth:"fixedWidth",footerAlignment:"footerAlignment",footerContent:"footerContent",footerTemplate:"footerTemplate",footerText:"footerText",footerTooltip:"footerTooltip",
groupText:"groupText",headerAlignment:"headerAlignment",headerContent:"headerContent",headerTemplate:"headerTemplate",headerTemplateModel:"headerTemplateModel",headerText:"headerText",headerTooltip:"headerTooltip",icon:"icon",id:"id",minWidth:"minWidth",maxWidth:"maxWidth",selected:"selected",style:"style",templateSettings:"templateSettings",visible:"visible",width:"width"};this.dataService&&this.dataService.updateDataFields(this.options.columnFields,this.columnDataKey)};b.prototype.updateRowFields=
function(a){this.options.rowFields=a?{allowDrag:a.allowDrag?a.allowDrag:"allowDrag",allowDrop:a.allowDrop?a.allowDrop:"allowDrop",allowEdit:a.allowEdit?a.allowEdit:"allowEdit",allowFocus:a.allowFocus?a.allowFocus:"allowFocus",autoCheck:a.autoCheck?a.autoCheck:"autoCheck",cells:a.cells?a.cells:"cells",checkBoxSettings:a.checkBoxSettings?a.checkBoxSettings:"checkBoxSettings",checked:a.checked?a.checked:"checked",checkState:a.checkState?a.checkState:"checkState",content:a.content?a.content:"content",
contextMenu:a.contextMenu?a.contextMenu:"contextMenu",enabled:a.enabled?a.enabled:"enabled",expanded:a.expanded?a.expanded:"expanded",hasChildren:a.hasChildren?a.hasChildren:"hasChildren",icon:a.icon?a.icon:"icon",id:a.id?a.id:"id",objects:a.rows?a.rows:"rows",pid:a.pid?a.pid:"pid",rows:a.rows?a.rows:"rows",selected:a.selected?a.selected:"selected",statusIcon:a.statusIcon?a.statusIcon:"statusIcon",style:a.style?a.style:"style",subobjects:a.cells?a.cells:"cells",templateObj:a.templateObj?a.templateObj:
"templateObj",text:a.text?a.text:"text",tooltip:a.tooltip?a.tooltip:"tooltip",value:a.value?a.value:"value",visible:a.visible?a.visible:"visible"}:{allowDrag:"allowDrag",allowDrop:"allowDrop",allowFocus:"allowFocus",cells:"cells",content:"content",contextMenu:"contextMenu",enabled:"enabled",expanded:"expanded",fixed:"fixed",hasChildren:"hasChildren",icon:"icon",id:"id",objects:"rows",pid:"pid",rows:"rows",selected:"selected",statusIcon:"statusIcon",style:"style",subobjects:"cells",text:"text",tooltip:"tooltip",
value:"value",visible:"visible"};this.dataService&&this.dataService.updateDataFields(this.options.rowFields,this.rowDataKey)};b.prototype.updateCellFields=function(a){this.options.cellFields=a?{allowEdit:a.allowEdit?a.allowEdit:"allowEdit",cid:a.cid?a.cid:"cid",content:a.content?a.content:"content",contextMenu:a.contextMenu?a.contextMenu:"contextMenu",enabled:a.enabled?a.enabled:"enabled",labelEdit:a.labelEdit?a.labelEdit:"labelEdit",rid:a.rid?a.rid:"rid",selected:a.selected?a.selected:"selected",
style:a.style?a.style:"style",templateObj:a.templateObj?a.templateObj:"templateObj",text:a.text?a.text:"text",tooltip:a.tooltip?a.tooltip:"tooltip",value:a.value?a.value:"value"}:{allowEdit:"allowEdit",cid:"cid",content:"content",contextMenu:"contextMenu",enabled:"enabled",labelEdit:"labelEdit",rid:"rid",selected:"selected",style:"style",templateObj:"templateObj",text:"text",tooltip:"tooltip",value:"value"}};b.prototype.processLoadData=function(a,d,e,c){var b=this;b.clearRows(d);b.updateRowFields(e);
var f=[];if(a)if(0!=c){var h=[];a.forEach(function(a,d){var c=a[b.options.rowFields.pid];h[c]?(h[c][b.options.rowFields.rows]||(h[c][b.options.rowFields.rows]=[]),h[a[b.options.rowFields.id]]=a,h[c][b.options.rowFields.rows].push(a)):(h[a[b.options.rowFields.id]]=a,f.push(a))});h.length=0}else f=a;if(d)for(d[b.options.rowFields.rows]=f,a=0;a<d[b.options.rowFields.rows].length;a++)d[b.options.rowFields.rows][a][b.options.rowFields.pid]=d[b.options.rowFields.id];else if(b.rows)for(a=b.rows.length=0;a<
f.length;a++)b.rows.push(f[a]);b.loadComplete.emit(null);this.updateLayout()};b.prototype.updateScrollColumnList=function(){};b.prototype.updateScrollRowList=function(){};b.prototype.addDropMark=function(a){this.appRef&&(this.removeDropMark(),a=this.cmpResolver.resolveComponentFactory(integralui_core_1.IntegralUIDragWindow))&&(this.dragCmpRef=this.appRef.createComponent(a),this.dragCmpRef._component?this.dragCmp=this.dragCmpRef._component:this.dragCmpRef._hostElement&&(this.dragCmp=this.dragCmpRef._hostElement.component))};
b.prototype.removeDropMark=function(){this.dragCmpRef&&this.dragCmpRef.destroy();this.dragCmp=null};b.prototype.callDragDropEvent=function(a,d,e){a={action:d.action,cancel:!1,dragRow:d.source,dropPos:d.dropPos,event:a,isDropAllowed:d.allow,mousePos:this.commonService.getMousePos(a),sourceCtrl:d.sourceCtrl,targetCtrl:d.targetCtrl,targetRow:d.target};e?this.dragDrop.emit(a):this.dragOver.emit(a);return a.cancel};b.prototype.checkEmptySpace=function(a){var d=this.getContentSize(),e=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild);
d=e.top+d.height;e=e.bottom;a=this.commonService.getMousePos(a);var c=this.commonService.getShiftPos();a.x-=c.x;a.y-=c.y;return a.y>=d&&a.y<=e};b.prototype.ctrlDragDrop=function(a){this.processDragDrop(a);a.stopPropagation()};b.prototype.ctrlDragLeave=function(a){this.dropMark(a);this.stopScrollTimer()};b.prototype.ctrlDragOver=function(a){this.processDragOver(a);a.stopPropagation()};b.prototype.dropMark=function(a,d){this.dragCmp||this.addDropMark({x:a.pageX,y:a.pageY});if(this.dragCmp){var e="none";
this.options.allowDrop&&(e=d?"block":"none");this.dragCmp.display=e}};b.prototype.updateDragComponent=function(a){this.dragCmp&&this.dragCmp.updatePos(a)};b.prototype.isDragAllowed=function(a){return this.options.allowDrag?a&&(a[this.options.rowFields.allowDrag]||void 0===a[this.options.rowFields.allowDrag])?!0:!1:!1};b.prototype.isDropAllowed=function(a,d,e){var c=this.options.allowDrop;if(c&&a&&d&&(c=d[this.options.rowFields.allowDrop]||void 0===d[this.options.rowFields.allowDrop]?!0:!1))if(Array.isArray(a))for(var b=
0;b<a.length;b++){if(this.commonService.isEqual(a[b][this.options.rowFields.id],d[this.options.rowFields.id])||0===e&&this.isParentOf(d,a[b])||this.isChildOf(d,a[b])){c=!1;break}if(!c)break}else if(this.commonService.isEqual(a[this.options.rowFields.id],d[this.options.rowFields.id])||0===e&&this.isParentOf(d,a)||this.isChildOf(d,a))c=!1;return c};b.prototype.processDragStart=function(a,d){this.dragDropService.clearData();if(!this.isDragAllowed(d))a.preventDefault();else if(d)if(this.isDragAllowed(d)){this.addDropMark({x:a.pageX,
y:a.pageY});a.dataTransfer?(a.dataTransfer.effectAllowed="move",a.dataTransfer.setData("text",d[this.options.rowFields.id]?d[this.options.rowFields.id].toString():"")):a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.effectAllowed="move",a.originalEvent.dataTransfer.setData("text",d[this.options.rowFields.id]?d[this.options.rowFields.id].toString():""));var e={clone:this.cloneRow(d),source:d,sourceCtrl:this,sourceData:this.rows};switch(this.selectionMode){case integralui_core_1.IntegralUISelectionMode.MultiSimple:e.clone=
this.createCloneList(this.currentSelectedRows);e.source=this.currentSelectedRows;break;case integralui_core_1.IntegralUISelectionMode.MultiExtended:e.clone=this.createCloneList(this.currentSelectedRows),e.source=this.currentSelectedRows}this.dragDropService.setData(e)}else a.dataTransfer?a.dataTransfer.effectAllowed="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.effectAllowed="none")};b.prototype.processDragOver=function(a,d,e,c){a.preventDefault();var b=!0;a.dataTransfer?
b="none"===a.dataTransfer.effectAllowed?!1:!0:a.originalEvent&&a.originalEvent.dataTransfer&&(b="none"===a.originalEvent.dataTransfer.effectAllowed?!1:!0);if(b){var f=this.dragDropService.getData();b=this.commonService.getShiftPos();if(d){var h=this.commonService.getMousePos(a);h.x-=b.x;h.y-=b.y;h=this.dragDropService.getDropPos(h,e,c);b=this.isDropAllowed(f.source,d,h);e={action:a.shiftKey?"copy":"move",source:f.source,dropPos:h,allow:b,sourceCtrl:f.sourceCtrl,target:d,targetCtrl:this};e=this.callDragDropEvent(a,
e);if(b&&1!=e){c=this.commonService.getMousePos(a);e=c.y+16;c=c.x+20;var l="iui-dragwin-icon";switch(h){case 0:l+=" iui-dragwin-move-in";break;case 1:l+=" iui-dragwin-move-up";break;case 2:l+=" iui-dragwin-move-down"}a.shiftKey&&(l+="-copy");this.updateDragComponent({"class":l,top:e,left:c,text:d[this.options.rowFields.text]});this.dropMark(a,b);this.dragDropService.setData({action:a.shiftKey?"copy":"move",source:f.source,sourceData:f.sourceData,target:d,targetCtrl:this,dropPos:h})}else a.dataTransfer?
a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a)}else this.options.allowDrop?(b=this.checkEmptySpace(a),e={action:a.shiftKey?"copy":"move",source:f.source,dropPos:-1,allow:b,sourceCtrl:f.sourceCtrl,target:null,targetCtrl:this},e=this.callDragDropEvent(a,e),b&&1!=e?(h=this.commonService.getMousePos(a),e=h.y+16,c=h.x+20,l="iui-dragwin-icon iui-dragwin-move-end",a.shiftKey&&(l+="-copy"),this.updateDragComponent({"class":l,
top:e,left:c,text:this.name?this.name:"Component"}),this.dropMark(a,b),this.dragDropService.setData({action:a.shiftKey?"copy":"move",source:f.source,sourceData:f.sourceData,target:null,targetCtrl:this,dropPos:-1})):(a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a))):(a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect=
"none"),this.dropMark(a))}};b.prototype.processDragDrop=function(a,d){a.preventDefault();this.dropMark(a);var b=!0;a.dataTransfer?b="none"===a.dataTransfer.effectAllowed?!1:!0:a.originalEvent&&a.originalEvent.dataTransfer&&(b="none"===a.originalEvent.dataTransfer.effectAllowed?!1:!0);if(b){var c=this.dragDropService.getData();(b=d?this.isDropAllowed(c.source,d,c.dropPos):this.checkEmptySpace(a))&&c.source&&(this.callDragDropEvent(a,{action:a.shiftKey?"copy":"move",source:c.source,dropPos:c.dropPos,
allow:b,sourceCtrl:c.sourceCtrl,target:c.target,targetCtrl:this},!0)||this.drop(a,c))}this.dragDropService.clearData()};b.prototype.drop=function(a,d){if(d&&d.sourceCtrl){var b=a.shiftKey&&d.clone?d.clone:d.source;if(Array.isArray(b)){for(var c=[],g=0;g<b.length;g++)c.push(b[g]);if(0<c.length){for(g=0;g<c.length;g++)this.processDataDrop(a,c[g],d);this.clearPrevSelection(c[c.length-1])}}else this.processDataDrop(a,b,d),this.clearPrevSelection(b);d.sourceCtrl!=d.targetCtrl&&d.sourceCtrl.updateLayout&&
d.sourceCtrl.updateLayout();this.updateLayout()}};b.prototype.processDataDrop=function(a,d,b){var c=a.shiftKey;!a.shiftKey&&b.sourceCtrl&&b.sourceCtrl.removeRow&&(c=b.sourceCtrl.removeRow(d));if(c)switch(b.dropPos){case 0:this.insertRowAt(d,-1,b.target);break;case 1:this.insertRowBefore(d,b.target);break;case 2:this.insertRowAfter(d,b.target);break;default:this.addRow(d)}};b.prototype.callAfterSelectEvent=function(a){this.afterSelect.emit({obj:a});this.selectionChanged.emit(null)};b.prototype.filter=
function(a,d){if(a)a[this.options.columnFields.filterParams]=d;else for(var b=0;b<this.currentColumnList.length;b++)this.currentColumnList[b].data[this.options.columnFields.filterParams]=null;this.updateLayout();this.change.emit({type:"filtering"})};b.prototype.cloneRow=function(a){return this.dataService.clone(a,this.rowDataKey)};b.prototype.createCloneList=function(a){for(var d=[],b=0;b<a.length;b++)d.push(this.cloneRow(a[b]));return d};b.prototype.getColumnById=function(a){for(var d=null,b=0;b<
this.currentColumnList.length;b++)if(this.currentColumnList[b].data[this.options.columnFields.id]==a){d=this.currentColumnList[b].data;break}return d};b.prototype.getColumnCurrentIndex=function(a){return a?this.getColumnIndexFromList(a):-1};b.prototype.getColumnIndexFromList=function(a){for(var d=-1,b=0;b<this.currentColumnList.length;b++)if(this.currentColumnList[b].data==a){d=b;break}return d};b.prototype.getFilterTree=function(a){for(var d=null,b=0;b<this.currentColumnList.length;b++)if(this.currentColumnList[b].data==
a){d=this.currentColumnList[b].filter;break}return d};b.prototype.getList=function(a,d){switch(a){case "selected":return this.currentSelectedRows}return this.dataService.getList(d,this.rowDataKey)};b.prototype.getObjFromRow=function(a){for(var d=null,b=0;b<this.currentRowList.length;b++)if(this.currentRowList[b].data==a){d=this.currentRowList[b];break}return d};b.prototype.getRowCurrentIndex=function(a){return a?(a=this.getObjFromRow(a))&&this.currentRowList?this.currentRowList.indexOf(a):-1:-1};
b.prototype.getRowFromComponent=function(a){return null};b.prototype.isChildOf=function(a,d){return!1};b.prototype.isColumnVisible=function(a){return a&&0!=a[this.options.columnFields.visible]?!0:!1};b.prototype.isComponentIndexInRange=function(a){return this.rowList?0<=a&&a<this.rowList.length:!1};b.prototype.isIndexInRange=function(a){return this.currentRowList?0<=a&&a<this.currentRowList.length:!1};b.prototype.isRowAllowed=function(a,d){if(0==a[this.options.rowFields.visible])return!1;if(0==this.options.allowFilter)return!0;
var b=!0;if(a)for(var c,g,f=0;f<a[this.options.rowFields.cells].length;f++){b=!0;g=a[this.options.rowFields.cells][f];c=g[this.options.cellFields.cid];c=this.getColumnById(c);!c&&f<this.currentColumnList.length&&(c=this.currentColumnList[f].data);if(c&&c[this.options.columnFields.filterParams]){var h=c[this.options.columnFields.filterParams],l=g[this.options.cellFields.value]?g[this.options.cellFields.value]:g[this.options.cellFields.text];h&&(h.callback?b=h.callback(l,g,a):(b=this.filterService.match(l,
h.conditions,h.formula,this.getFilterTree(c),h.caseSensitive),!b&&h.allowParent&&(b=this.filterIsThereChildren(a,d))))}if(!b)break}return b};b.prototype.filterIsThereChildren=function(a,d){var b=!1,c=a[this.options.rowFields.rows];if(c)for(var g=0;g<c.length&&!(b=this.isRowAllowed(c[g],d));g++);return b};b.prototype.isRowEnabled=function(a){return!0};b.prototype.isRowFixed=function(a){return!1};b.prototype.isRowHovered=function(a){return a&&a==this.hoverRow?!0:!1};b.prototype.isRowSelected=function(a){return a&&
1==a[this.options.rowFields.selected]?!0:!1};b.prototype.isParentOf=function(a,d){return!1};b.prototype.cellGotFocus=function(a){this.refresh()};b.prototype.cellLostFocus=function(a){this.refresh()};b.prototype.onContentScroll=function(a){a.srcElement.scrollTop=0;a.srcElement.scrollLeft=0;a.target.scrollTop=0;a.target.scrollLeft=0};b.prototype.cellMouseDown=function(a,d){1==a.buttons&&(this.currentFocusCell=d.data)};b.prototype.cellKeyDown=function(a,d){var b={cancel:!1,cell:d.data,event:a};this.keyDown.emit(b);
switch(a.keyCode){case 13:this.beforeEdit.emit(b);break;case 33:!b.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processPageUpKey(d));break;case 34:!b.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processPageDownKey(d));break;case 35:!b.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processEndKey(d));break;case 36:!b.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=
!0,this.processHomeKey(d));break;case 37:!b.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processLeftArrowKey(d));break;case 38:!b.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processUpArrowKey(d));break;case 39:!b.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processRightArrowKey(d));break;case 40:!b.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processDownArrowKey(d))}};
b.prototype.cellKeyPress=function(a,d){this.keyPress.emit({cancel:!1,cell:d.data,event:a})};b.prototype.cellKeyUp=function(a,d){this.keyUp.emit({cancel:!1,cell:d.data,event:a})};b.prototype.processDownArrowKey=function(a,d){var b=this.getDownCell(a);if(b){this.currentFocusCell=b.data;var c=this.getRowFromCell(b),g=this,f=setTimeout(function(){g.processRowSelection(d,c.data);clearTimeout(f)},1);this.isLastRow(b)&&this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y+2*this.avgRowHeight})}return b};
b.prototype.processEndKey=function(a,d){var b=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,y:this.maxScrollPos.y});var c=this;setTimeout(function(){var e=c.scrollRowList[c.scrollRowList.length-1];if(0<=a.colIndex&&a.colIndex<e.cells.length){b=e.cells[a.colIndex];c.currentFocusCell=b.data;var f=setTimeout(function(){c.processRowSelection(d,e.data);clearTimeout(f)},1)}},1)}return b};b.prototype.processHomeKey=function(a,d){var b=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,
y:0});var c=this;setTimeout(function(){var e=c.scrollRowList[0];if(0<=a.colIndex&&a.colIndex<e.cells.length){b=e.cells[a.colIndex];c.currentFocusCell=b.data;var f=setTimeout(function(){c.processRowSelection(d,e.data);clearTimeout(f)},1)}},1)}return b};b.prototype.processLeftArrowKey=function(a){if(a=this.getPrevCell(a)){this.currentFocusCell=a.data;this.isFirstCell(a)&&this.scrollPos({x:this.currentScrollPos.x-2*a.width,y:this.currentScrollPos.y});var d=this;setTimeout(function(){d.refresh()},1)}return a};
b.prototype.processPageDownKey=function(a,d){var b=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y+this.avgRowHeight*(this.scrollRowList.length-1)});var c=this;setTimeout(function(){var e=0<=a.rowIndex&&a.rowIndex<c.scrollRowList.length?a.rowIndex:c.scrollRowList.length-1;c.currentScrollPos.y==c.maxScrollPos.y&&(e=c.scrollRowList.length-1);var f=c.scrollRowList[e];if(0<=a.colIndex&&a.colIndex<f.cells.length){b=f.cells[a.colIndex];c.currentFocusCell=
b.data;var h=setTimeout(function(){c.processRowSelection(d,f.data);clearTimeout(h)},1)}},1)}return b};b.prototype.processPageUpKey=function(a,d){var b=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y-this.avgRowHeight*(this.scrollRowList.length-1)});var c=this;setTimeout(function(){var e=0<=a.rowIndex&&a.rowIndex<c.scrollRowList.length?a.rowIndex:0;0==c.currentScrollPos.y&&(e=0);var f=c.scrollRowList[e];if(0<=a.colIndex&&a.colIndex<f.cells.length){b=
f.cells[a.colIndex];c.currentFocusCell=b.data;var h=setTimeout(function(){c.processRowSelection(d,f.data);clearTimeout(h)},1)}},1)}return b};b.prototype.processRightArrowKey=function(a){if(a=this.getNextCell(a)){this.currentFocusCell=a.data;this.isLastCell(a)?this.scrollPos({x:this.currentScrollPos.x+2*a.width,y:this.currentScrollPos.y}):a.colIndex>=this.currentColumnList.length-2&&this.scrollPos({x:this.maxScrollPos.x,y:this.currentScrollPos.y});var d=this;setTimeout(function(){d.refresh()},1)}return a};
b.prototype.processUpArrowKey=function(a,d){var b=this.getUpCell(a);if(b){this.currentFocusCell=b.data;var c=this.getRowFromCell(b),g=this,f=setTimeout(function(){g.processRowSelection(d,c.data);clearTimeout(f)},1);this.isFirstRow(b)&&this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y-this.avgRowHeight})}return b};b.prototype.getDownCell=function(a){if(0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var b=a.rowIndex<this.scrollRowList.length-1?a.rowIndex+1:-1;return(b=0<=b?this.scrollRowList[b]:
null)&&0<=a.colIndex&&a.colIndex<b.cells.length?b.cells[a.colIndex]:null}return null};b.prototype.getNextCell=function(a){if(0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var b=this.scrollRowList[a.rowIndex];a=b.cells.indexOf(a);a=0<=a&&a<b.cells.length-1?a+1:-1;return 0<=a?b.cells[a]:null}return null};b.prototype.getPrevCell=function(a){if(0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var b=this.scrollRowList[a.rowIndex];a=b.cells.indexOf(a);a=0<a&&a<b.cells.length?a-1:-1;return 0<=
a?b.cells[a]:null}return null};b.prototype.getUpCell=function(a){if(0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var b=0<a.rowIndex?a.rowIndex-1:-1;return(b=0<=b?this.scrollRowList[b]:null)&&0<=a.colIndex&&a.colIndex<b.cells.length?b.cells[a.colIndex]:null}return null};b.prototype.isFirstCell=function(a){return 0==a.colIndex?!0:!1};b.prototype.isFirstRow=function(a){return 0==a.rowIndex?!0:!1};b.prototype.isLastCell=function(a){return a.colIndex==this.viewIndexRange.middle-this.viewIndexRange.left?
!0:!1};b.prototype.isLastRow=function(a){return a.rowIndex==this.scrollRowList.length-2?!0:!1};b.prototype.getRowFromCell=function(a){return 0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length?this.scrollRowList[a.rowIndex]:null};b.prototype.moveFocusFromCell=function(a,b){if(!this.options.allowFocus)return null;var d=null,c=this.getObjFromCell(a);if(c)switch(b){case "down":d=this.processDownArrowKey(c);break;case "end":d=this.processEndKey(c);break;case "home":d=this.processHomeKey(c);break;case "left":d=
this.processLeftArrowKey(c);break;case "pagedown":d=this.processPageDownKey(c);break;case "pageup":d=this.processPageUpKey(c);break;case "right":d=this.processRightArrowKey(c);break;case "up":d=this.processUpArrowKey(c)}return d?d.data:null};b.prototype.getObjFromCell=function(a){for(var b=null,e=0;e<this.scrollRowList.length;e++)for(var c=this.scrollRowList[e],g=0;g<c.cells.length;g++){var f=c.cells[g];if(f.data==a){b=f;break}}return b};b.prototype.onWindowKeyDown=function(a){this.isKeyboardActive&&
a.preventDefault()};b.prototype.onWindowKeyUp=function(a){this.isKeyboardActive=!1};b.prototype.getContentSize=function(){return{width:0,height:0}};b.prototype.refresh=function(a){this.clearComponentSelection();for(a=0;a<this.currentSelectedRows.length;a++){var b=this.getRowCurrentIndex(this.currentSelectedRows[a]);this.isComponentIndexInRange(b)&&(this.rowList[b].state|=integralui_core_1.IntegralUIObjectState.selected)}};b.prototype.suspendLayout=function(){this.allowUpdate=!1};b.prototype.resumeLayout=
function(){this.allowUpdate=!0;this.updateLayout()};b.prototype.updateLayout=function(){};b.prototype.updateRange=function(){};b.prototype.updateCloneElemPos=function(a){1==a.buttons&&this.cloneElem&&(this.cloneElem.style.top=a.pageY-this.cloneElemStartPos.y+"px",this.cloneElem.style.left=a.pageX-this.cloneElemStartPos.x+"px")};b.prototype.onCtrlMouseEnter=function(a){1==a.buttons&&this.cloneElem&&(this.cloneElem.style.display="block");this.elemRenderer.setElementStyle(this.elemRef.nativeElement,
"cursor","default")};b.prototype.onCtrlMouseLeave=function(a){1==a.buttons&&this.cloneElem&&(this.cloneElem.style.display="none");this.stopScrollTimer()};b.prototype.setCloneElem=function(a,b){this.cloneElem&&this.closeCloneElem();this.cloneElem=a;this.cloneElemStartPos=b};b.prototype.appendCloneElem=function(){document.body.appendChild(this.cloneElem)};b.prototype.closeCloneElem=function(){var a=this;a.elemRenderer.setElementStyle(a.elemRef.nativeElement,"cursor","default");setTimeout(function(){a.cloneElem&&
(document.body.removeChild(a.cloneElem),a.cloneElem=null)},10)};b.prototype.updatePaging=function(a){this.options.paging=a?{enabled:this.commonService.isFieldAvailable(a.enabled,!1),showControlPanel:this.commonService.isFieldAvailable(a.showControlPanel,!0),pageSize:this.commonService.isFieldAvailable(a.pageSize,100)}:{enabled:!1,showControlPanel:!0,pageSize:100}};b.prototype.scrollPos=function(a){a&&(this.currentScrollPos={x:Math.max(0,Math.min(a.x,this.maxScrollPos.x)),y:Math.max(0,Math.min(a.y,
this.maxScrollPos.y))});return{x:Math.floor(this.currentScrollPos.x),y:Math.floor(this.currentScrollPos.y)}};b.prototype.changeHorizontalScrollPos=function(a){this.currentScrollPos.x=Math.max(0,Math.min(a,this.maxScrollPos.x));this.currentScrollPos.x!=this.prevScrollPos.x&&(this.updateRange(),this.scrollPosChanged.emit({value:this.scrollPos()}),this.prevScrollPos.x=this.currentScrollPos.x)};b.prototype.changeVerticalScrollPos=function(a){this.currentScrollPos.y=Math.max(0,Math.min(a,this.maxScrollPos.y));
this.currentScrollPos.y!=this.prevScrollPos.y&&(this.updateView(),this.scrollPosChanged.emit({value:this.scrollPos()}),this.prevScrollPos.y=this.currentScrollPos.y)};b.prototype.gridMouseWheel=function(a){a.preventDefault();this.hoverRow=null;var b=0;a.wheelDelta?b=Math.max(-1,Math.min(1,a.wheelDelta||-a.detail)):a.originalEvent&&(b=Math.max(-1,Math.min(1,a.originalEvent.wheelDelta||-a.originalEvent.detail)));this.isVerScrollVisible()&&this.changeVerticalScrollPos(this.currentScrollPos.y+Math.floor(this.clientRect.height/
4)*b*-1);a.stopPropagation()};b.prototype.isVerScrollVisible=function(){return 0<this.scrollSize.height?!0:!1};b.prototype.isHorScrollVisible=function(){return 0<this.scrollSize.width?!0:!1};b.prototype.onVerticalScrollStart=function(a){this.hoverRow=null;this.isScrollActive=!0};b.prototype.onVerticalScrollEnd=function(a){this.isScrollActive=!1};b.prototype.onVerticalScrollChanged=function(a){this.changeVerticalScrollPos(a.value)};b.prototype.onHorizontalScrollStart=function(a){this.hoverRow=null;
this.isScrollActive=!0};b.prototype.onHorizontalScrollEnd=function(a){this.isScrollActive=!1};b.prototype.onHorizontalScrollChanged=function(a){this.currentScrollPos.x=a.value;this.scrollPosChanged.emit({value:this.scrollPos()});var b=this,e=setTimeout(function(){b.updateRange();clearTimeout(e)},1)};b.prototype.updateView=function(){this.currentIndex=0<this.avgRowHeight?Math.floor(this.currentScrollPos.y/this.avgRowHeight):0;this.currentIndex!=this.prevIndex&&(this.updateScrollRowList(),this.prevIndex=
this.currentIndex)};b.prototype.processScroll=function(a){if(this.isVerScrollVisible()){var b=this.commonService.getShiftPos();a=this.commonService.getMousePos(a);a.x-=b.x;a.y-=b.y;var e=this.commonService.getPageRect(this.elemRef.nativeElement);b=e.top+this.headerHeight+25;e=e.bottom-this.footerHeight-25;this.isHorScrollVisible()&&(e-=16);a.y<b?this.startScrollTimer(!1):a.y>e?this.startScrollTimer(!0):this.stopScrollTimer()}else this.stopScrollTimer()};b.prototype.startScrollTimer=function(a,b){var d=
this;d.isScrollTimerActive||(d.accelerator=.5,d.scrollCount=0,d.isScrollTimerActive=!0,d.scrollTimerID=setInterval(function(){d.scrollTimerElapsed(a)},b?b:100))};b.prototype.stopScrollTimer=function(){this.scrollTimerID&&(clearInterval(this.scrollTimerID),this.scrollTimerID=null);this.accelerator=.5;this.scrollCount=0;this.isScrollTimerActive=!1};b.prototype.scrollTimerElapsed=function(a){var b=this.currentScrollPos;0===this.scrollCount&&(this.scrollCount=5);this.scrollCount+=5;this.accelerator+=
.5;var e=this.scrollCount+=Math.floor(this.accelerator);this.currentScrollPos.y=a?this.currentScrollPos.y+e>this.maxScrollPos.y?this.maxScrollPos.y:this.currentScrollPos.y+e:0>this.currentScrollPos.y-e?0:this.currentScrollPos.y-e;(0>=b.y||this.currentScrollPos.y<b.y)&&this.stopScrollTimer()};b.prototype.scrollTo=function(a){a&&(a=this.getRowCurrentIndex(a),0<=a&&this.scrollPos({x:this.currentScrollPos.x,y:this.avgRowHeight*(a+1-this.visibleRange/2)}),this.updateLayout())};b.prototype.findRowById=
function(a){return this.dataService.findObjectById(a,this.rowDataKey)};b.prototype.findRowByText=function(a){return this.dataService.findObjectByText(a,this.rowDataKey)};b.prototype.clearSelection=function(){this.clearPrevSelection();this.refresh()};b.prototype.processColumnSelection=function(a,b,e){if(b)a=!0,this.currentSelectedColumn&&(a=!this.commonService.isEqual(this.currentSelectedColumn[this.options.columnFields.id],b[this.options.columnFields.id])),e={cancel:!1,obj:b},this.beforeSelect.emit(e),
a&&1!=e.cancel&&(this.currentSelectedColumn&&(this.currentSelectedColumn[this.options.columnFields.selected]=!1,this.refresh(this.currentSelectedColumn)),this.currentSelectedColumn=b,b[this.options.columnFields.selected]=!0,this.refresh(b),this.callAfterSelectEvent(b));else return this.currentSelectedColumn};b.prototype.clearComponentSelection=function(){this.rowList.forEach(function(a){return a.state&=~integralui_core_1.IntegralUIObjectState.selected})};b.prototype.clearPrevSelection=function(a){for(var b=
0;b<this.currentSelectedRows.length;b++)a&&!this.commonService.isEqual(this.currentSelectedRows[b][this.options.rowFields.id],a[this.options.rowFields.id])?this.currentSelectedRows[b][this.options.rowFields.selected]=!1:a||(this.currentSelectedRows[b][this.options.rowFields.selected]=!1);this.currentSelectedRows.length=0;a&&this.isRowEnabled(a)&&this.currentSelectedRows.push(a)};b.prototype.isRowInSelectionList=function(a){var b=!1,e=this.currentSelectedRows;if(a&&e)for(var c=0;c<e.length;c++)if(this.commonService.isEqual(e[c][this.options.rowFields.id],
a[this.options.rowFields.id])){b=!0;break}return b};b.prototype.processRowSelection=function(a,b,e){if(b&&this.selectionMode!=integralui_core_1.IntegralUISelectionMode.None){var d=0<this.currentSelectedRows.length;if(this.isRowEnabled(b)){var g=this.currentSelectedRow,f=!0;g&&(f=a&&(a.ctrlKey||a.metaKey)||!this.commonService.isEqual(g[this.options.rowFields.id],b[this.options.rowFields.id])||0==g[this.options.rowFields.selected]);var h={cancel:!1,obj:b};this.beforeSelect.emit(h);if(1!=h.cancel)if(h=
a&&(a.shiftKey||a.ctrlKey||a.metaKey)?!0:!1,f){this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiExtended&&(f=!this.isRowInSelectionList(b)||!h||a&&a.shiftKey);f&&(this.selectionMode==integralui_core_1.IntegralUISelectionMode.One?this.clearPrevSelection():a&&a.shiftKey?this.clearPrevSelection():h||this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiSimple||1!=this.currentSelectedRows.length&&this.isRowInSelectionList(b)||this.clearPrevSelection());this.currentSelectedRow=
b;if(a&&a.shiftKey&&this.selectionMode!=integralui_core_1.IntegralUISelectionMode.One){if(this.shiftFirstSelectedRow||(this.shiftFirstSelectedRow=g),a=this.getRowCurrentIndex(this.shiftFirstSelectedRow),e=this.getRowCurrentIndex(b),a>e&&(d=a,a=e,e=d),this.isIndexInRange(a)&&this.isIndexInRange(e))for(;a<=e;a++)this.currentRowList[a].data[this.options.rowFields.selected]=!0,this.currentSelectedRows.push(this.currentRowList[a].data)}else h||this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiSimple?
(a=null==b[this.options.rowFields.selected]||"undefined"==b[this.options.rowFields.selected]?!1:b[this.options.rowFields.selected],b[this.options.rowFields.selected]=!a,b[this.options.rowFields.selected]?this.isRowInSelectionList(b)||this.currentSelectedRows.push(b):this.currentSelectedRows=this.currentSelectedRows.filter(function(a){return a!=b})):(b[this.options.rowFields.selected]=!0,this.isRowInSelectionList(b)||this.currentSelectedRows.push(b)),this.shiftFirstSelectedRow=null;this.callAfterSelectEvent(b);
this.refresh()}else h||this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiSimple?(a=null===b[this.options.rowFields.selected]||"undefined"==b[this.options.rowFields.selected]?!1:b[this.options.rowFields.selected],e&&"undefined"!=e&&(a=e),b[this.options.rowFields.selected]=!a,b[this.options.rowFields.selected]?this.isRowInSelectionList(b)||this.currentSelectedRows.push(b):this.currentSelectedRows=this.currentSelectedRows.filter(function(a){return a!=b}),this.shiftFirstSelectedRow=null,
this.callAfterSelectEvent(b),this.refresh()):h||this.selectionMode&integralui_core_1.IntegralUISelectionMode.MultiSimple||1!=this.currentSelectedRows.length&&this.isRowInSelectionList(b)||(this.shiftFirstSelectedRow=null,this.clearPrevSelection(b),this.refresh(),d&&this.selectionChanged.emit(null))}else this.clearPrevSelection(),this.refresh(),d&&this.selectionChanged.emit(null)}};b.prototype.selectRows=function(a){if(a&&Array.isArray(a)){for(var b=this.currentSelectedRows.length=0;b<a.length;b++)a[b][this.options.rowFields.selected]=
!0,this.currentSelectedRows.push(a[b]);0<a.length?(this.currentSelectedRow=a[a.length-1],this.callAfterSelectEvent(this.currentSelectedRow)):this.currentSelectedRow=null;this.refresh()}};b.prototype.updateRowSelection=function(a,b){var d=a&&(a.shiftKey||a.ctrlKey||a.metaKey)?!0:!1;this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiExtended&&0<this.currentSelectedRows.length&&!a.shiftKey&&!d&&1==a.which&&(this.clearPrevSelection(),b[this.options.rowFields.selected]=!0,this.currentSelectedRows.push(b),
this.callAfterSelectEvent(b),this.refresh())};b.prototype.sort=function(a,b,e){this.sortColumn=a;this.sortComparer=e;this.options.sorting=b;this.updateLayout();this.change.emit({type:"sorting"})};b.prototype.getCellIndexInCollection=function(a,b,e){var d=-1;if(a)for(var g=0;g<a.length;g++)if(void 0==a[g][this.options.cellFields.cid]){d=b;break}else if(a[g][this.options.cellFields.cid]==e){d=g;break}return d};b.prototype.isSortingAllowed=function(){return this.options.sorting==integralui_core_1.IntegralUISortOrder.Ascending||
this.options.sorting==integralui_core_1.IntegralUISortOrder.Descending};b.prototype.isSortingColumn=function(a){return a&&a==this.sortColumn?!0:!1};b.prototype.applySorting=function(a){var b=this;if(a&&(!b.sortColumn||0!=b.sortColumn[b.options.columnFields.visible])){var e=b.getColumnCurrentIndex(b.sortColumn),c=0<=e?e:b.options.expandColIndex;if(c<b.currentColumnList.length){var g=b.currentColumnList[c].data[b.options.columnFields.id];b.sortColumn&&b.sortColumn[b.options.columnFields.comparer]?a.sort(b.sortColumn[b.options.columnFields.comparer]):
b.sortComparer?a.sort(b.sortComparer):b.isSortingAllowed()&&a.sort(function(a,d){var e=null,f=null;if(a[b.options.rowFields.cells]){var h=b.getCellIndexInCollection(a[b.options.rowFields.cells],c,g);0<=h&&((e=a[b.options.rowFields.cells][h][b.options.cellFields.value])||(e=a[b.options.rowFields.cells][h][b.options.cellFields.text]),b.commonService.isObject(e)&&(e=e.value?e.value:e.text))}d[b.options.rowFields.cells]&&(h=b.getCellIndexInCollection(d[b.options.rowFields.cells],c,g),0<=h&&((f=d[b.options.rowFields.cells][h][b.options.cellFields.value])||
(f=d[b.options.rowFields.cells][h][b.options.cellFields.text]),b.commonService.isObject(f)&&(f=f.value?f.value:f.text)));e=void 0!=e?e:null;f=void 0!=f?f:null;switch(b.options.sorting){case integralui_core_1.IntegralUISortOrder.Ascending:if(e<f)return-1;if(e>f)return 1;break;case integralui_core_1.IntegralUISortOrder.Descending:if(e>f)return-1;if(e<f)return 1;break;default:return 0}})}}};return b}(integralui_core_1.IntegralUIBaseComponent);
__decorate([core_1.Input(),__metadata("design:type",Object)],IntegralUIBaseGrid.prototype,"appRef",void 0);__decorate([core_1.Input(),__metadata("design:type",Number)],IntegralUIBaseGrid.prototype,"gridLines",void 0);__decorate([core_1.Input(),__metadata("design:type",Number)],IntegralUIBaseGrid.prototype,"rowHeight",void 0);__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],IntegralUIBaseGrid.prototype,"allowDrag",null);
__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],IntegralUIBaseGrid.prototype,"allowDrop",null);__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],IntegralUIBaseGrid.prototype,"allowFilter",null);__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],IntegralUIBaseGrid.prototype,"allowFocus",null);
__decorate([core_1.Input(),__metadata("design:type",Array),__metadata("design:paramtypes",[Array])],IntegralUIBaseGrid.prototype,"columns",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],IntegralUIBaseGrid.prototype,"dataFields",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],IntegralUIBaseGrid.prototype,"focusedCell",null);
__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],IntegralUIBaseGrid.prototype,"paging",null);__decorate([core_1.Input(),__metadata("design:type",Array),__metadata("design:paramtypes",[Array])],IntegralUIBaseGrid.prototype,"rows",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],IntegralUIBaseGrid.prototype,"selectedColumn",null);
__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],IntegralUIBaseGrid.prototype,"selectedRow",null);__decorate([core_1.Input(),__metadata("design:type",Number),__metadata("design:paramtypes",[Number])],IntegralUIBaseGrid.prototype,"selectionMode",null);__decorate([core_1.Input(),__metadata("design:type",Number),__metadata("design:paramtypes",[Number])],IntegralUIBaseGrid.prototype,"sorting",null);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"afterSelect",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"beforeEdit",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"beforeSelect",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"change",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnAdding",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnAdded",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnClick",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnRemoving",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnRemoved",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnsCleared",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"columnSizeChanged",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"dragDrop",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"dragOver",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"keyDown",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"keyPress",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"keyUp",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowAdding",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowAdded",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowClick",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowDblClick",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowRemoving",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowRemoved",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"rowsCleared",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"loadComplete",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"scrollPosChanged",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"selectionChanged",void 0);
__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],IntegralUIBaseGrid.prototype,"updateComplete",void 0);__decorate([core_1.HostListener("document:keydown",["$event"]),__metadata("design:type",Function),__metadata("design:paramtypes",[Object]),__metadata("design:returntype",void 0)],IntegralUIBaseGrid.prototype,"onWindowKeyDown",null);
__decorate([core_1.HostListener("document:keyup",["$event"]),__metadata("design:type",Function),__metadata("design:paramtypes",[Object]),__metadata("design:returntype",void 0)],IntegralUIBaseGrid.prototype,"onWindowKeyUp",null);
IntegralUIBaseGrid=__decorate([core_1.Component({selector:"iui-basegrid",template:"",providers:[integralui_data_service_1.IntegralUIDataService]}),__metadata("design:paramtypes",[integralui_data_service_1.IntegralUIDataService,integralui_dragdrop_service_1.IntegralUIDragDropService,core_1.ElementRef,core_1.Renderer,integralui_common_service_1.IntegralUICommonService,integralui_filter_service_1.IntegralUIFilterService,core_1.ComponentFactoryResolver])],IntegralUIBaseGrid);
exports.IntegralUIBaseGrid=IntegralUIBaseGrid;