/*
  filename: integralui.dragdrop.service.js
  version : 20.3.0
  Copyright © 2016-2020 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var core_1=require("@angular/core"),i0=require("@angular/core"),IntegralUIDragDropService=function(){function t(){this.data={action:"move",clone:null,dropPos:-1,handle:null,source:null,sourceCtrl:null,sourceData:null,sourceIndex:-1,target:null,targetCtrl:null,type:""}}t.prototype.getDropPosHalf=function(t,e,r){var o={left:e.x,top:e.y,right:e.x+e.width,bottom:e.y+e.height};switch(r){case"full":if(this.checkHit(t.x,t.y,o))return 0;break;case"horizontal":o.right=e.x+e.width/2;if(this.checkHit(t.x,t.y,o))return 1;else{o.left=o.right;o.right=e.x+e.width;if(this.checkHit(t.x,t.y,o))return 2}break;default:o.bottom=e.y+e.height/2;if(this.checkHit(t.x,t.y,o))return 1;else{o.top=o.bottom;o.bottom=e.y+e.height;if(this.checkHit(t.x,t.y,o))return 2}}return-1};t.prototype.getDropPosHorizontal=function(t,e,r){if(r)return this.getDropPosHalf(t,e,"horizontal");else{var o={left:e.x+e.width/4,top:e.y,right:e.x+3*e.width/4,bottom:e.y+e.height};if(this.checkHit(t.x,t.y,o))return 0;else{o.right=o.left;o.left=e.x;if(this.checkHit(t.x,t.y,o))return 1;else{o.left=e.x+3*e.width/4;o.right=e.x+e.width;if(this.checkHit(t.x,t.y,o))return 2}}}return-1};t.prototype.getDropPosVertical=function(t,e,r){if(r)return this.getDropPosHalf(t,e,"vertical");else{var o={left:e.x,top:e.y+e.height/4,right:e.x+e.width,bottom:e.y+3*e.height/4};if(this.checkHit(t.x,t.y,o))return 0;else{o.bottom=o.top;o.top=e.y;if(this.checkHit(t.x,t.y,o))return 1;else{o.top=e.y+3*e.height/4;o.bottom=e.y+e.height;if(this.checkHit(t.x,t.y,o))return 2}}}return-1};t.prototype.checkHit=function(t,e,r){if(t>=r.left&&t<=r.right&&e>=r.top&&e<=r.bottom)return!0;else return!1};t.prototype.clearData=function(){this.data={action:"move",clone:null,dropPos:-1,handle:null,source:null,sourceCtrl:null,sourceData:null,sourceIndex:-1,target:null,targetCtrl:null,type:""}};t.prototype.getData=function(){return this.data};t.prototype.setData=function(t){if(t){if(t.action)this.data.action=t.action;if(!isNaN(t.dropPos))this.data.dropPos=t.dropPos;if(!isNaN(t.sourceIndex))this.data.sourceIndex=t.sourceIndex;this.data.clone=void 0!=t.clone?t.clone:null;this.data.source=void 0!=t.source?t.source:null;this.data.handle=void 0!=t.handle?t.handle:null;this.data.sourceCtrl=void 0!=t.sourceCtrl?t.sourceCtrl:null;this.data.sourceData=void 0!=t.sourceData?t.sourceData:null;this.data.target=void 0!=t.target?t.target:null;this.data.targetCtrl=void 0!=t.targetCtrl?t.targetCtrl:null;this.data.type=void 0!=t.type?t.type:""}};t.prototype.hitTest=function(t,e,r){return this.checkHit(t,e,r)};t.prototype.getDropPos=function(t,e,r,o){if("horizontal"==o)return this.getDropPosHorizontal(t,e,r);else return this.getDropPosVertical(t,e,r)};t.ɵfac=function(e){return new(e||t)};t.ɵprov=i0.ɵɵdefineInjectable({token:t,factory:t.ɵfac});return t}();exports.IntegralUIDragDropService=IntegralUIDragDropService;