/*
  filename: integralui.tooltip.js
  version : 1.0.0
  Copyright © 2016-2017 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(d,b){function a(){this.constructor=d}for(var c in b)b.hasOwnProperty(c)&&(d[c]=b[c]);d.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)},__decorate=this&&this.__decorate||function(d,b,a,c){var f=arguments.length,e=3>f?b:null===c?c=Object.getOwnPropertyDescriptor(b,a):c,g;if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)e=Reflect.decorate(d,b,a,c);else for(var h=d.length-1;0<=h;h--)if(g=d[h])e=(3>f?g(e):3<f?g(b,a,e):
g(b,a))||e;return 3<f&&e&&Object.defineProperty(b,a,e),e},__metadata=this&&this.__metadata||function(d,b){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(d,b)},core_1=require("@angular/core"),integralui_core_1=require("../components/integralui.core"),integralui_common_service_1=require("../services/integralui.common.service"),IntegralUITooltipComponent=function(d){function b(a,b){d.call(this,b);this.elemRef=a;this.commonService=b;this.popupTimer=this.showTimer=
null;this.mousePos={x:0,y:0};this.tooltipDisplay="none";this.tooltipPos={top:0,left:0};this.tooltipSize={width:0,height:0};this.closed=new core_1.EventEmitter;this.updateOptions()}__extends(b,d);Object.defineProperty(b.prototype,"options",{get:function(){return this.tooltipOptions},set:function(a){this.updateOptions(a)},enumerable:!0,configurable:!0});b.prototype.updateOptions=function(a){this.tooltipOptions=a?{autoPopDelay:this.commonService.isFieldAvailable(a.autoPopDelay,5E3),enabled:this.commonService.isFieldAvailable(a.enabled,
!0),initialDelay:this.commonService.isFieldAvailable(a.initialDelay,500),position:this.commonService.isFieldAvailable(a.position,"mouse"),showMarker:this.commonService.isFieldAvailable(a.showMarker,!0),title:this.commonService.isFieldAvailable(a.title,"")}:{autoPopDelay:5E3,enabled:!0,initialDelay:500,position:"mouse",showMarker:!0,title:""}};b.prototype.removeTimers=function(){this.showTimer&&(clearTimeout(this.showTimer),this.showTimer=null);this.popupTimer&&(clearTimeout(this.popupTimer),this.popupTimer=
null)};b.prototype.open=function(a,b){var c=this;c.tooltipPos.top=-9999999;c.tooltipDisplay="block";var d=setTimeout(function(){c.tooltipSize=c.size();c.tooltipDisplay="none";c.removeTimers();c.tooltipOptions.enabled&&""!=c.tooltipOptions.title&&(c.showTimer=setTimeout(function(){c.show(a,b);c.popupTimer=setTimeout(function(){c.closed.emit(null);clearTimeout(c.popupTimer)},c.tooltipOptions.autoPopDelay);clearTimeout(c.showTimer)},c.tooltipOptions.initialDelay));clearTimeout(d)},1)};b.prototype.show=
function(a,b){this.tooltipPos={top:this.mousePos.y+24,left:this.mousePos.x};switch(this.tooltipOptions.position){case "above":this.tooltipPos={top:a.top-4-this.tooltipSize.height,left:a.left+Math.floor((b.width-this.tooltipSize.width)/2)};break;case "below":this.tooltipPos={top:a.bottom+4,left:a.left+Math.floor((b.width-this.tooltipSize.width)/2)};break;case "left":this.tooltipPos={top:a.top+Math.floor((b.height-this.tooltipSize.height)/2),left:a.left-4-this.tooltipSize.width};break;case "right":this.tooltipPos=
{top:a.top+Math.floor((b.height-this.tooltipSize.height)/2),left:a.right+4}}this.tooltipDisplay="block"};b.prototype.size=function(){return{width:this.elemRef.nativeElement.firstElementChild.offsetWidth,height:this.elemRef.nativeElement.firstElementChild.offsetHeight}};b.prototype.updateMousePos=function(a){this.mousePos!=a&&(this.mousePos=a)};b.prototype.updateControlClass=function(){this.ctrlClass.length=0;this.ctrlClass.push("iui-tooltip");if(this.tooltipOptions.showMarker)switch(this.tooltipOptions.position){case "above":this.ctrlClass.push("iui-tooltip-marker-bottom");
break;case "right":this.ctrlClass.push("iui-tooltip-marker-left");break;case "below":this.ctrlClass.push("iui-tooltip-marker-top");break;case "left":this.ctrlClass.push("iui-tooltip-marker-right")}};__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],b.prototype,"options",null);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"closed",void 0);return b=__decorate([core_1.Component({selector:"iui-tooltip",template:"\n\t\t<div class=\"iui-tooltip\" [ngClass]=\"getControlClass()\" [ngStyle]=\"{ 'display': tooltipDisplay, 'top': tooltipPos.top + 'px', 'left': tooltipPos.left + 'px' }\" style=\"opacity:1 !important\">{{tooltipOptions.title}}</div>\n\t",
inputs:["controlStyle","data","state"],encapsulation:core_1.ViewEncapsulation.None}),__metadata("design:paramtypes",[core_1.ElementRef,integralui_common_service_1.IntegralUICommonService])],b)}(integralui_core_1.IntegralUIBaseComponent);exports.IntegralUITooltipComponent=IntegralUITooltipComponent;
var IntegralUITooltip=function(){function d(b,a,c){this.elemRef=b;this.cmpResolver=a;this.commonService=c;this.eventList=[];this.cmpRef=null}d.prototype.closeTooltip=function(){this.cmpRef&&(this.eventList&&this.eventList.forEach(function(b){return b.unsubscribe()}),this.cmpRef.destroy())};d.prototype.size=function(){return{width:this.elemRef.nativeElement.offsetWidth,height:this.elemRef.nativeElement.offsetHeight}};d.prototype.onMouseEnter=function(b){var a=this;if(a.settings.appRef){a.closeTooltip();
var c=a.cmpResolver.resolveComponentFactory(IntegralUITooltipComponent);c&&(a.cmpRef=a.settings.appRef.createComponent(c),a.cmpRef&&(c=null,a.cmpRef._component?c=a.cmpRef._component:a.cmpRef._hostElement&&(c=a.cmpRef._hostElement.component),c&&(c.options=a.settings,c.updateMousePos(a.commonService.getMousePos(b)),b=this.elemRef.nativeElement.getBoundingClientRect(),c.open(b,a.size()),a.eventList.push(c.closed.subscribe(function(b){a.closeTooltip()})))))}};d.prototype.onMouseLeave=function(b){this.closeTooltip()};
d.prototype.onMouseMove=function(b){if(this.cmpRef)if(this.cmpRef._component){var a=this.cmpRef._component;a.updateMousePos(this.commonService.getMousePos(b))}else this.cmpRef&&this.cmpRef._hostElement&&(a=this.cmpRef._hostElement.component,a.updateMousePos(this.commonService.getMousePos(b)))};__decorate([core_1.Input("iuiTooltip"),__metadata("design:type",Object)],d.prototype,"settings",void 0);__decorate([core_1.HostListener("mouseenter",["$event"]),__metadata("design:type",Function),__metadata("design:paramtypes",
[Object]),__metadata("design:returntype",void 0)],d.prototype,"onMouseEnter",null);__decorate([core_1.HostListener("mouseleave",["$event"]),__metadata("design:type",Function),__metadata("design:paramtypes",[Object]),__metadata("design:returntype",void 0)],d.prototype,"onMouseLeave",null);__decorate([core_1.HostListener("mousemove",["$event"]),__metadata("design:type",Function),__metadata("design:paramtypes",[Object]),__metadata("design:returntype",void 0)],d.prototype,"onMouseMove",null);return d=
__decorate([core_1.Directive({selector:"[iuiTooltip]"}),__metadata("design:paramtypes",[core_1.ElementRef,core_1.ComponentFactoryResolver,integralui_common_service_1.IntegralUICommonService])],d)}();exports.IntegralUITooltip=IntegralUITooltip;