/*
  filename: integralui.base.list.js
  version : 1.2.0
  Copyright © 2016-2017 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
import { Component, ComponentFactoryResolver, ElementRef, EventEmitter, HostListener, Input, Output, Renderer } from '@angular/core';
import { IntegralUIBaseComponent, IntegralUIObjectState, IntegralUIOrientation, IntegralUISelectionMode, IntegralUISortOrder, IntegralUIDragWindow } from './integralui.core';
import { IntegralUICommonService } from '../services/integralui.common.service';
import { IntegralUIDataService } from '../services/integralui.data.service';
import { IntegralUIDragDropService } from '../services/integralui.dragdrop.service';
import { IntegralUIFilterService } from '../services/integralui.filter.service';
var IntegralUIBaseList = (function (_super) {
__extends(IntegralUIBaseList,_super);
function IntegralUIBaseList(a,b,c,d,f,g,h){var e=_super.call(this,f)||this;e.dataService=a;e.dragDropService=b;e.elemRef=c;e.elemRenderer=d;e.commonService=f;e.filterService=g;e.cmpResolver=h;e.currentList=[];e.options={allowDrag:!1,allowDrop:!0,dataFields:null,selectedItem:null,sorting:IntegralUISortOrder.None};e.dataItems=[];e.scrollItemList=[];e.dropMarkElem=null;e.dragCmpRef=null;e.dragCmp=null;e.cloneElem=null;e.cloneElemStartPos={x:0,y:0};e.filterParams=null;e.hoverItem=null;e.currentFocusItem=
null;e.isKeyboardActive=!1;e.allowUpdate=!0;e.avgItemHeight=0;e.blockSize={width:0,height:0};e.clientRect={width:0,height:0};e.contentSize={width:0,height:0};e.currentIndex=0;e.prevIndex=0;e.virtualization=!1;e.visibleRange=1;e.updateTimer=null;e.currentScrollPos={x:0,y:0};e.maxScrollPos={x:0,y:0};e.accelerator=.5;e.isScrollActive=!1;e.isScrollTimerActive=!1;e.prevScrollPos={x:0,y:0};e.scrollBarSize={width:0,height:0};e.scrollCount=0;e.scrollLargeChange={x:0,y:0};e.scrollSize={width:0,height:0};e.scrollTimerID=
null;e.horScrollOrientation=IntegralUIOrientation.Horizontal;e.currentSelectionMode=IntegralUISelectionMode.One;e.shiftFirstSelectedItem=null;e.removeIndex=-1;e.currentSelectedItems=[];e.sortComparer=null;e.refreshTimer=null;e.afterSelect=new EventEmitter;e.beforeEdit=new EventEmitter;e.beforeSelect=new EventEmitter;e.change=new EventEmitter;e.clear=new EventEmitter;e.dragDrop=new EventEmitter;e.dragOver=new EventEmitter;e.itemAdding=new EventEmitter;e.itemAdded=new EventEmitter;e.itemRemoving=new EventEmitter;
e.itemRemoved=new EventEmitter;e.keyDown=new EventEmitter;e.keyPress=new EventEmitter;e.keyUp=new EventEmitter;e.loadComplete=new EventEmitter;e.scrollPosChanged=new EventEmitter;e.selectionChanged=new EventEmitter;e.updateComplete=new EventEmitter;e.updateOptions();return e}Object.defineProperty(IntegralUIBaseList.prototype,"allowDrag",{set:function(a){this.options.allowDrag=a},enumerable:!0,configurable:!0});
Object.defineProperty(IntegralUIBaseList.prototype,"allowDrop",{set:function(a){this.options.allowDrop=a},enumerable:!0,configurable:!0});Object.defineProperty(IntegralUIBaseList.prototype,"allowFilter",{set:function(a){this.options.allowFilter=a},enumerable:!0,configurable:!0});Object.defineProperty(IntegralUIBaseList.prototype,"allowFocus",{set:function(a){this.options.allowFocus=a;a||(this.currentFocusItem=null);this.refresh()},enumerable:!0,configurable:!0});
Object.defineProperty(IntegralUIBaseList.prototype,"focusedItem",{get:function(){return this.currentFocusItem},set:function(a){this.currentFocusItem!=a&&(this.currentFocusItem=a)},enumerable:!0,configurable:!0});Object.defineProperty(IntegralUIBaseList.prototype,"items",{get:function(){return this.dataItems},set:function(a){this.dataItems=a;this.updateData()},enumerable:!0,configurable:!0});
Object.defineProperty(IntegralUIBaseList.prototype,"selectedItem",{get:function(){return this.currentSelection},set:function(a){if(this.currentSelection!=a)var b=this,c=setTimeout(function(){b.processSelection(null,a);clearTimeout(c)},1)},enumerable:!0,configurable:!0});
Object.defineProperty(IntegralUIBaseList.prototype,"selectionMode",{get:function(){return this.currentSelectionMode},set:function(a){if(this.currentSelectionMode!=a){this.currentSelectionMode=a;this.clearPrevSelection(this.currentSelectionMode!=IntegralUISelectionMode.None?this.currentSelection:null);var b=this,c=setTimeout(function(){b.refresh();b.currentSelectionMode==IntegralUISelectionMode.None&&(b.currentSelection=null,b.selectionChanged.emit({item:null}));clearTimeout(c)},1)}},enumerable:!0,
configurable:!0});Object.defineProperty(IntegralUIBaseList.prototype,"sorting",{set:function(a){this.options.sorting=a},enumerable:!0,configurable:!0});Object.defineProperty(IntegralUIBaseList.prototype,"virtualMode",{get:function(){return this.virtualization},set:function(a){this.virtualization=a;this.updateLayout()},enumerable:!0,configurable:!0});
IntegralUIBaseList.prototype.ngOnInit=function(){this.dataService.init([{data:this.items}]);this.itemClassName="iui-list";this.itemContentClassName=this.itemClassName+"-content"};
IntegralUIBaseList.prototype.initStyle=function(){this.defaultStyle={general:{disabled:this.generalClassName+"-disabled",focused:this.generalClassName+"-focused",normal:this.generalClassName,hovered:this.generalClassName+"-hovered",selected:this.generalClassName+"-selected"},item:{general:{disabled:this.itemClassName+"-disabled",focused:this.itemClassName+"-focused",normal:this.itemClassName,hovered:this.itemClassName+"-hovered",selected:this.itemClassName+"-selected"},content:{disabled:this.itemContentClassName+
"-disabled",focused:this.itemContentClassName+"-focused",normal:this.itemContentClassName,hovered:this.itemContentClassName+"-hovered",selected:this.itemContentClassName+"-selected"}}};this.updateStyle(this.controlStyle);this.updateControlClass();this.refresh()};IntegralUIBaseList.prototype.addItem=function(a,b){this.callEventAdd("add",a,-1,b)};
IntegralUIBaseList.prototype.clearItems=function(a){a||(this.currentSelectedItems.length=0,this.currentSelection=null);this.dataService.clear(a);this.clear.emit({parent:a});this.updateLayout()};IntegralUIBaseList.prototype.insertItemAt=function(a,b,c){this.callEventAdd("at",a,b,c)};IntegralUIBaseList.prototype.insertItemBefore=function(a,b){this.callEventAdd("ref",a,-1,null,b)};IntegralUIBaseList.prototype.insertItemAfter=function(a,b){this.callEventAdd("ref",a,-1,null,b,!0)};
IntegralUIBaseList.prototype.removeItem=function(a){return this.callEventRemove(a)};IntegralUIBaseList.prototype.removeItemAt=function(a,b){return this.callEventRemove(null,a,b)};
IntegralUIBaseList.prototype.callEventAdd=function(a,b,c,d,f,g){var h={cancel:!1,item:b};this.itemAdding.emit(h);if(1!=h.cancel){switch(a){case "at":this.dataService.insert(b,c,d);break;case "ref":this.dataService.insertByRef(b,f,g);break;default:this.dataService.insert(b,-1,d)}this.processItemAdd(b,d);this.updateItem(d);this.itemAdded.emit({item:b})}};
IntegralUIBaseList.prototype.callEventRemove=function(a,b,c){var d={cancel:!1,item:a};this.itemRemoving.emit(d);return 1!=d.cancel&&(this.removeIndex=this.items?this.items.indexOf(a):-1,b=this.dataService.removeAt(a,b,c),b.result)?(this.processItemRemoval(a,c),this.itemRemoved.emit({item:b.obj}),!0):!1};IntegralUIBaseList.prototype.processItemAdd=function(a,b){};IntegralUIBaseList.prototype.processItemRemoval=function(a,b){};IntegralUIBaseList.prototype.updateCurrentList=function(){};
IntegralUIBaseList.prototype.updateData=function(){};
IntegralUIBaseList.prototype.updateOptions=function(a){a?this.options={allowDrag:this.commonService.isFieldAvailable(a.allowDrag,!1),allowDrop:this.commonService.isFieldAvailable(a.allowDrop,!0),allowFilter:this.commonService.isFieldAvailable(a.allowFilter,!1),allowFocus:this.commonService.isFieldAvailable(a.allowFocus,!1),dataFields:null,selectedItem:this.commonService.isFieldAvailable(a.selectedItem,this.options.selectedItem?this.options.selectedItem:null)}:(this.options={allowDrag:!1,allowDrop:!0,
allowFilter:!1,allowFocus:!1,dataFields:null,selectedItem:null},this.updateDataFields())};
IntegralUIBaseList.prototype.updateDataFields=function(a){this.options.dataFields=a?{allowDrag:a.allowDrag?a.allowDrag:"allowDrag",allowDrop:a.allowDrop?a.allowDrop:"allowDrop",allowEdit:a.allowEdit?a.allowEdit:"allowEdit",allowFocus:a.allowFocus?a.allowFocus:"allowFocus",autoCheck:a.autoCheck?a.autoCheck:"autoCheck",checkBoxSettings:a.checkBoxSettings?a.checkBoxSettings:"checkBoxSettings",checked:a.checked?a.checked:"checked",checkState:a.checkState?a.checkState:"checkState",content:a.content?a.content:
"content",contextMenu:a.contextMenu?a.contextMenu:"contextMenu",enabled:a.enabled?a.enabled:"enabled",expanded:a.expanded?a.expanded:"expanded",hasChildren:a.hasChildren?a.hasChildren:"hasChildren",icon:a.icon?a.icon:"icon",id:a.id?a.id:"id",items:a.items?a.items:"items",pid:a.pid?a.pid:"pid",selected:a.selected?a.selected:"selected",statusIcon:a.statusIcon?a.statusIcon:"statusIcon",style:a.style?a.style:"style",templateObj:a.templateObj?a.templateObj:"templateObj",text:a.text?a.text:"text",tooltip:a.tooltip?
a.tooltip:"tooltip",value:a.value?a.value:"value",visible:a.visible?a.visible:"visible"}:{allowDrag:"allowDrag",allowDrop:"allowDrop",allowEdit:"allowEdit",allowFocus:"allowFocus",autoCheck:"autoCheck",checkBoxSettings:"checkBoxSettings",checked:"checked",checkState:"checkState",content:"content",contextMenu:"contextMenu",enabled:"enabled",expanded:"expanded",hasChildren:"hasChildren",icon:"icon",id:"id",items:"items",pid:"pid",selected:"selected",statusIcon:"statusIcon",style:"style",templateObj:"templateObj",
text:"text",tooltip:"tooltip",value:"value",visible:"visible"};this.dataService&&this.dataService.updateDataFields(this.options.dataFields)};
IntegralUIBaseList.prototype.processLoadData=function(a,b,c,d){var f=this;f.clearItems(b);f.updateDataFields(c);var g=[];if(a)if(0!=d){var h=[];a.forEach(function(a,b){var c=a[f.options.dataFields.pid];h[c]?(h[c][f.options.dataFields.items]||(h[c][f.options.dataFields.items]=[]),h[a[f.options.dataFields.id]]=a,h[c][f.options.dataFields.items].push(a)):(h[a[f.options.dataFields.id]]=a,g.push(a))});h.length=0}else g=a;if(b)for(b[f.options.dataFields.items]=g,a=0;a<b[f.options.dataFields.items].length;a++)b[f.options.dataFields.items][a][f.options.dataFields.pid]=
b[f.options.dataFields.id];else if(f.items)for(a=f.items.length=0;a<g.length;a++)f.items.push(g[a]);f.updateItem(b);f.loadComplete.emit(null);this.updateLayout()};IntegralUIBaseList.prototype.updateItem=function(a){};IntegralUIBaseList.prototype.updateScrollItemList=function(){this.scrollItemList.length=0};
IntegralUIBaseList.prototype.addDropMark=function(a){this.appRef&&(this.removeDropMark(),a=this.cmpResolver.resolveComponentFactory(IntegralUIDragWindow))&&(this.dragCmpRef=this.appRef.createComponent(a),this.dragCmpRef._component?this.dragCmp=this.dragCmpRef._component:this.dragCmpRef._hostElement&&(this.dragCmp=this.dragCmpRef._hostElement.component))};IntegralUIBaseList.prototype.removeDropMark=function(){this.dragCmpRef&&this.dragCmpRef.destroy();this.dragCmp=null};
IntegralUIBaseList.prototype.callDragDropEvent=function(a,b,c){a={action:b.action,cancel:!1,dragItem:b.source,dropPos:b.dropPos,event:a,isDropAllowed:b.allow,mousePos:this.commonService.getMousePos(a),sourceCtrl:b.sourceCtrl,targetCtrl:b.targetCtrl,targetItem:b.target};c?this.dragDrop.emit(a):this.dragOver.emit(a);return a.cancel};
IntegralUIBaseList.prototype.checkEmptySpace=function(a){var b=this.getContentSize(),c=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild);b=c.top+b.height;c=c.bottom;a=this.commonService.getMousePos(a);var d=this.commonService.getShiftPos();a.x-=d.x;a.y-=d.y;return a.y>=b&&a.y<=c};IntegralUIBaseList.prototype.ctrlDragDrop=function(a){this.processDragDrop(a);a.stopPropagation()};IntegralUIBaseList.prototype.ctrlDragLeave=function(a){this.dropMark(a);this.stopScrollTimer()};
IntegralUIBaseList.prototype.ctrlDragOver=function(a){this.processDragOver(a);a.stopPropagation()};IntegralUIBaseList.prototype.dropMark=function(a,b){this.dragCmp||this.addDropMark({x:a.pageX,y:a.pageY});if(this.dragCmp){var c="none";this.options.allowDrop&&(c=b?"block":"none");this.dragCmp.display=c}};IntegralUIBaseList.prototype.updateDragComponent=function(a){this.dragCmp&&this.dragCmp.updatePos(a)};
IntegralUIBaseList.prototype.isDragAllowed=function(a){return this.options.allowDrag?a&&(a[this.options.dataFields.allowDrag]||void 0===a[this.options.dataFields.allowDrag])?!0:!1:!1};
IntegralUIBaseList.prototype.isDropAllowed=function(a,b,c){var d=this.options.allowDrop;if(d&&a&&b&&(d=b[this.options.dataFields.allowDrop]||void 0===b[this.options.dataFields.allowDrop]?!0:!1))if(Array.isArray(a))for(var f=0;f<a.length;f++){if(this.commonService.isEqual(a[f][this.options.dataFields.id],b[this.options.dataFields.id])||0===c&&this.isParentOf(b,a[f])||this.isChildOf(b,a[f])){d=!1;break}if(!d)break}else if(this.commonService.isEqual(a[this.options.dataFields.id],b[this.options.dataFields.id])||
0===c&&this.isParentOf(b,a)||this.isChildOf(b,a))d=!1;return d};
IntegralUIBaseList.prototype.processDragStart=function(a,b){this.dragDropService.clearData();if(!this.isDragAllowed(b))a.preventDefault();else if(b)if(this.isDragAllowed(b)){this.addDropMark({x:a.pageX,y:a.pageY});a.dataTransfer?(a.dataTransfer.effectAllowed="move",a.dataTransfer.setData("text",b[this.options.dataFields.id]?b[this.options.dataFields.id].toString():"")):a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.effectAllowed="move",a.originalEvent.dataTransfer.setData("text",
b[this.options.dataFields.id]?b[this.options.dataFields.id].toString():""));var c={clone:this.cloneItem(b),source:b,sourceCtrl:this,sourceData:this.items};switch(this.selectionMode){case IntegralUISelectionMode.MultiSimple:c.clone=this.createCloneList(this.currentSelectedItems);c.source=this.currentSelectedItems;break;case IntegralUISelectionMode.MultiExtended:c.clone=this.createCloneList(this.currentSelectedItems),c.source=this.currentSelectedItems}this.dragDropService.setData(c)}else a.dataTransfer?
a.dataTransfer.effectAllowed="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.effectAllowed="none")};
IntegralUIBaseList.prototype.processDragOver=function(a,b,c,d){a.preventDefault();var f=!0;a.dataTransfer?f="none"===a.dataTransfer.effectAllowed?!1:!0:a.originalEvent&&a.originalEvent.dataTransfer&&(f="none"===a.originalEvent.dataTransfer.effectAllowed?!1:!0);if(f){var g=this.dragDropService.getData();f=this.commonService.getShiftPos();if(b){var h=this.commonService.getMousePos(a);h.x-=f.x;h.y-=f.y;h=this.dragDropService.getDropPos(h,c,d);f=this.isDropAllowed(g.source,b,h);c={action:a.shiftKey?"copy":
"move",source:g.source,dropPos:h,allow:f,sourceCtrl:g.sourceCtrl,target:b,targetCtrl:this};c=this.callDragDropEvent(a,c);if(f&&1!=c){d=this.commonService.getMousePos(a);c=d.y+16;d=d.x+20;var e="iui-dragwin-icon";switch(h){case 0:e+=" iui-dragwin-move-in";break;case 1:e+=" iui-dragwin-move-up";break;case 2:e+=" iui-dragwin-move-down"}a.shiftKey&&(e+="-copy");this.updateDragComponent({"class":e,top:c,left:d,text:b[this.options.dataFields.text]});this.dropMark(a,f);this.dragDropService.setData({action:a.shiftKey?
"copy":"move",source:g.source,sourceData:g.sourceData,target:b,targetCtrl:this,dropPos:h})}else a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a)}else this.options.allowDrop?(f=this.checkEmptySpace(a),c={action:a.shiftKey?"copy":"move",source:g.source,dropPos:-1,allow:f,sourceCtrl:g.sourceCtrl,target:null,targetCtrl:this},c=this.callDragDropEvent(a,c),f&&1!=c?(h=this.commonService.getMousePos(a),
c=h.y+16,d=h.x+20,e="iui-dragwin-icon iui-dragwin-move-end",a.shiftKey&&(e+="-copy"),this.updateDragComponent({"class":e,top:c,left:d,text:this.name?this.name:"Component"}),this.dropMark(a,f),this.dragDropService.setData({action:a.shiftKey?"copy":"move",source:g.source,sourceData:g.sourceData,target:null,targetCtrl:this,dropPos:-1})):(a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a))):(a.dataTransfer?
a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a))}};
IntegralUIBaseList.prototype.processDragDrop=function(a,b){a.preventDefault();this.dropMark(a);var c=!0;a.dataTransfer?c="none"===a.dataTransfer.effectAllowed?!1:!0:a.originalEvent&&a.originalEvent.dataTransfer&&(c="none"===a.originalEvent.dataTransfer.effectAllowed?!1:!0);if(c){var d=this.dragDropService.getData();(c=b?this.isDropAllowed(d.source,b,d.dropPos):this.checkEmptySpace(a))&&d.source&&(this.callDragDropEvent(a,{action:a.shiftKey?"copy":"move",source:d.source,dropPos:d.dropPos,allow:c,sourceCtrl:d.sourceCtrl,
target:d.target,targetCtrl:this},!0)||this.drop(a,d))}this.dragDropService.clearData()};
IntegralUIBaseList.prototype.drop=function(a,b){if(b&&b.sourceCtrl){var c=a.shiftKey&&b.clone?b.clone:b.source;if(Array.isArray(c)){for(var d=[],f=0;f<c.length;f++)d.push(c[f]);if(0<d.length){for(f=0;f<d.length;f++)this.processDataDrop(a,d[f],b);this.clearPrevSelection(d[d.length-1])}}else this.processDataDrop(a,c,b),this.clearPrevSelection(c);b.sourceCtrl!=b.targetCtrl&&b.sourceCtrl.updateLayout&&b.sourceCtrl.updateLayout();this.updateLayout()}};
IntegralUIBaseList.prototype.processDataDrop=function(a,b,c){var d=a.shiftKey;!a.shiftKey&&c.sourceCtrl&&c.sourceCtrl.removeItem&&(d=c.sourceCtrl.removeItem(b));if(d)switch(c.dropPos){case 0:this.insertItemAt(b,-1,c.target);break;case 1:this.insertItemBefore(b,c.target);break;case 2:this.insertItemAfter(b,c.target);break;default:this.addItem(b)}};IntegralUIBaseList.prototype.callAfterSelectEvent=function(a){a={item:a};this.afterSelect.emit(a);this.selectionChanged.emit(a)};
IntegralUIBaseList.prototype.itemDragStart=function(a,b){this.processDragStart(a,b.data);a.stopPropagation()};IntegralUIBaseList.prototype.itemDragOver=function(a,b,c,d){var f=this.getItemElemList();f&&0<=c&&c<f.length&&(c=this.commonService.getPageRect(f[c].nativeElement),c={x:c.left,y:c.top,width:c.right-c.left,height:c.bottom-c.top},this.processScroll(a),this.processDragOver(a,b.data,c,d));a.stopPropagation()};
IntegralUIBaseList.prototype.itemDragDrop=function(a,b){this.processDragDrop(a,b.data);a.stopPropagation()};IntegralUIBaseList.prototype.filter=function(a){this.filterParams=a;this.updateLayout();this.change.emit({type:"filtering"})};IntegralUIBaseList.prototype.cloneItem=function(a){return this.dataService.clone(a)};IntegralUIBaseList.prototype.createCloneList=function(a){for(var b=[],c=0;c<a.length;c++)b.push(this.cloneItem(a[c]));return b};
IntegralUIBaseList.prototype.getFilterTree=function(a){return a?this.filterService.createTree(a.conditions,a.formula):null};IntegralUIBaseList.prototype.getObjFromItem=function(a){for(var b=null,c=0;c<this.currentList.length;c++)if(this.currentList[c].data==a){b=this.currentList[c];break}return b};IntegralUIBaseList.prototype.getObjFromScrollItem=function(a){for(var b=null,c=0;c<this.scrollItemList.length;c++){var d=this.scrollItemList[c];if(d.data==a){b=d;break}}return b};
IntegralUIBaseList.prototype.getItemCurrentIndex=function(a){if(a)return(a=this.getObjFromItem(a))&&this.currentList?this.currentList.indexOf(a):-1};IntegralUIBaseList.prototype.getItemElemList=function(){return null};IntegralUIBaseList.prototype.getItemFromComponent=function(a){return null};IntegralUIBaseList.prototype.getList=function(a){switch(a){case "selected":return this.currentSelectedItems}return this.dataService.getList()};
IntegralUIBaseList.prototype.invokeMethod=function(a,b){var c=!0;if(b)switch(a){case "SELECT_ITEM":c=this.processSelection(b.event,b.item);break;case "UPDATE_SELECTION":this.updateSelection(b.event,b.item)}return c};IntegralUIBaseList.prototype.isChildOf=function(a,b){return!1};IntegralUIBaseList.prototype.isComponentIndexInRange=function(a){return this.itemList?0<=a&&a<this.itemList.length:!1};
IntegralUIBaseList.prototype.isIndexInRange=function(a){return this.currentList?0<=a&&a<this.currentList.length:!1};
IntegralUIBaseList.prototype.isItemAllowed=function(a){if(0==a[this.options.dataFields.visible])return!1;if(0==this.options.allowFilter)return!0;var b=!0;a&&this.filterParams&&(b=(b=a[this.options.dataFields.value])?b:a[this.options.dataFields.text],this.filterParams.callback?b=this.filterParams.callback(b,a):(b=this.filterService.match(b,this.filterParams.conditions,this.filterParams.formula,this.getFilterTree(this.filterParams),this.filterParams.caseSensitive),!b&&this.filterParams.allowParent&&
(b=this.filterIsThereChildren(a))));return b};IntegralUIBaseList.prototype.filterIsThereChildren=function(a){var b=!1;if(a=a[this.options.dataFields.items])for(var c=0;c<a.length&&!(b=this.isItemAllowed(a[c]));c++);return b};IntegralUIBaseList.prototype.isItemEnabled=function(a){return!0};IntegralUIBaseList.prototype.isItemHovered=function(a){return a&&a==this.hoverItem?!0:!1};IntegralUIBaseList.prototype.isItemSelected=function(a){return a&&1==a[this.options.dataFields.selected]?!0:!1};
IntegralUIBaseList.prototype.isParentOf=function(a,b){return!1};IntegralUIBaseList.prototype.updateItemList=function(){};IntegralUIBaseList.prototype.itemMouseEnter=function(a,b){this.isScrollActive||(this.hoverItem=b.data,this.updateItemStyle(b))};IntegralUIBaseList.prototype.itemMouseLeave=function(a,b){this.isScrollActive||(this.hoverItem=null,this.updateItemStyle(b))};IntegralUIBaseList.prototype.itemGotFocus=function(a){this.refresh()};IntegralUIBaseList.prototype.itemLostFocus=function(a){this.refresh()};
IntegralUIBaseList.prototype.itemKeyDown=function(a,b){var c={cancel:!1,item:b.data,event:a};this.keyDown.emit(c);switch(a.keyCode){case 13:this.beforeEdit.emit(c);break;case 33:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processPageUpKey(b));break;case 34:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processPageDownKey(b));break;case 35:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,
this.processEndKey(b));break;case 36:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processHomeKey(b));break;case 37:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processLeftArrowKey(b));break;case 38:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processUpArrowKey(b));break;case 39:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processRightArrowKey(b));
break;case 40:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processDownArrowKey(b))}};IntegralUIBaseList.prototype.itemKeyPress=function(a,b){this.keyPress.emit({cancel:!1,item:b.data,event:a})};IntegralUIBaseList.prototype.itemKeyUp=function(a,b){this.keyUp.emit({cancel:!1,item:b.data,event:a})};
IntegralUIBaseList.prototype.processDownArrowKey=function(a,b){var c=this.getDownItem(a);if(c){this.currentFocusItem=c.data;var d=this,f=setTimeout(function(){d.processSelection(b,c.data);clearTimeout(f)},1);this.isLastItem(c)&&this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y+2*this.avgItemHeight})}return c};
IntegralUIBaseList.prototype.processEndKey=function(a,b){var c=null;if(0<this.scrollItemList.length){this.scrollPos({x:this.currentScrollPos.x,y:this.maxScrollPos.y});var d=this;setTimeout(function(){c=d.scrollItemList[d.scrollItemList.length-1];d.currentFocusItem=c.data;var a=setTimeout(function(){d.processSelection(b,c.data);clearTimeout(a)},1)},1)}return c};
IntegralUIBaseList.prototype.processHomeKey=function(a,b){var c=null;if(0<this.scrollItemList.length){this.scrollPos({x:this.currentScrollPos.x,y:0});var d=this;setTimeout(function(){c=d.scrollItemList[0];d.currentFocusItem=c.data;var a=setTimeout(function(){d.processSelection(b,c.data);clearTimeout(a)},1)},1)}return c};IntegralUIBaseList.prototype.processLeftArrowKey=function(a,b){return null};
IntegralUIBaseList.prototype.processPageDownKey=function(a,b){var c=null;if(0<this.scrollItemList.length){this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y+this.avgItemHeight*(this.scrollItemList.length-1)});var d=this;setTimeout(function(){var f=0<=a.index&&a.index<d.scrollItemList.length?a.index:d.scrollItemList.length-1;d.currentScrollPos.y==d.maxScrollPos.y&&(f=d.scrollItemList.length-1);c=d.scrollItemList[f];d.currentFocusItem=c.data;var g=setTimeout(function(){d.processSelection(b,
c.data);clearTimeout(g)},1)},1)}return c};
IntegralUIBaseList.prototype.processPageUpKey=function(a,b){var c=null;if(0<this.scrollItemList.length){this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y-this.avgItemHeight*(this.scrollItemList.length-1)});var d=this;setTimeout(function(){var f=0<=a.index&&a.index<d.scrollItemList.length?a.index:0;0==d.currentScrollPos.y&&(f=0);c=d.scrollItemList[f];d.currentFocusItem=c.data;var g=setTimeout(function(){d.processSelection(b,c.data);clearTimeout(g)},1)},1)}return c};
IntegralUIBaseList.prototype.processRightArrowKey=function(a,b){return null};IntegralUIBaseList.prototype.processUpArrowKey=function(a,b){var c=this.getUpItem(a);if(c){this.currentFocusItem=c.data;var d=this,f=setTimeout(function(){d.processSelection(b,c.data);clearTimeout(f)},1);this.isFirstItem(c)&&this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y-this.avgItemHeight})}return c};
IntegralUIBaseList.prototype.getDownItem=function(a){a=0<=a.index&&a.index<this.scrollItemList.length-1?a.index+1:-1;return 0<=a?this.scrollItemList[a]:null};IntegralUIBaseList.prototype.getUpItem=function(a){a=0<a.index?a.index-1:-1;return 0<=a?this.scrollItemList[a]:null};IntegralUIBaseList.prototype.isFirstItem=function(a){return 0==a.index?!0:!1};IntegralUIBaseList.prototype.isLastItem=function(a){return a.index==this.scrollItemList.length-2?!0:!1};
IntegralUIBaseList.prototype.moveFocusFromItem=function(a,b){if(!this.options.allowFocus)return null;var c=null,d=this.getObjFromScrollItem(a);if(d)switch(b){case "down":c=this.processDownArrowKey(d);break;case "end":c=this.processEndKey(d);break;case "home":c=this.processHomeKey(d);break;case "left":c=this.processLeftArrowKey(d);break;case "pagedown":c=this.processPageDownKey(d);break;case "pageup":c=this.processPageUpKey(d);break;case "right":c=this.processRightArrowKey(d);break;case "up":c=this.processUpArrowKey(d)}return c?
c.data:null};IntegralUIBaseList.prototype.onWindowKeyDown=function(a){this.isKeyboardActive&&a.preventDefault()};IntegralUIBaseList.prototype.onWindowKeyUp=function(a){this.isKeyboardActive=!1};IntegralUIBaseList.prototype.getContentSize=function(){return{width:0,height:0}};
IntegralUIBaseList.prototype.refresh=function(){this.updateItemList();this.clearComponentSelection();for(var a=0;a<this.currentSelectedItems.length;a++){var b=this.getItemCurrentIndex(this.currentSelectedItems[a]);this.isComponentIndexInRange(b)&&(this.itemList[b].state|=IntegralUIObjectState.selected)}};IntegralUIBaseList.prototype.updateBlockSize=function(){this.blockSize={width:0,height:0}};
IntegralUIBaseList.prototype.resetLayout=function(){this.updateTimer&&clearTimeout(this.updateTimer);this.updateTimer=null};IntegralUIBaseList.prototype.suspendLayout=function(){this.allowUpdate=!1};IntegralUIBaseList.prototype.resumeLayout=function(){this.allowUpdate=!0;this.updateLayout()};
IntegralUIBaseList.prototype.updateLayout=function(){var a=this;a.allowUpdate&&(a.updateTimer=setTimeout(function(){a.updateCurrentList();a.clientRect={width:a.elemRef.nativeElement.firstElementChild.clientWidth,height:a.elemRef.nativeElement.firstElementChild.clientHeight};a.virtualMode&&a.updateScrollItemList();var b=setTimeout(function(){a.updateVisibleRange();a.virtualMode&&a.updateScrollItemList();var c=setTimeout(function(){a.updateBlockSize();var b=a.getItemElemList();a.avgItemHeight=0;if(b&&
0<b.length){for(var f=0,g=0;g<b.length;g++)f+=b[g].nativeElement.offsetHeight;a.avgItemHeight=Math.floor(f/b.length)}a.updateScrollSize();a.refresh();a.updateComplete.emit(null);clearTimeout(c)},1);clearTimeout(b)},1);clearTimeout(a.updateTimer)},100))};
IntegralUIBaseList.prototype.updateScrollSize=function(){this.contentSize={width:this.clientRect.width-2,height:this.clientRect.height-2};this.scrollSize={width:0,height:this.avgItemHeight*this.currentList.length-this.clientRect.height+this.avgItemHeight};this.isVerScrollVisible()&&(this.contentSize.width-=18,0<this.scrollSize.width&&(this.scrollSize.width+=16));this.isHorScrollVisible()&&(this.scrollSize.height+=16);this.scrollSize.width=0<this.scrollSize.width?this.scrollSize.width:0;this.scrollSize.height=
0<this.scrollSize.height?this.scrollSize.height:0;this.maxScrollPos={x:this.scrollSize.width,y:this.scrollSize.height};this.currentScrollPos.x>this.maxScrollPos.x&&this.changeHorizontalScrollPos(this.maxScrollPos.x);this.currentScrollPos.y>this.maxScrollPos.y&&this.changeVerticalScrollPos(this.maxScrollPos.y);this.scrollBarSize={width:this.isVerScrollVisible()?this.clientRect.width-20:this.clientRect.width-4,height:this.isHorScrollVisible()?this.clientRect.height-20:this.clientRect.height-4};this.scrollLargeChange=
{x:this.scrollBarSize.width,y:this.scrollBarSize.height}};IntegralUIBaseList.prototype.updateVisibleRange=function(){this.visibleRange=1;var a=this.getItemElemList();if(a&&0<a.length){for(var b=0,c=0;c<a.length;c++)b+=a[c].nativeElement.offsetHeight;a=Math.floor(b/a.length);0<a&&(this.visibleRange=Math.floor(this.clientRect.height/a)+1)}};
IntegralUIBaseList.prototype.updateView=function(){this.currentIndex=0<this.avgItemHeight?Math.floor(this.currentScrollPos.y/this.avgItemHeight):0;this.currentIndex!=this.prevIndex&&(this.updateScrollItemList(),this.prevIndex=this.currentIndex)};IntegralUIBaseList.prototype.updateCloneElemPos=function(a){1==a.buttons&&this.cloneElem&&(this.cloneElem.style.top=a.pageY-this.cloneElemStartPos.y+"px",this.cloneElem.style.left=a.pageX-this.cloneElemStartPos.x+"px")};
IntegralUIBaseList.prototype.onCtrlMouseEnter=function(a){1==a.buttons&&this.cloneElem&&(this.cloneElem.style.display="block");this.elemRenderer.setElementStyle(this.elemRef.nativeElement,"cursor","default")};IntegralUIBaseList.prototype.onCtrlMouseLeave=function(a){1==a.buttons&&this.cloneElem&&(this.cloneElem.style.display="none");this.stopScrollTimer()};IntegralUIBaseList.prototype.setCloneElem=function(a,b){this.cloneElem&&this.closeCloneElem();this.cloneElem=a;this.cloneElemStartPos=b};
IntegralUIBaseList.prototype.appendCloneElem=function(){document.body.appendChild(this.cloneElem)};IntegralUIBaseList.prototype.closeCloneElem=function(){var a=this;a.elemRenderer.setElementStyle(a.elemRef.nativeElement,"cursor","default");setTimeout(function(){a.cloneElem&&(document.body.removeChild(a.cloneElem),a.cloneElem=null)},10)};IntegralUIBaseList.prototype.itemMouseDown=function(a,b){this.options.allowFocus&&1==a.buttons&&(this.currentFocusItem=b.data);this.processSelection(a,b.data);a.stopPropagation()};
IntegralUIBaseList.prototype.itemMouseUp=function(a,b){this.updateSelection(a,b.data)};IntegralUIBaseList.prototype.itemClickEvent=function(a,b){a.stopPropagation()};IntegralUIBaseList.prototype.itemDblClickEvent=function(a,b){a.stopPropagation()};IntegralUIBaseList.prototype.onScroll=function(a){a.target&&(this.virtualMode?(a.target.scrollTop=0,a.target.scrollLeft=0):this.scrollPos({x:a.target.scrollLeft,y:a.target.scrollTop}))};
IntegralUIBaseList.prototype.scrollPos=function(a){if(0!=this.virtualMode)return a&&(this.currentScrollPos={x:Math.max(0,Math.min(a.x,this.maxScrollPos.x)),y:Math.max(0,Math.min(a.y,this.maxScrollPos.y))},this.scrollPosChanged.emit({value:this.currentScrollPos})),{x:Math.floor(this.currentScrollPos.x),y:Math.floor(this.currentScrollPos.y)};if(this.elemRef){var b=this.elemRef.nativeElement.firstElementChild.scrollWidth,c=this.elemRef.nativeElement.firstElementChild.scrollHeight;this.maxScrollPos={x:b>
this.elemRef.nativeElement.firstElementChild.clientWidth?b-this.elemRef.nativeElement.firstElementChild.clientWidth:0,y:c>this.elemRef.nativeElement.firstElementChild.clientHeight?c-this.elemRef.nativeElement.firstElementChild.clientHeight:0};a?(this.currentScrollPos.x=Math.max(0,Math.min(a.x,this.maxScrollPos.x)),this.currentScrollPos.y=Math.max(0,Math.min(a.y,this.maxScrollPos.y)),this.elemRef.nativeElement.firstElementChild.scrollLeft=this.currentScrollPos.x,this.elemRef.nativeElement.firstElementChild.scrollTop=
this.currentScrollPos.y,this.scrollPosChanged.emit({value:this.currentScrollPos})):(this.currentScrollPos.x=Math.max(0,Math.min(this.elemRef.nativeElement.firstElementChild.scrollLeft,this.maxScrollPos.x)),this.currentScrollPos.y=Math.max(0,Math.min(this.elemRef.nativeElement.firstElementChild.scrollTop,this.maxScrollPos.y)))}return this.currentScrollPos};
IntegralUIBaseList.prototype.changeHorizontalScrollPos=function(a){this.currentScrollPos.x=Math.max(0,Math.min(a,this.maxScrollPos.x));this.currentScrollPos.x!=this.prevScrollPos.x&&(this.scrollPosChanged.emit({value:this.scrollPos()}),this.prevScrollPos.x=this.currentScrollPos.x)};
IntegralUIBaseList.prototype.changeVerticalScrollPos=function(a){this.currentScrollPos.y=Math.max(0,Math.min(a,this.maxScrollPos.y));this.currentScrollPos.y!=this.prevScrollPos.y&&(this.updateView(),this.scrollPosChanged.emit({value:this.scrollPos()}),this.prevScrollPos.y=this.currentScrollPos.y)};
IntegralUIBaseList.prototype.processMouseWheel=function(a,b){if(0!=this.virtualMode){a.preventDefault();this.hoverItem=null;var c=0;a.wheelDelta?c=Math.max(-1,Math.min(1,a.wheelDelta||-a.detail)):a.originalEvent&&(c=Math.max(-1,Math.min(1,a.originalEvent.wheelDelta||-a.originalEvent.detail)));if(this.isVerScrollVisible()){var d=Math.floor(this.clientRect.height/4);c=this.currentScrollPos.y+d*c*-1;this.changeVerticalScrollPos(c)}else b&&this.isHorScrollVisible()&&(d=Math.floor(this.clientRect.width/
4),c=this.currentScrollPos.x+d*c*-1,this.changeHorizontalScrollPos(c));a.stopPropagation()}};IntegralUIBaseList.prototype.isVerScrollVisible=function(){return 0<this.scrollSize.height?!0:!1};IntegralUIBaseList.prototype.isHorScrollVisible=function(){return 0<this.scrollSize.width?!0:!1};IntegralUIBaseList.prototype.onVerticalScrollStart=function(a){this.hoverItem=null;this.isScrollActive=!0};IntegralUIBaseList.prototype.onVerticalScrollEnd=function(a){this.isScrollActive=!1};
IntegralUIBaseList.prototype.onVerticalScrollChanged=function(a){this.changeVerticalScrollPos(a.value)};IntegralUIBaseList.prototype.onHorizontalScrollStart=function(a){this.hoverItem=null;this.isScrollActive=!0};IntegralUIBaseList.prototype.onHorizontalScrollEnd=function(a){this.isScrollActive=!1};IntegralUIBaseList.prototype.onHorizontalScrollChanged=function(a){this.currentScrollPos.x=a.value;this.scrollPosChanged.emit({value:this.scrollPos()})};
IntegralUIBaseList.prototype.processScroll=function(a){if(this.isVerScrollVisible()){var b=this.commonService.getShiftPos();a=this.commonService.getMousePos(a);a.x-=b.x;a.y-=b.y;var c=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild);b=c.top+25;c=c.bottom-25;this.isHorScrollVisible()&&(c-=16);a.y<b?this.startScrollTimer(!1):a.y>c?this.startScrollTimer(!0):this.stopScrollTimer()}else this.stopScrollTimer()};
IntegralUIBaseList.prototype.startScrollTimer=function(a,b){var c=this;c.isScrollTimerActive||(c.accelerator=.5,c.scrollCount=0,c.isScrollTimerActive=!0,c.scrollTimerID||(c.scrollTimerID=setInterval(function(){c.scrollTimerElapsed(a)},b?b:100)))};IntegralUIBaseList.prototype.stopScrollTimer=function(){this.scrollTimerID&&(clearInterval(this.scrollTimerID),this.scrollTimerID=null);this.accelerator=.5;this.scrollCount=0;this.isScrollTimerActive=!1};
IntegralUIBaseList.prototype.scrollTimerElapsed=function(a){var b=this.currentScrollPos;0===this.scrollCount&&(this.scrollCount=5);this.scrollCount+=5;this.accelerator+=.5;var c=this.scrollCount+=Math.floor(this.accelerator);this.currentScrollPos.y=a?this.currentScrollPos.y+c>this.maxScrollPos.y?this.maxScrollPos.y:this.currentScrollPos.y+c:0>this.currentScrollPos.y-c?0:this.currentScrollPos.y-c;(0>=b.y||this.currentScrollPos.y<b.y)&&this.stopScrollTimer()};
IntegralUIBaseList.prototype.scrollTo=function(a){0!=this.virtualMode&&a&&(a=this.getItemCurrentIndex(a),0<=a&&this.scrollPos({x:this.currentScrollPos.x,y:this.avgItemHeight*(a+this.visibleRange/2)}),this.updateLayout())};IntegralUIBaseList.prototype.findItemById=function(a){return this.dataService.findObjectById(a)};IntegralUIBaseList.prototype.findItemByText=function(a){return this.dataService.findObjectByText(a)};
IntegralUIBaseList.prototype.clearSelection=function(){this.clearPrevSelection();this.refresh()};IntegralUIBaseList.prototype.clearComponentSelection=function(){this.itemList.forEach(function(a){return a.state&=~IntegralUIObjectState.selected})};
IntegralUIBaseList.prototype.clearPrevSelection=function(a){for(var b=0;b<this.currentSelectedItems.length;b++)a&&!this.commonService.isEqual(this.currentSelectedItems[b][this.options.dataFields.id],a[this.options.dataFields.id])?this.currentSelectedItems[b][this.options.dataFields.selected]=!1:a||(this.currentSelectedItems[b][this.options.dataFields.selected]=!1);this.currentSelectedItems.length=0;a&&this.isItemEnabled(a)&&this.currentSelectedItems.push(a)};
IntegralUIBaseList.prototype.isItemInSelectionList=function(a){var b=!1,c=this.currentSelectedItems;if(a&&c)for(var d=0;d<c.length;d++)if(this.commonService.isEqual(c[d][this.options.dataFields.id],a[this.options.dataFields.id])){b=!0;break}return b};
IntegralUIBaseList.prototype.processSelection=function(a,b,c){var d=!0;if(b){if(this.selectionMode==IntegralUISelectionMode.None)return;var f=0<this.currentSelectedItems.length;if(this.isItemEnabled(b)){var g=this.currentSelection,h=!0;g&&(h=a&&(a.ctrlKey||a.metaKey)||!this.commonService.isEqual(g[this.options.dataFields.id],b[this.options.dataFields.id])||0==g[this.options.dataFields.selected]);var e={cancel:!1,item:b};this.beforeSelect.emit(e);d=1==e.cancel?!1:!0;if(1!=e.cancel)if(e=a&&(a.shiftKey||
a.ctrlKey||a.metaKey)?!0:!1,h){this.selectionMode==IntegralUISelectionMode.MultiExtended&&(h=!this.isItemInSelectionList(b)||!e||a&&a.shiftKey);h&&(this.selectionMode==IntegralUISelectionMode.One?this.clearPrevSelection():a&&a.shiftKey?this.clearPrevSelection():e||this.selectionMode==IntegralUISelectionMode.MultiSimple||1!=this.currentSelectedItems.length&&this.isItemInSelectionList(b)||this.clearPrevSelection());this.currentSelection=b;if(a&&a.shiftKey&&this.selectionMode!=IntegralUISelectionMode.One){if(this.shiftFirstSelectedItem||
(this.shiftFirstSelectedItem=g),a=this.getItemCurrentIndex(this.shiftFirstSelectedItem),c=this.getItemCurrentIndex(b),a>c&&(f=a,a=c,c=f),this.isIndexInRange(a)&&this.isIndexInRange(c))for(;a<=c;a++)this.currentList[a].data[this.options.dataFields.selected]=!0,this.currentSelectedItems.push(this.currentList[a].data)}else e||this.selectionMode==IntegralUISelectionMode.MultiSimple?(a=null==b[this.options.dataFields.selected]||"undefined"==b[this.options.dataFields.selected]?!1:b[this.options.dataFields.selected],
b[this.options.dataFields.selected]=!a,b[this.options.dataFields.selected]?this.isItemInSelectionList(b)||this.currentSelectedItems.push(b):this.currentSelectedItems=this.currentSelectedItems.filter(function(a){return a!=b})):(b[this.options.dataFields.selected]=!0,this.isItemInSelectionList(b)||this.currentSelectedItems.push(b)),this.shiftFirstSelectedItem=null;this.callAfterSelectEvent(b);this.refresh()}else e||this.selectionMode==IntegralUISelectionMode.MultiSimple?(a=null===b[this.options.dataFields.selected]||
"undefined"==b[this.options.dataFields.selected]?!1:b[this.options.dataFields.selected],c&&"undefined"!=c&&(a=c),b[this.options.dataFields.selected]=!a,b[this.options.dataFields.selected]?this.isItemInSelectionList(b)||this.currentSelectedItems.push(b):this.currentSelectedItems=this.currentSelectedItems.filter(function(a){return a!=b}),this.shiftFirstSelectedItem=null,this.callAfterSelectEvent(b),this.refresh()):e||this.selectionMode&IntegralUISelectionMode.MultiSimple||1!=this.currentSelectedItems.length&&
this.isItemInSelectionList(b)||(this.shiftFirstSelectedItem=null,this.clearPrevSelection(b),this.refresh(),h&&f&&this.selectionChanged.emit({item:null}))}else this.clearPrevSelection(),this.refresh(),f&&this.selectionChanged.emit({item:null})}return d};
IntegralUIBaseList.prototype.selectItems=function(a){if(a&&Array.isArray(a)){for(var b=this.currentSelectedItems.length=0;b<a.length;b++)a[b][this.options.dataFields.selected]=!0,this.currentSelectedItems.push(a[b]);0<a.length?(this.currentSelection=a[a.length-1],this.callAfterSelectEvent(this.currentSelection)):this.currentSelection=null;this.refresh()}};
IntegralUIBaseList.prototype.updateSelection=function(a,b){var c=a&&(a.shiftKey||a.ctrlKey||a.metaKey)?!0:!1;this.selectionMode==IntegralUISelectionMode.MultiExtended&&0<this.currentSelectedItems.length&&!a.shiftKey&&!c&&1==a.which&&(this.clearPrevSelection(),b[this.options.dataFields.selected]=!0,this.currentSelectedItems.push(b),this.callAfterSelectEvent(b),this.refresh())};
IntegralUIBaseList.prototype.applySorting=function(a){var b=this;a&&(b.sortComparer?a.sort(b.sortComparer):b.isSortingAllowed()&&a.sort(function(a,d){var c,g;(c=a[b.options.dataFields.value])||(c=a[b.options.dataFields.text]);b.commonService.isObject(c)&&(c=c.value?c.value:c.text);(g=d[b.options.dataFields.value])||(g=d[b.options.dataFields.text]);b.commonService.isObject(g)&&(g=g.value?g.value:g.text);c=void 0!=c?c:null;g=void 0!=g?g:null;switch(b.options.sorting){case IntegralUISortOrder.Ascending:if(c<
g)return-1;if(c>g)return 1;break;case IntegralUISortOrder.Descending:if(c>g)return-1;if(c<g)return 1;break;default:return 0}}))};IntegralUIBaseList.prototype.isSortingAllowed=function(){return this.options.sorting==IntegralUISortOrder.Ascending||this.options.sorting==IntegralUISortOrder.Descending};IntegralUIBaseList.prototype.sort=function(a,b){this.options.sorting=a;this.sortComparer=b?b:null;this.updateLayout();this.change.emit({type:"sorting"})};
IntegralUIBaseList.prototype.updateItemStyle=function(a){a&&(a.style={general:[],content:[]},a.style.general.push(this.itemClassName),a.style.general.push(this.options.currentStyle.item.general.normal),a.style.content.push(this.itemContentClassName),a.style.content.push(this.options.currentStyle.item.content.normal),this.isItemEnabled(a.data)?this.isItemSelected(a.data)?(a.style.general.push(this.options.currentStyle.item.general.selected),a.style.content.push(this.options.currentStyle.item.content.selected)):
this.isItemHovered(a.data)&&(a.style.general.push(this.options.currentStyle.item.general.hovered),a.style.content.push(this.options.currentStyle.item.content.hovered)):(a.style.general.push(this.options.currentStyle.item.general.disabled),a.style.content.push(this.options.currentStyle.item.content.disabled)),a.data==this.currentFocusItem&&a.style.general.push(this.options.currentStyle.item.general.focused))};
IntegralUIBaseList.prototype.getItemStyle=function(a){return a?{general:this.getItemGeneralStyle(a.general),content:this.getItemContentStyle(a.content)}:this.getDefaultItemStyle()};
IntegralUIBaseList.prototype.getItemGeneralStyle=function(a){return this.commonService.isString(a)?a:a?{disabled:this.commonService.isFieldAvailable(a.disabled,this.itemClassName+"-disabled"),focused:this.commonService.isFieldAvailable(a.focused,this.itemClassName+"-focused"),normal:this.commonService.isFieldAvailable(a.normal,this.itemClassName),hovered:this.commonService.isFieldAvailable(a.hovered,this.itemClassName+"-hovered"),selected:this.commonService.isFieldAvailable(a.selected,this.itemClassName+
"-selected")}:this.getDefaultItemGeneralStyle()};
IntegralUIBaseList.prototype.getItemContentStyle=function(a){return this.commonService.isString(a)?a:a?{disabled:this.commonService.isFieldAvailable(a.disabled,this.itemContentClassName+"-disabled"),focused:this.commonService.isFieldAvailable(a.focused,this.itemContentClassName+"-focused"),normal:this.commonService.isFieldAvailable(a.normal,this.itemContentClassName),hovered:this.commonService.isFieldAvailable(a.hovered,this.itemContentClassName+"-hovered"),selected:this.commonService.isFieldAvailable(a.selected,
this.itemContentClassName+"-selected")}:this.getDefaultItemContentStyle()};IntegralUIBaseList.prototype.getDefaultListStyle=function(){return{general:this.getDefaultGeneralStyle(),item:this.getDefaultItemStyle()}};IntegralUIBaseList.prototype.getDefaultItemStyle=function(){return{general:this.getDefaultItemGeneralStyle(),content:this.getDefaultItemContentStyle()}};
IntegralUIBaseList.prototype.getDefaultItemGeneralStyle=function(){return{disabled:this.defaultStyle.item.general.disabled,focused:this.defaultStyle.item.general.focused,normal:this.defaultStyle.item.general.normal,hovered:this.defaultStyle.item.general.hovered,selected:this.defaultStyle.item.general.selected}};
IntegralUIBaseList.prototype.getDefaultItemContentStyle=function(){return{disabled:this.defaultStyle.item.content.disabled,focused:this.defaultStyle.item.content.focused,normal:this.defaultStyle.item.content.normal,hovered:this.defaultStyle.item.content.hovered,selected:this.defaultStyle.item.content.selected}};IntegralUIBaseList.prototype.updateStyle=function(a){this.options.currentStyle=a?{general:this.getGeneralStyle(a.general),item:this.getItemStyle(a.item)}:this.getDefaultListStyle()};    return IntegralUIBaseList;
}(IntegralUIBaseComponent));
export { IntegralUIBaseList };
IntegralUIBaseList.decorators = [
    { type: Component, args: [{
                selector: 'iui-baselist',
                template: '',
                providers: [IntegralUIDataService]
            },] },
];
/** @nocollapse */
IntegralUIBaseList.ctorParameters = function () { return [
    { type: IntegralUIDataService, },
    { type: IntegralUIDragDropService, },
    { type: ElementRef, },
    { type: Renderer, },
    { type: IntegralUICommonService, },
    { type: IntegralUIFilterService, },
    { type: ComponentFactoryResolver, },
]; };
IntegralUIBaseList.propDecorators = {
    'appRef': [{ type: Input },],
    'allowDrag': [{ type: Input },],
    'allowDrop': [{ type: Input },],
    'allowFilter': [{ type: Input },],
    'allowFocus': [{ type: Input },],
    'focusedItem': [{ type: Input },],
    'items': [{ type: Input },],
    'selectedItem': [{ type: Input },],
    'selectionMode': [{ type: Input },],
    'sorting': [{ type: Input },],
    'virtualMode': [{ type: Input },],
    'afterSelect': [{ type: Output },],
    'beforeEdit': [{ type: Output },],
    'beforeSelect': [{ type: Output },],
    'change': [{ type: Output },],
    'clear': [{ type: Output },],
    'dragDrop': [{ type: Output },],
    'dragOver': [{ type: Output },],
    'itemAdding': [{ type: Output },],
    'itemAdded': [{ type: Output },],
    'itemRemoving': [{ type: Output },],
    'itemRemoved': [{ type: Output },],
    'keyDown': [{ type: Output },],
    'keyPress': [{ type: Output },],
    'keyUp': [{ type: Output },],
    'loadComplete': [{ type: Output },],
    'scrollPosChanged': [{ type: Output },],
    'selectionChanged': [{ type: Output },],
    'updateComplete': [{ type: Output },],
    'onWindowKeyDown': [{ type: HostListener, args: ['document:keydown', ['$event'],] },],
    'onWindowKeyUp': [{ type: HostListener, args: ['document:keyup', ['$event'],] },],
};
//# sourceMappingURL=integralui.base.list.js.map