/*
  filename: integralui.base.grid.js
  version : 1.2.0
  Copyright © 2016-2017 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
import { Component, ComponentFactoryResolver, ElementRef, EventEmitter, HostListener, Input, Output, Renderer } from '@angular/core';
import { IntegralUIBaseComponent, IntegralUIObjectState, IntegralUISelectionMode, IntegralUISortOrder, IntegralUIDragWindow } from './integralui.core';
import { IntegralUICommonService } from '../services/integralui.common.service';
import { IntegralUIDataService } from '../services/integralui.data.service';
import { IntegralUIDragDropService } from '../services/integralui.dragdrop.service';
import { IntegralUIFilterService } from '../services/integralui.filter.service';
// ---------------------------------------------------------------------------------------
// Anchor Styles Enumeration
// ---------------------------------------------------------------------------------------
export var IntegralUIGridLines;
(function (IntegralUIGridLines) {
    IntegralUIGridLines[IntegralUIGridLines["None"] = 0] = "None";
    IntegralUIGridLines[IntegralUIGridLines["Horizontal"] = 1] = "Horizontal";
    IntegralUIGridLines[IntegralUIGridLines["Vertical"] = 2] = "Vertical";
    IntegralUIGridLines[IntegralUIGridLines["Both"] = 3] = "Both";
})(IntegralUIGridLines || (IntegralUIGridLines = {}));
var IntegralUIBaseGrid = (function (_super) {
__extends(IntegralUIBaseGrid,_super);
function IntegralUIBaseGrid(a,b,c,d,f,g,h){var e=_super.call(this,f)||this;e.dataService=a;e.dragDropService=b;e.elemRef=c;e.elemRenderer=d;e.commonService=f;e.filterService=g;e.cmpResolver=h;e.currentColumnList=[];e.currentRowList=[];e.dataColumns=[];e.dataRows=[];e.options={};e.scrollColumnList=[];e.scrollRowList=[];e.columnDataKey="columns";e.rowDataKey="rows";e.dropMarkElem=null;e.dragCmpRef=null;e.dragCmp=null;e.cloneElem=null;e.cloneElemStartPos={x:0,y:0};e.hoverColumn=null;e.hoverRow=null;
e.currentIndex=0;e.prevIndex=0;e.currentFocusCell=null;e.isKeyboardActive=!1;e.allowUpdate=!0;e.avgRowHeight=0;e.headerHeight=0;e.footerHeight=0;e.viewIndexRange={left:0,middle:999,right:999};e.visibleRange=1;e.isHeaderVisible=!0;e.isFooterVisible=!0;e.scrollSize={width:0,height:0};e.clientRect={width:0,height:0};e.contentLeftPos=0;e.allColWidth=0;e.isColumnResizing=!1;e.currentScrollPos={x:0,y:0};e.maxScrollPos={x:0,y:0};e.accelerator=.5;e.scrollTimerID=null;e.isScrollTimerActive=!1;e.scrollCount=
0;e.isScrollActive=!1;e.prevScrollPos={x:0,y:0};e.scrollBarSize={width:0,height:0};e.scrollLargeChange={x:0,y:0};e.currentSelectedColumn=null;e.currentSelectedRow=null;e.currentSelectionMode=IntegralUISelectionMode.One;e.shiftFirstSelectedRow=null;e.removeIndex=-1;e.currentSelectedRows=[];e.gridLines=IntegralUIGridLines.Both;e.rowHeight=0;e.afterSelect=new EventEmitter;e.beforeEdit=new EventEmitter;e.beforeSelect=new EventEmitter;e.change=new EventEmitter;e.columnAdding=new EventEmitter;e.columnAdded=
new EventEmitter;e.columnClick=new EventEmitter;e.columnRemoving=new EventEmitter;e.columnRemoved=new EventEmitter;e.columnsCleared=new EventEmitter;e.columnSizeChanged=new EventEmitter;e.dragDrop=new EventEmitter;e.dragOver=new EventEmitter;e.keyDown=new EventEmitter;e.keyPress=new EventEmitter;e.keyUp=new EventEmitter;e.rowAdding=new EventEmitter;e.rowAdded=new EventEmitter;e.rowClick=new EventEmitter;e.rowDblClick=new EventEmitter;e.rowRemoving=new EventEmitter;e.rowRemoved=new EventEmitter;e.rowsCleared=
new EventEmitter;e.loadComplete=new EventEmitter;e.scrollPosChanged=new EventEmitter;e.selectionChanged=new EventEmitter;e.updateComplete=new EventEmitter;e.sortColumn=null;e.sortComparer=null;e.updateOptions();return e}Object.defineProperty(IntegralUIBaseGrid.prototype,"allowDrag",{set:function(a){this.options.allowDrag=a},enumerable:!0,configurable:!0});Object.defineProperty(IntegralUIBaseGrid.prototype,"allowDrop",{set:function(a){this.options.allowDrop=a},enumerable:!0,configurable:!0});
Object.defineProperty(IntegralUIBaseGrid.prototype,"allowFilter",{set:function(a){this.options.allowFilter=a},enumerable:!0,configurable:!0});Object.defineProperty(IntegralUIBaseGrid.prototype,"allowFocus",{set:function(a){this.options.allowFocus=a;a||(this.currentFocusCell=null);this.refresh()},enumerable:!0,configurable:!0});Object.defineProperty(IntegralUIBaseGrid.prototype,"columns",{get:function(){return this.dataColumns},set:function(a){this.dataColumns=a;this.updateData()},enumerable:!0,configurable:!0});
Object.defineProperty(IntegralUIBaseGrid.prototype,"dataFields",{set:function(a){this.updateDataFields(a)},enumerable:!0,configurable:!0});Object.defineProperty(IntegralUIBaseGrid.prototype,"focusedCell",{get:function(){return this.currentFocusCell},set:function(a){this.currentFocusCell!=a&&(this.currentFocusCell=a)},enumerable:!0,configurable:!0});Object.defineProperty(IntegralUIBaseGrid.prototype,"paging",{set:function(a){this.updatePaging(a)},enumerable:!0,configurable:!0});
Object.defineProperty(IntegralUIBaseGrid.prototype,"rows",{get:function(){return this.dataRows},set:function(a){this.dataRows=a;this.updateData()},enumerable:!0,configurable:!0});Object.defineProperty(IntegralUIBaseGrid.prototype,"selectedColumn",{get:function(){return this.currentSelectedColumn},set:function(a){this.currentSelectedColumn!=a&&this.processColumnSelection(null,a)},enumerable:!0,configurable:!0});
Object.defineProperty(IntegralUIBaseGrid.prototype,"selectedRow",{get:function(){return this.currentSelectedRow},set:function(a){this.currentSelectedRow!=a&&this.processRowSelection(null,a)},enumerable:!0,configurable:!0});
Object.defineProperty(IntegralUIBaseGrid.prototype,"selectionMode",{get:function(){return this.currentSelectionMode},set:function(a){this.currentSelectionMode!=a&&(this.currentSelectionMode=a,this.clearPrevSelection(this.currentSelectionMode!=IntegralUISelectionMode.None?this.currentSelectedRow:null),this.refresh(),this.currentSelectionMode==IntegralUISelectionMode.None&&(this.currentSelectedRow=null,this.selectionChanged.emit(null)))},enumerable:!0,configurable:!0});
Object.defineProperty(IntegralUIBaseGrid.prototype,"sorting",{set:function(a){this.options.sorting=a},enumerable:!0,configurable:!0});IntegralUIBaseGrid.prototype.ngOnInit=function(){this.dataService.init([{data:this.columns,fields:this.options.columnFields,key:this.columnDataKey},{data:this.rows,fields:this.options.rowFields,key:this.rowDataKey}])};IntegralUIBaseGrid.prototype.addColumn=function(a){this.callEventAddColumn("add",a)};
IntegralUIBaseGrid.prototype.clearColumns=function(){this.dataService.clear(null,this.columnDataKey);this.columnsCleared.emit(null);this.currentScrollPos.x=0};IntegralUIBaseGrid.prototype.insertColumnAt=function(a,b){this.callEventAddColumn("at",a,b)};IntegralUIBaseGrid.prototype.insertColumnBefore=function(a,b){this.callEventAddColumn("ref",a,-1,b)};IntegralUIBaseGrid.prototype.insertColumnAfter=function(a,b){this.callEventAddColumn("ref",a,-1,b,!0)};IntegralUIBaseGrid.prototype.removeColumn=function(a){return this.callEventRemoveColumn(a)};
IntegralUIBaseGrid.prototype.removeColumnAt=function(a){return this.callEventRemoveColumn(null,a)};IntegralUIBaseGrid.prototype.callEventAddColumn=function(a,b,c,d,f){var g={cancel:!1,column:b};this.columnAdding.emit(g);if(1!=g.cancel){switch(a){case "at":this.dataService.insert(b,c,null,null,!1,this.columnDataKey);break;case "ref":this.dataService.insertByRef(b,d,f,this.columnDataKey);break;default:this.dataService.insert(b,-1,null,null,!1,this.columnDataKey)}this.columnAdded.emit({column:b})}};
IntegralUIBaseGrid.prototype.callEventRemoveColumn=function(a,b){var c={cancel:!1,column:a};this.columnRemoving.emit(c);return 1!=c.cancel&&(this.removeIndex=this.columns?this.columns.indexOf(a):-1,c=this.dataService.removeAt(a,b,null,this.columnDataKey),c.result)?(this.columnRemoved.emit({column:c.obj}),!0):!1};IntegralUIBaseGrid.prototype.addRow=function(a,b){this.callEventAddRow("add",a,-1,b)};
IntegralUIBaseGrid.prototype.clearRows=function(a){this.dataService.clear(a,this.rowDataKey);this.rowsCleared.emit({parent:a});this.clearSelection();this.currentScrollPos.y=0};IntegralUIBaseGrid.prototype.insertRowAt=function(a,b,c){this.callEventAddRow("at",a,b,c)};IntegralUIBaseGrid.prototype.insertRowBefore=function(a,b){this.callEventAddRow("ref",a,-1,null,b)};IntegralUIBaseGrid.prototype.insertRowAfter=function(a,b){this.callEventAddRow("ref",a,-1,null,b,!0)};
IntegralUIBaseGrid.prototype.removeRow=function(a){return this.callEventRemoveRow(a)};IntegralUIBaseGrid.prototype.removeRowAt=function(a,b){return this.callEventRemoveRow(null,a,b)};
IntegralUIBaseGrid.prototype.callEventAddRow=function(a,b,c,d,f,g){var h={cancel:!1,row:b};this.rowAdding.emit(h);if(1!=h.cancel){switch(a){case "at":this.dataService.insert(b,c,d,null,!1,this.rowDataKey);break;case "ref":this.dataService.insertByRef(b,f,g,this.rowDataKey);break;default:this.dataService.insert(b,-1,d,null,!1,this.rowDataKey)}this.rowAdded.emit({row:b})}};
IntegralUIBaseGrid.prototype.callEventRemoveRow=function(a,b,c){var d={cancel:!1,row:a};this.rowRemoving.emit(d);return 1!=d.cancel&&(this.removeIndex=this.rows?this.rows.indexOf(a):-1,a=this.dataService.removeAt(a,b,c,this.rowDataKey),a.result)?(this.rowRemoved.emit({row:a.obj}),!0):!1};IntegralUIBaseGrid.prototype.updateData=function(){};
IntegralUIBaseGrid.prototype.updateDataFields=function(a){a?(this.updateColumnFields(a.column),this.updateRowFields(a.row),this.updateCellFields(a.cell)):(this.updateColumnFields(),this.updateRowFields(),this.updateCellFields())};
IntegralUIBaseGrid.prototype.updateOptions=function(a){a?(this.options={allowAnimation:this.commonService.isFieldAvailable(a.allowAnimation,!0),allowCellFocus:this.commonService.isFieldAvailable(a.allowCellFocus,!0),allowColumnReorder:this.commonService.isFieldAvailable(a.allowColumnReorder,!1),allowDrag:this.commonService.isFieldAvailable(a.allowDrag,!1),allowDrop:this.commonService.isFieldAvailable(a.allowDrop,!0),allowFilter:this.commonService.isFieldAvailable(a.allowFilter,!1),allowFocus:this.commonService.isFieldAvailable(a.allowFocus,
!1),animationSpeed:200,autoExpand:this.commonService.isFieldAvailable(a.autoExpand,!0),displayMode:this.commonService.isFieldAvailable(a.displayMode,"normal"),editorSettings:{activate:"click"},enabled:this.commonService.isFieldAvailable(a.enabled,!0),expandColIndex:this.commonService.isFieldAvailable(a.expandColIndex,void 0!=this.options.expandColIndex?this.options.expandColIndex:0),fillSpace:this.commonService.isFieldAvailable(a.fillSpace,!1),gridLines:this.commonService.isFieldAvailable(a.gridLines,
"both"),hoverSelection:this.commonService.isFieldAvailable(a.hoverSelection,!1),indent:this.commonService.isFieldAvailable(a.indent,15),labelEdit:this.commonService.isFieldAvailable(a.labelEdit,!1),loadRows:[],mouseWheelSpeed:this.commonService.isFieldAvailable(a.mouseWheelSpeed,"normal"),pathSeparator:this.commonService.isFieldAvailable(a.pathSeparator,"\\"),rowHeight:this.commonService.isFieldAvailable(a.rowHeight,-1),rtl:this.commonService.isFieldAvailable(a.rtl,!1),selectedColumn:this.commonService.isFieldAvailable(a.selectedColumn,
this.currentSelectedColumn?this.currentSelectedColumn:null),selectedIndex:-1,selectedRow:this.commonService.isFieldAvailable(a.selectedRow,this.currentSelectedRow?this.currentSelectedRow:null),selectedRows:[],selectionMode:this.commonService.isFieldAvailable(a.selectionMode,IntegralUISelectionMode.One),showFooter:this.commonService.isFieldAvailable(a.showFooter,!0),showHeader:this.commonService.isFieldAvailable(a.showHeader,!0),showIcons:this.commonService.isFieldAvailable(a.showIcons,!0),sorting:this.commonService.isFieldAvailable(a.sorting,
IntegralUISortOrder.None)},this.updatePaging(a.paging),this.updateDataFields(a.dataFields)):(this.options={allowAnimation:!0,allowCellFocus:!0,allowColumnReorder:!1,allowDrag:!1,allowDrop:!0,allowFilter:!1,allowFocus:!1,animationSpeed:200,autoExpand:!0,displayMode:"normal",editorSettings:{activate:"click"},enabled:!0,expandColIndex:0,fillSpace:!1,gridLines:"both",hoverSelection:!1,indent:15,labelEdit:!1,loadRows:[],mouseWheelSpeed:"normal",pathSeparator:"\\",rowHeight:-1,rtl:!1,selectedColumn:null,
selectedIndex:-1,selectedRow:null,selectedRows:[],selectionMode:IntegralUISelectionMode.One,showFooter:!0,showHeader:!0,showIcons:!0,sorting:IntegralUISortOrder.None},this.updatePaging(),this.updateDataFields())};
IntegralUIBaseGrid.prototype.updateColumnFields=function(a){this.options.columnFields=a?{allowDrag:a.allowDrag?a.allowDrag:"allowDrag",allowDrop:a.allowDrop?a.allowDrop:"allowDrop",allowFilter:a.allowFilter?a.allowFilter:"allowFilter",allowGrouping:a.allowGrouping?a.allowGrouping:"allowGrouping",cellTemplateUrl:a.cellTemplateUrl?a.cellTemplateUrl:"cellTemplateUrl",comparer:a.comparer?a.comparer:"comparer",contentAlignment:a.contentAlignment?a.contentAlignment:"contentAlignment",contextMenu:a.contextMenu?
a.contextMenu:"contextMenu",editorType:a.editorType?a.editorType:"editorType",editorSettings:a.editorSettings?a.editorSettings:"editorSettings",editorTemplate:a.editorTemplate?a.editorTemplate:"editorTemplate",filterParams:a.filterParams?a.filterParams:"filterParams",filterTemplate:a.filterTemplate?a.filterTemplate:"filterTemplate",fixed:a.fixed?a.fixed:"fixed",fixedWidth:a.fixedWidth?a.fixedWidth:"fixedWidth",footerAlignment:a.footerAlignment?a.footerAlignment:"footerAlignment",footerContent:a.footerContent?
a.footerContent:"footerContent",footerTemplate:a.footerTemplate?a.footerTemplate:"footerTemplate",footerTemplateModel:a.footerTemplateModel?a.footerTemplateModel:"footerTemplateModel",footerText:a.footerText?a.footerText:"footerText",footerTooltip:a.footerTooltip?a.footerTooltip:"footerTooltip",groupText:a.groupText?a.groupText:"groupText",headerAlignment:a.headerAlignment?a.headerAlignment:"headerAlignment",headerContent:a.headerContent?a.headerContent:"headerContent",headerTemplate:a.headerTemplate?
a.headerTemplate:"headerTemplate",headerTemplateModel:a.headerTemplateModel?a.headerTemplateModel:"headerTemplateModel",headerText:a.headerText?a.headerText:"headerText",headerTooltip:a.headerTooltip?a.headerTooltip:"headerTooltip",icon:a.icon?a.icon:"icon",id:a.id?a.id:"id",minWidth:a.minWidth?a.minWidth:"minWidth",maxWidth:a.maxWidth?a.maxWidth:"maxWidth",selected:a.selected?a.selected:"selected",style:a.style?a.style:"style",templateSettings:a.templateSettings?a.templateSettings:"templateSettings",
visible:a.visible?a.visible:"visible",width:a.width?a.width:"width"}:{allowDrag:"allowDrag",allowDrop:"allowDrop",allowFilter:"allowFilter",allowGrouping:"allowGrouping",cellTemplateUrl:"cellTemplateUrl",comparer:"comparer",contentAlignment:"contentAlignment",contextMenu:"contextMenu",editorType:"editorType",editorSettings:"editorSettings",editorTemplate:"editorTemplate",filterParams:"filterParams",filterTemplate:"filterTemplate",footerTemplateModel:"footerTemplateModel",fixed:"fixed",fixedWidth:"fixedWidth",
footerAlignment:"footerAlignment",footerContent:"footerContent",footerTemplate:"footerTemplate",footerText:"footerText",footerTooltip:"footerTooltip",groupText:"groupText",headerAlignment:"headerAlignment",headerContent:"headerContent",headerTemplate:"headerTemplate",headerTemplateModel:"headerTemplateModel",headerText:"headerText",headerTooltip:"headerTooltip",icon:"icon",id:"id",minWidth:"minWidth",maxWidth:"maxWidth",selected:"selected",style:"style",templateSettings:"templateSettings",visible:"visible",
width:"width"};this.dataService&&this.dataService.updateDataFields(this.options.columnFields,this.columnDataKey)};
IntegralUIBaseGrid.prototype.updateRowFields=function(a){this.options.rowFields=a?{allowDrag:a.allowDrag?a.allowDrag:"allowDrag",allowDrop:a.allowDrop?a.allowDrop:"allowDrop",allowEdit:a.allowEdit?a.allowEdit:"allowEdit",allowFocus:a.allowFocus?a.allowFocus:"allowFocus",autoCheck:a.autoCheck?a.autoCheck:"autoCheck",cells:a.cells?a.cells:"cells",checkBoxSettings:a.checkBoxSettings?a.checkBoxSettings:"checkBoxSettings",checked:a.checked?a.checked:"checked",checkState:a.checkState?a.checkState:"checkState",
content:a.content?a.content:"content",contextMenu:a.contextMenu?a.contextMenu:"contextMenu",enabled:a.enabled?a.enabled:"enabled",expanded:a.expanded?a.expanded:"expanded",hasChildren:a.hasChildren?a.hasChildren:"hasChildren",icon:a.icon?a.icon:"icon",id:a.id?a.id:"id",objects:a.rows?a.rows:"rows",pid:a.pid?a.pid:"pid",rows:a.rows?a.rows:"rows",selected:a.selected?a.selected:"selected",statusIcon:a.statusIcon?a.statusIcon:"statusIcon",style:a.style?a.style:"style",subobjects:a.cells?a.cells:"cells",
templateObj:a.templateObj?a.templateObj:"templateObj",text:a.text?a.text:"text",tooltip:a.tooltip?a.tooltip:"tooltip",value:a.value?a.value:"value",visible:a.visible?a.visible:"visible"}:{allowDrag:"allowDrag",allowDrop:"allowDrop",allowFocus:"allowFocus",cells:"cells",content:"content",contextMenu:"contextMenu",enabled:"enabled",expanded:"expanded",fixed:"fixed",hasChildren:"hasChildren",icon:"icon",id:"id",objects:"rows",pid:"pid",rows:"rows",selected:"selected",statusIcon:"statusIcon",style:"style",
subobjects:"cells",text:"text",tooltip:"tooltip",value:"value",visible:"visible"};this.dataService&&this.dataService.updateDataFields(this.options.rowFields,this.rowDataKey)};
IntegralUIBaseGrid.prototype.updateCellFields=function(a){this.options.cellFields=a?{allowEdit:a.allowEdit?a.allowEdit:"allowEdit",cid:a.cid?a.cid:"cid",content:a.content?a.content:"content",contextMenu:a.contextMenu?a.contextMenu:"contextMenu",enabled:a.enabled?a.enabled:"enabled",labelEdit:a.labelEdit?a.labelEdit:"labelEdit",rid:a.rid?a.rid:"rid",selected:a.selected?a.selected:"selected",style:a.style?a.style:"style",templateObj:a.templateObj?a.templateObj:"templateObj",text:a.text?a.text:"text",
tooltip:a.tooltip?a.tooltip:"tooltip",value:a.value?a.value:"value"}:{allowEdit:"allowEdit",cid:"cid",content:"content",contextMenu:"contextMenu",enabled:"enabled",labelEdit:"labelEdit",rid:"rid",selected:"selected",style:"style",templateObj:"templateObj",text:"text",tooltip:"tooltip",value:"value"}};
IntegralUIBaseGrid.prototype.processLoadData=function(a,b,c,d){var f=this;f.clearRows(b);f.updateRowFields(c);var g=[];if(a)if(0!=d){var h=[];a.forEach(function(a,b){var c=a[f.options.rowFields.pid];h[c]?(h[c][f.options.rowFields.rows]||(h[c][f.options.rowFields.rows]=[]),h[a[f.options.rowFields.id]]=a,h[c][f.options.rowFields.rows].push(a)):(h[a[f.options.rowFields.id]]=a,g.push(a))});h.length=0}else g=a;if(b)for(b[f.options.rowFields.rows]=g,a=0;a<b[f.options.rowFields.rows].length;a++)b[f.options.rowFields.rows][a][f.options.rowFields.pid]=
b[f.options.rowFields.id];else if(f.rows)for(a=f.rows.length=0;a<g.length;a++)f.rows.push(g[a]);f.loadComplete.emit(null);this.updateLayout()};IntegralUIBaseGrid.prototype.updateScrollColumnList=function(){};IntegralUIBaseGrid.prototype.updateScrollRowList=function(){};
IntegralUIBaseGrid.prototype.addDropMark=function(a){this.appRef&&(this.removeDropMark(),a=this.cmpResolver.resolveComponentFactory(IntegralUIDragWindow))&&(this.dragCmpRef=this.appRef.createComponent(a),this.dragCmpRef._component?this.dragCmp=this.dragCmpRef._component:this.dragCmpRef._hostElement&&(this.dragCmp=this.dragCmpRef._hostElement.component))};IntegralUIBaseGrid.prototype.removeDropMark=function(){this.dragCmpRef&&this.dragCmpRef.destroy();this.dragCmp=null};
IntegralUIBaseGrid.prototype.callDragDropEvent=function(a,b,c){a={action:b.action,cancel:!1,dragRow:b.source,dropPos:b.dropPos,event:a,isDropAllowed:b.allow,mousePos:this.commonService.getMousePos(a),sourceCtrl:b.sourceCtrl,targetCtrl:b.targetCtrl,targetRow:b.target};c?this.dragDrop.emit(a):this.dragOver.emit(a);return a.cancel};
IntegralUIBaseGrid.prototype.checkEmptySpace=function(a){var b=this.getContentSize(),c=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild);b=c.top+b.height;c=c.bottom;a=this.commonService.getMousePos(a);var d=this.commonService.getShiftPos();a.x-=d.x;a.y-=d.y;return a.y>=b&&a.y<=c};IntegralUIBaseGrid.prototype.ctrlDragDrop=function(a){this.processDragDrop(a);a.stopPropagation()};IntegralUIBaseGrid.prototype.ctrlDragLeave=function(a){this.dropMark(a);this.stopScrollTimer()};
IntegralUIBaseGrid.prototype.ctrlDragOver=function(a){this.processDragOver(a);a.stopPropagation()};IntegralUIBaseGrid.prototype.dropMark=function(a,b){this.dragCmp||this.addDropMark({x:a.pageX,y:a.pageY});if(this.dragCmp){var c="none";this.options.allowDrop&&(c=b?"block":"none");this.dragCmp.display=c}};IntegralUIBaseGrid.prototype.updateDragComponent=function(a){this.dragCmp&&this.dragCmp.updatePos(a)};
IntegralUIBaseGrid.prototype.isDragAllowed=function(a){return this.options.allowDrag?a&&(a[this.options.rowFields.allowDrag]||void 0===a[this.options.rowFields.allowDrag])?!0:!1:!1};
IntegralUIBaseGrid.prototype.isDropAllowed=function(a,b,c){var d=this.options.allowDrop;if(d&&a&&b&&(d=b[this.options.rowFields.allowDrop]||void 0===b[this.options.rowFields.allowDrop]?!0:!1))if(Array.isArray(a))for(var f=0;f<a.length;f++){if(this.commonService.isEqual(a[f][this.options.rowFields.id],b[this.options.rowFields.id])||0===c&&this.isParentOf(b,a[f])||this.isChildOf(b,a[f])){d=!1;break}if(!d)break}else if(this.commonService.isEqual(a[this.options.rowFields.id],b[this.options.rowFields.id])||
0===c&&this.isParentOf(b,a)||this.isChildOf(b,a))d=!1;return d};
IntegralUIBaseGrid.prototype.processDragStart=function(a,b){this.dragDropService.clearData();if(!this.isDragAllowed(b))a.preventDefault();else if(b)if(this.isDragAllowed(b)){this.addDropMark({x:a.pageX,y:a.pageY});a.dataTransfer?(a.dataTransfer.effectAllowed="move",a.dataTransfer.setData("text",b[this.options.rowFields.id]?b[this.options.rowFields.id].toString():"")):a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.effectAllowed="move",a.originalEvent.dataTransfer.setData("text",
b[this.options.rowFields.id]?b[this.options.rowFields.id].toString():""));var c={clone:this.cloneRow(b),source:b,sourceCtrl:this,sourceData:this.rows};switch(this.selectionMode){case IntegralUISelectionMode.MultiSimple:c.clone=this.createCloneList(this.currentSelectedRows);c.source=this.currentSelectedRows;break;case IntegralUISelectionMode.MultiExtended:c.clone=this.createCloneList(this.currentSelectedRows),c.source=this.currentSelectedRows}this.dragDropService.setData(c)}else a.dataTransfer?a.dataTransfer.effectAllowed=
"none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.effectAllowed="none")};
IntegralUIBaseGrid.prototype.processDragOver=function(a,b,c,d){a.preventDefault();var f=!0;a.dataTransfer?f="none"===a.dataTransfer.effectAllowed?!1:!0:a.originalEvent&&a.originalEvent.dataTransfer&&(f="none"===a.originalEvent.dataTransfer.effectAllowed?!1:!0);if(f){var g=this.dragDropService.getData();f=this.commonService.getShiftPos();if(b){var h=this.commonService.getMousePos(a);h.x-=f.x;h.y-=f.y;h=this.dragDropService.getDropPos(h,c,d);f=this.isDropAllowed(g.source,b,h);c={action:a.shiftKey?"copy":
"move",source:g.source,dropPos:h,allow:f,sourceCtrl:g.sourceCtrl,target:b,targetCtrl:this};c=this.callDragDropEvent(a,c);if(f&&1!=c){d=this.commonService.getMousePos(a);c=d.y+16;d=d.x+20;var e="iui-dragwin-icon";switch(h){case 0:e+=" iui-dragwin-move-in";break;case 1:e+=" iui-dragwin-move-up";break;case 2:e+=" iui-dragwin-move-down"}a.shiftKey&&(e+="-copy");this.updateDragComponent({"class":e,top:c,left:d,text:b[this.options.rowFields.text]});this.dropMark(a,f);this.dragDropService.setData({action:a.shiftKey?
"copy":"move",source:g.source,sourceData:g.sourceData,target:b,targetCtrl:this,dropPos:h})}else a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a)}else this.options.allowDrop?(f=this.checkEmptySpace(a),c={action:a.shiftKey?"copy":"move",source:g.source,dropPos:-1,allow:f,sourceCtrl:g.sourceCtrl,target:null,targetCtrl:this},c=this.callDragDropEvent(a,c),f&&1!=c?(h=this.commonService.getMousePos(a),
c=h.y+16,d=h.x+20,e="iui-dragwin-icon iui-dragwin-move-end",a.shiftKey&&(e+="-copy"),this.updateDragComponent({"class":e,top:c,left:d,text:this.name?this.name:"Component"}),this.dropMark(a,f),this.dragDropService.setData({action:a.shiftKey?"copy":"move",source:g.source,sourceData:g.sourceData,target:null,targetCtrl:this,dropPos:-1})):(a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a))):(a.dataTransfer?
a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a))}};
IntegralUIBaseGrid.prototype.processDragDrop=function(a,b){a.preventDefault();this.dropMark(a);var c=!0;a.dataTransfer?c="none"===a.dataTransfer.effectAllowed?!1:!0:a.originalEvent&&a.originalEvent.dataTransfer&&(c="none"===a.originalEvent.dataTransfer.effectAllowed?!1:!0);if(c){var d=this.dragDropService.getData();(c=b?this.isDropAllowed(d.source,b,d.dropPos):this.checkEmptySpace(a))&&d.source&&(this.callDragDropEvent(a,{action:a.shiftKey?"copy":"move",source:d.source,dropPos:d.dropPos,allow:c,sourceCtrl:d.sourceCtrl,
target:d.target,targetCtrl:this},!0)||this.drop(a,d))}this.dragDropService.clearData()};
IntegralUIBaseGrid.prototype.drop=function(a,b){if(b&&b.sourceCtrl){var c=a.shiftKey&&b.clone?b.clone:b.source;if(Array.isArray(c)){for(var d=[],f=0;f<c.length;f++)d.push(c[f]);if(0<d.length){for(f=0;f<d.length;f++)this.processDataDrop(a,d[f],b);this.clearPrevSelection(d[d.length-1])}}else this.processDataDrop(a,c,b),this.clearPrevSelection(c);b.sourceCtrl!=b.targetCtrl&&b.sourceCtrl.updateLayout&&b.sourceCtrl.updateLayout();this.updateLayout()}};
IntegralUIBaseGrid.prototype.processDataDrop=function(a,b,c){var d=a.shiftKey;!a.shiftKey&&c.sourceCtrl&&c.sourceCtrl.removeRow&&(d=c.sourceCtrl.removeRow(b));if(d)switch(c.dropPos){case 0:this.insertRowAt(b,-1,c.target);break;case 1:this.insertRowBefore(b,c.target);break;case 2:this.insertRowAfter(b,c.target);break;default:this.addRow(b)}};IntegralUIBaseGrid.prototype.callAfterSelectEvent=function(a){this.afterSelect.emit({obj:a});this.selectionChanged.emit(null)};
IntegralUIBaseGrid.prototype.filter=function(a,b){if(a)a[this.options.columnFields.filterParams]=b;else for(var c=0;c<this.currentColumnList.length;c++)this.currentColumnList[c].data[this.options.columnFields.filterParams]=null;this.updateLayout();this.change.emit({type:"filtering"})};IntegralUIBaseGrid.prototype.cloneRow=function(a){return this.dataService.clone(a,this.rowDataKey)};
IntegralUIBaseGrid.prototype.createCloneList=function(a){for(var b=[],c=0;c<a.length;c++)b.push(this.cloneRow(a[c]));return b};IntegralUIBaseGrid.prototype.getColumnById=function(a){for(var b=null,c=0;c<this.currentColumnList.length;c++)if(this.currentColumnList[c].data[this.options.columnFields.id]==a){b=this.currentColumnList[c].data;break}return b};IntegralUIBaseGrid.prototype.getColumnCurrentIndex=function(a){return a?this.getColumnIndexFromList(a):-1};
IntegralUIBaseGrid.prototype.getColumnIndexFromList=function(a){for(var b=-1,c=0;c<this.currentColumnList.length;c++)if(this.currentColumnList[c].data==a){b=c;break}return b};IntegralUIBaseGrid.prototype.getFilterTree=function(a){for(var b=null,c=0;c<this.currentColumnList.length;c++)if(this.currentColumnList[c].data==a){b=this.currentColumnList[c].filter;break}return b};
IntegralUIBaseGrid.prototype.getList=function(a,b){switch(a){case "selected":return this.currentSelectedRows}return this.dataService.getList(b,this.rowDataKey)};IntegralUIBaseGrid.prototype.getObjFromRow=function(a){for(var b=null,c=0;c<this.currentRowList.length;c++)if(this.currentRowList[c].data==a){b=this.currentRowList[c];break}return b};IntegralUIBaseGrid.prototype.getRowCurrentIndex=function(a){return a?(a=this.getObjFromRow(a))&&this.currentRowList?this.currentRowList.indexOf(a):-1:-1};
IntegralUIBaseGrid.prototype.getRowFromComponent=function(a){return null};IntegralUIBaseGrid.prototype.isChildOf=function(a,b){return!1};IntegralUIBaseGrid.prototype.isColumnVisible=function(a){return a&&0!=a[this.options.columnFields.visible]?!0:!1};IntegralUIBaseGrid.prototype.isComponentIndexInRange=function(a){return this.rowList?0<=a&&a<this.rowList.length:!1};IntegralUIBaseGrid.prototype.isIndexInRange=function(a){return this.currentRowList?0<=a&&a<this.currentRowList.length:!1};
IntegralUIBaseGrid.prototype.isRowAllowed=function(a,b){if(0==a[this.options.rowFields.visible])return!1;if(0==this.options.allowFilter)return!0;var c=!0;if(a)for(var d,f,g=0;g<a[this.options.rowFields.cells].length;g++){c=!0;f=a[this.options.rowFields.cells][g];d=f[this.options.cellFields.cid];d=this.getColumnById(d);!d&&g<this.currentColumnList.length&&(d=this.currentColumnList[g].data);if(d&&d[this.options.columnFields.filterParams]){var h=d[this.options.columnFields.filterParams],e=f[this.options.cellFields.value]?
f[this.options.cellFields.value]:f[this.options.cellFields.text];h&&(h.callback?c=h.callback(e,f,a):(c=this.filterService.match(e,h.conditions,h.formula,this.getFilterTree(d),h.caseSensitive),!c&&h.allowParent&&(c=this.filterIsThereChildren(a,b))))}if(!c)break}return c};IntegralUIBaseGrid.prototype.filterIsThereChildren=function(a,b){var c=!1,d=a[this.options.rowFields.rows];if(d)for(var f=0;f<d.length&&!(c=this.isRowAllowed(d[f],b));f++);return c};IntegralUIBaseGrid.prototype.isRowEnabled=function(a){return!0};
IntegralUIBaseGrid.prototype.isRowFixed=function(a){return!1};IntegralUIBaseGrid.prototype.isRowHovered=function(a){return a&&a==this.hoverRow?!0:!1};IntegralUIBaseGrid.prototype.isRowSelected=function(a){return a&&1==a[this.options.rowFields.selected]?!0:!1};IntegralUIBaseGrid.prototype.isParentOf=function(a,b){return!1};IntegralUIBaseGrid.prototype.cellGotFocus=function(a){this.refresh()};IntegralUIBaseGrid.prototype.cellLostFocus=function(a){this.refresh()};
IntegralUIBaseGrid.prototype.onContentScroll=function(a){a.srcElement.scrollTop=0;a.srcElement.scrollLeft=0;a.target.scrollTop=0;a.target.scrollLeft=0};IntegralUIBaseGrid.prototype.cellMouseDown=function(a,b){1==a.buttons&&(this.currentFocusCell=b.data)};
IntegralUIBaseGrid.prototype.cellKeyDown=function(a,b){var c={cancel:!1,cell:b.data,event:a};this.keyDown.emit(c);switch(a.keyCode){case 13:this.beforeEdit.emit(c);break;case 33:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processPageUpKey(b));break;case 34:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processPageDownKey(b));break;case 35:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,
this.processEndKey(b));break;case 36:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processHomeKey(b));break;case 37:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processLeftArrowKey(b));break;case 38:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processUpArrowKey(b));break;case 39:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processRightArrowKey(b));
break;case 40:!c.cancel&&this.options.allowFocus&&(a.preventDefault(),this.isKeyboardActive=!0,this.processDownArrowKey(b))}};IntegralUIBaseGrid.prototype.cellKeyPress=function(a,b){this.keyPress.emit({cancel:!1,cell:b.data,event:a})};IntegralUIBaseGrid.prototype.cellKeyUp=function(a,b){this.keyUp.emit({cancel:!1,cell:b.data,event:a})};
IntegralUIBaseGrid.prototype.processDownArrowKey=function(a,b){var c=this.getDownCell(a);if(c){this.currentFocusCell=c.data;var d=this.getRowFromCell(c),f=this,g=setTimeout(function(){f.processRowSelection(b,d.data);clearTimeout(g)},1);this.isLastRow(c)&&this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y+2*this.avgRowHeight})}return c};
IntegralUIBaseGrid.prototype.processEndKey=function(a,b){var c=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,y:this.maxScrollPos.y});var d=this;setTimeout(function(){var f=d.scrollRowList[d.scrollRowList.length-1];if(0<=a.colIndex&&a.colIndex<f.cells.length){c=f.cells[a.colIndex];d.currentFocusCell=c.data;var g=setTimeout(function(){d.processRowSelection(b,f.data);clearTimeout(g)},1)}},1)}return c};
IntegralUIBaseGrid.prototype.processHomeKey=function(a,b){var c=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,y:0});var d=this;setTimeout(function(){var f=d.scrollRowList[0];if(0<=a.colIndex&&a.colIndex<f.cells.length){c=f.cells[a.colIndex];d.currentFocusCell=c.data;var g=setTimeout(function(){d.processRowSelection(b,f.data);clearTimeout(g)},1)}},1)}return c};
IntegralUIBaseGrid.prototype.processLeftArrowKey=function(a){if(a=this.getPrevCell(a)){this.currentFocusCell=a.data;this.isFirstCell(a)&&this.scrollPos({x:this.currentScrollPos.x-2*a.width,y:this.currentScrollPos.y});var b=this;setTimeout(function(){b.refresh()},1)}return a};
IntegralUIBaseGrid.prototype.processPageDownKey=function(a,b){var c=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y+this.avgRowHeight*(this.scrollRowList.length-1)});var d=this;setTimeout(function(){var f=0<=a.rowIndex&&a.rowIndex<d.scrollRowList.length?a.rowIndex:d.scrollRowList.length-1;d.currentScrollPos.y==d.maxScrollPos.y&&(f=d.scrollRowList.length-1);var g=d.scrollRowList[f];if(0<=a.colIndex&&a.colIndex<g.cells.length){c=g.cells[a.colIndex];
d.currentFocusCell=c.data;var h=setTimeout(function(){d.processRowSelection(b,g.data);clearTimeout(h)},1)}},1)}return c};
IntegralUIBaseGrid.prototype.processPageUpKey=function(a,b){var c=null;if(0<this.scrollRowList.length){this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y-this.avgRowHeight*(this.scrollRowList.length-1)});var d=this;setTimeout(function(){var f=0<=a.rowIndex&&a.rowIndex<d.scrollRowList.length?a.rowIndex:0;0==d.currentScrollPos.y&&(f=0);var g=d.scrollRowList[f];if(0<=a.colIndex&&a.colIndex<g.cells.length){c=g.cells[a.colIndex];d.currentFocusCell=c.data;var h=setTimeout(function(){d.processRowSelection(b,
g.data);clearTimeout(h)},1)}},1)}return c};IntegralUIBaseGrid.prototype.processRightArrowKey=function(a){if(a=this.getNextCell(a)){this.currentFocusCell=a.data;this.isLastCell(a)?this.scrollPos({x:this.currentScrollPos.x+2*a.width,y:this.currentScrollPos.y}):a.colIndex>=this.currentColumnList.length-2&&this.scrollPos({x:this.maxScrollPos.x,y:this.currentScrollPos.y});var b=this;setTimeout(function(){b.refresh()},1)}return a};
IntegralUIBaseGrid.prototype.processUpArrowKey=function(a,b){var c=this.getUpCell(a);if(c){this.currentFocusCell=c.data;var d=this.getRowFromCell(c),f=this,g=setTimeout(function(){f.processRowSelection(b,d.data);clearTimeout(g)},1);this.isFirstRow(c)&&this.scrollPos({x:this.currentScrollPos.x,y:this.currentScrollPos.y-this.avgRowHeight})}return c};
IntegralUIBaseGrid.prototype.getDownCell=function(a){if(0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var b=a.rowIndex<this.scrollRowList.length-1?a.rowIndex+1:-1;return(b=0<=b?this.scrollRowList[b]:null)&&0<=a.colIndex&&a.colIndex<b.cells.length?b.cells[a.colIndex]:null}return null};
IntegralUIBaseGrid.prototype.getNextCell=function(a){if(0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var b=this.scrollRowList[a.rowIndex];a=b.cells.indexOf(a);a=0<=a&&a<b.cells.length-1?a+1:-1;return 0<=a?b.cells[a]:null}return null};IntegralUIBaseGrid.prototype.getPrevCell=function(a){if(0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var b=this.scrollRowList[a.rowIndex];a=b.cells.indexOf(a);a=0<a&&a<b.cells.length?a-1:-1;return 0<=a?b.cells[a]:null}return null};
IntegralUIBaseGrid.prototype.getUpCell=function(a){if(0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length){var b=0<a.rowIndex?a.rowIndex-1:-1;return(b=0<=b?this.scrollRowList[b]:null)&&0<=a.colIndex&&a.colIndex<b.cells.length?b.cells[a.colIndex]:null}return null};IntegralUIBaseGrid.prototype.isFirstCell=function(a){return 0==a.colIndex?!0:!1};IntegralUIBaseGrid.prototype.isFirstRow=function(a){return 0==a.rowIndex?!0:!1};
IntegralUIBaseGrid.prototype.isLastCell=function(a){return a.colIndex==this.viewIndexRange.middle-this.viewIndexRange.left?!0:!1};IntegralUIBaseGrid.prototype.isLastRow=function(a){return a.rowIndex==this.scrollRowList.length-2?!0:!1};IntegralUIBaseGrid.prototype.getRowFromCell=function(a){return 0<=a.rowIndex&&a.rowIndex<this.scrollRowList.length?this.scrollRowList[a.rowIndex]:null};
IntegralUIBaseGrid.prototype.moveFocusFromCell=function(a,b){if(!this.options.allowFocus)return null;var c=null,d=this.getObjFromCell(a);if(d)switch(b){case "down":c=this.processDownArrowKey(d);break;case "end":c=this.processEndKey(d);break;case "home":c=this.processHomeKey(d);break;case "left":c=this.processLeftArrowKey(d);break;case "pagedown":c=this.processPageDownKey(d);break;case "pageup":c=this.processPageUpKey(d);break;case "right":c=this.processRightArrowKey(d);break;case "up":c=this.processUpArrowKey(d)}return c?
c.data:null};IntegralUIBaseGrid.prototype.getObjFromCell=function(a){for(var b=null,c=0;c<this.scrollRowList.length;c++)for(var d=this.scrollRowList[c],f=0;f<d.cells.length;f++){var g=d.cells[f];if(g.data==a){b=g;break}}return b};IntegralUIBaseGrid.prototype.onWindowKeyDown=function(a){this.isKeyboardActive&&a.preventDefault()};IntegralUIBaseGrid.prototype.onWindowKeyUp=function(a){this.isKeyboardActive=!1};IntegralUIBaseGrid.prototype.getContentSize=function(){return{width:0,height:0}};
IntegralUIBaseGrid.prototype.refresh=function(a){this.clearComponentSelection();for(a=0;a<this.currentSelectedRows.length;a++){var b=this.getRowCurrentIndex(this.currentSelectedRows[a]);this.isComponentIndexInRange(b)&&(this.rowList[b].state|=IntegralUIObjectState.selected)}};IntegralUIBaseGrid.prototype.suspendLayout=function(){this.allowUpdate=!1};IntegralUIBaseGrid.prototype.resumeLayout=function(){this.allowUpdate=!0;this.updateLayout()};IntegralUIBaseGrid.prototype.updateLayout=function(){};
IntegralUIBaseGrid.prototype.updateRange=function(){};IntegralUIBaseGrid.prototype.updateCloneElemPos=function(a){1==a.buttons&&this.cloneElem&&(this.cloneElem.style.top=a.pageY-this.cloneElemStartPos.y+"px",this.cloneElem.style.left=a.pageX-this.cloneElemStartPos.x+"px")};IntegralUIBaseGrid.prototype.onCtrlMouseEnter=function(a){1==a.buttons&&this.cloneElem&&(this.cloneElem.style.display="block");this.elemRenderer.setElementStyle(this.elemRef.nativeElement,"cursor","default")};
IntegralUIBaseGrid.prototype.onCtrlMouseLeave=function(a){1==a.buttons&&this.cloneElem&&(this.cloneElem.style.display="none");this.stopScrollTimer()};IntegralUIBaseGrid.prototype.setCloneElem=function(a,b){this.cloneElem&&this.closeCloneElem();this.cloneElem=a;this.cloneElemStartPos=b};IntegralUIBaseGrid.prototype.appendCloneElem=function(){document.body.appendChild(this.cloneElem)};
IntegralUIBaseGrid.prototype.closeCloneElem=function(){var a=this;a.elemRenderer.setElementStyle(a.elemRef.nativeElement,"cursor","default");setTimeout(function(){a.cloneElem&&(document.body.removeChild(a.cloneElem),a.cloneElem=null)},10)};
IntegralUIBaseGrid.prototype.updatePaging=function(a){this.options.paging=a?{enabled:this.commonService.isFieldAvailable(a.enabled,!1),showControlPanel:this.commonService.isFieldAvailable(a.showControlPanel,!0),pageSize:this.commonService.isFieldAvailable(a.pageSize,100)}:{enabled:!1,showControlPanel:!0,pageSize:100}};
IntegralUIBaseGrid.prototype.scrollPos=function(a){a&&(this.currentScrollPos={x:Math.max(0,Math.min(a.x,this.maxScrollPos.x)),y:Math.max(0,Math.min(a.y,this.maxScrollPos.y))});return{x:Math.floor(this.currentScrollPos.x),y:Math.floor(this.currentScrollPos.y)}};
IntegralUIBaseGrid.prototype.changeHorizontalScrollPos=function(a){this.currentScrollPos.x=Math.max(0,Math.min(a,this.maxScrollPos.x));this.currentScrollPos.x!=this.prevScrollPos.x&&(this.updateRange(),this.scrollPosChanged.emit({value:this.scrollPos()}),this.prevScrollPos.x=this.currentScrollPos.x)};
IntegralUIBaseGrid.prototype.changeVerticalScrollPos=function(a){this.currentScrollPos.y=Math.max(0,Math.min(a,this.maxScrollPos.y));this.currentScrollPos.y!=this.prevScrollPos.y&&(this.updateView(),this.scrollPosChanged.emit({value:this.scrollPos()}),this.prevScrollPos.y=this.currentScrollPos.y)};
IntegralUIBaseGrid.prototype.gridMouseWheel=function(a){a.preventDefault();this.hoverRow=null;var b=0;a.wheelDelta?b=Math.max(-1,Math.min(1,a.wheelDelta||-a.detail)):a.originalEvent&&(b=Math.max(-1,Math.min(1,a.originalEvent.wheelDelta||-a.originalEvent.detail)));this.isVerScrollVisible()&&this.changeVerticalScrollPos(this.currentScrollPos.y+Math.floor(this.clientRect.height/4)*b*-1);a.stopPropagation()};
IntegralUIBaseGrid.prototype.isVerScrollVisible=function(){return 0<this.scrollSize.height?!0:!1};IntegralUIBaseGrid.prototype.isHorScrollVisible=function(){return 0<this.scrollSize.width?!0:!1};IntegralUIBaseGrid.prototype.onVerticalScrollStart=function(a){this.hoverRow=null;this.isScrollActive=!0};IntegralUIBaseGrid.prototype.onVerticalScrollEnd=function(a){this.isScrollActive=!1};IntegralUIBaseGrid.prototype.onVerticalScrollChanged=function(a){this.changeVerticalScrollPos(a.value)};
IntegralUIBaseGrid.prototype.onHorizontalScrollStart=function(a){this.hoverRow=null;this.isScrollActive=!0};IntegralUIBaseGrid.prototype.onHorizontalScrollEnd=function(a){this.isScrollActive=!1};IntegralUIBaseGrid.prototype.onHorizontalScrollChanged=function(a){this.currentScrollPos.x=a.value;this.scrollPosChanged.emit({value:this.scrollPos()});var b=this,c=setTimeout(function(){b.updateRange();clearTimeout(c)},1)};
IntegralUIBaseGrid.prototype.updateView=function(){this.currentIndex=0<this.avgRowHeight?Math.floor(this.currentScrollPos.y/this.avgRowHeight):0;this.currentIndex!=this.prevIndex&&(this.updateScrollRowList(),this.prevIndex=this.currentIndex)};
IntegralUIBaseGrid.prototype.processScroll=function(a){if(this.isVerScrollVisible()){var b=this.commonService.getShiftPos();a=this.commonService.getMousePos(a);a.x-=b.x;a.y-=b.y;var c=this.commonService.getPageRect(this.elemRef.nativeElement);b=c.top+this.headerHeight+25;c=c.bottom-this.footerHeight-25;this.isHorScrollVisible()&&(c-=16);a.y<b?this.startScrollTimer(!1):a.y>c?this.startScrollTimer(!0):this.stopScrollTimer()}else this.stopScrollTimer()};
IntegralUIBaseGrid.prototype.startScrollTimer=function(a,b){var c=this;c.isScrollTimerActive||(c.accelerator=.5,c.scrollCount=0,c.isScrollTimerActive=!0,c.scrollTimerID=setInterval(function(){c.scrollTimerElapsed(a)},b?b:100))};IntegralUIBaseGrid.prototype.stopScrollTimer=function(){this.scrollTimerID&&(clearInterval(this.scrollTimerID),this.scrollTimerID=null);this.accelerator=.5;this.scrollCount=0;this.isScrollTimerActive=!1};
IntegralUIBaseGrid.prototype.scrollTimerElapsed=function(a){var b=this.currentScrollPos;0===this.scrollCount&&(this.scrollCount=5);this.scrollCount+=5;this.accelerator+=.5;var c=this.scrollCount+=Math.floor(this.accelerator);this.currentScrollPos.y=a?this.currentScrollPos.y+c>this.maxScrollPos.y?this.maxScrollPos.y:this.currentScrollPos.y+c:0>this.currentScrollPos.y-c?0:this.currentScrollPos.y-c;(0>=b.y||this.currentScrollPos.y<b.y)&&this.stopScrollTimer()};
IntegralUIBaseGrid.prototype.scrollTo=function(a){a&&(a=this.getRowCurrentIndex(a),0<=a&&this.scrollPos({x:this.currentScrollPos.x,y:this.avgRowHeight*(a+1-this.visibleRange/2)}),this.updateLayout())};IntegralUIBaseGrid.prototype.findRowById=function(a){return this.dataService.findObjectById(a,this.rowDataKey)};IntegralUIBaseGrid.prototype.findRowByText=function(a){return this.dataService.findObjectByText(a,this.rowDataKey)};
IntegralUIBaseGrid.prototype.clearSelection=function(){this.clearPrevSelection();this.refresh()};
IntegralUIBaseGrid.prototype.processColumnSelection=function(a,b,c){if(b)a=!0,this.currentSelectedColumn&&(a=!this.commonService.isEqual(this.currentSelectedColumn[this.options.columnFields.id],b[this.options.columnFields.id])),c={cancel:!1,obj:b},this.beforeSelect.emit(c),a&&1!=c.cancel&&(this.currentSelectedColumn&&(this.currentSelectedColumn[this.options.columnFields.selected]=!1,this.refresh(this.currentSelectedColumn)),this.currentSelectedColumn=b,b[this.options.columnFields.selected]=!0,this.refresh(b),
this.callAfterSelectEvent(b));else return this.currentSelectedColumn};IntegralUIBaseGrid.prototype.clearComponentSelection=function(){this.rowList.forEach(function(a){return a.state&=~IntegralUIObjectState.selected})};
IntegralUIBaseGrid.prototype.clearPrevSelection=function(a){for(var b=0;b<this.currentSelectedRows.length;b++)a&&!this.commonService.isEqual(this.currentSelectedRows[b][this.options.rowFields.id],a[this.options.rowFields.id])?this.currentSelectedRows[b][this.options.rowFields.selected]=!1:a||(this.currentSelectedRows[b][this.options.rowFields.selected]=!1);this.currentSelectedRows.length=0;a&&this.isRowEnabled(a)&&this.currentSelectedRows.push(a)};
IntegralUIBaseGrid.prototype.isRowInSelectionList=function(a){var b=!1,c=this.currentSelectedRows;if(a&&c)for(var d=0;d<c.length;d++)if(this.commonService.isEqual(c[d][this.options.rowFields.id],a[this.options.rowFields.id])){b=!0;break}return b};
IntegralUIBaseGrid.prototype.processRowSelection=function(a,b,c){if(b&&this.selectionMode!=IntegralUISelectionMode.None){var d=0<this.currentSelectedRows.length;if(this.isRowEnabled(b)){var f=this.currentSelectedRow,g=!0;f&&(g=a&&(a.ctrlKey||a.metaKey)||!this.commonService.isEqual(f[this.options.rowFields.id],b[this.options.rowFields.id])||0==f[this.options.rowFields.selected]);var h={cancel:!1,obj:b};this.beforeSelect.emit(h);if(1!=h.cancel)if(h=a&&(a.shiftKey||a.ctrlKey||a.metaKey)?!0:!1,g){this.selectionMode==
IntegralUISelectionMode.MultiExtended&&(g=!this.isRowInSelectionList(b)||!h||a&&a.shiftKey);g&&(this.selectionMode==IntegralUISelectionMode.One?this.clearPrevSelection():a&&a.shiftKey?this.clearPrevSelection():h||this.selectionMode==IntegralUISelectionMode.MultiSimple||1!=this.currentSelectedRows.length&&this.isRowInSelectionList(b)||this.clearPrevSelection());this.currentSelectedRow=b;if(a&&a.shiftKey&&this.selectionMode!=IntegralUISelectionMode.One){if(this.shiftFirstSelectedRow||(this.shiftFirstSelectedRow=
f),a=this.getRowCurrentIndex(this.shiftFirstSelectedRow),c=this.getRowCurrentIndex(b),a>c&&(d=a,a=c,c=d),this.isIndexInRange(a)&&this.isIndexInRange(c))for(;a<=c;a++)this.currentRowList[a].data[this.options.rowFields.selected]=!0,this.currentSelectedRows.push(this.currentRowList[a].data)}else h||this.selectionMode==IntegralUISelectionMode.MultiSimple?(a=null==b[this.options.rowFields.selected]||"undefined"==b[this.options.rowFields.selected]?!1:b[this.options.rowFields.selected],b[this.options.rowFields.selected]=
!a,b[this.options.rowFields.selected]?this.isRowInSelectionList(b)||this.currentSelectedRows.push(b):this.currentSelectedRows=this.currentSelectedRows.filter(function(a){return a!=b})):(b[this.options.rowFields.selected]=!0,this.isRowInSelectionList(b)||this.currentSelectedRows.push(b)),this.shiftFirstSelectedRow=null;this.callAfterSelectEvent(b);this.refresh()}else h||this.selectionMode==IntegralUISelectionMode.MultiSimple?(a=null===b[this.options.rowFields.selected]||"undefined"==b[this.options.rowFields.selected]?
!1:b[this.options.rowFields.selected],c&&"undefined"!=c&&(a=c),b[this.options.rowFields.selected]=!a,b[this.options.rowFields.selected]?this.isRowInSelectionList(b)||this.currentSelectedRows.push(b):this.currentSelectedRows=this.currentSelectedRows.filter(function(a){return a!=b}),this.shiftFirstSelectedRow=null,this.callAfterSelectEvent(b),this.refresh()):h||this.selectionMode&IntegralUISelectionMode.MultiSimple||1!=this.currentSelectedRows.length&&this.isRowInSelectionList(b)||(this.shiftFirstSelectedRow=
null,this.clearPrevSelection(b),this.refresh(),d&&this.selectionChanged.emit(null))}else this.clearPrevSelection(),this.refresh(),d&&this.selectionChanged.emit(null)}};
IntegralUIBaseGrid.prototype.selectRows=function(a){if(a&&Array.isArray(a)){for(var b=this.currentSelectedRows.length=0;b<a.length;b++)a[b][this.options.rowFields.selected]=!0,this.currentSelectedRows.push(a[b]);0<a.length?(this.currentSelectedRow=a[a.length-1],this.callAfterSelectEvent(this.currentSelectedRow)):this.currentSelectedRow=null;this.refresh()}};
IntegralUIBaseGrid.prototype.updateRowSelection=function(a,b){var c=a&&(a.shiftKey||a.ctrlKey||a.metaKey)?!0:!1;this.selectionMode==IntegralUISelectionMode.MultiExtended&&0<this.currentSelectedRows.length&&!a.shiftKey&&!c&&1==a.which&&(this.clearPrevSelection(),b[this.options.rowFields.selected]=!0,this.currentSelectedRows.push(b),this.callAfterSelectEvent(b),this.refresh())};
IntegralUIBaseGrid.prototype.sort=function(a,b,c){this.sortColumn=a;this.sortComparer=c;this.options.sorting=b;this.updateLayout();this.change.emit({type:"sorting"})};IntegralUIBaseGrid.prototype.getCellIndexInCollection=function(a,b,c){var d=-1;if(a)for(var f=0;f<a.length;f++)if(void 0==a[f][this.options.cellFields.cid]){d=b;break}else if(a[f][this.options.cellFields.cid]==c){d=f;break}return d};
IntegralUIBaseGrid.prototype.isSortingAllowed=function(){return this.options.sorting==IntegralUISortOrder.Ascending||this.options.sorting==IntegralUISortOrder.Descending};IntegralUIBaseGrid.prototype.isSortingColumn=function(a){return a&&a==this.sortColumn?!0:!1};
IntegralUIBaseGrid.prototype.applySorting=function(a){var b=this;if(a&&(!b.sortColumn||0!=b.sortColumn[b.options.columnFields.visible])){var c=b.getColumnCurrentIndex(b.sortColumn),d=0<=c?c:b.options.expandColIndex;if(d<b.currentColumnList.length){var f=b.currentColumnList[d].data[b.options.columnFields.id];b.sortColumn&&b.sortColumn[b.options.columnFields.comparer]?a.sort(b.sortColumn[b.options.columnFields.comparer]):b.sortComparer?a.sort(b.sortComparer):b.isSortingAllowed()&&a.sort(function(a,
c){var e=null,g=null;if(a[b.options.rowFields.cells]){var h=b.getCellIndexInCollection(a[b.options.rowFields.cells],d,f);0<=h&&((e=a[b.options.rowFields.cells][h][b.options.cellFields.value])||(e=a[b.options.rowFields.cells][h][b.options.cellFields.text]),b.commonService.isObject(e)&&(e=e.value?e.value:e.text))}c[b.options.rowFields.cells]&&(h=b.getCellIndexInCollection(c[b.options.rowFields.cells],d,f),0<=h&&((g=c[b.options.rowFields.cells][h][b.options.cellFields.value])||(g=c[b.options.rowFields.cells][h][b.options.cellFields.text]),
b.commonService.isObject(g)&&(g=g.value?g.value:g.text)));e=void 0!=e?e:null;g=void 0!=g?g:null;switch(b.options.sorting){case IntegralUISortOrder.Ascending:if(e<g)return-1;if(e>g)return 1;break;case IntegralUISortOrder.Descending:if(e>g)return-1;if(e<g)return 1;break;default:return 0}})}}};    return IntegralUIBaseGrid;
}(IntegralUIBaseComponent));
export { IntegralUIBaseGrid };
IntegralUIBaseGrid.decorators = [
    { type: Component, args: [{
                selector: 'iui-basegrid',
                template: '',
                providers: [IntegralUIDataService]
            },] },
];
/** @nocollapse */
IntegralUIBaseGrid.ctorParameters = function () { return [
    { type: IntegralUIDataService, },
    { type: IntegralUIDragDropService, },
    { type: ElementRef, },
    { type: Renderer, },
    { type: IntegralUICommonService, },
    { type: IntegralUIFilterService, },
    { type: ComponentFactoryResolver, },
]; };
IntegralUIBaseGrid.propDecorators = {
    'appRef': [{ type: Input },],
    'gridLines': [{ type: Input },],
    'rowHeight': [{ type: Input },],
    'allowDrag': [{ type: Input },],
    'allowDrop': [{ type: Input },],
    'allowFilter': [{ type: Input },],
    'allowFocus': [{ type: Input },],
    'columns': [{ type: Input },],
    'dataFields': [{ type: Input },],
    'focusedCell': [{ type: Input },],
    'paging': [{ type: Input },],
    'rows': [{ type: Input },],
    'selectedColumn': [{ type: Input },],
    'selectedRow': [{ type: Input },],
    'selectionMode': [{ type: Input },],
    'sorting': [{ type: Input },],
    'afterSelect': [{ type: Output },],
    'beforeEdit': [{ type: Output },],
    'beforeSelect': [{ type: Output },],
    'change': [{ type: Output },],
    'columnAdding': [{ type: Output },],
    'columnAdded': [{ type: Output },],
    'columnClick': [{ type: Output },],
    'columnRemoving': [{ type: Output },],
    'columnRemoved': [{ type: Output },],
    'columnsCleared': [{ type: Output },],
    'columnSizeChanged': [{ type: Output },],
    'dragDrop': [{ type: Output },],
    'dragOver': [{ type: Output },],
    'keyDown': [{ type: Output },],
    'keyPress': [{ type: Output },],
    'keyUp': [{ type: Output },],
    'rowAdding': [{ type: Output },],
    'rowAdded': [{ type: Output },],
    'rowClick': [{ type: Output },],
    'rowDblClick': [{ type: Output },],
    'rowRemoving': [{ type: Output },],
    'rowRemoved': [{ type: Output },],
    'rowsCleared': [{ type: Output },],
    'loadComplete': [{ type: Output },],
    'scrollPosChanged': [{ type: Output },],
    'selectionChanged': [{ type: Output },],
    'updateComplete': [{ type: Output },],
    'onWindowKeyDown': [{ type: HostListener, args: ['document:keydown', ['$event'],] },],
    'onWindowKeyUp': [{ type: HostListener, args: ['document:keyup', ['$event'],] },],
};
//# sourceMappingURL=integralui.base.grid.js.map