import { ElementRef, QueryList } from '@angular/core';
import { IntegralUIBaseService } from './integralui.core';
import { IntegralUICommonService } from '../services/integralui.common.service';
import { IntegralUIDataService } from '../services/integralui.data.service';
import { IntegralUIListItem } from './integralui.listitem';
export declare class IntegralUITreeItem extends IntegralUIListItem {
    protected elemRef: ElementRef;
    private dataService;
    protected commonService: IntegralUICommonService;
    protected baseService: IntegralUIBaseService;
    private contentAnimation;
    private numItems;
    private templateData;
    private isExpanded;
    private expandState;
    private blockElemHeight;
    contentElem: ElementRef;
    dragElem: ElementRef;
    blockElem: ElementRef;
    contentList: QueryList<IntegralUITreeItem>;
    private itemList;
    private eventList;
    protected parentItem: IntegralUITreeItem;
    protected blockClassName: string;
    protected expandBoxClassName: string;
    protected blockClass: Array<any>;
    protected expandBoxClass: Array<any>;
    items: Array<any>;
    templateRef: any;
    expanded: boolean;
    constructor(elemRef: ElementRef, dataService: IntegralUIDataService, commonService?: IntegralUICommonService, baseService?: IntegralUIBaseService);
    ngOnInit(): void;
    protected initStyle(): void;
    ngAfterViewInit(): void;
    ngAfterContentChecked(): void;
    protected itemDragDrop(e: any): void;
    isBlockExpanded(): boolean;
    collapse(flag?: boolean): void;
    expand(flag?: boolean): void;
    toggle(value?: boolean, flag?: boolean): void;
    onExpandBoxMouseDown(e: any): void;
    toggleContent(): void;
    getComponentFromItem(item: any): any;
    getItemFromComponent(cmp: IntegralUITreeItem): any;
    protected isThereVisibleChildren(): boolean;
    clearComponentSelection(): void;
    selectItem(): void;
    refresh(): void;
    protected updateBlockClass(): void;
    protected getBlockClass(): any[];
    protected getGeneralClass(): string;
    protected updateExpandBoxClass(): void;
    protected getExpandBoxClass(): any[];
    protected getExpandBoxStyle(value: any): any;
    protected updateStyle(value: any): void;
}
