/*
  filename: integralui.core.js
  version : 0.5.0 BETA
  Copyright © 2016 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/iui-web-license-agreement.pdf.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(b,a){function d(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);b.prototype=null===a?Object.create(a):(d.prototype=a.prototype,new d)},__decorate=this&&this.__decorate||function(b,a,d,c){var f=arguments.length,e=3>f?a:null===c?c=Object.getOwnPropertyDescriptor(a,d):c,g;if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)e=Reflect.decorate(b,a,d,c);else for(var h=b.length-1;0<=h;h--)if(g=b[h])e=(3>f?g(e):3<f?g(a,d,e):
g(a,d))||e;return 3<f&&e&&Object.defineProperty(a,d,e),e},__metadata=this&&this.__metadata||function(b,a){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(b,a)},core_1=require("@angular/core"),integralui_common_service_1=require("../services/integralui.common.service");(function(b){b[b.None=0]="None";b[b.Top=1]="Top";b[b.Right=2]="Right";b[b.Bottom=4]="Bottom";b[b.Left=8]="Left"})(exports.IntegralUIAnchorStyle||(exports.IntegralUIAnchorStyle={}));
var IntegralUIAnchorStyle=exports.IntegralUIAnchorStyle;(function(b){b[b.normal=0]="normal";b[b.hovered=1]="hovered";b[b.selected=2]="selected";b[b.focused=4]="focused";b[b.disabled=8]="disabled"})(exports.IntegralUIObjectState||(exports.IntegralUIObjectState={}));var IntegralUIObjectState=exports.IntegralUIObjectState;
(function(b){b[b.None=0]="None";b[b.One=1]="One";b[b.MultiSimple=2]="MultiSimple";b[b.MultiExtended=3]="MultiExtended"})(exports.IntegralUISelectionMode||(exports.IntegralUISelectionMode={}));var IntegralUISelectionMode=exports.IntegralUISelectionMode;(function(b){b[b.Top=0]="Top";b[b.Right=1]="Right";b[b.Middle=2]="Middle";b[b.Bottom=3]="Bottom";b[b.Left=4]="Left"})(exports.IntegralUITabStripPlacement||(exports.IntegralUITabStripPlacement={}));var IntegralUITabStripPlacement=exports.IntegralUITabStripPlacement;
(function(b){b[b.None=0]="None";b[b.Hover=1]="Hover";b[b.Click=2]="Click";b[b.Always=3]="Always"})(exports.IntegralUIVisibility||(exports.IntegralUIVisibility={}));
var IntegralUIVisibility=exports.IntegralUIVisibility,IntegralUIBaseComponent=function(){function b(a){this.commonService=a;this.ctrlState=IntegralUIObjectState.normal;this.options={};this.generalClassName="";this.defaultStyle={};this.ctrlClass=[];this.styleChanged=new core_1.EventEmitter;this.stateChanged=new core_1.EventEmitter;this.options={currentStyle:null}}Object.defineProperty(b.prototype,"state",{get:function(){return this.ctrlState},set:function(a){this.ctrlState!=a&&(this.ctrlState=a,this.updateControlClass(),
this.processStateChanged(),this.stateChanged.emit(this))},enumerable:!0,configurable:!0});b.prototype.ngOnInit=function(){this.generalClassName="iui-control";this.initStyle()};b.prototype.initStyle=function(){this.defaultStyle={general:{disabled:this.generalClassName+"-disabled",focused:this.generalClassName+"-focused",normal:this.generalClassName,hovered:this.generalClassName+"-hovered",selected:this.generalClassName+"-selected"}};this.updateStyle(this.controlStyle);this.updateControlClass()};b.prototype.processStateChanged=
function(){};b.prototype.updateControlClass=function(){this.ctrlClass.length=0;this.ctrlClass.push(this.generalClassName);this.ctrlClass.push(this.options.currentStyle.general.normal);this.state&IntegralUIObjectState.disabled?this.ctrlClass.push(this.options.currentStyle.general.disabled):this.state&IntegralUIObjectState.focused?this.ctrlClass.push(this.options.currentStyle.general.focused):this.state&IntegralUIObjectState.selected?this.ctrlClass.push(this.options.currentStyle.general.selected):this.state&
IntegralUIObjectState.hovered&&this.ctrlClass.push(this.options.currentStyle.general.hovered)};b.prototype.getControlClass=function(){return this.ctrlClass};b.prototype.getDefaultStyle=function(){return{disabled:this.defaultStyle.general.disabled,focused:this.defaultStyle.general.focused,hovered:this.defaultStyle.general.hovered,normal:this.defaultStyle.general.normal,selected:this.defaultStyle.general.selected}};b.prototype.getGeneralStyle=function(a){if(this.commonService){if(this.commonService.isString(a))return a;
if(a)return{disabled:this.commonService.isFieldAvailable(a.disabled,this.generalClassName+"-disabled"),focused:this.commonService.isFieldAvailable(a.focused,this.generalClassName+"-focused"),hovered:this.commonService.isFieldAvailable(a.hovered,this.generalClassName+"-hovered"),normal:this.commonService.isFieldAvailable(a.normal,this.generalClassName),selected:this.commonService.isFieldAvailable(a.selected,this.generalClassName+"-selected")}}return this.getDefaultStyle()};b.prototype.updateStyle=
function(a){this.options.currentStyle=a?{general:this.getGeneralStyle(a.general)}:{general:{disabled:this.defaultStyle.general.disabled,focused:this.defaultStyle.general.focused,hovered:this.defaultStyle.general.hovered,normal:this.defaultStyle.general.normal,selected:this.defaultStyle.general.selected}}};__decorate([core_1.Input(),__metadata("design:type",Object)],b.prototype,"controlStyle",void 0);__decorate([core_1.Input(),__metadata("design:type",Object)],b.prototype,"data",void 0);__decorate([core_1.Input(),
__metadata("design:type",Number),__metadata("design:paramtypes",[Number])],b.prototype,"state",null);__decorate([core_1.Output(),__metadata("design:type",Object)],b.prototype,"styleChanged",void 0);__decorate([core_1.Output(),__metadata("design:type",Object)],b.prototype,"stateChanged",void 0);return b=__decorate([core_1.Component({selector:"iui-base",template:""}),__metadata("design:paramtypes",[integralui_common_service_1.IntegralUICommonService])],b)}();exports.IntegralUIBaseComponent=IntegralUIBaseComponent;
var IntegralUIBaseService=function(){function b(){this.componentRef=null}b.prototype.getComponent=function(){return this.componentRef};b.prototype.setComponent=function(a){this.componentRef=a};return b=__decorate([core_1.Injectable(),__metadata("design:paramtypes",[])],b)}();exports.IntegralUIBaseService=IntegralUIBaseService;
var IntegralUIDragWindow=function(){function b(){this.iconClass="";this.position={x:0,y:0};this.size={width:0,height:0};this.title="";this.display="block"}b.prototype.updatePos=function(a){a&&(a["class"]&&(this.iconClass=a["class"]),this.position={x:a.left,y:a.top},a.text&&(this.title=a.text))};__decorate([core_1.Input(),__metadata("design:type",String)],b.prototype,"iconClass",void 0);__decorate([core_1.Input(),__metadata("design:type",Object)],b.prototype,"position",void 0);__decorate([core_1.Input(),
__metadata("design:type",Object)],b.prototype,"size",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],b.prototype,"title",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],b.prototype,"display",void 0);return b=__decorate([core_1.Component({moduleId:module.id,selector:"iui-dragwin",template:"\n        <div class=\"iui-dragwin\" data-element=\"drag-window\" [ngStyle]=\"{ 'display': display, 'top': position.y + 'px', 'left': position.x + 'px' }\">\n            <span [ngClass]=\"iconClass\"></span>\n            <span class='iui-dragwin-title'>{{title}}</span>\n        </div>\n    ",
styleUrls:["css/integralui.css"]}),__metadata("design:paramtypes",[])],b)}();exports.IntegralUIDragWindow=IntegralUIDragWindow;
var IntegralUIItem=function(b){function a(a,c){b.call(this,c);this.elemRef=a;this.commonService=c;this.itemPos={top:0,left:0};this.positionType="static";this.contentClass=[];this.click=new core_1.EventEmitter;this.mouseDown=new core_1.EventEmitter;this.mouseUp=new core_1.EventEmitter;this.mouseEnter=new core_1.EventEmitter;this.mouseMove=new core_1.EventEmitter;this.mouseLeave=new core_1.EventEmitter}__extends(a,b);a.prototype.ngOnInit=function(){this.generalClassName="iui-item";this.contentClassName=
this.generalClassName+"-content";this.initStyle()};a.prototype.initStyle=function(){this.defaultStyle={general:{disabled:this.generalClassName+"-disabled",focused:this.generalClassName+"-focused",normal:this.generalClassName,hovered:this.generalClassName+"-hovered",selected:this.generalClassName+"-selected"},content:{disabled:this.contentClassName+"-disabled",focused:this.contentClassName+"-focused",normal:this.contentClassName,hovered:this.contentClassName+"-hovered",selected:this.contentClassName+
"-selected"}};this.updateStyle(this.controlStyle);this.updateControlClass();this.updateContentClass()};a.prototype.updateContentClass=function(){this.contentClass.length=0;this.contentClass.push(this.contentClassName);this.contentClass.push(this.options.currentStyle.content.normal);this.state&IntegralUIObjectState.disabled?this.contentClass.push(this.options.currentStyle.content.disabled):this.state&IntegralUIObjectState.focused?this.contentClass.push(this.options.currentStyle.content.focused):this.state&
IntegralUIObjectState.selected?this.contentClass.push(this.options.currentStyle.content.selected):this.state&IntegralUIObjectState.hovered&&this.contentClass.push(this.options.currentStyle.content.hovered)};a.prototype.getContentClass=function(){return this.contentClass};a.prototype.getContentStyle=function(a){return this.commonService.isString(a)?a:a?{disabled:this.commonService.isFieldAvailable(a.disabled,this.contentClassName+"-disabled"),focused:this.commonService.isFieldAvailable(a.focused,this.contentClassName+
"-focused"),hovered:this.commonService.isFieldAvailable(a.hovered,this.contentClassName+"-hovered"),normal:this.commonService.isFieldAvailable(a.normal,this.contentClassName),selected:this.commonService.isFieldAvailable(a.selected,this.contentClassName+"-selected")}:{disabled:this.defaultStyle.content.disabled,focused:this.defaultStyle.content.focused,hovered:this.defaultStyle.content.hovered,normal:this.defaultStyle.content.normal,selected:this.defaultStyle.content.selected}};a.prototype.updateStyle=
function(a){this.options.currentStyle=a?{general:this.getGeneralStyle(a.general),content:this.getContentStyle(a.content)}:{general:{disabled:this.defaultStyle.general.disabled,focused:this.defaultStyle.general.focused,hovered:this.defaultStyle.general.hovered,normal:this.defaultStyle.general.normal,selected:this.defaultStyle.general.selected},content:{disabled:this.defaultStyle.content.disabled,focused:this.defaultStyle.content.focused,hovered:this.defaultStyle.content.hovered,normal:this.defaultStyle.content.normal,
selected:this.defaultStyle.content.selected}}};a.prototype.processStateChanged=function(){this.updateContentClass()};a.prototype.onClick=function(a){this.click.emit(a);a.stopPropagation()};a.prototype.onMouseDown=function(a){this.mouseDown.emit(a);a.stopPropagation()};a.prototype.onMouseUp=function(a){this.mouseUp.emit(a);a.stopPropagation()};a.prototype.onMouseEnter=function(a){this.state|=IntegralUIObjectState.hovered;this.mouseEnter.emit(a);a.stopPropagation()};a.prototype.onMouseMove=function(a){this.mouseMove.emit(a);
a.stopPropagation()};a.prototype.onMouseLeave=function(a){this.state&=~IntegralUIObjectState.hovered;this.mouseLeave.emit(a);a.stopPropagation()};a.prototype.getContentSize=function(){var a={width:0,height:0};this.contentElem&&(a=this.commonService.getMargin(this.contentElem.nativeElement),a={width:this.contentElem.nativeElement.offsetWidth+(a.left+a.right),height:this.contentElem.nativeElement.offsetHeight+(a.top+a.bottom)/2});return a};a.prototype.getIconStatus=function(){return this.icon?"inline-block":
"none"};a.prototype.getMargin=function(){return this.elemRef?this.commonService.getMargin(this.elemRef.nativeElement.firstElementChild):{top:0,right:0,bottom:0,left:0}};a.prototype.getPageRect=function(){var a={top:0,right:0,bottom:0,left:0};this.elemRef&&(a=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild));return a};a.prototype.getSize=function(){var a={width:0,height:0};this.elemRef&&(a=this.commonService.getMargin(this.elemRef.nativeElement.firstElementChild),a={width:this.elemRef.nativeElement.firstElementChild.offsetWidth+
(a.left+a.right),height:this.elemRef.nativeElement.firstElementChild.offsetHeight+(a.top+a.bottom)/2});return a};a.prototype.resetPos=function(){this.updateLayout("static",{x:"auto",y:"auto"})};a.prototype.updateLayout=function(a,b){this.positionType=a;this.itemPos={top:b.y,left:b.x}};a.prototype.updatePos=function(a){this.updateLayout("absolute",a)};__decorate([core_1.ViewChild("content",{read:core_1.ElementRef}),__metadata("design:type",core_1.ElementRef)],a.prototype,"contentElem",void 0);__decorate([core_1.Input(),
__metadata("design:type",String)],a.prototype,"icon",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],a.prototype,"text",void 0);__decorate([core_1.Output(),__metadata("design:type",Object)],a.prototype,"click",void 0);__decorate([core_1.Output(),__metadata("design:type",Object)],a.prototype,"mouseDown",void 0);__decorate([core_1.Output(),__metadata("design:type",Object)],a.prototype,"mouseUp",void 0);__decorate([core_1.Output(),__metadata("design:type",Object)],a.prototype,"mouseEnter",
void 0);__decorate([core_1.Output(),__metadata("design:type",Object)],a.prototype,"mouseMove",void 0);__decorate([core_1.Output(),__metadata("design:type",Object)],a.prototype,"mouseLeave",void 0);return a=__decorate([core_1.Component({moduleId:module.id,selector:"iui-item",templateUrl:"templates/integralui.item.html",styleUrls:["css/integralui.item.css"],inputs:["controlStyle","data","state"],encapsulation:core_1.ViewEncapsulation.None}),__metadata("design:paramtypes",[core_1.ElementRef,integralui_common_service_1.IntegralUICommonService])],
a)}(IntegralUIBaseComponent);exports.IntegralUIItem=IntegralUIItem;
var IntegralUIFocus=function(){function b(a){this.elemRef=a;this.settings=!1}Object.defineProperty(b.prototype,"settings",{get:function(){return this.isFocused},set:function(a){this.isFocused!=a&&(this.isFocused=a)&&this.elemRef.nativeElement.focus()},enumerable:!0,configurable:!0});__decorate([core_1.Input("iuiFocus"),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],b.prototype,"settings",null);return b=__decorate([core_1.Directive({selector:"[iuiFocus]"}),__metadata("design:paramtypes",
[core_1.ElementRef])],b)}();exports.IntegralUIFocus=IntegralUIFocus;
var IntegralUIHeaderItem=function(b){function a(a,c){b.call(this,a,c);this.elemRef=a;this.commonService=c;this.expandHorizontalClass=[];this.expandVerticalClass=[];this.expandArrowBottomLeftClass=[];this.expandArrowBottomRightClass=[];this.expandArrowVerticalClass=[];this.expandArrowTopLeftClass=[];this.expandArrowTopRightClass=[];this.animationState=this.animationType="";this.expandClicked=new core_1.EventEmitter}__extends(a,b);a.prototype.ngOnInit=function(){this.generalClassName="iui-header";this.expandBoxClassName=
this.generalClassName+"expand-box";this.contentClassName=this.generalClassName+"-content";this.initStyle()};a.prototype.initStyle=function(){this.defaultStyle={general:{disabled:this.generalClassName+"-disabled",focused:this.generalClassName+"-focused",normal:this.generalClassName,hovered:this.generalClassName+"-hovered",selected:this.generalClassName+"-selected"},content:{disabled:this.contentClassName+"-disabled",focused:this.contentClassName+"-focused",normal:this.contentClassName,hovered:this.contentClassName+
"-hovered",selected:this.contentClassName+"-selected"},expandBox:this.expandBoxClassName};this.updateStyle(this.controlStyle);this.updateControlClass();this.updateContentClass()};a.prototype.getExpandVerticalClass=function(){this.expandVerticalClass.length=0;this.expandVerticalClass.push("iui-header-expand-box-vertical");this.state&IntegralUIObjectState.selected?this.expandVerticalClass.push("iui-header-expand-box-vertical-collapse"):this.expandVerticalClass.push("iui-header-expand-box-vertical-expand");
this.options.currentStyle.expandBox&&this.expandVerticalClass.push(this.options.currentStyle.expandBox);return this.expandVerticalClass};a.prototype.getExpandHorizontalClass=function(){this.expandHorizontalClass.length=0;this.expandHorizontalClass.push("iui-header-expand-box-horizontal");this.state&IntegralUIObjectState.selected?this.expandHorizontalClass.push("iui-header-expand-box-horizontal-collapse"):this.expandHorizontalClass.push("iui-header-expand-box-horizontal-expand");this.options.currentStyle.expandBox&&
this.expandHorizontalClass.push(this.options.currentStyle.expandBox);return this.expandHorizontalClass};a.prototype.getExpandArrowBottomLeftClass=function(){this.expandArrowBottomLeftClass.length=0;this.expandArrowBottomLeftClass.push("iui-header-expand-box-arrow-bottom-left");"expand"==this.animationState?this.expandArrowBottomLeftClass.push("iui-header-expand-box-arrow-bottom-left-collapse"):this.expandArrowBottomLeftClass.push("iui-header-expand-box-arrow-bottom-left-expand");this.options.currentStyle.expandBox&&
this.expandArrowBottomLeftClass.push(this.options.currentStyle.expandBox);return this.expandArrowBottomLeftClass};a.prototype.getExpandArrowBottomRightClass=function(){this.expandArrowBottomRightClass.length=0;this.expandArrowBottomRightClass.push("iui-header-expand-box-arrow-bottom-right");"expand"==this.animationState?this.expandArrowBottomRightClass.push("iui-header-expand-box-arrow-bottom-right-collapse"):this.expandArrowBottomRightClass.push("iui-header-expand-box-arrow-bottom-right-expand");
this.options.currentStyle.expandBox&&this.expandArrowBottomRightClass.push(this.options.currentStyle.expandBox);return this.expandArrowBottomRightClass};a.prototype.getExpandArrowVerticalClass=function(){this.expandArrowVerticalClass.length=0;this.expandArrowVerticalClass.push("iui-header-expand-box-arrow-vertical");"expand"==this.animationState?this.expandArrowVerticalClass.push("iui-header-expand-box-arrow-vertical-collapse"):this.expandArrowVerticalClass.push("iui-header-expand-box-arrow-vertical-expand");
this.options.currentStyle.expandBox&&this.expandArrowVerticalClass.push(this.options.currentStyle.expandBox);return this.expandArrowVerticalClass};a.prototype.getExpandArrowTopLeftClass=function(){this.expandArrowTopLeftClass.length=0;this.expandArrowTopLeftClass.push("iui-header-expand-box-arrow-top-left");"expand"==this.animationState?this.expandArrowTopLeftClass.push("iui-header-expand-box-arrow-top-left-expand"):this.expandArrowTopLeftClass.push("iui-header-expand-box-arrow-top-left-collapse");
this.options.currentStyle.expandBox&&this.expandArrowTopLeftClass.push(this.options.currentStyle.expandBox);return this.expandArrowTopLeftClass};a.prototype.getExpandArrowTopRightClass=function(){this.expandArrowTopRightClass.length=0;this.expandArrowTopRightClass.push("iui-header-expand-box-arrow-top-right");"expand"==this.animationState?this.expandArrowTopRightClass.push("iui-header-expand-box-arrow-top-right-expand"):this.expandArrowTopRightClass.push("iui-header-expand-box-arrow-top-right-collapse");
this.options.currentStyle.expandBox&&this.expandArrowTopRightClass.push(this.options.currentStyle.expandBox);return this.expandArrowTopRightClass};a.prototype.expandBoxClicked=function(a){1==a.buttons&&this.expandClicked.emit(null)};a.prototype.updateStyle=function(a){this.options.currentStyle=a?{general:this.getGeneralStyle(a.general),content:this.getContentStyle(a.content),expandBox:this.commonService.isFieldAvailable(a.expandBox,this.expandBoxClassName)}:{general:{disabled:this.defaultStyle.general.disabled,
focused:this.defaultStyle.general.focused,hovered:this.defaultStyle.general.hovered,normal:this.defaultStyle.general.normal,selected:this.defaultStyle.general.selected},content:{disabled:this.defaultStyle.content.disabled,focused:this.defaultStyle.content.focused,hovered:this.defaultStyle.content.hovered,normal:this.defaultStyle.content.normal,selected:this.defaultStyle.content.selected},expandBox:this.defaultStyle.expandBox}};__decorate([core_1.Input(),__metadata("design:type",String)],a.prototype,
"animationType",void 0);__decorate([core_1.Input(),__metadata("design:type",String)],a.prototype,"animationState",void 0);__decorate([core_1.Output(),__metadata("design:type",Object)],a.prototype,"expandClicked",void 0);return a=__decorate([core_1.Component({moduleId:module.id,selector:"iui-header",templateUrl:"templates/integralui.header.html",styleUrls:["css/integralui.header.css"],inputs:["controlStyle","data","icon","state","text"],outputs:"click mouseDown mouseEnter mouseLeave mouseMove mouseUp".split(" "),
encapsulation:core_1.ViewEncapsulation.None}),__metadata("design:paramtypes",[core_1.ElementRef,integralui_common_service_1.IntegralUICommonService])],a)}(IntegralUIItem);exports.IntegralUIHeaderItem=IntegralUIHeaderItem;
var IntegralUITComponent=function(){function b(){this.tvData="";this.tvTimer=null;this.tvCycle=6E4;this.tvDefault="none"}b.prototype.crpar=function(){return["si","Tri","Ver","on","al "]};b.prototype.crtr=function(a){return a[1]+a[4]+a[2]+a[0]+a[3]};b.prototype.ngOnInit=function(){var a=this;a.tvData=a.crtr(a.crpar());a.tvStyle=a.tvDefault;a.tvTimer=setInterval(function(){a.tvStyle="block";var b=setTimeout(function(){a.tvStyle=a.tvDefault;clearTimeout(b)},3E3)},a.tvCycle)};b.prototype.ngOnDestroy=
function(){this.tvTimer&&clearInterval(this.tvTimer)};__decorate([core_1.Input(),__metadata("design:type",String)],b.prototype,"tvStyle",void 0);return b=__decorate([core_1.Component({selector:"iui-tc",template:'\n        <style>\n            .tr-cmp\n            {\n            \tbackground: white;\n            \tcolor: #c60d0d;\n            \tborder: thin solid black;\n            \tpadding: 5px;\n            \tposition: absolute;\n            \ttop: 0;\n            \tleft: 0;\n            \tz-index: 999;\n            }\n        </style>\n\t\t<div class="tr-cmp" [ngStyle]="{ \'display\': tvStyle }">{{tvData}}</div>\n\t'}),
__metadata("design:paramtypes",[])],b)}();exports.IntegralUITComponent=IntegralUITComponent;