/*
  filename: integralui.base.grid.js
  version : 1.0.0
  Copyright © 2016-2017 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(f,b){function a(){this.constructor=f}for(var c in b)b.hasOwnProperty(c)&&(f[c]=b[c]);f.prototype=null===b?Object.create(b):(a.prototype=b.prototype,new a)},__decorate=this&&this.__decorate||function(f,b,a,c){var d=arguments.length,e=3>d?b:null===c?c=Object.getOwnPropertyDescriptor(b,a):c,k;if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)e=Reflect.decorate(f,b,a,c);else for(var h=f.length-1;0<=h;h--)if(k=f[h])e=(3>d?k(e):3<d?k(b,a,e):
k(b,a))||e;return 3<d&&e&&Object.defineProperty(b,a,e),e},__metadata=this&&this.__metadata||function(f,b){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(f,b)},core_1=require("@angular/core"),integralui_core_1=require("./integralui.core"),integralui_common_service_1=require("../services/integralui.common.service"),integralui_data_service_1=require("../services/integralui.data.service"),integralui_dragdrop_service_1=require("../services/integralui.dragdrop.service");
(function(f){f[f.None=0]="None";f[f.Horizontal=1]="Horizontal";f[f.Vertical=2]="Vertical";f[f.Both=3]="Both"})(exports.IntegralUIGridLines||(exports.IntegralUIGridLines={}));
var IntegralUIGridLines=exports.IntegralUIGridLines,IntegralUIBaseGrid=function(f){function b(a,c,b,e,k,h){f.call(this,k);this.dataService=a;this.dragDropService=c;this.elemRef=b;this.elemRenderer=e;this.commonService=k;this.cmpResolver=h;this.currentColumnList=[];this.currentRowList=[];this.options={};this.columnDataKey="columns";this.rowDataKey="rows";this.cloneElem=this.dragCmp=this.dragCmpRef=this.dropMarkElem=null;this.cloneElemStartPos={x:0,y:0};this.hoverRow=this.hoverColumn=null;this.currentScrollPos=
{x:0,y:0};this.maxScrollPos={x:0,y:0};this.currentSelectedRow=this.currentSelectedColumn=null;this.currentSelectionMode=integralui_core_1.IntegralUISelectionMode.One;this.shiftFirstSelectedRow=null;this.removeIndex=-1;this.currentSelectedRows=[];this.gridLines=IntegralUIGridLines.Both;this.rowHeight=0;this.afterSelect=new core_1.EventEmitter;this.beforeSelect=new core_1.EventEmitter;this.columnAdding=new core_1.EventEmitter;this.columnAdded=new core_1.EventEmitter;this.columnRemoving=new core_1.EventEmitter;
this.columnRemoved=new core_1.EventEmitter;this.columnsCleared=new core_1.EventEmitter;this.dragDrop=new core_1.EventEmitter;this.dragOver=new core_1.EventEmitter;this.rowAdding=new core_1.EventEmitter;this.rowAdded=new core_1.EventEmitter;this.rowClick=new core_1.EventEmitter;this.rowDblClick=new core_1.EventEmitter;this.rowRemoving=new core_1.EventEmitter;this.rowRemoved=new core_1.EventEmitter;this.rowsCleared=new core_1.EventEmitter;this.loadComplete=new core_1.EventEmitter;this.scrollPosChanged=
new core_1.EventEmitter;this.selectionChanged=new core_1.EventEmitter;this.updateComplete=new core_1.EventEmitter;this.updateOptions()}__extends(b,f);Object.defineProperty(b.prototype,"allowDrag",{set:function(a){this.options.allowDrag=a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"allowDrop",{set:function(a){this.options.allowDrop=a},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"dataFields",{set:function(a){this.updateDataFields(a)},enumerable:!0,configurable:!0});
Object.defineProperty(b.prototype,"paging",{set:function(a){this.updatePaging(a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectedColumn",{get:function(){return this.currentSelectedColumn},set:function(a){this.currentSelectedColumn!=a&&this.processColumnSelection(null,a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectedRow",{get:function(){return this.currentSelectedRow},set:function(a){this.currentSelectedRow!=a&&this.processRowSelection(null,
a)},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectionMode",{get:function(){return this.currentSelectionMode},set:function(a){this.currentSelectionMode!=a&&(this.currentSelectionMode=a,this.updateLayout())},enumerable:!0,configurable:!0});b.prototype.ngOnInit=function(){this.dataService.init([{data:this.columns,fields:this.options.columnFields,key:this.columnDataKey},{data:this.rows,fields:this.options.rowFields,key:this.rowDataKey}])};b.prototype.addColumn=function(a){this.callEventAddColumn("add",
a)};b.prototype.clearColumns=function(){this.dataService.clear(null,this.columnDataKey);this.columnsCleared.emit(null);this.currentScrollPos.x=0};b.prototype.insertColumnAt=function(a,c){this.callEventAddColumn("at",a,c)};b.prototype.insertColumnBefore=function(a,c){this.callEventAddColumn("ref",a,-1,c)};b.prototype.insertColumnAfter=function(a,c){this.callEventAddColumn("ref",a,-1,c,!0)};b.prototype.removeColumn=function(a){return this.callEventRemoveColumn(a)};b.prototype.removeColumnAt=function(a){return this.callEventRemoveColumn(null,
a)};b.prototype.callEventAddColumn=function(a,c,b,e,k){var d={cancel:!1,column:c};this.columnAdding.emit(d);if(1!=d.cancel){switch(a){case "at":this.dataService.insert(c,b,null,null,!1,this.columnDataKey);break;case "ref":this.dataService.insertByRef(c,e,k,this.columnDataKey);break;default:this.dataService.insert(c,-1,null,null,!1,this.columnDataKey)}this.columnAdded.emit({column:c})}};b.prototype.callEventRemoveColumn=function(a,c){var b={cancel:!1,column:a};this.columnRemoving.emit(b);return 1!=
b.cancel&&(this.removeIndex=this.columns?this.columns.indexOf(a):-1,b=this.dataService.removeAt(a,c,null,this.columnDataKey),b.result)?(this.columnRemoved.emit({column:b.obj}),!0):!1};b.prototype.addRow=function(a,c){this.callEventAddRow("add",a,c)};b.prototype.clearRows=function(a){this.dataService.clear(a,this.rowDataKey);this.rowsCleared.emit({parent:a});this.currentScrollPos.y=0};b.prototype.insertRowAt=function(a,c,b){this.callEventAddRow("at",a,c,b)};b.prototype.insertRowBefore=function(a,c){this.callEventAddRow("ref",
a,-1,null,c)};b.prototype.insertRowAfter=function(a,c){this.callEventAddRow("ref",a,-1,null,c,!0)};b.prototype.removeRow=function(a){return this.callEventRemoveRow(a)};b.prototype.removeRowAt=function(a,c){return this.callEventRemoveRow(null,a,c)};b.prototype.callEventAddRow=function(a,c,b,e,k,h){var d={cancel:!1,row:c};this.rowAdding.emit(d);if(1!=d.cancel){switch(a){case "at":this.dataService.insert(c,b,e,null,!1,this.rowDataKey);break;case "ref":this.dataService.insertByRef(c,k,h,this.rowDataKey);
break;default:this.dataService.insert(c,-1,e,null,!1,this.rowDataKey)}this.rowAdded.emit({row:c})}};b.prototype.callEventRemoveRow=function(a,c,b){var d={cancel:!1,row:a};this.rowRemoving.emit(d);return 1!=d.cancel&&(this.removeIndex=this.rows?this.rows.indexOf(a):-1,a=this.dataService.removeAt(a,c,b,this.rowDataKey),a.result)?(this.rowRemoved.emit({row:a.obj}),!0):!1};b.prototype.updateDataFields=function(a){a?(this.updateColumnFields(a.column),this.updateRowFields(a.row),this.updateCellFields(a.cell)):
(this.updateColumnFields(),this.updateRowFields(),this.updateCellFields())};b.prototype.updateOptions=function(a){a?(this.options={allowAnimation:this.commonService.isFieldAvailable(a.allowAnimation,!0),allowCellFocus:this.commonService.isFieldAvailable(a.allowCellFocus,!0),allowColumnReorder:this.commonService.isFieldAvailable(a.allowColumnReorder,!1),allowDrag:this.commonService.isFieldAvailable(a.allowDrag,!1),allowDrop:this.commonService.isFieldAvailable(a.allowDrop,!0),allowFilter:this.commonService.isFieldAvailable(a.allowFilter,
!1),allowFocus:this.commonService.isFieldAvailable(a.allowFocus,!0),animationSpeed:200,autoExpand:this.commonService.isFieldAvailable(a.autoExpand,!0),displayMode:this.commonService.isFieldAvailable(a.displayMode,"normal"),editorSettings:{activate:"click"},enabled:this.commonService.isFieldAvailable(a.enabled,!0),expandColIndex:this.commonService.isFieldAvailable(a.expandColIndex,void 0!=this.options.expandColIndex?this.options.expandColIndex:0),fillSpace:this.commonService.isFieldAvailable(a.fillSpace,
!1),gridLines:this.commonService.isFieldAvailable(a.gridLines,"both"),hoverSelection:this.commonService.isFieldAvailable(a.hoverSelection,!1),indent:this.commonService.isFieldAvailable(a.indent,15),labelEdit:this.commonService.isFieldAvailable(a.labelEdit,!1),loadRows:[],mouseWheelSpeed:this.commonService.isFieldAvailable(a.mouseWheelSpeed,"normal"),pathSeparator:this.commonService.isFieldAvailable(a.pathSeparator,"\\"),rowHeight:this.commonService.isFieldAvailable(a.rowHeight,-1),rtl:this.commonService.isFieldAvailable(a.rtl,
!1),selectedColumn:this.commonService.isFieldAvailable(a.selectedColumn,this.currentSelectedColumn?this.currentSelectedColumn:null),selectedIndex:-1,selectedRow:this.commonService.isFieldAvailable(a.selectedRow,this.currentSelectedRow?this.currentSelectedRow:null),selectedRows:[],selectionMode:this.commonService.isFieldAvailable(a.selectionMode,integralui_core_1.IntegralUISelectionMode.One),showFooter:this.commonService.isFieldAvailable(a.showFooter,!0),showHeader:this.commonService.isFieldAvailable(a.showHeader,
!0),showIcons:this.commonService.isFieldAvailable(a.showIcons,!0),sorting:this.commonService.isFieldAvailable(a.sorting,"none")},this.updatePaging(a.paging),this.updateDataFields(a.dataFields)):(this.options={allowAnimation:!0,allowCellFocus:!0,allowColumnReorder:!1,allowDrag:!1,allowDrop:!0,allowFilter:!1,allowFocus:!0,animationSpeed:200,autoExpand:!0,displayMode:"normal",editorSettings:{activate:"click"},enabled:!0,expandColIndex:0,fillSpace:!1,gridLines:"both",hoverSelection:!1,indent:15,labelEdit:!1,
loadRows:[],mouseWheelSpeed:"normal",pathSeparator:"\\",rowHeight:-1,rtl:!1,selectedColumn:null,selectedIndex:-1,selectedRow:null,selectedRows:[],selectionMode:integralui_core_1.IntegralUISelectionMode.One,showFooter:!0,showHeader:!0,showIcons:!0,sorting:"none"},this.updatePaging(),this.updateDataFields())};b.prototype.updateColumnFields=function(a){this.options.columnFields=a?{allowDrag:a.allowDrag?a.allowDrag:"allowDrag",allowDrop:a.allowDrop?a.allowDrop:"allowDrop",allowFilter:a.allowFilter?a.allowFilter:
"allowFilter",allowGrouping:a.allowGrouping?a.allowGrouping:"allowGrouping",cellTemplateUrl:a.cellTemplateUrl?a.cellTemplateUrl:"cellTemplateUrl",comparer:a.comparer?a.comparer:"comparer",contentAlignment:a.contentAlignment?a.contentAlignment:"contentAlignment",contextMenu:a.contextMenu?a.contextMenu:"contextMenu",editorType:a.editorType?a.editorType:"editorType",editorSettings:a.editorSettings?a.editorSettings:"editorSettings",editorTemplate:a.editorTemplate?a.editorTemplate:"editorTemplate",filterParams:a.filterParams?
a.filterParams:"filterParams",filterTemplate:a.filterTemplate?a.filterTemplate:"filterTemplate",fixed:a.fixed?a.fixed:"fixed",fixedWidth:a.fixedWidth?a.fixedWidth:"fixedWidth",footerAlignment:a.footerAlignment?a.footerAlignment:"footerAlignment",footerContent:a.footerContent?a.footerContent:"footerContent",footerTemplate:a.footerTemplate?a.footerTemplate:"footerTemplate",footerTemplateModel:a.footerTemplateModel?a.footerTemplateModel:"footerTemplateModel",footerText:a.footerText?a.footerText:"footerText",
footerTooltip:a.footerTooltip?a.footerTooltip:"footerTooltip",groupText:a.groupText?a.groupText:"groupText",headerAlignment:a.headerAlignment?a.headerAlignment:"headerAlignment",headerContent:a.headerContent?a.headerContent:"headerContent",headerTemplate:a.headerTemplate?a.headerTemplate:"headerTemplate",headerTemplateModel:a.headerTemplateModel?a.headerTemplateModel:"headerTemplateModel",headerText:a.headerText?a.headerText:"headerText",headerTooltip:a.headerTooltip?a.headerTooltip:"headerTooltip",
icon:a.icon?a.icon:"icon",id:a.id?a.id:"id",minWidth:a.minWidth?a.minWidth:"minWidth",maxWidth:a.maxWidth?a.maxWidth:"maxWidth",selected:a.selected?a.selected:"selected",style:a.style?a.style:"style",templateSettings:a.templateSettings?a.templateSettings:"templateSettings",visible:a.visible?a.visible:"visible",width:a.width?a.width:"width"}:{allowDrag:"allowDrag",allowDrop:"allowDrop",allowFilter:"allowFilter",allowGrouping:"allowGrouping",cellTemplateUrl:"cellTemplateUrl",comparer:"comparer",contentAlignment:"contentAlignment",
contextMenu:"contextMenu",editorType:"editorType",editorSettings:"editorSettings",editorTemplate:"editorTemplate",filterParams:"filterParams",filterTemplate:"filterTemplate",footerTemplateModel:"footerTemplateModel",fixed:"fixed",fixedWidth:"fixedWidth",footerAlignment:"footerAlignment",footerContent:"footerContent",footerTemplate:"footerTemplate",footerText:"footerText",footerTooltip:"footerTooltip",groupText:"groupText",headerAlignment:"headerAlignment",headerContent:"headerContent",headerTemplate:"headerTemplate",
headerTemplateModel:"headerTemplateModel",headerText:"headerText",headerTooltip:"headerTooltip",icon:"icon",id:"id",minWidth:"minWidth",maxWidth:"maxWidth",selected:"selected",style:"style",templateSettings:"templateSettings",visible:"visible",width:"width"};this.dataService&&this.dataService.updateDataFields(this.options.columnFields,this.columnDataKey)};b.prototype.updateRowFields=function(a){this.options.rowFields=a?{allowDrag:a.allowDrag?a.allowDrag:"allowDrag",allowDrop:a.allowDrop?a.allowDrop:
"allowDrop",allowEdit:a.allowEdit?a.allowEdit:"allowEdit",allowFocus:a.allowFocus?a.allowFocus:"allowFocus",autoCheck:a.autoCheck?a.autoCheck:"autoCheck",cells:a.cells?a.cells:"cells",checkBoxSettings:a.checkBoxSettings?a.checkBoxSettings:"checkBoxSettings",checked:a.checked?a.checked:"checked",checkState:a.checkState?a.checkState:"checkState",content:a.content?a.content:"content",contextMenu:a.contextMenu?a.contextMenu:"contextMenu",enabled:a.enabled?a.enabled:"enabled",expanded:a.expanded?a.expanded:
"expanded",hasChildren:a.hasChildren?a.hasChildren:"hasChildren",icon:a.icon?a.icon:"icon",id:a.id?a.id:"id",objects:a.rows?a.rows:"rows",pid:a.pid?a.pid:"pid",rows:a.rows?a.rows:"rows",selected:a.selected?a.selected:"selected",statusIcon:a.statusIcon?a.statusIcon:"statusIcon",style:a.style?a.style:"style",subobjects:a.cells?a.cells:"cells",templateObj:a.templateObj?a.templateObj:"templateObj",text:a.text?a.text:"text",tooltip:a.tooltip?a.tooltip:"tooltip",value:a.value?a.value:"value"}:{allowDrag:"allowDrag",
allowDrop:"allowDrop",allowFocus:"allowFocus",cells:"cells",content:"content",contextMenu:"contextMenu",enabled:"enabled",expanded:"expanded",fixed:"fixed",hasChildren:"hasChildren",icon:"icon",id:"id",objects:"rows",pid:"pid",rows:"rows",selected:"selected",statusIcon:"statusIcon",style:"style",subobjects:"cells",text:"text",tooltip:"tooltip"};this.dataService&&this.dataService.updateDataFields(this.options.rowFields,this.rowDataKey)};b.prototype.updateCellFields=function(a){this.options.cellFields=
a?{allowEdit:a.allowEdit?a.allowEdit:"allowEdit",cid:a.cid?a.cid:"cid",content:a.content?a.content:"content",contextMenu:a.contextMenu?a.contextMenu:"contextMenu",enabled:a.enabled?a.enabled:"enabled",labelEdit:a.labelEdit?a.labelEdit:"labelEdit",rid:a.rid?a.rid:"rid",selected:a.selected?a.selected:"selected",style:a.style?a.style:"style",templateObj:a.templateObj?a.templateObj:"templateObj",text:a.text?a.text:"text",tooltip:a.tooltip?a.tooltip:"tooltip",value:a.value?a.value:"value"}:{allowEdit:"allowEdit",
cid:"cid",content:"content",contextMenu:"contextMenu",enabled:"enabled",labelEdit:"labelEdit",rid:"rid",selected:"selected",style:"style",templateObj:"templateObj",text:"text",tooltip:"tooltip",value:"value"}};b.prototype.processLoadData=function(a,c,b,e){var d=this;d.clearRows(c);d.updateRowFields(b);var h=[];if(a)if(0!=e){var g=[];a.forEach(function(a,c){var b=a[d.options.rowFields.pid];g[b]?(g[b][d.options.rowFields.rows]||(g[b][d.options.rowFields.rows]=[]),g[a[d.options.rowFields.id]]=a,g[b][d.options.rowFields.rows].push(a)):
(g[a[d.options.rowFields.id]]=a,h.push(a))});g.length=0}else h=a;if(c)for(c[d.options.rowFields.rows]=h,a=0;a<c[d.options.rowFields.rows].length;a++)c[d.options.rowFields.rows][a][d.options.rowFields.pid]=c[d.options.rowFields.id];else if(d.rows)for(a=d.rows.length=0;a<h.length;a++)d.rows.push(h[a]);d.loadComplete.emit(null);this.updateLayout()};b.prototype.addDropMark=function(a){this.appRef&&(this.removeDropMark(),a=this.cmpResolver.resolveComponentFactory(integralui_core_1.IntegralUIDragWindow))&&
(this.dragCmpRef=this.appRef.createComponent(a),this.dragCmpRef._component?this.dragCmp=this.dragCmpRef._component:this.dragCmpRef._hostElement&&(this.dragCmp=this.dragCmpRef._hostElement.component))};b.prototype.removeDropMark=function(){this.dragCmpRef&&this.dragCmpRef.destroy();this.dragCmp=null};b.prototype.callDragDropEvent=function(a,c,b){a={action:c.action,cancel:!1,dragRow:c.source,dropPos:c.dropPos,event:a,isDropAllowed:c.allow,mousePos:this.commonService.getMousePos(a),sourceCtrl:c.sourceCtrl,
targetCtrl:c.targetCtrl,targetRow:c.target};b?this.dragDrop.emit(a):this.dragOver.emit(a);return a.cancel};b.prototype.checkEmptySpace=function(a){var c=this.getContentSize(),b=this.commonService.getPageRect(this.elemRef.nativeElement.firstElementChild),c=b.top+c.height,b=b.bottom;a=this.commonService.getMousePos(a);var e=this.commonService.getShiftPos();a.x-=e.x;a.y-=e.y;return a.y>=c&&a.y<=b};b.prototype.ctrlDragDrop=function(a){this.processDragDrop(a);a.stopPropagation()};b.prototype.ctrlDragLeave=
function(a){this.dropMark(a)};b.prototype.ctrlDragOver=function(a){this.processDragOver(a);a.stopPropagation()};b.prototype.dropMark=function(a,c){this.dragCmp||this.addDropMark({x:a.pageX,y:a.pageY});if(this.dragCmp){var b="none";this.options.allowDrop&&(b=c?"block":"none");this.dragCmp.display=b}};b.prototype.updateDragComponent=function(a){this.dragCmp&&this.dragCmp.updatePos(a)};b.prototype.isDragAllowed=function(a){return this.options.allowDrag?a&&(a[this.options.rowFields.allowDrag]||void 0===
a[this.options.rowFields.allowDrag])?!0:!1:!1};b.prototype.isDropAllowed=function(a,b,d){var c=this.options.allowDrop;if(c&&a&&b&&(c=b[this.options.rowFields.allowDrop]||void 0===b[this.options.rowFields.allowDrop]?!0:!1))if(Array.isArray(a))for(var k=0;k<a.length;k++){if(this.commonService.isEqual(a[k][this.options.rowFields.id],b[this.options.rowFields.id])||0===d&&this.isParentOf(b,a[k])||this.isChildOf(b,a[k])){c=!1;break}if(!c)break}else if(this.commonService.isEqual(a[this.options.rowFields.id],
b[this.options.rowFields.id])||0===d&&this.isParentOf(b,a)||this.isChildOf(b,a))c=!1;return c};b.prototype.processDragStart=function(a,b){this.dragDropService.clearData();if(!this.isDragAllowed(b))a.preventDefault();else if(b)if(this.isDragAllowed(b)){this.addDropMark({x:a.pageX,y:a.pageY});a.dataTransfer?(a.dataTransfer.effectAllowed="move",a.dataTransfer.setData("text",b[this.options.rowFields.id]?b[this.options.rowFields.id].toString():"")):a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.effectAllowed=
"move",a.originalEvent.dataTransfer.setData("text",b[this.options.rowFields.id]?b[this.options.rowFields.id].toString():""));var c={clone:this.cloneRow(b),source:b,sourceCtrl:this,sourceData:this.rows};this.dragDropService.setData(c)}else a.dataTransfer?a.dataTransfer.effectAllowed="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.effectAllowed="none")};b.prototype.processDragOver=function(a,b,d,e){a.preventDefault();var c=!0;a.dataTransfer?c="none"===a.dataTransfer.effectAllowed?
!1:!0:a.originalEvent&&a.originalEvent.dataTransfer&&(c="none"===a.originalEvent.dataTransfer.effectAllowed?!1:!0);if(c){var h=this.dragDropService.getData(),c=this.commonService.getShiftPos();if(b){var g=this.commonService.getMousePos(a);g.x-=c.x;g.y-=c.y;g=this.dragDropService.getDropPos(g,d,e);c=this.isDropAllowed(h.source,b,g);d={action:a.shiftKey?"copy":"move",source:h.source,dropPos:g,allow:c,sourceCtrl:h.sourceCtrl,target:b,targetCtrl:this};d=this.callDragDropEvent(a,d);if(c&&1!=d){e=this.commonService.getMousePos(a);
d=e.y+16;e=e.x+20;var f="iui-dragwin-icon";switch(g){case 0:f+=" iui-dragwin-move-in";break;case 1:f+=" iui-dragwin-move-up";break;case 2:f+=" iui-dragwin-move-down"}a.shiftKey&&(f+="-copy");this.updateDragComponent({"class":f,top:d,left:e,text:b[this.options.rowFields.text]});this.dropMark(a,c);this.dragDropService.setData({action:a.shiftKey?"copy":"move",source:h.source,sourceData:h.sourceData,target:b,targetCtrl:this,dropPos:g})}else a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&
a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a)}else c=this.checkEmptySpace(a),d={action:a.shiftKey?"copy":"move",source:h.source,dropPos:-1,allow:c,sourceCtrl:h.sourceCtrl,target:null,targetCtrl:this},d=this.callDragDropEvent(a,d),c&&1!=d?(g=this.commonService.getMousePos(a),d=g.y+16,e=g.x+20,f="iui-dragwin-icon iui-dragwin-move-end",a.shiftKey&&(f+="-copy"),this.updateDragComponent({"class":f,top:d,left:e,text:"TreeView"}),this.dropMark(a,c),this.dragDropService.setData({action:a.shiftKey?
"copy":"move",source:h.source,sourceData:h.sourceData,target:null,targetCtrl:this,dropPos:-1})):(a.dataTransfer?a.dataTransfer.dropEffect="none":a.originalEvent&&a.originalEvent.dataTransfer&&(a.originalEvent.dataTransfer.dropEffect="none"),this.dropMark(a))}};b.prototype.processDragDrop=function(a,b){a.preventDefault();this.dropMark(a);var c=!0;a.dataTransfer?c="none"===a.dataTransfer.effectAllowed?!1:!0:a.originalEvent&&a.originalEvent.dataTransfer&&(c="none"===a.originalEvent.dataTransfer.effectAllowed?
!1:!0);if(c){var e=this.dragDropService.getData();(c=b?this.isDropAllowed(e.source,b,e.dropPos):this.checkEmptySpace(a))&&e.source&&(this.callDragDropEvent(a,{action:a.shiftKey?"copy":"move",source:e.source,dropPos:e.dropPos,allow:c,sourceCtrl:e.sourceCtrl,target:e.target,targetCtrl:this},!0)||this.drop(a,e))}this.dragDropService.clearData()};b.prototype.drop=function(a,b){b&&b.sourceCtrl&&this.processDataDrop(a,b.source,b)};b.prototype.processDataDrop=function(a,b,d){var c=a.shiftKey;!a.shiftKey&&
d.sourceCtrl&&d.sourceCtrl.removeRow&&(c=d.sourceCtrl.removeRow(b));if(c){a=a.shiftKey&&d.clone?d.clone:b;switch(d.dropPos){case 0:this.insertRowAt(a,-1,d.target);break;case 1:this.insertRowBefore(a,d.target);break;case 2:this.insertRowAfter(a,d.target);break;default:this.addRow(a)}this.clearPrevSelection(a)}this.updateLayout()};b.prototype.callAfterSelectEvent=function(a){this.afterSelect.emit({obj:a});this.selectionChanged.emit(null)};b.prototype.cloneRow=function(a){return this.dataService.clone(a,
this.rowDataKey)};b.prototype.getList=function(a){switch(a){case "selected":return this.currentSelectedRows}return this.dataService.getList(null,this.rowDataKey)};b.prototype.getObjFromRow=function(a){for(var b=null,d=0;d<this.currentRowList.length;d++)if(this.currentRowList[d].data==a){b=this.currentRowList[d];break}return b};b.prototype.getRowCurrentIndex=function(a){return a?(a=this.getObjFromRow(a))&&this.currentRowList?this.currentRowList.indexOf(a):-1:-1};b.prototype.getRowFromComponent=function(a){return null};
b.prototype.isChildOf=function(a,b){return!1};b.prototype.isComponentIndexInRange=function(a){return this.rowList?0<=a&&a<this.rowList.length:!1};b.prototype.isIndexInRange=function(a){return this.currentRowList?0<=a&&a<this.currentRowList.length:!1};b.prototype.isRowAllowed=function(a,b){return!0};b.prototype.isRowEnabled=function(a){return!0};b.prototype.isRowFixed=function(a){return!1};b.prototype.isRowHovered=function(a){return a&&a==this.hoverRow?!0:!1};b.prototype.isRowSelected=function(a){return a&&
1==a[this.options.rowFields.selected]?!0:!1};b.prototype.isParentOf=function(a,b){return!1};b.prototype.getContentSize=function(){return{width:0,height:0}};b.prototype.refresh=function(a){this.clearComponentSelection();for(a=0;a<this.currentSelectedRows.length;a++){var b=this.getRowCurrentIndex(this.currentSelectedRows[a]);this.isComponentIndexInRange(b)&&(this.rowList[b].state|=integralui_core_1.IntegralUIObjectState.selected)}};b.prototype.updateLayout=function(){};b.prototype.onWindowMouseMove=
function(a){this.updateCloneElemPos(a)};b.prototype.onWindowMouseUp=function(a){this.closeCloneElem()};b.prototype.updateCloneElemPos=function(a){1==a.buttons&&this.cloneElem&&(this.cloneElem.style.top=a.pageY-this.cloneElemStartPos.y+"px",this.cloneElem.style.left=a.pageX-this.cloneElemStartPos.x+"px")};b.prototype.onCtrlMouseEnter=function(a){1==a.buttons&&this.cloneElem&&(this.cloneElem.style.display="block");this.elemRenderer.setElementStyle(this.elemRef.nativeElement,"cursor","default")};b.prototype.onCtrlMouseLeave=
function(a){1==a.buttons&&this.cloneElem&&(this.cloneElem.style.display="none")};b.prototype.setCloneElem=function(a,b){this.cloneElem&&this.closeCloneElem();this.cloneElem=a;this.cloneElemStartPos=b};b.prototype.appendCloneElem=function(){document.body.appendChild(this.cloneElem)};b.prototype.closeCloneElem=function(){var a=this;a.elemRenderer.setElementStyle(a.elemRef.nativeElement,"cursor","default");setTimeout(function(){a.cloneElem&&(document.body.removeChild(a.cloneElem),a.cloneElem=null)},
10)};b.prototype.updatePaging=function(a){this.options.paging=a?{enabled:this.commonService.isFieldAvailable(a.enabled,!1),showControlPanel:this.commonService.isFieldAvailable(a.showControlPanel,!0),pageSize:this.commonService.isFieldAvailable(a.pageSize,100)}:{enabled:!1,showControlPanel:!0,pageSize:100}};b.prototype.scrollPos=function(a){a&&(this.currentScrollPos={x:Math.max(0,Math.min(a.x,this.maxScrollPos.x)),y:Math.max(0,Math.min(a.y,this.maxScrollPos.y))},this.scrollPosChanged.emit({value:this.currentScrollPos}));
return{x:Math.floor(this.currentScrollPos.x),y:Math.floor(this.currentScrollPos.y)}};b.prototype.findRowById=function(a){return this.dataService.findObjectById(a,this.rowDataKey)};b.prototype.findRowByText=function(a){return this.dataService.findObjectByText(a,this.rowDataKey)};b.prototype.processColumnSelection=function(a,b,d){if(b)a=!0,this.currentSelectedColumn&&(a=!this.commonService.isEqual(this.currentSelectedColumn[this.options.columnFields.id],b[this.options.columnFields.id])),d={cancel:!1,
obj:b},this.beforeSelect.emit(d),a&&1!=d.cancel&&(this.currentSelectedColumn&&(this.currentSelectedColumn[this.options.columnFields.selected]=!1,this.refresh(this.currentSelectedColumn)),this.currentSelectedColumn=b,b[this.options.columnFields.selected]=!0,this.refresh(b),this.callAfterSelectEvent(b));else return this.currentSelectedColumn};b.prototype.clearComponentSelection=function(){this.rowList.forEach(function(a){return a.state&=~integralui_core_1.IntegralUIObjectState.selected})};b.prototype.clearPrevSelection=
function(a){for(var b=0;b<this.currentSelectedRows.length;b++)a&&!this.commonService.isEqual(this.currentSelectedRows[b][this.options.rowFields.id],a[this.options.rowFields.id])?this.currentSelectedRows[b][this.options.rowFields.selected]=!1:a||(this.currentSelectedRows[b][this.options.rowFields.selected]=!1);this.currentSelectedRows.length=0;a&&this.isRowEnabled(a)&&this.currentSelectedRows.push(a)};b.prototype.isRowInSelectionList=function(a){var b=!1,d=this.currentSelectedRows;if(a&&d)for(var e=
0;e<d.length;e++)if(this.commonService.isEqual(d[e][this.options.rowFields.id],a[this.options.rowFields.id])){b=!0;break}return b};b.prototype.processRowSelection=function(a,b,d){if(b&&this.selectionMode!=integralui_core_1.IntegralUISelectionMode.None){var c=0<this.currentSelectedRows.length;if(this.isRowEnabled(b)){var f=this.currentSelectedRow,h=!0;f&&(h=a&&(a.ctrlKey||a.metaKey)||!this.commonService.isEqual(f[this.options.rowFields.id],b[this.options.rowFields.id])||0==f[this.options.rowFields.selected]);
var g={cancel:!1,obj:b};this.beforeSelect.emit(g);if(1!=g.cancel)if(g=a&&(a.shiftKey||a.ctrlKey||a.metaKey)?!0:!1,h){this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiExtended&&(h=!this.isRowInSelectionList(b)||!g||a&&a.shiftKey);h&&(this.selectionMode==integralui_core_1.IntegralUISelectionMode.One?this.clearPrevSelection():a&&a.shiftKey?this.clearPrevSelection():g||this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiSimple||1!=this.currentSelectedRows.length&&this.isRowInSelectionList(b)||
this.clearPrevSelection());this.currentSelectedRow=b;if(a&&a.shiftKey&&this.selectionMode!=integralui_core_1.IntegralUISelectionMode.One){if(this.shiftFirstSelectedRow||(this.shiftFirstSelectedRow=f),a=this.getRowCurrentIndex(this.shiftFirstSelectedRow),d=this.getRowCurrentIndex(b),a>d&&(c=a,a=d,d=c),this.isIndexInRange(a)&&this.isIndexInRange(d))for(;a<=d;a++)this.currentRowList[a].data[this.options.rowFields.selected]=!0,this.currentSelectedRows.push(this.currentRowList[a].data)}else g||this.selectionMode==
integralui_core_1.IntegralUISelectionMode.MultiSimple?(a=null==b[this.options.rowFields.selected]||"undefined"==b[this.options.rowFields.selected]?!1:b[this.options.rowFields.selected],b[this.options.rowFields.selected]=!a,b[this.options.rowFields.selected]?this.isRowInSelectionList(b)||this.currentSelectedRows.push(b):this.currentSelectedRows=this.currentSelectedRows.filter(function(a){return a!=b})):(b[this.options.rowFields.selected]=!0,this.isRowInSelectionList(b)||this.currentSelectedRows.push(b)),
this.shiftFirstSelectedRow=null;this.callAfterSelectEvent(b);this.refresh()}else g||this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiSimple?(a=null===b[this.options.rowFields.selected]||"undefined"==b[this.options.rowFields.selected]?!1:b[this.options.rowFields.selected],d&&"undefined"!=d&&(a=d),b[this.options.rowFields.selected]=!a,b[this.options.rowFields.selected]?this.isRowInSelectionList(b)||this.currentSelectedRows.push(b):this.currentSelectedRows=this.currentSelectedRows.filter(function(a){return a!=
b}),this.shiftFirstSelectedRow=null,this.callAfterSelectEvent(b),this.refresh()):g||this.selectionMode&integralui_core_1.IntegralUISelectionMode.MultiSimple||1!=this.currentSelectedRows.length&&this.isRowInSelectionList(b)||(this.shiftFirstSelectedRow=null,this.clearPrevSelection(b),this.refresh(),c&&this.selectionChanged.emit(null))}else this.clearPrevSelection(),this.refresh(),c&&this.selectionChanged.emit(null)}};b.prototype.selectRows=function(a){if(a&&Array.isArray(a)){for(var b=this.currentSelectedRows.length=
0;b<a.length;b++)a[b][this.options.rowFields.selected]=!0,this.currentSelectedRows.push(a[b]);0<a.length?(this.currentSelectedRow=a[a.length-1],this.callAfterSelectEvent(this.currentSelectedRow)):this.currentSelectedRow=null;this.refresh()}};b.prototype.updateRowSelection=function(a,b){var c=a&&(a.shiftKey||a.ctrlKey||a.metaKey)?!0:!1;this.selectionMode==integralui_core_1.IntegralUISelectionMode.MultiExtended&&0<this.currentSelectedRows.length&&!a.shiftKey&&!c&&(this.clearPrevSelection(),b[this.options.rowFields.selected]=
!0,this.currentSelectedRows.push(b),this.callAfterSelectEvent(b),this.refresh())};__decorate([core_1.Input(),__metadata("design:type",Object)],b.prototype,"appRef",void 0);__decorate([core_1.Input(),__metadata("design:type",Array)],b.prototype,"columns",void 0);__decorate([core_1.Input(),__metadata("design:type",Array)],b.prototype,"rows",void 0);__decorate([core_1.Input(),__metadata("design:type",Number)],b.prototype,"gridLines",void 0);__decorate([core_1.Input(),__metadata("design:type",Number)],
b.prototype,"rowHeight",void 0);__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],b.prototype,"allowDrag",null);__decorate([core_1.Input(),__metadata("design:type",Boolean),__metadata("design:paramtypes",[Boolean])],b.prototype,"allowDrop",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],b.prototype,"dataFields",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",
[Object])],b.prototype,"paging",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],b.prototype,"selectedColumn",null);__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],b.prototype,"selectedRow",null);__decorate([core_1.Input(),__metadata("design:type",Number),__metadata("design:paramtypes",[Number])],b.prototype,"selectionMode",null);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],
b.prototype,"afterSelect",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"beforeSelect",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"columnAdding",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"columnAdded",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"columnRemoving",void 0);__decorate([core_1.Output(),
__metadata("design:type",core_1.EventEmitter)],b.prototype,"columnRemoved",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"columnsCleared",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"dragDrop",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"dragOver",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"rowAdding",
void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"rowAdded",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"rowClick",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"rowDblClick",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"rowRemoving",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],
b.prototype,"rowRemoved",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"rowsCleared",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"loadComplete",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"scrollPosChanged",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"selectionChanged",void 0);__decorate([core_1.Output(),
__metadata("design:type",core_1.EventEmitter)],b.prototype,"updateComplete",void 0);__decorate([core_1.HostListener("document:mousemove",["$event"]),__metadata("design:type",Function),__metadata("design:paramtypes",[Object]),__metadata("design:returntype",void 0)],b.prototype,"onWindowMouseMove",null);__decorate([core_1.HostListener("document:mouseup",["$event"]),__metadata("design:type",Function),__metadata("design:paramtypes",[Object]),__metadata("design:returntype",void 0)],b.prototype,"onWindowMouseUp",
null);return b=__decorate([core_1.Component({selector:"iui-basegrid",template:"",providers:[integralui_data_service_1.IntegralUIDataService]}),__metadata("design:paramtypes",[integralui_data_service_1.IntegralUIDataService,integralui_dragdrop_service_1.IntegralUIDragDropService,core_1.ElementRef,core_1.Renderer,integralui_common_service_1.IntegralUICommonService,core_1.ComponentFactoryResolver])],b)}(integralui_core_1.IntegralUIBaseComponent);exports.IntegralUIBaseGrid=IntegralUIBaseGrid;