/*
  filename: integralui.tooltip.js
  version : 1.6.0
  Copyright © 2016-2019 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __extends=this&&this.__extends||function(){var d=function(b,a){d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,c){a.__proto__=c}||function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])};return d(b,a)};return function(b,a){function f(){this.constructor=b}d(b,a);b.prototype=null===a?Object.create(a):(f.prototype=a.prototype,new f)}}(),__decorate=this&&this.__decorate||function(d,b,a,f){var c=arguments.length,e=3>c?b:null===f?f=Object.getOwnPropertyDescriptor(b,a):f,g;
if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)e=Reflect.decorate(d,b,a,f);else for(var h=d.length-1;0<=h;h--)if(g=d[h])e=(3>c?g(e):3<c?g(b,a,e):g(b,a))||e;return 3<c&&e&&Object.defineProperty(b,a,e),e},__metadata=this&&this.__metadata||function(d,b){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(d,b)};Object.defineProperty(exports,"__esModule",{value:!0});
var core_1=require("@angular/core"),integralui_core_1=require("../components/integralui.core"),integralui_common_service_1=require("../services/integralui.common.service"),IntegralUITooltipComponent=function(d){function b(a,b){var c=d.call(this,b)||this;c.elemRef=a;c.commonService=b;c.showTimer=null;c.popupTimer=null;c.mousePos={x:0,y:0};c.tooltipDisplay="none";c.tooltipPos={top:0,left:0};c.tooltipSize={width:0,height:0};c.closed=new core_1.EventEmitter;c.updateOptions();return c}__extends(b,d);Object.defineProperty(b.prototype,
"options",{get:function(){return this.tooltipOptions},set:function(a){this.updateOptions(a)},enumerable:!0,configurable:!0});b.prototype.ngOnInit=function(){this.generalClassName="iui-tooltip";this.initStyle()};b.prototype.updateOptions=function(a){this.tooltipOptions=a?{allowAnimation:this.commonService.isFieldAvailable(a.allowAnimation,!0),autoPopDelay:this.commonService.isFieldAvailable(a.autoPopDelay,5E3),enabled:this.commonService.isFieldAvailable(a.enabled,!0),initialDelay:this.commonService.isFieldAvailable(a.initialDelay,
500),position:this.commonService.isFieldAvailable(a.position,"mouse"),showMarker:this.commonService.isFieldAvailable(a.showMarker,!0),title:this.commonService.isFieldAvailable(a.title,"")}:{allowAnimation:!0,autoPopDelay:5E3,enabled:!0,initialDelay:500,position:"mouse",showMarker:!0,title:""}};b.prototype.removeTimers=function(){this.showTimer&&(clearTimeout(this.showTimer),this.showTimer=null);this.popupTimer&&(clearTimeout(this.popupTimer),this.popupTimer=null)};b.prototype.close=function(){this.removeTimers()};
b.prototype.open=function(a,b){var c=this;c.tooltipPos.top=-9999999;c.tooltipDisplay="block";var d=setTimeout(function(){c.tooltipSize=c.getSize();c.tooltipDisplay="none";c.removeTimers();c.tooltipOptions.enabled&&""!=c.tooltipOptions.title&&(c.showTimer=setTimeout(function(){c.show(a,b);c.popupTimer=setTimeout(function(){c.closed.emit(null);clearTimeout(c.popupTimer)},c.tooltipOptions.autoPopDelay);clearTimeout(c.showTimer)},c.tooltipOptions.initialDelay));clearTimeout(d)},1)};b.prototype.show=function(a,
b){this.tooltipPos={top:this.mousePos.y+24,left:this.mousePos.x};switch(this.tooltipOptions.position){case "above":this.tooltipPos={top:a.top-4-this.tooltipSize.height,left:a.left+Math.floor((b.width-this.tooltipSize.width)/2)};break;case "below":this.tooltipPos={top:a.bottom+4,left:a.left+Math.floor((b.width-this.tooltipSize.width)/2)};break;case "left":this.tooltipPos={top:a.top+Math.floor((b.height-this.tooltipSize.height)/2),left:a.left-4-this.tooltipSize.width};break;case "right":this.tooltipPos=
{top:a.top+Math.floor((b.height-this.tooltipSize.height)/2),left:a.right+4}}this.tooltipDisplay="block"};b.prototype.getSize=function(){return{width:this.elemRef.nativeElement.firstElementChild.offsetWidth,height:this.elemRef.nativeElement.firstElementChild.offsetHeight}};b.prototype.updateMousePos=function(a){this.mousePos!=a&&(this.mousePos=a)};b.prototype.updateControlClass=function(){this.ctrlClass.length=0;this.ctrlClass.push("iui-tooltip");if(this.tooltipOptions.showMarker)switch(this.tooltipOptions.position){case "above":this.ctrlClass.push("iui-tooltip-marker-bottom");
break;case "right":this.ctrlClass.push("iui-tooltip-marker-left");break;case "below":this.ctrlClass.push("iui-tooltip-marker-top");break;case "left":this.ctrlClass.push("iui-tooltip-marker-right")}0==this.options.allowAnimation&&this.ctrlClass.push("iui-tooltip-animation-none")};__decorate([core_1.Input(),__metadata("design:type",Object),__metadata("design:paramtypes",[Object])],b.prototype,"options",null);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,"closed",
void 0);return b=__decorate([core_1.Component({selector:"iui-tooltip",template:"\n\t\t<div [ngClass]=\"getControlClass()\" [ngStyle]=\"{ 'display': tooltipDisplay, 'top': tooltipPos.top + 'px', 'left': tooltipPos.left + 'px' }\" style=\"opacity:1 !important\">{{tooltipOptions.title}}</div>\n\t",inputs:["controlStyle","data","state"],encapsulation:core_1.ViewEncapsulation.None}),__metadata("design:paramtypes",[core_1.ElementRef,integralui_common_service_1.IntegralUICommonService])],b)}(integralui_core_1.IntegralUIBaseComponent);
exports.IntegralUITooltipComponent=IntegralUITooltipComponent;
var IntegralUITooltip=function(){function d(b,a,d){this.elemRef=b;this.cmpResolver=a;this.commonService=d;this.eventList=[];this.cmp=this.cmpRef=null}d.prototype.ngOnDestroy=function(){this.closeTooltip()};d.prototype.closeTooltip=function(){this.cmp&&(this.cmp.close(),this.cmp=null);this.cmpRef&&(this.eventList&&this.eventList.forEach(function(b){return b.unsubscribe()}),this.cmpRef.destroy())};d.prototype.getSize=function(){return{width:this.elemRef.nativeElement.offsetWidth,height:this.elemRef.nativeElement.offsetHeight}};
d.prototype.onMouseEnter=function(b){var a=this,d=a.tooltipRef?a.tooltipRef:a.settings.appRef;if(d){a.closeTooltip();var c=a.cmpResolver.resolveComponentFactory(IntegralUITooltipComponent);c&&(a.cmpRef=d.createComponent(c),a.cmpRef&&(a.cmpRef._component?a.cmp=a.cmpRef._component:a.cmpRef._hostElement&&(a.cmp=a.cmpRef._hostElement.component),a.cmp&&(a.cmp.options=a.settings,a.cmp.updateMousePos(a.commonService.getMousePos(b)),b=this.elemRef.nativeElement.getBoundingClientRect(),a.cmp.open(b,a.getSize()),
a.eventList.push(a.cmp.closed.subscribe(function(b){a.closeTooltip()})))))}};d.prototype.onMouseLeave=function(b){this.closeTooltip()};d.prototype.onMouseMove=function(b){this.cmp&&this.cmp.updateMousePos(this.commonService.getMousePos(b))};__decorate([core_1.Input("iuiTooltip"),__metadata("design:type",Object)],d.prototype,"settings",void 0);__decorate([core_1.Input(),__metadata("design:type",Object)],d.prototype,"tooltipRef",void 0);__decorate([core_1.HostListener("mouseenter",["$event"]),__metadata("design:type",
Function),__metadata("design:paramtypes",[Object]),__metadata("design:returntype",void 0)],d.prototype,"onMouseEnter",null);__decorate([core_1.HostListener("mouseleave",["$event"]),__metadata("design:type",Function),__metadata("design:paramtypes",[Object]),__metadata("design:returntype",void 0)],d.prototype,"onMouseLeave",null);__decorate([core_1.HostListener("mousemove",["$event"]),__metadata("design:type",Function),__metadata("design:paramtypes",[Object]),__metadata("design:returntype",void 0)],
d.prototype,"onMouseMove",null);return d=__decorate([core_1.Directive({selector:"[iuiTooltip]"}),__metadata("design:paramtypes",[core_1.ElementRef,core_1.ComponentFactoryResolver,integralui_common_service_1.IntegralUICommonService])],d)}();exports.IntegralUITooltip=IntegralUITooltip;