/*
  filename: integralui.range.js
  version : 1.5.0
  Copyright © 2016-2019 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
var __decorate=this&&this.__decorate||function(b,a,d,c){var f=arguments.length,e=3>f?a:null===c?c=Object.getOwnPropertyDescriptor(a,d):c,g;if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)e=Reflect.decorate(b,a,d,c);else for(var h=b.length-1;0<=h;h--)if(g=b[h])e=(3>f?g(e):3<f?g(a,d,e):g(a,d))||e;return 3<f&&e&&Object.defineProperty(a,d,e),e},__metadata=this&&this.__metadata||function(b,a){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(b,
a)};Object.defineProperty(exports,"__esModule",{value:!0});
var core_1=require("@angular/core"),integralui_core_1=require("../components/integralui.core"),integralui_common_service_1=require("../services/integralui.common.service"),IntegralUIRange=function(){function b(a,d,c){this.elemRef=a;this.elemRenderer=d;this.commonService=c;this.defaultSettings={anchor:integralui_core_1.IntegralUIAnchorStyle.Top|integralui_core_1.IntegralUIAnchorStyle.Left,factor:1,height:0,maxHeight:9999999,maxWidth:9999999,minHeight:0,minWidth:0,ref:"parent",width:0};this.resizeInterval=
null;this.originalElemSize={width:0,height:0};this.sizeChanged=new core_1.EventEmitter}b.prototype.ngAfterViewInit=function(){var a=this;a.defaultSettings.width=parseInt(a.elemRef.nativeElement.width,10);var d={anchor:integralui_core_1.IntegralUIAnchorStyle.Top|integralui_core_1.IntegralUIAnchorStyle.Left,factor:1,height:0,maxHeight:9999999,maxWidth:9999999,minHeight:0,minWidth:0,ref:"parent",width:0};a.settings&&(d.anchor=a.commonService.isFieldAvailable(a.settings.anchor,a.defaultSettings.anchor),
d.factor=a.commonService.isFieldAvailable(a.settings.factor,a.defaultSettings.factor),d.minWidth=parseInt(a.commonService.isFieldAvailable(a.settings.minWidth,a.defaultSettings.minWidth),10),d.maxWidth=parseInt(a.commonService.isFieldAvailable(a.settings.maxWidth,a.defaultSettings.maxWidth),10),d.minHeight=parseInt(a.commonService.isFieldAvailable(a.settings.minHeight,a.defaultSettings.minHeight),10),d.maxHeight=parseInt(a.commonService.isFieldAvailable(a.settings.maxHeight,a.defaultSettings.maxHeight),
10));var c=a.elemRef.nativeElement.parentElement.offsetWidth,b=a.elemRef.nativeElement.parentElement.offsetHeight,e=0,g=0;a.originalElemSize={width:a.elemRef.nativeElement.offsetWidth,height:a.elemRef.nativeElement.offsetHeight};var h={dx:0,dy:0};a.resizeInterval=setInterval(function(){var f=a.elemRef.nativeElement.parentElement.offsetWidth-2,k=a.elemRef.nativeElement.parentElement.offsetHeight-2;f!=e&&(h.dx=(f-c)*d.factor);k!=g&&(h.dy=(k-b)*d.factor);a.settings&&"parent"==a.settings.ref&&a.updateSize(d,
h);e=f;g=k},10)};b.prototype.ngOnDestroy=function(){null!=this.resizeInterval&&clearInterval(this.resizeInterval)};b.prototype.onMouseEnter=function(){this.sizeChanged.emit(null)};b.prototype.onChange=function(a){};b.prototype.onResize=function(a){};b.prototype.updateSize=function(a,b){this.commonService.getPadding(this.elemRef.nativeElement.parentElement);if(a.anchor&integralui_core_1.IntegralUIAnchorStyle.Right){var c=this.originalElemSize.width+b.dx;c=c<a.minWidth?a.minWidth:c;c=c>a.maxWidth?a.maxWidth:
c;this.elemRenderer.setElementStyle(this.elemRef.nativeElement,"width",c-2+"px")}a.anchor&integralui_core_1.IntegralUIAnchorStyle.Bottom&&(c=this.originalElemSize.height+b.dy,c=c<a.minHeight?a.minHeight:c,c=c>a.maxHeight?a.maxHeight:c,this.elemRenderer.setElementStyle(this.elemRef.nativeElement,"height",c-2+"px"))};__decorate([core_1.Input("iuiRange"),__metadata("design:type",Object)],b.prototype,"settings",void 0);__decorate([core_1.Output(),__metadata("design:type",core_1.EventEmitter)],b.prototype,
"sizeChanged",void 0);__decorate([core_1.HostListener("mouseenter"),__metadata("design:type",Function),__metadata("design:paramtypes",[]),__metadata("design:returntype",void 0)],b.prototype,"onMouseEnter",null);__decorate([core_1.HostListener("change"),__metadata("design:type",Function),__metadata("design:paramtypes",[Object]),__metadata("design:returntype",void 0)],b.prototype,"onChange",null);__decorate([core_1.HostListener("window:resize"),__metadata("design:type",Function),__metadata("design:paramtypes",
[Object]),__metadata("design:returntype",void 0)],b.prototype,"onResize",null);return b=__decorate([core_1.Directive({selector:"[iuiRange]"}),__metadata("design:paramtypes",[core_1.ElementRef,core_1.Renderer,integralui_common_service_1.IntegralUICommonService])],b)}();exports.IntegralUIRange=IntegralUIRange;